### ISSUE TITLE
first comment

### ISSUE THREAD

**Issue by rmz14** [ebeshero/DHClass-Hub#11]
good times

**Comment by RJP43** [comment]
see here you have made a new issue ... you also  want to go ahead and try to comment on one of the issues already made

**Comment by rmz14** [comment]
Okay thanks haha

**Comment by ebeshero** [comment]
I'm going to close all the "sandbox" issues here so the Issues board is a little tidier for us, and draws attention to our scheduled class discussion of the readings!
