### ISSUE TITLE
Six Degrees of Francis Bacon Network Entry Add-athon: Sat. January 23

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#112]
Information here: http://networkingwomen.sixdegreesoffrancisbacon.com/

**MORE INFO COMING SOON**

**Comment by nlottig94** [comment]
@ebeshero @ghbondar @RJP43 @mjb232 @jlm323 @laurenmcguigan @mmm202 @spadafour @brookestewart 
Hello all!  So our class has been approved to join the Six Degrees of Francis Bacon Network Entry Add-a-Thon!  If any of you would like to participate tomorrow (Saturday, January 23, 2016), here are some things you need to look over and know!
1. You will need to familiarize yourselves with the Six Degrees of Francis Bacon website, so you know how to use it and what it is all about.
          * You can access this [here](http://sixdegreesoffrancisbacon.com/).
          * When you open this site, you will automatically come to an Introduction page that is a video that will guide you through the site.
2. Next, you will need to familiarize yourselves with what the Add-a-Thon is all about, when it is occurring, and the schedule of events planned.
          * You can access this [here](http://networkingwomen.sixdegreesoffrancisbacon.com/).
3. Now you must register on the Six Degrees of Francis Bacon's Slack page, which you can find by following this [link](https://networkingwomen.slack.com/signup).
          * When you go to this site, you will be prompted to create an account with your @pitt,edu account.  **You must create the account with your @pitt.edu email, or this will not work.**
          * After creating your account, you will be taken directly to the Networking Women Slack page!  You will then have to read through the various channels that are listed to get a feel for the site, which I also have to do!  This list will look like this: ![list_of_channels](https://cloud.githubusercontent.com/assets/14095715/12520319/dc2c626c-c111-11e5-84f7-27ce8b50b011.png)
)
4. Log in tomorrow at 10:30am and participate!  You can also watch the livestream at the bottom of [this page](http://networkingwomen.sixdegreesoffrancisbacon.com/).
5. If anyone feels like talking about what we're doing with this, just post here on GitHub!!

**Comment by nlottig94** [comment]
One more thing to add!!  You must go onto the [Six Degrees of Francis Bacon site](http://sixdegreesoffrancisbacon.com) and create an account to add your information!
There is much more information on the [Networking Women site]() for the project this morning as well!
Also, the live stream starts at 10am!!  I look forward to a discussion on here all!! :):)

**Comment by nlottig94** [comment]
Who is tuned into the [Livestream](http://networkingwomen.sixdegreesoffrancisbacon.com/)????
@ebeshero @ghbondar @RJP43 @spadafour @brookestewart @mjb232 @jlm323 @mmm202 @laurenmcguigan 

I am currently looking up connections for Anne Lucas!

**Comment by ebeshero** [comment]
Greg and I are listening to the keynote!

**Comment by nlottig94** [comment]
I am too!  Except it's a little slow because we have so much snow here!

**Comment by nlottig94** [comment]
Hi all!  I have just successfully created a few of Anne Lucas' connections within the [Six Degrees of Francis Bacon site](http://sixdegreesoffrancisbacon.com/?id=10051933&confidence=60,100,&date=1500,1700)!

**Comment by ebeshero** [comment]
@nlottig94 I've just added a relationship to Mary Rowlandson, and a group affiliation with the Puritans: http://www.sixdegreesoffrancisbacon.com/?id=10010508&confidence=60,100&date=1500,1700

The Puritans in New England are a kind of underrepresented area in this England-centered data set, but the New Englanders were very much a part of the intellectual world of early modern England, so if I keep digging around here and looking for relationships to connect, I might want to hunt for people who knew both Mary Rowlandson, [Anne Bradstreet](http://www.sixdegreesoffrancisbacon.com/?id=10001469&confidence=60,100&date=1500,1700) and the radical dissenter [Anne Hutchinson](http://www.sixdegreesoffrancisbacon.com/?id=10006418&confidence=60,100&date=1500,1700)!
