### ISSUE TITLE
HELP - with text versus mixed content

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#115]
oxygen keeps telling me that the line  tags are coming up invalid. I don't understand why. 

start = poem
poem = element poem {type?,author?,p+}
type = attribute type {"RomeoandJuliet"}
author = attribute author {"Shakespeare"}
p = element p {speaker+, (speaking|stageDirection)*}
speaker = element speaker {text}
speaking = element speaking {character,l} 
character = attribute character {"Juliet"|"Romeo"}
stageDirection = element stageDirection {text}
l = element l {text | mixed {(bodyParts|reference|surname)*}}
bodyParts = element bodyParts {ref,empty}
reference = element reference {ref,text}
ref = attribute ref {"Montague"|"start"|"end"}
surname = element surname {character, text}

<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="lmcguigan_01-20_schema-01.rnc" type="application/relax-ng-compact-syntax"?>
<poem type="RomeoandJuliet" author="Shakespeare">

    <p>
        <speaker>Juliet.</speaker>
        <speaking character="Juliet">

            <l>O Romeo, Romeo! wherefore art thou Romeo?</l>
            <l>Deny thy father and refuse thy <reference ref="Montague">name</reference>;</l>
            <l>Or, if thou wilt not, be but sworn my love,</l>
            <l>And I'll no longer be a <surname character="Juliet">Capulet</surname>.</l>
        </speaking>
    </p>

    <p>
        <speaker>Romeo.</speaker>
        <stageDirection>[Aside.]</stageDirection>
        <speaking character="Romeo">

            <l>Shall I hear more, or shall I speak at this?</l>
        </speaking>
    </p>

    <p>
        <speaker>Juliet.</speaker>
        <speaking character="Juliet">
            <l>'Tis but thy <reference ref="Montague">name</reference> that is my enemy:</l>
            <l>Thou art thyself, though not a <surname character="Romeo">Montague</surname>.</l>
            <l>What's <surname character="Romeo">Montague</surname>?,It is <bodyParts ref="start"
                />nor hand, nor foot,</l>
            <l>Nor arm, nor face,<bodyParts ref="end"/> nor any other part</l>
            <l>Belonging to a man. O, be some other <reference ref="Montague">name</reference>.</l>
            <l>What's in a name? That which we call a rose</l>
            <l>By any other word would smell as sweet;</l>
            <l>So Romeo would, were he not Romeo call'd,</l>
            <l>Retain that dear perfection which he owes</l>
            <l>Without that <reference ref="Montague">title</reference>. Romeo, doff thy <reference
                    ref="Montague">name</reference>,</l>
            <l>And for that <reference ref="Montague">name</reference>, which is no part of
                thee,</l>
            <l>Take all myself.</l>

        </speaking>
    </p>

    <p>
        <speaker>Romeo.</speaker>
        <speaking character="Romeo">
            <l>I take thee at thy word.</l>
            <l>Call me but love, and I'll be new baptis'd;</l>
            <l>Henceforth I never will be Romeo.</l>
        </speaking>
    </p>
</poem>

**Comment by RJP43** [comment]
@laurenmcguigan it is important to remember that defining a rule with mixed content as mixed indicates that the contents of the given element can have text and elements within, just text, or even just elements. So reconsider your use of `text` and `mixed` together and consider why that might be causing an angry oXygen

**Comment by RJP43** [comment]
Show us your fix if you get it or comment back and we can debug further

**Comment by RJP43** [comment]
http://relaxng.org/compact-tutorial-20030326.html#keywords --- my sleepiness forgot to also say text is a special word in Relax-NG so if you want to use it as an element name you will need to escape it. I was just rolling with the notion that you everyone knows text is special without thinking duh! I wouldn't even have known that if I wouldn't of had a very similar issue my first round writing Relax-NG

**Comment by laurenmcguigan** [comment]
I tried added text into the mixed elements and it still comes out wrong. 

I've tried

l = element l {mixed {text | bodyParts | reference | surname}}

l = element l {mixed {(text | bodyParts | reference | surname)+}}

l = element l {text | bodyParts | reference | surname}

l = element l {text | (bodyParts | reference | surname)+}

I don't know if adding repitition indicators is the problem, but I have tried a million different things and I can't figure out why it is having a problem with the line elements??

**Comment by RJP43** [comment]
Ok so I'm using my phone and its a little difficult for me to pan your xml, but let's try to work through this ... is text an element in your xml?

**Comment by RJP43** [comment]
If it is an element you are using you need to escape, but if it's not then reconsider what you are saying by having both text and mixed together in one rule. If mixed means there could be text, elements, or bother what is the use of putting text and mixed? Is there any?

**Comment by RJP43** [comment]
*need to escape it

**Comment by RJP43** [comment]
*text, elements, or both

**Comment by laurenmcguigan** [comment]
text is not an element name. But when I take out text, it had problems with the lines that are only text and don't have elements in them

**Comment by RJP43** [comment]
Furthermore if text is not an element you are using and you want to say that a line can have text or text with those three elements then the or would yes need to be addressed on a multiplication indicator saying there could be 0 or 1 or maybe 0 or a lot (pending on what you want to indicate)

**Comment by RJP43** [comment]
*addressed with

**Comment by RJP43** [comment]
I think you were on the right track leaving it out because saying mixed says text and elements are okay in this element, but it doesn't say only text and elements can be in this element. Understand?

**Comment by laurenmcguigan** [comment]
I understand that I had to leave out text, and I did that, but it still has issues. 

l = element l {mixed {(reference | surname | bodyParts)*} }

this is how it is now, and how it was originally. Still coming up wrong??

**Comment by RJP43** [comment]
Interesting ... ok I'm pulling out my computter ... give me a sec

**Comment by laurenmcguigan** [comment]
it says l is not allowed here, expected element end-tag

**Comment by laurenmcguigan** [comment]
im sorry if you are trying to go to bed, I can come in early before class to show you

**Comment by RJP43** [comment]
no worries I'm a night owl ... okay I just got my computer on I'm going to copy your code over and we can try to figure this out

**Comment by RJP43** [comment]
i'm getting some other big validation errors that aren't letting me see the line error first based off the code that you have pasted here ... can you sync your github account and then push your two files (as you have them now) into the troubleshooting folder?

**Comment by laurenmcguigan** [comment]
I can’t figure out how to put it in the folder. I’ll just bring it in tomorrow. This is the one from last time that they want me to revise, so I have time to work on it. Plus I still need to figure out the problems with the one that is due tomorrow.
On Jan 22, 2016, at 2:31 AM, Rebecca Parker <notifications@github.com<mailto:notifications@github.com>> wrote:


i'm getting some other big validation errors that aren't letting me see the line error first based off the code that you have pasted here ... can you sync your github account and then push your two files (as you have them now) into the troubleshooting folder?

**Comment by RJP43** [comment]
Ok, we can take a peak at in the morning then. Sorry if I ran your head in circles trying to debug without having my computer open.

**Comment by laurenmcguigan** [comment]
It’s okay! thank you for your help. Now I am just trying to figure out what is wrong with me new one!

On Jan 22, 2016, at 2:42 AM, Rebecca Parker <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, we can take a peak at in the morning then. Sorry if I ran your head in circles trying to debug without having my computer open.

**Comment by ebeshero** [comment]
@laurenmcguigan I think I might have spotted the reason you're getting a validation error on your `<l>` elements: Look up at your rule that defines the parent element, `<speaking>`: That element is allowed to contain character (an attribute) and l (an element), but **how many** `<l>` elements do you expect speaker can contain? Right now, without a repetition indicator, you're only allowed to have one! Which repetition indicator would you want to set on l?

Hope that helps! @RJP43 is right about "mixed" syntax, by the way: using it means text can appear anywhere around the elements you designate inside. Those elements would have to appear in the order and quantities you designate, but text sort of floats in and around them all.

**Comment by RJP43** [comment]
debugged in class !
