### ISSUE TITLE
RegEx Helpful Hint

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#122]
Hi everyone, 

@mmm202 @mjb232 @jlm323 @laurenmcguigan 

It might be helpful to turn on the option in oXygen so that you can see where there are spaces, new line breaks, etc. I am pasting an image here that will show you were to find that option. Hope this helps!

![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/12699474/689ded28-c78a-11e5-9440-826ded9d9b99.jpg)

**Step-by-Step**  
  1. Go to Options
  2. Then Preferences 
  3. Then the Editor Tab
  4. Then select both boxes under the section titled "Whitespaces"
  6. Make sure to select apply
  7. Then OK

**Comment by ebeshero** [comment]
@RJP43 Thanks, Becca! Awesome screen shot! :+1:

**Comment by ebeshero** [comment]
In case anyone was a little confused by the section early on in our homework assignment on dealing with special reserved characters and "entity strings," I rewrote it to provide a little more information, and reposted our assignment page. The new material is just this:

````
### Reserved characters

The plain text file could, at least in principle, contain characters that have special meaning in XML: the ampersand and the angle brackets. You need to search for those and replace them with their corresponding XML entities. (These are those character strings that start with an & character.) You can read some detailed information about entity strings and what they are for on Obdurodon’s "Entities and numerical character references" section of http://dh.obdurodon.org/what-is-xml.xhtml, but for just a quick list, see "Special Reserved Characters" at the bottom of our Introducing XML tutorial. Note that you need to process them in the correct order, because of the ampersand (&) in each one! Think about this carefully: You always want to replace the & characters first. (Why? Explain in your homework write-up.)
````
