### ISSUE TITLE
Regex 2 HW Heads Up

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#125]
Dr. B's marked up example of the Voyager text (which you will be marking up using Regex in the assignment for Wednesday, here's a [link)](http://newtfire.org/dh/ForsterGeorgComplete-regex2-xml.xml) has a few elements called div. You might be confused as to why there are so many extra layers of these elements, but the [div](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-div.html),or text division, is a TEI element that "contains a subdivision of the front, body, or back of a text."

While we don't expect your homework to completely model Dr. B's (we don't expect to see the div elements in your submission, and you can name your elements whatever you feel is appropriate), it might be beneficial to try and add the div elements in anyway. This would help familiarize you with a more formal document structure as you consider the structure that the Boccaccio will take. It would also give you more Regex practice.

**Comment by ebeshero** [comment]
Thanks @spadafour !
