### ISSUE TITLE
Submitting Regex Assignments

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#127]
@ebeshero @RJP43 @spadafour @brookestewart @mjb232 @mmm202 @jlm323 @laurenmcguigan 
Hi all! We are having a few issues when trying to open regex assignments that are submitted from files other than `.txt` files. I want to remind everyone to only submit your regex steps saved as `.txt` files, please. For Windows users, you can use Notepad to type out your steps.  For Mac users, you can use the default TextEdit. Or for any platform, it may be easier for everyone just to open a plain text file in Oxygen and if you want it to be it's own separate window simply pull the tab out of the main oxygen window.  I can't stress enough how important it is that you save your regex steps in `.txt`.
If anyone needs help opening a new text document in Oxygen, just let me know!

**Comment by jlm323** [comment]
There isn't a Regex Ex 2 upload point available on Courseweb yet! @nlottig94 @rjp43 @brookestewart @spadafour @ebeshero.

**Comment by RJP43** [comment]
okay I am on it ! Thanks Jess!

**Comment by RJP43** [comment]
Okay it should be available now :+1:
