### ISSUE TITLE
REGEX 02/03

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#128]
Hi all, 
I am having trouble figuring out how to tag the captions under the chapters in the homework. I have already tagged the chapters the books and the paragraphs. Anyone have suggestions?

**Comment by laurenmcguigan** [comment]
Also, those captions don't have start tags. I don't understand why that is happening or how to fix it without doing it manually...

**Comment by nlottig94** [comment]
@laurenmcguigan let me take a quick look!  Give me one second!

**Comment by nlottig94** [comment]
@laurenmcguigan Okay, I see your issue...only because I didn't notice that I actually have this issue as well!  Give me a couple minutes to see what I can come up with!  Good eye!

**Comment by laurenmcguigan** [comment]
@nlottig94 instead of starting with the paragraph tags, I had to start with the chapter tags and place a space after it because in the original there is no space between chapter titles and the captions and that causes issues with the paragraph tags

**Comment by nlottig94** [comment]
Okay @laurenmcguigan !!!  I HAVE FOUND A SOLUTION!  So first I was just trying to find the lines that started with words after a new space and ended with a period followed by a new line (`\n^\w.+?\.\n`).  However, this didn't work because there were many lines throughout the text like this!  So then I tried to look for all of the lines that started with a capital letter and ended with a period and a new line (`\n^[A-Z].+?\.\n`), but this had the same effect.  Finally, I tried to be super specific by saying that before the start of the line, there was a chapter element followed by text and a new line and then start the previous expression.  Overall it looked like this: `<chapter>.+?\n^[A-Z].+?\.\n`.  And it worked!  Let me know how it works for you!  Thanks for sending this issue out!!

**Comment by nlottig94** [comment]
Okay, hold on, it's not working correctly.

**Comment by nlottig94** [comment]
@laurenmcguigan I found another issue. When you wrap the paragraphs, some of the descriptions under the chapter titles were wrapped as paragraphs..which causes a whole bunch of issues!  @ebeshero what should we do? Should we just forget tagging the descriptions?
For right now, just forget about the descriptions @laurenmcguigan. If we don't hear back from Dr. B, we'll just go over the issue tomorrow in class!

**Comment by nlottig94** [comment]
@laurenmcguigan @mjb232 @mmm202 @jlm323 
I know that the upload point on CourseWeb says that you only need to upload your `.txt` file, but the assignment page states that you should submit your `.txt` file AND your end result XML document.  Go ahead and upload both to CourseWeb please!!

**Comment by ebeshero** [comment]
Oops! Yes, we do want both files this time, so we see what you're building! I'll fix that now on Courseweb.

**Comment by ebeshero** [comment]
Fixed! Everyone, please upload two files: 
1) your text file outlining your steps and 
2) the XML file as you've built it.

**Comment by laurenmcguigan** [comment]
@nlottig94 this is what I started with instead, and it works up until I want to tag the descriptions. 

Find `(CHAP.+)`

Replace `<1>\1</1>\n`


Find `\n{3,}`

Replace `\n\n`


Find `\n\n`

Replace`</p>\n\n<p>`


Find `<p>(BOOK.+)</p>`

Replace `<head>\1</head>`


Find `<p>(<1>CHAP.+</1>)</p>`

Replace `\1`

But then I can not tag the descriptions. They are wrapped in paragraph tags. Is there a way to find a paragraph group that is only 1 or 2 lines?

**Comment by nlottig94** [comment]
@laurenmcguigan I'm not sure.  I tried to find them but couldn't.  If you figure it out, great!  Let me know how you did it.  But if you can't, the just make note of it in your instructions so we can at least see that you tried!

**Comment by ebeshero** [comment]
@laurenmcguigan @nlottig94 Lauren and Nicole--I'm taking a look now! Give me a few minutes...

**Comment by laurenmcguigan** [comment]
@nlottig94 @ebeshero 

WAIT I think I got it! Don't tell me yet!!!

**Comment by laurenmcguigan** [comment]
I DID IT I DID IT I DID IT I DID IT!!!!!!!!

**Comment by nlottig94** [comment]
@laurenmcguigan Enlighten us!!!

**Comment by laurenmcguigan** [comment]
Find:`(</1>\n\n)<p>(.+)</p>(\n\n<p>)`

Replace: `\1<1>\2</1>\3`

**Comment by laurenmcguigan** [comment]
@nlottig94 

the find actually has to look like this 
`(</1>\n\n)<p>(.+?)</p>(\n\n<p>)`
and you have to click dot matches all

**Comment by ebeshero** [comment]
HUZZAH! Good for you, Lauren! :+1:

**Comment by ebeshero** [comment]
@nlottig94 @laurenmcguigan @RJP43 @brookestewart @spadafour @mjb232 @mmm202 @jlm323 @ghbondar My own detailed solution to Regex Exercise 2 is posted in markdown (thanks, Becca!) [here on GitHub](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/Regex_Exercise_Solutions/Regex_Exercise2_Solution/ForsterGeorgUpconvert-ebb.md).  See you if you can read it carefully and follow what I am doing! I tried something a little unusual with capturing dates, which will show you a couple of different ways we can use parenthetical expressions ( )  in the Find window in a regular expression, and what happens with capturing them. You do NOT have to have created your XML file the way I did, and in fact I expect you all found your own ways! But I think you may learn a few things from walking through my solution slowly and reading my explanation! Hope this is useful!
--Dr. B
