### ISSUE TITLE
How to get to project folders in PSC

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#132]
1. Walk up to root (`/` or `<root>`)
2. Go into `var`
3. Go into `www`
4. Go into `html`
5. Go into your project folder!!

**Comment by RJP43** [comment]
How to get back to personal webs pace from project folder....

1. Walk back up to root 
2. Go into home 
3. Find your user ID
4. And personal website should sit in public_html folder

**Comment by RJP43** [comment]
*webspace

**Comment by ebeshero** [comment]
...and as we mentioned in class Friday, you may want to save your session or profile in your SFTP client  to access each space quickly!

**Comment by ebeshero** [comment]
@jonhoranic @ahunker Here's how to get to the PSC folders.

**Comment by RJP43** [comment]
@ajnewton1 @bsf15 @gretchenuhrinek @Samantha-Mcguigan @ahunker @jonhoranic Here is the issue @ebeshero mentioned on Friday that details how to navigate to and from your personal spaces and project spaces on the PSC.
