### ISSUE TITLE
Lightshot - tool for Print Screen 

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#134]
Just in case you were curious how I was getting the screenshots with all the nifty colored lines, boxes, and text descriptions (seen on the [GitShell Tutorial](http://newtfire.org/dh/explainGitShell.html), [HTML Exercise 1](http://newtfire.org/dh/HTMLExercise1.html), and the [XML Exam solution](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/XML_Exam-Solution.jpg)) here is the [link](https://app.prntscr.com/en/index.html) to the program. It is called Lightshot and works with both Mac and Windows. After download, all you do is press "Print Screen" and it brings up the Lightshot editing tool.

**Comment by ghbondar** [comment]
The "snip" tool is included in Windows 7, 8, and 10 as well.

**Comment by RJP43** [comment]
From my knowledge snip doesn't allow you to add text, boxes, and lines but hey if it does then people can use that too. Or use it in combo with paint. I was just sharing a cool tool I like to use and it is free also.

**Comment by tonyjoker** [comment]
There are many types [to take a screenshot on a Mac computer](https://usefulpcguide.com/16959/how-to-take-a-screenshot-on-a-mac/). I found [these print screen Mac tips](https://usefulpcguide.com/16751/how-to-print-screen-mac-os-x/) from Google, and think it's useful.

Check it out!

You can also easily change type of screenshots file as well as change location where it will be stored after capturing.
