### ISSUE TITLE
website

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#136]
hi everyone! I am having a little trouble uploading an image to my site. First I uploaded a picture of myself from my own computer and it did not show up on my site. Then I tried to upload one from google images when I googled myself and that still didn't work? Is there something I am doing wrong, or something I need to add to my tag if it is coming from my own computer and not from the web? My code looks like this:
`<img src="s200_lauren.mcguigan.jpg"/>`

Does anyone see an issue there? This is the title of the image given by google images...

**Comment by nlottig94** [comment]
@laurenmcguigan in order to put it on your site, you also have to put the picture into your site directory where your .xhtml sits!  See if that works!

**Comment by laurenmcguigan** [comment]
I went into fetch and uploaded my css and my xhtml and the image to a folder called webpage1. What do I do from there?

**Comment by nlottig94** [comment]
@laurenmcguigan now you have to make sure you are using the correct file path to point to your images.  So you have to make sure your `@href` knows that your images are in a folder.

**Comment by laurenmcguigan** [comment]
@nlottig94 how do i do that?

**Comment by nlottig94** [comment]
Okay, so all you have to do is go into the folder and copy the image from there.  Then in your `<a href="">` you'll need to paste that in between the quotes.  That will give you the correct file path!

**Comment by mjb232** [comment]
So, after doing this, will we be able to see the images if we open up the HTML locally (by using the crtl+O command)?

**Comment by nlottig94** [comment]
@mjb232 You should be able to!  Try it out!!

**Comment by laurenmcguigan** [comment]
@nlottig94 I'm confused.... this is what my xhtml looks like

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<?xml-stylesheet type="text/css" href="lmcguiganwebpagesstylesheet.css"?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
       `<title>Lauren McGuigan</title>
     
    </head>
    <body>
        <h1>Lauren McGuigan</h1>
        <section>208 Summit View Drive, Jeannette PA, 15644 | (724)-757-8841 | lmm182@pitt.edu </section>
        <p>Hello! My name is Lauren McGuigan and I am a Junior Communication Major at the University
            of Pittsburgh at Greensburg. My focus is in Media Studies, and I am currently pursuing a
            Digital Media Certificate. I will graduate in April of 2017, and am looking for opportunities in the entertainment industry.</p>
        <img src="s200_lauren.mcguigan.jpg" />
        <h2>Accomplishments</h2>
        <ul>
            <li>Merit Scholarship</li>
            <li>GPA:3.76</li>
            <li>Dean's List: 4 Semesters</li>



        </ul>
    </body>
</html>`

I have the image tag in there and I have downloaded the image the css and the xhtml to fetch in my public folder. I don't understand why it isn't showing up on my  page. Do I need to add an <a> element with the link to the image??

**Comment by mjb232** [comment]
See my image looks like this
`<p>
'<img href="/home/mjb232/public_html/public_html/web1" src="theHouse.jpg" alt="my house" />'
`</p>'
but oxygen is saying that im not allowed to have href in there

**Comment by nlottig94** [comment]
@laurenmcguigan Okay!  I just looked in your folder to see how you had it set up.  First, you want your webpage to be named `index.xhtml` so that your webage will sow up. Second, you want this webpage to be sitting only in your public folder, not in your webpage1 folder. Then navigate to your images and CSS that are located in your folder in yout `@src`.
@mjb232 I am so sorry!!  I was just working with `@href`, but you want to put what is in your `@href` into your `@src`!  I am so so sorry for the confusion!!  
Try those guys, and let me know if it helps!!

**Comment by nlottig94** [comment]
Right now I am seeing this when searching for your webpage @laurenmcguigan :
![image](https://cloud.githubusercontent.com/assets/14095715/12877500/45164dc4-cde2-11e5-953f-f12b89e208a5.png)

**Comment by nlottig94** [comment]
If it helps, go one back from inside your directory (into the `home` directory) and go into mine to see what it looks like!

**Comment by laurenmcguigan** [comment]
@nlottig94  okay, I added all the files to my public folder. The image still does not show up. Can you access my file now? or does it look the same? and right now when i go to my webpage the address is file:///Users/laurenmcguigan/Documents/lmcguiganwebpage.xhtml do I need to change that somehow for it to show up in newt fire?

**Comment by nlottig94** [comment]
@laurenmcguigan You still have to rename your webpage `index.html`. This is what I get:
![image](https://cloud.githubusercontent.com/assets/14095715/12877610/319800a6-cde4-11e5-8d77-7ba72528ce4c.png)
However, when I click"lmcguiganwebpage.xhtml", this is what I get:
![image](https://cloud.githubusercontent.com/assets/14095715/12877613/5324687c-cde4-11e5-8650-134dc4690994.png)

**Comment by laurenmcguigan** [comment]
@nlottig94 okay good! I don't know why it is not showing up for me. And when you say rename my webpage to you mean the name between the title tags? for example:
`<title> index.html </title>`
or you want me to change the name of my xhtml from lmcguiganwepage.xhtml to index.html?

**Comment by nlottig94** [comment]
@laurenmcguigan I want you to rename your xhtml. :)

**Comment by nlottig94** [comment]
Great job, @laurenmcguigan!!  I can see your webpage now!!

**Comment by mjb232** [comment]
@nlottig94 ok, my turn. So first things first: can you access my page?

**Comment by nlottig94** [comment]
@mjb232 no, I cannot. This is what I see:
![image](https://cloud.githubusercontent.com/assets/14095715/12877843/db9c3b5a-cde7-11e5-95eb-c1c204940b45.png)

**Comment by mjb232** [comment]
ok hold on I think i see my issues, give me a few

**Comment by laurenmcguigan** [comment]
Okay, one more problem. sorry @nlottig94 maybe someone else is online to help you out? 

So now that I changed my xhtml document to index.html, when I try to upload it to the web, it is showing up without the styles on the css style sheet. I re-associated it just to be sure. It looks like this now 

`<link rel="stylesheet" type="text/css" href="lmcguiganwebpagestylesheet.css"/>`

Yet, when I open it up in chrome the aspects from the style sheet do not show up. 
However, if I upload my original xhtml everything from the style sheet shows up.. 
I think my computer is confused.. I don't know what to do

**Comment by laurenmcguigan** [comment]
and all my changes will still show up on [file:///Users/laurenmcguigan/Documents/lmcguiganwebpage.xhtml](url)

but not on
[ file:///Users/laurenmcguigan/Documents/index.html](url)

**Comment by nlottig94** [comment]
Okay, @laurenmcguigan, I see your issue.  When I select "View page source" when I'm looking at your webpage, I see this:
![image](https://cloud.githubusercontent.com/assets/14095715/12878001/7c5f7d2a-cdea-11e5-9bbe-2b29b8145607.png)
I see that you're linking your CSS above your head element, not in your head element.

**Comment by laurenmcguigan** [comment]
can you look at it again? I changed it and it still is not showing up. @nlottig94

**Comment by laurenmcguigan** [comment]
is it still showing up for you even though it isn't for me? I deleted my original xhtml and uploaded the renamed one. does it still show up the same, Im worried it wont

**Comment by mjb232** [comment]
did you put the commad in a '<link>' tag? it would look like this:
`<link rel="stylesheet" type="text/css" href="webpage1.CSS"/>`
and it would also be contained in the `<head>`

**Comment by laurenmcguigan** [comment]
yes @mjb232

**Comment by nlottig94** [comment]
Give me one second, guys.

**Comment by laurenmcguigan** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Lauren McGuigan</title>
        <link rel="stylesheet" type="text/css" href="lmcguiganwebpagestylesheet.css"/>
    </head>
    <body>
        <h1>Lauren McGuigan</h1>
        <section>208 Summit View Drive, Jeannette PA, 15644 | (724)-757-8841 | lmm182@pitt.edu </section>
        <p>Hello! My name is Lauren McGuigan and I am a Junior Communication Major at the University
            of Pittsburgh at Greensburg. My focus is in Media Studies, and I am currently pursuing a
            Digital Media Certificate. I will graduate in April of 2017, and am looking for opportunities in the entertainment industry.</p>
        <img src="s200_lauren.mcguigan.jpg"/>
        <h2>Accomplishments</h2>
        <ul>
            <li>Merit Scholarship</li>
            <li>GPA:3.76</li>
            <li>Dean's List: 4 Semesters</li>



        </ul>
    </body>
</html>`

**Comment by laurenmcguigan** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    `<head>
        <title>Lauren McGuigan</title>
        <link rel="stylesheet" type="text/css" href="lmcguiganwebpagestylesheet.css"/>
    </head>
    <body>
        <h1>Lauren McGuigan</h1>
        <section>208 Summit View Drive, Jeannette PA, 15644 | (724)-757-8841 | lmm182@pitt.edu </section>
        <p>Hello! My name is Lauren McGuigan and I am a Junior Communication Major at the University
            of Pittsburgh at Greensburg. My focus is in Media Studies, and I am currently pursuing a
            Digital Media Certificate. I will graduate in April of 2017, and am looking for opportunities in the entertainment industry.</p>
        <img src="s200_lauren.mcguigan.jpg"/>
        <h2>Accomplishments</h2>
        <ul>
            <li>Merit Scholarship</li>
            <li>GPA:3.76</li>
            <li>Dean's List: 4 Semesters</li>



        </ul>
    </body>
`</html>

```

**Comment by laurenmcguigan** [comment]
Again, it does show all the changes in this address
`file:///Users/laurenmcguigan/Documents/lmcguiganwebpage.xhtml`
but not this
`file:///Users/laurenmcguigan/Documents/index.xhtml`

I don't understand this, but all I really want is to make sure when @nlottig94 clicks on it in my folder it shows up correctly for her, so that I don't get a bad grade. We can worry about fixing the web address another time.

**Comment by laurenmcguigan** [comment]
AND none of my changes are showing up anymore... ARGGGGG

**Comment by mjb232** [comment]
I'm running into the same problem, also, @laurenmcguigan how did you make your picture that size? my picture takes up half the screen (its rather amusing actually)

**Comment by laurenmcguigan** [comment]
@mjb232 no clue. this is frustrating.

**Comment by mjb232** [comment]
@laurenmcguigan trying moving your `<link` that contains all of your CSS info above the `<title>` tag.

**Comment by nlottig94** [comment]
@ebeshero @rjp43 @gbondar My internet just went down. Is there any way you guys can see what's up with @laurenmcguigan and @mjb232 's pages??

**Comment by mjb232** [comment]
mine looks like 
`<link rel="stylesheet" type="text/css" href="webpage1.CSS"/>
        <title>The Tale of Matt</title>`
and dont forget to sync your documents from your computer to the web

**Comment by nlottig94** [comment]
As long as your `<link>` is within `<head>` should work.

**Comment by laurenmcguigan** [comment]
I'm going to change it and re-upload it to Fetch. Thank you for all your help @nlottig94 and @mjb232 !!! Just check that it works for you after the re-upload!

**Comment by mjb232** [comment]
her `<link>` isnt self closing, would that be an issue?
it looks like 
`<link rel="blah" type="blah" href="blah"></link>`
as opposed to 
`<link rel="blah" type="blah" href="blah"/>

**Comment by nlottig94** [comment]
No, that isn't a problem because as long as it's empty, it's like a self-closing tag.

**Comment by mjb232** [comment]
Wait she fixed it! its working now!

**Comment by laurenmcguigan** [comment]
@mjb232 @nlottig94  I THINK I FIXED IT. The webpage will load now. Could you just check it from your end Nicole to be sure it shows up like it originally did?

**Comment by mjb232** [comment]
All good from my end! What did you do to fix it???

**Comment by laurenmcguigan** [comment]
@mjb232 I had to rename my stylesheet to index.css!

**Comment by laurenmcguigan** [comment]
@mjb232 is the image still showing up?

**Comment by mjb232** [comment]
Yup, your pick and CSS are all good to go! Nice job!

**Comment by laurenmcguigan** [comment]
@mjb232 YAY!!!! Thank you both for all your help. Sorry if I kept you up, and kept you from everything else you need to get done!  @nlottig94

**Comment by laurenmcguigan** [comment]
And sorry to everyone else for the spam :/

**Comment by mjb232** [comment]
That's what this is for haha. And I was running into the same issues so I'm glad I wasn't the only one

**Comment by ebeshero** [comment]
@laurenmcguigan @mjb232 @nlottig94 @jlm323 @mmm202  Sorry for the delay Lauren and Matt--but I think GitHub came to the rescue, right? Are you both good? I'm going to take a look at your pages. 

To be clear, you want your main page for your website to be named **index.html** so that we can access your page from the web from your addresses here:
* Matt Burch: http://newtfire.org/~mjb232/  (Matt , the site is up and the picture is--very large! You can try changing the size with CSS...)
* Lauren McGuigan: http://newtfire.org/~lmm182/  (Lauren, a quick note on the content of your page: the certificate is Digital Studies Certificate.)
* Jessica Milewski: http://newtfire.org/~jlm323/  (Looks great, Jessica!)
* Megan Mills:  http://newtfire.org/~mmm202/  (There's no index.html page inside your public_html folder, but we found your site here: http://newtfire.org/~mmm202/Mills_XHTML1/Mills_XHTML1.xhtml and it's a good start for this assignment. We suggest you rename your page "index.html" and save it in the main directory space of your site. (Naming this assignment isn't quite the same as the ones you upload to Courseweb, because it's your webspace and you're moving in!) Try adding an image to your site...

Ideally, we won't even have to look inside your folder in the PSC (though of course we will)--because if everything is working right, your html and css will be functioning together. Good work here in clarifying the positioning of the `<link>` element that references your CSS. That *always* goes inside the `<head>` element, and that `<head>` element in HTML contains information about your site that tells its title and any associated stylesheets and JavaScript files that help it to run. Then the HTML code inside the `<body>` element is what shows as the content of your site.

**Comment by nlottig94** [comment]
* [Nicole's Webpage](newtfire.org/~lottig)
* [Brooke's Webpage](newtfire.org/~bstewart)
* [Rob's Webpage](newtfire.org/~spadafor)
* [Becca's Webpage](newtfire.org/~rjp43)

**Comment by nlottig94** [comment]
@laurenmcguigan @mjb232 @mmm202 @jlm323 I will be on campus all day today.  I'll try to stay in the Cassell Hall computer lab, but if I move, I will post on here.  I will be here until about 5:30pm or 6pm.  If you need any help with anything or if you just want to stop by and say hello, that's okay too!

**Comment by ebeshero** [comment]
Here are the newtFire sites for our returning students, some of whom are experimenting with CSS tricks!
Rob Spadafore: http://newtfire.org/~spadafor/  @spadafour 
Brooke Stewart: http://newtfire.org/~bstewart/  @brookestewart 
Nicole Lottig: http://newtfire.org/~lottig/    @nlottig94 
Becca Parker: http://newtfire.org/~rjp43/   @rCarls 
...and I'm adding one more, from a former just-graduated student, @amielnicki , who had lots of web design experience: He experimented a lot with CSS last fall, and we all learned a lot working together with him! http://newtfire.org/~mielnic/ 
 
Happy web designing and developing!
