### ISSUE TITLE
Webpage 2/10/16

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#137]
Does anyone know how to center an image in css? I know how to center to text, but not an image. Thanks!

**Comment by ebeshero** [comment]
@laurenmcguigan Off the top of my head (without looking it up, which is dangerous, so somebody check me), I think what I've done is set a margin property on it, so the margin is equal on the left and right. . .  
Here's a page from the w3 on how to center everything! There's a lot to look at here, because they cover vertical and horizontal centering: 
https://www.w3.org/Style/Examples/007/center.en.html

**Comment by nlottig94** [comment]
Here's what I found on W3Schools!  P.S. This website will give you answers to pretty much anything you want to know for HTML, CSS, and, later, JavaScript!  It has everything!!!!
http://www.w3schools.com/css/css_align.asp

**Comment by ebeshero** [comment]
@nlottig94 @laurenmcguigan Looks like you want to think of an `<img>` as a block level element, so centering it would be the same as how you'd center an h1 or h2...

**Comment by laurenmcguigan** [comment]
Thank you very much! just one more question. I know how to add external links, but how to I link to another webpage that I have created, for example, a resume?

**Comment by nlottig94** [comment]
@laurenmcguigan  You actually use the same method as adding external links, but your `@href` here will look more like you're linking to an image.  This is what the link to my curriculum vitae looks like in html:
![image](https://cloud.githubusercontent.com/assets/14095715/12925754/dd63eaae-cf2d-11e5-9d28-dd516a9a573f.png)

**Comment by laurenmcguigan** [comment]
@nlottig94 even if it is not a pdf? I am creating my resume in an xhtml document, do I just `href="resume"`?

**Comment by nlottig94** [comment]
@laurenmcguigan You'll need to state that you want your link to take you to that specific page, so technically it is an external link then!  Your code would look like this: `<a href="resume.xhtml">Resume</a>`

**Comment by ebeshero** [comment]
@nlottig94 @laurenmcguigan but please use .html file extensions on our newtfire site, or SSIs won't work!

**Comment by ebeshero** [comment]
Just save as .html (not .xhtml) please.

**Comment by laurenmcguigan** [comment]
@nlottig94 on your webpage, how did you get your image to align with your body?

**Comment by nlottig94** [comment]
@laurenmcguigan I used `padding` in CSS. If you right-click on my webpage, then click view source, then find my CSS linked at the top, you can see how it is used :)

**Comment by RJP43** [comment]
probably good idea to remind everyone ( @laurenmcguigan @mjb232 @mmm202 @jlm323 ) that for this assignment and future postings on newtFire where you are using SSIs you should use the file extension **.html** instead of .xhtml

**Comment by RJP43** [comment]
@laurenmcguigan here is a link to [W3SCHOOLS padding](http://www.w3schools.com/css/css_padding.asp). Hopefully this helps make sense of the different ways you can using padding.

**Comment by mjb232** [comment]
Hey! So nothing crazy, but if someone wanted to take a look at my page and give me some feedback that'd be suuuuuuper cool of you

**Comment by nlottig94** [comment]
@mjb232 I'm on it! It looks good!  I really like the colors!!  I have found a few typos though! 
1. Pitt in your pitt.edu probably shouldn't be capitalized.
2. You need a comma after Burch (My name is Matthew Burch, and I am...)
3. The 'U' in University of Pittsburgh at Greensburg should be capitalized.
4. Fellos students?
5. The 'L' in Blog shouldn't be capitalized, right?
Those are all the typos that I can see taking a look at it!  Overall, your site looks awesome!  Good job playing with the lines, borders, links, and lists!!

**Comment by ebeshero** [comment]
@mjb232 So, your resume is linked and you figured out how to upload it--all good--except it's in Microsoft Word. If you're not going to represent that in HTML, you may want to represent it in PDF format, which should be viewable in most browsers as well as printable. Ideally you'll make an HTML version of your resume and see what it's like to format that for web view! (It may look a lot different from your for-print version.)

There's actually a way to style HTML pages in CSS in two ways: for browser viewing AND for printing--so you really don't have to think of HTML as just about presentation in a browser window. To control CSS for printing, read all about it here: https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/

What's great about this is you can actually write CSS to optimize your pages for printing only what people are likely to need on an 8.5 x 11 sheet of paper (so you try to remove the clutter of images and such. You don't need to play with this now, but it's worth thinking about if you're building an HTML resume!
