### ISSUE TITLE
Some XPath tips!

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/DHClass-Hub#139]
I was running through the first exercise and came across a couple things that I think will help!

First, it often helps to tackle this in small steps. The first exercise sort of walks you through this, with first selecting the book, then the chapter, etc. It helps to start big and make sure you're on the right path (haha) before you try to go more in depth. This is also helpful when you're trying to figure out what's going wrong. If you're stuck, try going back to the start of your expression and go through what you're selecting one thing at a time. This way you can easily identify what step is causing trouble!

Second, I was trying to enter an XPath expression and I kept getting a message saying "XPath failed due to: Finding root of tree: the context item is absent" and it was getting pretty frustrating, until I realized that I had the wrong document selected - my text document was selected instead of the xml! So if this happens, make sure you have the right file selected first and try again. 

I hope this helps!

**Comment by nlottig94** [comment]
To add to what @brookestewart said, I would suggest writing down the number of results that came up in every one of your XPath searches because then if there is a mistake, it will be easier to figure out.
Happy XPath-ing everyone!!
