### ISSUE TITLE
Splash page for the Decameron project

### ISSUE THREAD

**Issue by mjb232** [ebeshero/DHClass-Hub#140]
So, I was wondering if it'd be ok if I just used "filler text" for parts of my splash page, since we don't really have anything concert to base the project off of.

**Comment by RJP43** [comment]
It might be a good idea to do a little research on Boccacio or the Decameron see if you can come up with a logical, small paragraph and a meaningful picture. Notice how on the main [homepage of the Nelson Project](http://nelson.newtfire.org/index.html) that there isn't much text. You could even just say this will be where a project on such and such will be. Simple is fine.

**Comment by ghbondar** [comment]
Regarding "filler text": for the last 500 years, there has actually been a tradition in typesetting of using a Latin quote from Cicero that begins "Lorem ipsum dolor" to fill a page with "nonsense" text, and this is still quite common. Check is out! http://www.lipsum.com/

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus lorem, aliquam id tempor quis, viverra ut odio. Pellentesque ultricies, ex sit amet auctor sodales, ex est hendrerit turpis, nec sagittis ex mauris ut magna. Pellentesque accumsan diam ut risus dictum, maximus suscipit ex tempor. Aenean eget tempus sapien. Nunc non nunc pharetra tellus tempus pretium. Quisque mattis quam a sagittis mollis. Praesent nec purus vel metus posuere venenatis a ut magna. Pellentesque turpis leo, lobortis sit amet enim ac, venenatis molestie ligula. Nam ultrices viverra quam, vitae finibus eros gravida id. Sed dictum enim vitae mauris pulvinar pellentesque. Nam pretium, eros vel lobortis rhoncus, sapien lacus vehicula urna, quis porttitor mi turpis et justo. Aliquam vitae urna nunc. Quisque finibus efficitur tempor. Nunc iaculis purus in vestibulum posuere. Quisque volutpat, nunc sed mattis ultrices, velit lacus lobortis eros, ac ullamcorper arcu metus nec tortor. Nunc auctor metus vitae consectetur placerat. Aenean eget semper purus. In lacinia sapien vitae felis pellentesque ultrices. Donec ornare leo et eros semper, eu consequat purus malesuada. Suspendisse potenti. Fusce sed felis turpis. Nunc quis faucibus arcu. Duis posuere ante sed pretium luctus. Duis volutpat faucibus eros, in luctus mauris condimentum nec. Ut sit amet mauris et eros lacinia malesuada. Sed in diam mauris. Integer placerat lectus id libero malesuada iaculis. Sed enim odio, dictum non velit vitae, pulvinar mattis nibh. Fusce efficitur sapien et viverra maximus. Phasellus laoreet vel leo ac ultricies. Praesent pharetra odio urna, quis finibus libero tempor vitae. Praesent ut justo est. Vivamus dignissim mi ultrices nisi lobortis posuere. In accumsan dolor vitae ipsum faucibus sagittis. Nunc in risus vel est facilisis fringilla id vel justo. Duis dapibus gravida dui cursus rutrum. Nulla ultricies elit sed felis ullamcorper varius. Suspendisse dapibus magna a dolor rutrum, sit amet finibus ligula accumsan. Sed sed eleifend mauris, in commodo dolor. Sed pulvinar, ligula fringilla sagittis finibus, neque quam aliquam quam, a vestibulum neque purus a sapien. Ut bibendum lacus lectus, semper tincidunt leo tempus lacinia. Ut non sem facilisis, pharetra sem quis, laoreet mauris. Quisque quis vulputate sem. Pellentesque nisi arcu, ultrices quis velit gravida, ultricies mollis lorem. Fusce eros quam, molestie eget velit at, placerat mollis sem. Fusce ultricies eros nunc, porta ultrices risus imperdiet vitae. Cras feugiat ipsum ullamcorper, ullamcorper urna ut, dictum metus. Nunc urna justo, porttitor ac rhoncus vitae, maximus eu ipsum. Sed eget dapibus felis. Nullam commodo a quam sit amet auctor. Nulla convallis dignissim tortor at pharetra. Sed at sem odio. Sed non velit semper, tincidunt leo eget, cursus urna. Vestibulum urna risus, tincidunt non felis et, dapibus pretium tellus. Etiam eleifend leo id erat gravida consequat. Donec elementum dolor vel luctus aliquam.

**Comment by RJP43** [comment]
There are several generators of lorem ipsum text 

Check these out to if you just want filler text.

http://baconipsum.com/

http://hipsum.co/

http://star-wars-ipsum.herokuapp.com/

http://slipsum.com/

**Comment by laurenmcguigan** [comment]
I don't know if anyone is even awake still, but is there any way we can push the splash page back until Monday. I have done a little work on it, but I still haven't finished our homework, and I wanted to study for the exam tomorrow, but with all my other homework I just haven't had time to but a lot of effort into it. I want a chance to make it look nice.

**Comment by mjb232** [comment]
I'm kind of with Lauren on this one, I've gotten as far as a banner and my xpath still needs doing

**Comment by setriplette** [comment]
Hi Decameron project,

This discussion reminds me that I told Dr. B I’d suggest some stories for you.

For tales of contact in the Mediterranean, start with 2.7, 2.9, and 10.9. Others that will fit your theme and give you things to map are 2.3, 2.4, 2.9, 5.1, 5.2.

I did some looking around and 3.10 is considered the most scandalous story in the Decameron (as I had guessed) and translators often expurgate large portions of it.

Good luck! Let me know if you want me to look over the website text when you eventually get it together.

Best,
Dr. T

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Feb 12, 2016, at 12:51 AM, Rebecca Parker <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm kind of with Lauren on this one, I've gotten as far as a banner and my xpath still needs doing

**Comment by ebeshero** [comment]
@setriplette Thanks! :+1: 
@laurenmcguigan @mjb232 and Decameronistas: sounds like you have at least some starter files for making splash pages, so that's fine for today--of course you can keep working on this. For today we want to orient you all to a good GitHub project workflow. Lots of what you do will be in progress like this, and you can take note here on your GitHub issues page of where you left off and what's remaining to do.
