### ISSUE TITLE
XPath Predicates, Axes, and Functions (2/12)

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/DHClass-Hub#143]
## Parenthesis in path steps:
Wrapping the whole expression in parenthesis gives a single result.

## Predicates and Axes:

- **Sibling axes**

     Siblings are used to step over to other sibling elements. 
     Following-sibling::* will return the following sibling, regardless of what the name of the element is.
     Following-sibling::placeName will return any placeName element that is a following sibling.

- **Preceding sibling vs. preceding**
     
     Preceding will go through the whole preceding document and return the any indicated nodes, regardless if they are siblings or not, whereas preceding-sibling will start where you are in the document and select only preceding siblings from that point. 

- **Self::axis and the dot (.)**

- **//pathstep[ ]**  

     //pathstep[something] and //pathstep[@something]

     //pathstep[.//something] vs. //pathstep[//something] and why the dot (.) is important!
     The dot (.) indicates self inside a predicate. It starts from your current location in the document and looks down from that point. 

- **//pathstep[ ][ ]**

- **//pathstep[something[ ]]**: nesting predicates!

## Functions
Positioning a function in a path step! How to do it; why it matters!
- **count()**   
     Turns up a plain text count of what is indicated. 
Notice the difference between positioning the function here `//stuff//p//count(placeName)` vs. here: `count(//stuff//p//placeName)`  
If you put the function at the *end* of a path step, say, to count all the placeName elements that are children of paragraph elements, and you have a document with 100 paragraphs, you'll get 100 separate counts of placeName, one for each instance of its parent context! If we want only one single total count of all the placeName elements in a document that are children of paragraphs, set count() to wrap around the whole entire XPath expression. 

- **not()**
     Turns up a node that does not contain the indicated condition.

- **distinct-values()**
     Turns up a list of plain text, eliminates any duplicates. 

- **matches()**  
Used to locate text strings that match something we're hunting for. (We could use matches() to help find the text content of an element or an attribute value.) Matches() is one of a set of XPath string-matching functions that takes two "arguments", like hunting for a needle in a haystack
1) the XPath location you're hunting in (the haystack), and 
2) the string you're searching, set in quotation marks ("the needle")
so it's often formatted with the dot (.) in a predicate like this:
//pathStep//pathStep[matches(., "string")]
This says, walk down the tree and stop at the element (or attribute) whose text value matches "string."

We demonstrated this in class to show how to use a function inside a predicate. So, for example, if we want to find all the placeName elements whose text content is "London"? We use the XPath matches() function, and if we want our XPath to land ONLY on those placeName elements that match the string "London" we set the function inside a predicate: 
 `//placeName[matches(., "London")]`

**Comment by ebeshero** [comment]
I've just added some detail to flesh out @brookestewart 's class notes here. Thanks for posting these, Brooke!
