### ISSUE TITLE
HTML Exercise 2 -- updated to include SSI

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#147]
Hello! I just wanted to let you know that I updated my page to include an ssi. If you go to the link to my page http://newtfire.org/~lmm182/index.html you will see the update. However, when you go to the page I added "theatre.html" you will notice that my ssi is included, but it does not follow the css rules from my home page. Can I just associate both the theatre.html  and the top.html with my css, or does my top.html have to have it's own internal stylesheet?

**Comment by RJP43** [comment]
Just associate both pages with your CSS and the styling should hold over for your SSI and both pages

**Comment by laurenmcguigan** [comment]
thank you!

**Comment by RJP43** [comment]
You don't need to add the CSS link to your SSI file because it will associate with whatever CSS is on the page the SSI sits on

**Comment by laurenmcguigan** [comment]
@RJP43 when I include the CSS in my theatre.html file, the SSI doesn't appear on the theatre page.

**Comment by laurenmcguigan** [comment]
here is my code for the SSI 
`<h1>Lauren McGuigan</h1>
<div id="links"> <a href="index.html"> Home </a> | <a href="https://www.linkedin.com/in/lauren-mcguigan-9aaa57111?trk=hp-identity-photo"
    >My LinkedIn Page</a>  |  <a href="https://laurenmcguigan.wordpress.com/"> My Blog</a> | <a href="Theatre.html">Theatre</a>
</div>`

**Comment by RJP43** [comment]
Interesting ... let me get my computer started and I will see if we can figure this out ... did you put all of your files on the server using your file transfer program?

**Comment by laurenmcguigan** [comment]
@RJP43 yes, they are all in my fetch file. Also here is the code for my theatre page 
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Theatre</title>
        <link rel="stylesheet" type="text/css" href="index.css" />
    </head>
    <body>
        
        <h2>Shows</h2>
        <ul>
            <li> Guys and Dolls (2013)</li>
            <li> A Very Potter Musical (2014)</li>
            <li> Chemical Imbalance (2015) </li>
            <li> Middle Town (2015) </li>
            <li> Man of la Mancha (2016) </li>
        </ul>
    </body>
</html>`

Maybe this will help you find the issue?

**Comment by laurenmcguigan** [comment]
@RJP43 WAIT!
I FIXED IT when I re-uploaded everything,  forgot to hit the execute boxes!

**Comment by RJP43** [comment]
@laurenmcguigan  Oh okay ... yes it is working now! GOOD JOB!
 
You could also replace the section on your index page with a different SSI that excludes the h1 if you think it is likely that you will want your links to appear on other pages without the main header.... like how you have it on your main page. What I am saying is you don't have to have just a single SSI.

**Comment by RJP43** [comment]
@mmm202 and @mjb232 ping us on here when you get your SSIs running. Make sure to check the permissions for each file you are running an SSI on!

--Happy Coding :)

**Comment by RJP43** [comment]
If you need help with SSIs feel free to ping us here as well... and of course reference our [SSI Tutorial](http://newtfire.org/dh/SSI.html)!

**Comment by RJP43** [comment]
Oh and this [link](https://httpd.apache.org/docs/2.4/howto/ssi.html) takes you to a page that shows you a lot of other really cool functions allowed by SSIs!

**Comment by jlm323** [comment]
I got my SSI to work! :)

**Comment by RJP43** [comment]
yes, Huzzah! Jess, I see your SSIs!

**Comment by RJP43** [comment]
@jlm323... your SSIs are working but it looks like you may have accidentally copied an extra folder into your account space ... check it out...
![jess](https://cloud.githubusercontent.com/assets/8645521/13097648/e5e7987e-d4f0-11e5-8a55-46e62dfed03e.jpg)

**Comment by jlm323** [comment]
Whoops! Thanks for pointing that out. I got rid of it!

**Comment by mmm202** [comment]
I finally had time to get my SSI to work, check it out!

**Comment by ebeshero** [comment]
Nice work, @mmm202! Looks great! :+1:
