### ISSUE TITLE
xpath 3

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#148]
are all the parent elements of the attribute @type supposed to be "div" or am I doing something wrong??

**Comment by laurenmcguigan** [comment]
I'm really confused with the parent elements. Could someone give an example of how to find one?

**Comment by laurenmcguigan** [comment]
Also, for 3a: Write an XPath expression to return all the attributes of any kind, anywhere in this file.

the expression I used was //@*
but this is returning all the values of the attributes, is this correct or am I looking up the wrong thing?

**Comment by RJP43** [comment]
Hi @laurenmcguigan... yes I am available tomorrow after class... a little clue for now thought some functions like name ()  can come after your XPath expression. So for let's say getting the names of all a certain kind of attribute think out the XPath ...  I want all off the attributes in the whole document (which by the way your expression looks good to me) and then you say ok give me the names `/name ()`

**Comment by RJP43** [comment]
Now as for parents of any given attribute you have to step all the way down to get the first thing so in this case the `@type` attribute then say ok XPath now give me the parent ... remember from github  we used ../ to get to the parent directory ... see if you can work with that clue to get to the parent axis ... or you could declare the parent axis with the double colon `parent::`

**Comment by RJP43** [comment]
I know it seems kinda silly but talking the XPath out really helps ...

**Comment by RJP43** [comment]
*also sorry for the typos ... I'm working off my cell phone and auto correct blows and mobile github won't let me edit comments ... I think you can get the jist though of what I am saying

**Comment by RJP43** [comment]
We can meet after class and I can help you :)

**Comment by RJP43** [comment]
@laurenmcguigan web development is cancelled ... so I have English Capstone class from 2:30-4 then I will likely be over in Cassell Hall till a 7:00 event I have to attend for digital storytelling. Let me know if you still want to meet up. Like I said I'm free and be happy to help you.

**Comment by laurenmcguigan** [comment]
@RJP43 I found the parent elements (I think) like this: 
`//@type/parent::*`
but when I try to do distinct values, either:
`//@type/distinct-values(parent::*)` or
`distinct-values(//@type/parent::*)`
my computer goes crazy.

**Comment by RJP43** [comment]
Okay try measing with your placement of the `*` and you might try also messing with the dot slash annotation for getting to the parent axis. 

What if you found all the `@type` first then asked for the parents instead of asking for all the parents of the `@type` 

I am not sure if I'm explaining this the best on here might be best to meet up ... or perhaps @ebeshero can clarify better?


Do you think you stikk would want to meet today after 4? I'm trying to setup my ride home from campus and I need to tell him an estimated time.

**Comment by laurenmcguigan** [comment]
@RJP43 I'm not sure.. I would like to, but the roads might be too bad for me to come out there. I'm still waiting to hear if my 2:30 class is cancelled.

**Comment by laurenmcguigan** [comment]
@RJP43 could you possibly just show me an example of how to use the parent:: axis without the * ?
Because XPath won't let me put nothing after a parent axis and I'm confused as to what is supposed to come after it

**Comment by laurenmcguigan** [comment]
@RJP43  wait I think I understand what you are saying about the dot. It looks like it is working now

**Comment by RJP43** [comment]
@laurenmcguigan huzzah!

**Comment by laurenmcguigan** [comment]
@RJP43 I think I am going to meet you in cassell at 4. Is that okay?

**Comment by RJP43** [comment]
Yes we can meet in front of the computer lab at 4.

**Comment by RJP43** [comment]
KmlLol

**Comment by mmm202** [comment]
Now, what if we wanted to find all the parent elements (without knowing what they are) of any attributes in use within the body element of the file? Write the XPath expression.
for this step I'm trying to do `//body/@*/name(parent::*)` but thats not returning anything. I tried messing with it but I'm just stuck now.

**Comment by nlottig94** [comment]
@mmm202 You are on the right path! Your `parent::*` is in the wrong place. Try moving it outside the `name()` function (you'll have to mess with it either before or after it) and see what you get.

**Comment by mmm202** [comment]
I moved it around but i'm still now getting anyting

**Comment by nlottig94** [comment]
@mmm202 Have you stepped down far enough into your `body` to find the `@*`? Right now what you have (`//body/@*/name(parent::*)`) says that you're only looking for the attributes on the body element. We want to find **all** of the attributes within any element in the body element..

**Comment by RJP43** [comment]
Some functions follow expressions without having anything inside of them. In this case `name ()` is like that... think of it like you are telling XPATH to give you all the attributes in body then step to the parents then give you the names of those parents. Each then in this past statement corresponds with a path step (`/`) and the name function sits empty `name ()`.

**Comment by RJP43** [comment]
And yes pay careful attention to how many slashes you have because one slash says it's a direct descendent (a child) whereas 2 slashes say anywhere on the descendent line (grabs both children and grandchildren)

**Comment by mmm202** [comment]
Write an XPath expression that returns the last paragraph in the ENTIRE Georg Forster file that contains more than one latitude record, coded as <geo select="lat">. 
for this step I can't remember how to do the greater than or less than

**Comment by nlottig94** [comment]
@mmm202 You can use the signs themselves here! `<` `>`

**Comment by mmm202** [comment]
//p/geo[@select="lat"]>1 
okay i tried this but that's not working

**Comment by nlottig94** [comment]
You will want to use the `count()` function within this one.

**Comment by RJP43** [comment]
Set up what is being counted and then set in accordance with the equation... like Nicole says you can use the `<` and `>` but like Dr. B. Recommended in class lt works for less than and gt works for greater than ge is greater than or equal to and le is less than or equal  to

**Comment by mmm202** [comment]
I don't understand where I would use the `count()` here

**Comment by RJP43** [comment]
Think of what it is that needs counted and put in relation to the `gt 1`

**Comment by RJP43** [comment]
Also be weary of whether you want a predicate statement `[ ]` versus a path step `/`

**Comment by mmm202** [comment]
`//p/count(geo[@select="lat"])ge 1`
I got to this but i'm still just stuck

**Comment by RJP43** [comment]
Talk yourself through this... if you want all the paragraphs that have a certain thing we use a predicate where as if you want the attributes them self you want to take the path step... so here we want all the paragraphs that have a count of geo lats greater than 1 ... does that help?

**Comment by mmm202** [comment]
No I still can't figure out any of number 3

**Comment by RJP43** [comment]
Ok so let's take it piece by piece to say you want a count of geo lats how would you write that?

**Comment by mmm202** [comment]
`count(geo[@select="lat])`

**Comment by RJP43** [comment]
right! now you want the paragraphs that have that count of geo lats greater than 1

**Comment by mmm202** [comment]
`p/count(geo[@select="lat])> 1`

**Comment by RJP43** [comment]
close but no... use a predicate instead... p that have this count of geo lats greater than 1 NOT p and then step down into the count of geo lats greater than 1

**Comment by RJP43** [comment]
just the like with the geo you are saying give me the geo that have `@select="lat"`

**Comment by RJP43** [comment]
you are very close!!!

**Comment by RJP43** [comment]
look back at our solution for part 1 of question 4 on the last assignment:

````Q4. Write an XPath to bring up all the paragraphs in this WHOLE file that contain both latitude AND longitude readings.

//p[geo[@select="lat"]][geo[@select="lon"]]````

**Comment by mmm202** [comment]
`//p[count(geo[@select="lat"])]`

**Comment by RJP43** [comment]
yes!!!! but you left out the gt than 1 which you had correctly placed above outside of the count but within the predicate... now you are say give me the paragraphs that have a count of geo lats just have to add that are greater than 1

**Comment by RJP43** [comment]
important where you place this because you still are saying what you want the p to have but you are setting your count of the geo lats in relation to the gt 1

**Comment by mmm202** [comment]
`//p[count(geo[@select="lat"])>1 ]`
this still gets me 32 results

**Comment by RJP43** [comment]
looks good ... now you need to say you want the last of those paragraphs

**Comment by mmm202** [comment]
`//p[count(geo[@select="lat"])>1 [last()] ]`
I can't even figure out where to put that

**Comment by RJP43** [comment]
Ok you want to keep what you had and really think about what I am saying when I say you want the last paragraph that has all of that ... sooooo lets just forget about all the extra stuff and get the last paragraph.... how would you do that ?

**Comment by mmm202** [comment]
`//p[last()][count(geo[@select="lat"])>1 ]`
I would think it would have to be by the p but I don't get any results

**Comment by RJP43** [comment]
lets just run what you have minus all the extra specifications on the p and just get the last p ... with what you have written above it seems you would want to say //p[last()] ... run that see what you get...
not the last p ... how could you modify that to get the last p ?

**Comment by mmm202** [comment]
I really don't know because I thought it said that was supposed to give you the last thing

**Comment by RJP43** [comment]
`//p[last()]` this gives you the last p that comes before the closing of whatever the p sits in ... if you grab the whole statement and say give me that last of it you will get what you are actually looking for.... so compare what `//p[last()]` gives you versus what (//p)[last()] gives you

**Comment by RJP43** [comment]
yea interesting I was just looking over the tutorial to try to tell you where to reference this and I see how it is rather confusing ... this might be a bug in the tutorial we need to address @ebeshero

**Comment by mmm202** [comment]
` (//p)[last()][count(geo[@select="lat"])>1 ]`
so what do I have I have to do now to get this to work

**Comment by RJP43** [comment]
did you run ` //p[last()]` versus `(//p)[last()]` ?

**Comment by mmm202** [comment]
it ended up getting the very last paragraph

**Comment by RJP43** [comment]
yes now remember the predicate regarding the count of geo lats greater than 1 needs to be a part of the paragraph that you want the last one of... you aren't saying give me the last paragraph you are saying give me the last paragraph that has all of that specification

**Comment by mmm202** [comment]
` (//p)[count(geo[@select="lat"])>1 ][last()]`

**Comment by RJP43** [comment]
not quite... you want to group the p and everything specific about the p together so then you can say you want the last p that has all of that

**Comment by RJP43** [comment]
so if I want the last paragraph that has a geo lat ... I would say `(//p[geo[@select="lat"]])[last()]`

**Comment by ebeshero** [comment]
Okay--this is a little belated for the conversation, but @laurenmcguigan and @RJP43 you may have figured this out already! When you take distinct-values() on your expression `distinct-values(//@type/parent::*)` you're going to get ENTIRE div elements which are HUGE...and it doesn't make sense to take distinct-values() over those. But it *does* make sense to take distinct-values of the *names* of those elements. So if you used the name() function to retrieve those names, as we asked in the previous step in number 1, the idea is to get the distinct-values of the *names* of the elements.

And yes, we should probably clarify that in the assignment--I'll call it a bugfix! Hope you figured this out!

**Comment by RJP43** [comment]
so  `(//p)[count(geo) gt 1][last()]` would of worked like `(//p[count(geo) gt 1][last()]0[last()]` @mmm202 sorry you were right!
