### ISSUE TITLE
xpath 4

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#149]
I'm confused as to what number 1 in the homework is asking us to do.

**Comment by laurenmcguigan** [comment]
@RJP43 can you meet Matt and I in fireside lounge?

**Comment by RJP43** [comment]
@laurenmcguigan I just left campus, but I am available if you want to call me or we can work over github ... I'm sorry I figured no one wanted to me so I left ... as for XPath Exercise 4 question 1 we are looking for you to provide us with the function that creates a list of the authors separated with a semi-colon (hint: we reviewed this function on Wed. except we modeled it with a comma)

**Comment by RJP43** [comment]
*meet

**Comment by RJP43** [comment]
Show us the XPATH expression using the function that grabs both authors and places them in a list separated by semi-colons

**Comment by laurenmcguigan** [comment]
so do we use string-join for that?

**Comment by RJP43** [comment]
Bingo!

**Comment by laurenmcguigan** [comment]
Another question. This is for 3B. So It wants me to find all the Fridays in the document but return it in ISO format. Right now my code looks like this:
`//date[@when][contains(.,"F")][matches(.,"\d")]`
it is still returning all the Friday dates but not in ISO format

**Comment by RJP43** [comment]
Pay attention to the hint on the assignment.

**Comment by laurenmcguigan** [comment]
is it something with the matches function that I am doing wrong? or is everything I have okay except I need to add an attribute value?

**Comment by mjb232** [comment]
is this right for 3b (the thing Lauren was working on)?
`//date [contains(.,"F ")]/@when [matches(.,"2015")]`

**Comment by RJP43** [comment]
I mean that looks more right ... but I don't have my laptop open because I'm on my way to home still. Are you getting the Friday dates in ISO form? I imagine you are since yes the the when attribute is the key to getting the ISO format

**Comment by laurenmcguigan** [comment]
I think we got it! now I have a question about 4 b. Finding the min and max values. Im confused about how to use them. It says the work the same as count, but when I wrap the whole thing in min and max it is coming up as an error.

**Comment by ebeshero** [comment]
@laurenmcguigan Hi Lauren! For min() or max() to work, they need to be run over numbers...To determine the longest `<div>` element you need to get a numerical result for all of them--you want to read their string-length() first, and then take the max() of that to get the longest!

**Comment by mjb232** [comment]
Figured out 4b! Thanks @ebeshero!

**Comment by mjb232** [comment]
Ok, now Im stuck on 5b (I'm trying to only get Fridays from my format-date). So far I have:
`//@when /count(format-date(xs:date(.),'[FNn]'))[contains(.,"Friday")]`
I think I have all the pieces buuuuuuuuuut not in the right order. Help!

**Comment by ebeshero** [comment]
Hmmm...So why would a count() of something contain a "Friday"?

**Comment by mjb232** [comment]
ohhhhhhhhhhh for some reason I read "contains" as "counts". let me mess around with this

**Comment by mjb232** [comment]
Alright this is what I have:
`//@when /contains(.,format-date(xs:date(.),'[FNn]'))`
So, I put the contains around the format-date like the homework said, but Im not exactly sure why. Also I know I need a predicate somewhere in here, but also not sure why. Maybe if some one explained the contains a little better? For instance I keep writing contains as:
`contains(.,"TEXT")` 
but what does the dot actually do?

**Comment by ebeshero** [comment]
So...contains() is a function (whose cousin is matches()). We pretty much use these inside predicates--think about why! You use the function to find out whether something *contains* something you're looking for. (So we use contains() to find out which placeName elements contain the string "London"--that's gotta be in a predicate). 

So, think about your placement of the function in terms of *what it does.* Wouldn't it make more sense to use the format-date() function in a step after @when? Think about it: @when gives you a date in numbers. If you wanted to *display* the date in the results window in a different format, you'd format-date() in a next step: '//@when/@format-date(xs:date(.), '[FNn]')) or `//date/format-date(xs:date(@when), '[FNn]')` 
See how that's a different kind of thing going on? The function `format-date()` makes a conversion of one kind of string to another. The function `contains()` does something very different: it *checks to see* if something you designate *contains* something. 

Hope this helps!

**Comment by mjb232** [comment]
@ebeshero Got my answer! Thanks!!!!

**Comment by ebeshero** [comment]
Yay! :+1:
