### ISSUE TITLE
schematron 1

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#150]
`<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"
    xmlns:sqf="http://www.schematron-quickfix.com/validator/process"
    xmlns="http://purl.oclc.org/dsdl/schematron">
    <ns uri="http://www.tei-c.org/ns/1.0" prefix="tei"/>

    <pattern>
        <rule context="tei:results/place[@name][preceding-sibling::tei:results/place[@name]">
            <assert test="">
                
            </assert>
        </rule>

    </pattern>

</schema>`

am I doing this right so far?

**Comment by mjb232** [comment]
This might be a dumb question, but the xml file we are working with is just the one we copied and pasted from the exercise, correct? If so, is that example TEI? And if it is how do we tell?

**Comment by mjb232** [comment]
@laurenmcguigan so the context for your `<rule>` should essentially be the xpath to get to whatever you want to change. One way of checking to make sure that your context is selecting the right information is to translate it into an xpath and use it on your xml file. When I did this for your schematron I didnt get any returns. Also, i think all of your elements should have tei: in front of it, even your `<place>` element.

**Comment by mjb232** [comment]
So this is what I have. Just for experimental purposes I'm just trying to say that I want all my `<place @name>` to be less than 100 buuuuuuuut nothing is happening. Help? 
@ebeshero @RJP43 @nlottig94 
`<schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"
    xmlns:sqf="http://www.schematron-quickfix.com/validator/process"
    xmlns="http://purl.oclc.org/dsdl/schematron">
    <ns uri="http://www.tei-c.org/ns/1.0" prefix="tei"/>
<pattern>
    <rule context="tei:results">
        <assert test="number(tei:place[@name] lt number(100)">
            All percentages together must total 100
        </assert>
    </rule>
</pattern>
</schema>`

**Comment by nlottig94** [comment]
Matt, try to use the count() function rather than the number() function.  Tell me what that does.

**Comment by mjb232** [comment]
so I turned it into
`<assert test="count(tei:place[@name])lt number(100)">`
but I'm still not getting any results. Is this still an issue of my `<assert>` or could it be the context of my rule, which is:
`<rule context="tei:results">`

**Comment by nlottig94** [comment]
I think it's your `<assert>`.  I think it's because you have 100 also wrapped in the number () function.  Your XPath already knows that 100 in a numerical value.  We really only need to use the number() function when you're turning a string of characters into a number. See what I mean?

**Comment by mjb232** [comment]
Ok, I see how to use number but I wrapped 100 in count as well but nothing happened. Does 100 need a function?

**Comment by nlottig94** [comment]
No, your 100 should not need a function at all.

**Comment by mjb232** [comment]
Hmmmmm this didnt work either 
`<assert test="count(tei:place[@name])lt 100">`

**Comment by nlottig94** [comment]
Okay, Matt, I have figured out what's wrong!  So think of this like a math equation.  You want all of the place elements (added together) to be less than 100.  Here is where you may want to look up the sum() function...just a suggestion.

**Comment by mjb232** [comment]
oh snap theres a sum function???? Dope. Ok so I'm going to try and set the sum equal to 100, so to do that I need to find each instance of `<place [@name]>` and put them inside of the sum() and then set that equal to 100. right?

**Comment by nlottig94** [comment]
You may be able to just put `place[@name]` in the sum() function.  Or you could just try adding all of the specific `@name="..."` (...+...+...=100) and doing it that way.

**Comment by mjb232** [comment]
I've got it down to this, but still nothing 
` <assert test="sum(place[@name])eq 100">`

**Comment by nlottig94** [comment]
Matt!  I've got it!  This document isn't in TEI!  So don't use `tei:results` in your @context or anywhere else! :)

**Comment by mjb232** [comment]
ah ha! That worked! I had a feeling it wasnt tei, but no one responded to my question about it earlier so I just thought i was dumb haha. ok, awesome! I'm all good now, thanks!

**Comment by nlottig94** [comment]
Sorry!  It just clicked in my head! And then I went back and looked at what you first put. Good job figuring it out!!

**Comment by ebeshero** [comment]
@mjb232 @laurenmcguigan @mmm202 @jlm323 Hey everyone! I think you may have figured this out, but our source XML for Schematron Exercise 1 is *not* TEI. Matt, I'm glad you asked how you can tell whether an XML is in TEI or some other namespace. The answer is, a namespace is declared in an xmlns attribute on the root node, *and* a TEI file's root node is always named `<tei>`.

TEI comes with a special Relax NG schema, which governs its "grammatical" structure (the organization of its elements and attributes in a set hierarchy) and that schema is applied by TEI project writers--You can actually open a TEI document in oXygen, and it comes front-loaded with its own schema lines. And we constrain TEI for specific project needs using Schematron. For the kinds of XML you write yourself (like the one in our assignment) you write your own Relax NG *and* Schematron too. Hope that helps! No namespace prefixes are needed for *this* assignment. But when I wrote Schematron for our class on my TEI syllabus, I needed the special '<ns uri="TEI stuff...">` and tei:prefixes on all the elements but not the attributes.

**Comment by laurenmcguigan** [comment]
okay, so I have bee trying to use this ` <assert test="number(place[@name]) gt 0"></assert>` to say that the numbers of the votes have to be between 0 and 100. But I can not go any further, because oxygen is saying that you can't use the number function for an element where there is more that one of it. So, it is not working because there is more than one place[name]. So my question is, am I using the wrong function, or do I need to add something to my test attribute?

**Comment by nlottig94** [comment]
@laurenmcguigan Try using a function other than the number() function.  Go back through the conversation here and look what Matt figured out.
