### ISSUE TITLE
schematron 2

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#152]
This is what I have for number 1 on the homework

`    <rule context="tei:app">
        <report test="not(tei:rdg/@wit)" >`
            

do I have something wrong in the context or the test?

**Comment by ebeshero** [comment]
@laurenmcguigan We're not seeing the whole elements here, but it looks right for referencing the TEI elements. Did you write a message to display when your rule fires?

**Comment by laurenmcguigan** [comment]
@ebeshero  no, but nothing is firing when I change the attribute name.  Here is the whole thing:

`<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"
    xmlns:sqf="http://www.schematron-quickfix.com/validator/process"
    xmlns="http://purl.oclc.org/dsdl/schematron">
    <ns uri="http://www.tei-c.org/ns/1.0" prefix="tei"/>
    <pattern>
    <rule context="tei:app">
        <report test="not(tei:rdg[@wit])">
             </report>
    </rule>
</pattern>
</schema>`

**Comment by ebeshero** [comment]
@laurenmcguigan This may seem really obvious but...did you associate your schema with the XML file? ans is your schema file saved in the same place as when you associated it? Just make sure your schema association line is present...

**Comment by ebeshero** [comment]
@laurenmcguigan What you've written seems right to me: Your rule says, look at an `app` element, and then test to see if there is *not* a child rdg element with an `@wit` attribute. I'd maybe want to set the context on `rdg`, and just test on the attribute itself, since that would help us spot the immediate places where the `@wit` is missing. And maybe you need to write the alert message so it's visible when it fires...

**Comment by laurenmcguigan** [comment]
I figured it out!!! What I had before was incorrect, I got it now!!!

**Comment by ebeshero** [comment]
Yay! Good! I stopped short of actually testing your code last night, so I'm glad you figured it out! :+1:

**Comment by mjb232** [comment]
So for number three I have this:
` <rule context="tei:head/tei:title [following::tei:head/tei:title]">
            <assert test="number(substring(.,6,2))[+1]"></assert>`
buuuuuuuuut I can't get it to fire. Am I on the right track? Is this a text issue or a context issue?

**Comment by laurenmcguigan** [comment]
`
    <pattern>

        <rule context="tei:rdg">
            <report test="not(.[@wit])"> element rdg can not have an attribute other than wit
            </report>
        </rule>

        <rule context="tei:app">
            <assert test="count(tei:rdg) ge 1"> element app must contain at least one element rdg
            </assert>
        </rule>
    </pattern>
    
    <pattern>
        <rule context="tei:div[@type = 'poem']/tei:head/tei:title">
            <assert test="following::tei:title[number(substring(., 6, 2)[+1])]"> </assert>
        </rule>
    </pattern>

</schema>`


This is what I have so far, my file is associated but nothing is firing... HELP!

**Comment by jlm323** [comment]
It fires for me when I change the number I want to start from. I picked 3 and it seems to work. When I changed it to 6 like @mjb232 and @laurenmcguigan it doesn't work. But I'm not really sure if I'm doing it right either.

`
<pattern>
        <rule context="tei:head/tei:title [following::tei:title]">
            <assert test="number(substring(., 3, 2)) [+1]">
                Poems must be in chronological order.
            </assert>
        </rule>
    </pattern>
`

**Comment by nlottig94** [comment]
@laurenmcguigan @mjb232 @jlm323 I see one BIG problem that you all three seem to be having! Your `+1` should NOT be in square brackets! Square brackets mean a predicate. What would `+1` be doing in a predicate? Think about it. We don't want a predicate; we want something that looks like a math equation, and math equations only use square brackets when the equation is _super_ complex.

**Comment by ebeshero** [comment]
@laurenmcguigan @mjb232 @jlm323 Think about what you're setting up in your test: 
(SOME NUMERICAL VALUE + 1) EQUALS (SOME OTHER VALUE)

**Comment by jlm323** [comment]
I think it's working now... I changed it to this:

`
<rule context="tei:head/tei:title [following::tei:title]">
            <assert test="number(substring(., 6, 2)) +1 eq following::poem">
                Poems must be in chronological order.
            </assert>
        </rule>
`

**Comment by nlottig94** [comment]
@jlm323 Is your rule firing?

**Comment by jlm323** [comment]
Yes, I got errors on each poem title.

**Comment by nlottig94** [comment]
You should not be getting errors on every title though... I think it has to do with your `following::poem`. Think about what _element_ we want to be there.

**Comment by mjb232** [comment]
Well, its not `number(substring(.,6,2))+1 eq tei:title`

**Comment by nlottig94** [comment]
@mjb232 Try to put `following::` in front of your `tei:title` and see what happens.

**Comment by mjb232** [comment]
an error comes up that says:
Severity: fatal
Description: A sequence of more than one item is not allowed as the second operand of 'eq'

**Comment by ebeshero** [comment]
@mjb232 Sound familiar from class on Monday? Think about why you'd be getting a **sequence** error like that...
Very simply: You are testing to check *each* poem title in turn and make sure its **number** is equal to the **number** inside the **next following** poem title.

**Comment by nlottig94** [comment]
Okay @mjb232, think about what we want the first part of our equation to be equal to: the first _following_ `tei:title` that has equals the same `substring()`..........

**Comment by ebeshero** [comment]
Also, if you skim through the XML file you're testing (have a look in Outline view) notice which poems should be triggering an error. We set this up so there would be just a couple, I think.

**Comment by nlottig94** [comment]
@ebeshero Yes, I think just one should be out of order.

**Comment by mjb232** [comment]
Ok, so this is a test issue and my context is fine?
` <rule context="tei:head/tei:title [following::tei:title]">`
I just want to make sure im looking in the right place

**Comment by ebeshero** [comment]
It's an issue with your @test, yes.

**Comment by spadafour** [comment]
@ebeshero I think the upload point for schematron 2 is missing (I don't see one). Anyone else not seeing it?

**Comment by laurenmcguigan** [comment]
`<pattern>
        <rule context="tei:head/tei:title [following::tei:title]">
            <assert test="number(substring(., 6, 2))+1"> </assert>
        </rule>
        <rule context="tei:title">
            <assert test="(.) eq following::tei:title">
                 </assert>
        </rule>
    </pattern>`
can someone tell me if I am on the right track here?

**Comment by ebeshero** [comment]
@spadafour just posted the upload point--thanks for the heads up!
@laurenmcguigan You don't need two separate tests for this. In order for **eq** to work it needs to evaluate two numbers.

Think about WHY you are adding +1 to the number you located in the current title. What's that for?

**Comment by laurenmcguigan** [comment]
@ebeshero you are saying that the following title is the number of the previous plus one, so do you just have to add another following:: so it evaluates two?

**Comment by ebeshero** [comment]
@laurenmcguigan You'd reach over to the following:: title to evaluate something in it...(in the same test)

**Comment by ebeshero** [comment]
You know, you could do it the other way around, using the preceding:: axis and subtracting 1..,

**Comment by ebeshero** [comment]
...or do it just as we've set it here: the number in the current title should be equal to the following one - 1

**Comment by laurenmcguigan** [comment]
I'm so confused

**Comment by laurenmcguigan** [comment]
I changed it to this: 
`<rule context="tei:head/tei:title [following::tei:title]">
            <assert test="number(substring(., 6, 2))+1 eq following::tei:title[number(substring(.,6,2))]"> </assert>
        </rule>`
but it still isnt working

**Comment by ebeshero** [comment]
@laurenmcguigan You're close! Your second expression is the title itself, (a string of text) that happens to *have* a number inside. So it doesn't compare as a number to the first expression.

**Comment by ebeshero** [comment]
@laurenmcguigan hint: Do you really want that number to be inside a predicate?

**Comment by laurenmcguigan** [comment]
@ebeshero so do I not need number at all?

**Comment by laurenmcguigan** [comment]
`test="number(substring(., 6, 2)) + 1 eq following::tei:title/(substring(., 6, 2))">`

like this or

` test="number(substring(., 6, 2)) + 1 eq following::tei:title/number(substring(., 6, 2))">`

**Comment by laurenmcguigan** [comment]
neither of these are working it is still saying that a sequence of more than one item is not allowed after eq

**Comment by ebeshero** [comment]
@laurenmcguigan No--you *do* definitely need a number. And you need to be checking on just the very first following title.

**Comment by ebeshero** [comment]
Your test basically needs to check and make sure that the following is true:
Current Number + 1 = Next Number

**Comment by laurenmcguigan** [comment]
`test="number(substring(., 6, 2)) + 1 eq following::tei:title/number(substring(., 6, 2)) [1]">` like this?

**Comment by ebeshero** [comment]
Close! Is it working? I think you may need to move that [1]. You want the first title element on the following axis..

**Comment by laurenmcguigan** [comment]
`test="number(substring(., 6, 2)) + 1 eq (following::tei:title)[1]/number(substring(., 6, 2))">` ???

**Comment by ebeshero** [comment]
@laurenmcguigan Is it working? I think you don't need the parentheses around following::tei:title[1] . But I doubt they are doing any harm...

**Comment by laurenmcguigan** [comment]
@ebeshero yes, I think I got it! Thank you!

**Comment by ebeshero** [comment]
Huzzah! :+1:
