### ISSUE TITLE
XSLT-1

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#153]
Is anyone else having problems when you try to run the xslt? I don't know if it's my computer or what but every time I try to run it, the program freezes.

**Comment by RJP43** [comment]
In the top right of the XSLT view under where you select the XML source make sure you change from Saxon to Saxon-PE

![saxon](https://cloud.githubusercontent.com/assets/8645521/13306546/8e190d10-db32-11e5-831a-11f5994eb8f8.PNG)

**CHANGE IT**

![saxon-pe](https://cloud.githubusercontent.com/assets/8645521/13306550/94ff3730-db32-11e5-85e7-1492e54556aa.PNG)

**Comment by RJP43** [comment]
@mmm202 Does that help?

**Comment by RJP43** [comment]
@mmm202 you might also try closing oXygen and reopening

**Comment by mmm202** [comment]
Nope its still freezing

**Comment by mmm202** [comment]
I closed oXygen multiple times and restarted my computer and nothing seems to be working.

**Comment by RJP43** [comment]
Are you on campus or working from home?

**Comment by RJP43** [comment]
I don't think this would matter too much but did you update your license?

**Comment by mmm202** [comment]
I'm at home and I did the update already

**Comment by mmm202** [comment]
Should I just wait till tomorrow and try using a computer on campus?

**Comment by RJP43** [comment]
Okay ... I was using XSLT earlier today without any issues here on a lab computer so you could save what you have and bring it in tomorrow and try to complete it using a lab computer. I wanted to review with you everything we went over class tomorrow after web development if you have time. And we can test out your XSLT on a lab computer then if you don't have time to do so before hand.

**Comment by mmm202** [comment]
I have a class right after that one so I just have a couple minutes and yes sorry my mom had surgery today and I ended up having to take her.

**Comment by RJP43** [comment]
Oh man I hope everything is okay. We can catch up before class on Friday then. Just ping us on here as you encounter problems with your first XSLT. Or we are having a coding event in Village 118 tomorrow from 11-1:00 if you are free after that we could catch you up then too. Otherwise like I said Friday before class works. Make sure you check out the Decameron issues board we are all supposed to review Day 1 and make some conclusions about the structure of the document and what we want to mark up.

**Comment by RJP43** [comment]
@ebeshero any other suggestions to troubleshoot @mmm202 oXygen issue?

**Comment by ebeshero** [comment]
@mmm202 @RJP43 I'd need more information about what's happening. Can you tell how much available memory you have on your computer? 
Here's a really simple question: Can you run the identity transformation line by itself, without writing any template matches? Go ahead and paste in your code, or push your code here to DHClass-Hub. Could be the code you're writing--might be generating an infinite processing loop! Not sure without seeing it.

**Comment by mmm202** [comment]
I started by just trying the identity transformation line and I didn't work and then tried writing something else and it still freezes and I lost the code I had because the program froze and I had to restart my computer so at this point I think it is my computer

**Comment by ebeshero** [comment]
@mmm202 Yeah, it might be that, *and* you probably need to set the parser to Saxon PE (see Becca's screen shot above). (With the other parser set, you'll get an error, I know that.) Try restarting your computer and oXygen, and rewrite the code--and come back here with it, okay?

**Comment by mmm202** [comment]
I used the computers on campus and now I'm not having a problem with it freezing

**Comment by laurenmcguigan** [comment]
For number 4 on the homework, for the chapters, do you want them to be counted collectively, or do you want the numbers to start from n=1 for a new book?

**Comment by laurenmcguigan** [comment]
Also, how do you save your output?? @RJP43 @ebeshero

**Comment by mmm202** [comment]
When I try clicking the AVT tutorial, it says the webpage is unavailable can some just send the link to me?

**Comment by jlm323** [comment]
[Here's the AVT tutorial](http://dh.obdurodon.org/avt.xhtml)

Does that link work?

**Comment by mmm202** [comment]
Yes thank you!

**Comment by ebeshero** [comment]
@laurenmcguigan Great question about the chapter numbering! You could do it either way, really, but I think it makes the most sense to count within the books, so the counting starts over with each book. It's the difference between using preceding:: vs. preceding-sibling:: in your count().

To save, you can right-click in the output window, and select Save as, and be sure to give your file a name and an appropriate file extension (in this case, .xml). You can also plug in the filename and extension in the output window to the right of the transformation arrows.
