### ISSUE TITLE
Coding Session Tonight

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#160]
@mjb232 @laurenmcguigan @mmm202 @jlm323 
For anyone who wants help with the homework, I'll be hanging out in Village Hall room 122 for anyone who wants to stop by. I'll be there starting at 5:30.

**Comment by ebeshero** [comment]
Thanks for hosting that, @spadafour!

**Comment by ghbondar** [comment]
Great idea, @spadafour ! Thanks for helping!

**Comment by ebeshero** [comment]
All--I've posted a much improved XQuery introduction (refresh your browsers). The first assignment will go up shortly too.

**Comment by ebeshero** [comment]
http://newtfire.org/dh/explainXQuery.html
