### ISSUE TITLE
FLWOR in XQuery

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#162]
So I was able to do the entire assignment through XPath, but I'm not understanding how to work with variables over an entire collection. I understand how to set up variables and call them, but I cannot get output that represents ONLY one thing (it'll always just output everything from the collection). How do I limit my results?

Here is a sample of something smaller; I'm just trying to output a count of the distinct speaker tags in a given document:

````
let $shakes := collection('/db/shakespeare/plays')
let $play := $shakes/*
let $speaker := $play//SPEAKER
let $countSpeaker := count(distinct-values($speaker))

return $countSpeaker
````

The result is 109, meaning that XQuery is adding every single distinct value of speaker in the collection. My guess would be to add some kind of for statement in, but I'm not sure. The examples in the tutorial do not show work with collections, only single files. Should we be creating a new variable for every play in the collection? Or should we be implementing 'for'?

**Comment by ebeshero** [comment]
@spadafour Sorry for the delayed response! No you do not need a special variable for every play, but you have noticed something significant about how XQuery works. Your line
````
let $play := $shakes/*
````

**Comment by ebeshero** [comment]
@spadafour Okay, here's an example of how to return one document from a collection. I'll add it to the tutorial today when I get a minute! 

````
declare default element namespace "http://www.tei-c.org/ns/1.0";
let $pacific := collection('/db/pacific/voyages')/*
let $GeorgFile := $pacific[.//author[contains(., 'Georg')]]//titleStmt/title
return $GeorgFile
````

**Comment by laurenmcguigan** [comment]
````
let $shakes := collection('/db/shakespeare/plays')
let $play := $shakes/PLAY
let $speaker := $play//SPEAKER
let $countSpeaker := count(distinct-values($speaker))
where $countSpeaker gt 40
return $play
````
I'm still returning all three plays. can someone tell me what I am doing wrong? Do I need to add a "for" statement?

**Comment by ebeshero** [comment]
@laurenmcguigan Good thinking! Your diagnosis is correct: You can solve the problem with a "For" statement--yes! Here's why you're still getting all three plays: Your $speaker variable is hunting up ALL the speakers in *all three* plays because XQuery isn't just looking at each play one by one. If you add a "For" statement, and define a **range variable**, say, like this: 
`For $p in $play` 
You'll then be able to run your XQuery from inside what we call the "For" loop: It'll evaluate your statements for each $p (or single play) in turn, and you will want to define your `$speaker` variable from the context of the range variable, `$p` (or whatever you decide to call it)!

Give it a whirl and let us know how it goes!

**Comment by laurenmcguigan** [comment]
got it! thank you @ebeshero

**Comment by laurenmcguigan** [comment]
Also, I am a little confused on how to use tokenize. My last line looks like this:

`return $p/TITLE/base-uri()/tokenize(., )`

 But I am not sure what to put after the comma inside tokenize. I have tried a few thinks but nothing has worked. Should there not be a dot there? or am I doing something wrong with the order?

**Comment by laurenmcguigan** [comment]
so I tried this:
`return $p/TITLE/base-uri()[tokenize('.','/s+')][last()]`

but it is still returning the whole string

**Comment by ebeshero** [comment]
@laurenmcguigan Hint: Think about what you're doing with a predicate expression. What's a predicate for? Don't you want to *actively* create tokens, instead of passively describing something *that can be tokenized*?

**Comment by laurenmcguigan** [comment]
@ebeshero when I do it like this:
`return $p/TITLE/base-uri()/tokenize('.','\s+')[last()]`

I get an error

**Comment by ebeshero** [comment]
@laurenmcguigan Look at the regex you're using to split the string into tokens. What character do you *want* to split on?

**Comment by ebeshero** [comment]
@laurenmcguigan The construction is better! :+1: Just get the token-splitter down!

**Comment by laurenmcguigan** [comment]
@ebeshero I want to split on a slash like this:
`return $p/TITLE/base-uri()/tokenize('.','/')[last()]`
but I am still getting an error saying "left operand of "/" must be a node"

**Comment by ebeshero** [comment]
@laurenmcguigan Good...the error is because the forward slash is a special XPath character...so you need to escape it...

**Comment by ebeshero** [comment]
@laurenmcguigan Let me just test that and make sure...

**Comment by ebeshero** [comment]
@laurenmcguigan Hmmm.. I don't have to escape the forward slash in my tokenize expression, but I also wrote mine a little differently than you did... The problem isn't actually the forward slash character, because you've got it properly in quotation marks--that's okay. I guess the problem is that you've positioned tokenize() just after base-uri(), and you need to just put the XPath directly IN the function. SO instead of the dot (.), try *wrapping* your XPath expression in tokenize!

**Comment by laurenmcguigan** [comment]
@ebeshero YES! that worked. It didn't like me using the dot (.) Thank you!!

**Comment by ebeshero** [comment]
@laurenmcguigan Good! Let's think about why it didn't like the dot(.): Dot (.) is supposed to be self::* node and it's intended to be an element or attribute result! So if you land on something that is a text *result* of an XPath function--it's a calculation rather than an element or attribute node...and so if we want to do a function *on* a function, we have to wrap one function inside the other!

**Comment by mmm202** [comment]
```let $shakes := collection('/db/shakespeare/plays')
let $play := $shakes/PLAY
let $speaker := $play//SPEAKER
let $countSpeaker := count(distinct-values($speaker))

where $countSpeaker gt 40
return $play
```
I think i'm stuck where @laurenmcguigan was but I can't figure out the "for" statement.

**Comment by mmm202** [comment]
I think i'm stuck where @laurenmcguigan was but I can't figure out the "for" statement. 

`let $shakes := collection('/db/shakespeare/plays')
let $play := $shakes/PLAY
let $speaker := $play//SPEAKER
let $countSpeaker := count(distinct-values($speaker))

where $countSpeaker gt 40
return $play`

**Comment by ebeshero** [comment]
@mmm202 You are probably returning all three plays in the collection, just as @laurenmcguigan and @spadafour were. Your $play is really all three plays at once. So you need a way to look at just *one* play at a time, and do your count of distinct values inside each one. To do that you can use a "For" statement to set up what we call a *range variable*: This basically takes something multiple and looks at each part of it in turn. You write a range variable in this format:

`For $p in $play`

(You can call the first variable--the range variable--anything you like, but the understanding is that it is each singular piece of something plural.) After you set that variable you can use it to determine *which* $p is the one where the count of distinct speakers is greater than 40.

**Comment by mmm202** [comment]
i am still confused because it is returning 9 items now

**Comment by ebeshero** [comment]
@mmm202 post your code?

**Comment by mmm202** [comment]
`let $shakes := collection('/db/shakespeare/plays')
let $play := $shakes/PLAY
let $speaker := $play//SPEAKER
let $countSpeaker := count(distinct-values($speaker))
for $p in $play
where $countSpeaker gt 40
return $play`

**Comment by mjb232** [comment]
I know this is just an xpath issue but Im having trouble returning the PLAY that contains more than 40 SPEAKERS. So far I have: 
`collection('/db/shakespeare/plays')//PLAY[distinct-values(count(//SPEAKER) gt 40)]/TITLE`

**Comment by RJP43** [comment]
@mmm202 work each variable at a time and I think you will be able to work out your own issue here. What I mean is run a singe line like your `let $shakes := collection('/db/shakespeare/plays')` and then return `$shakes` ... when you are returning your speaker variable are you asking for each play `$p` or are you asking for them all $play. Be careful not to get caught up in your own variables. It might be easier to first right it out as an Xpath expression linked to just a single variable and then work you variables back in. Either way running each segment of code and comparing what each variable declaration returns would be a good exercise to try to debug. Hope this helps.

**Comment by RJP43** [comment]
@mjb232 read your Xpath from the inside out... as you have it now you are saying count all of the speaker and then taking the distinct value of that count ... but what you want to do is count the distinct-value of speakers that are greater than 40 ... hope this helps.
