### ISSUE TITLE
svg exercise 1

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#166]
So this is what my code looks like right now for the bar graph (just testing the line elements is w3)
```` 
<!DOCTYPE html>
<html>
<body>

<svg height="50" width="100">
  <line x1="0" y1="0" x2="0" y2="100" style="stroke:rgb(255,0,0);stroke-width:4" />
  Sorry, your browser does not support inline SVG.
</svg>


<svg height="350" width="500">
  <line x1="0" y1="0" x2="100" y2="0" style="stroke:rgb(255,0,0);stroke-width:4" />
  Sorry, your browser does not support inline SVG.
</svg>

</body>
</html>
````

But my graph is very very tiny and the lines aren't completely touching. I'm not really sure how the height and width work.

**Comment by laurenmcguigan** [comment]
so I put both lines in the same svg tag, and now they are touching, but it has turned upside down..

**Comment by laurenmcguigan** [comment]
Never mind I got it!

**Comment by laurenmcguigan** [comment]
Oxygen doesn't like me using svg. Should it be okay with it? Is any one else getting an error?

**Comment by ebeshero** [comment]
@laurenmcguigan I just realized that we didn't post instructions on how to open an SVG file in oXygen! I've just added that in [SVG Exercise 1](http://newtfire.org/dh/SVGExercise1.html), so you can just refresh your browser. 

But you can write SVG inside HTML and we'll be doing a lot of that, too. To make oXygen okay with embedding SVG, you need to use HTML 5, and that's just changing the lines at the top of the HTML. Let me go look up what you need there...

**Comment by ebeshero** [comment]
...So, remember me saying, "It's always a namespace issue?" Well, it's always a namespace issue! Try this at the top:
````
<!DOCTYPE html
  SYSTEM "about:legacy-compat">
<html xmlns="http://www.w3.org/1999/xhtml">
```` 
That's going to be the way we want to output HTML on our projects we post at the PSC anyway. Let me know if oXygen is still giving you trouble with the SVG.

**Comment by laurenmcguigan** [comment]
@ebeshero I changed that at the top of my html file

````
<!DOCTYPE html
  SYSTEM "about:legacy-compat">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>svg 1</title>
    </head>
````
It looks like this at the top, but it is still giving me an error at the svg element. Do I need to open it as an svg file instead?

**Comment by laurenmcguigan** [comment]
@ebeshero it still appears correctly in my browser though

**Comment by ebeshero** [comment]
@laurenmcguigan Hmmm. Did you add the SVG namespace to the SVG element? It's on the SVG homework assignment page now (refresh the page). 

Or here: <svg xmlns="http://www.w3.org/2000/svg">

**Comment by laurenmcguigan** [comment]
All done! thanks for your help @ebeshero !
