### ISSUE TITLE
SVG 2

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#167]
````<svg xmlns="http://www.w3.org/2000/svg" width="500" height="3000">
<g transform="translate(30, 100)">
<line x1="200" y1="0" x2="200" y2="3000" style="stroke:black;stroke-width:2"/>
1818-01-12 1819-01-09 1819-01-12 1819-02-10 1819-02-13 1819-02-18 1819-02-27 1819-03-13 1819-04-08 1819-04-19 1819-05-16 1819-05-30 1819-06-08 1819-07-05 1819-08-08 1819-08-21 1819-12 1819-12-10 1820-01-30 1820-06-29 1820-08-24 1820-09-01 1820-09-09 1820-09-30 1820-11-04 1821-01-29 1821-02-08 1821-02-09 1821-03-10 1821-04-04 1821-04-18 1821-06-21 1821-07-31 1821-10-22 1821-10-28 1821-10-31 1821-11-06 1821-11-09 1821-11-12 1821-11-16 1821-11-22 1822-05-19 1822-07-23 1822-08-13 1822-08-31 1823-03-20 1823-04-03 1823-06-14 1823-10-01 1824-06-13 1825-05-11 1825-06-29 1825-07-29 1825-08-12</g>
</svg>````
This is my output so far. Am I just supposed to be getting the year? Just confused what I am supposed to be getting.

**Comment by brookestewart** [comment]
Sorry, @mmm202  I'm not that far! 
I'm stuck on the part where you add dates to the timeline. It says there should be a global variable to calculate the number of years on the timeline. I subtracted the integer values of the max year from the min year and I get 7 as a result, but there appears to be 8 dates on the timeline. Any suggestions, anyone?

**Comment by laurenmcguigan** [comment]
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];

<svg>
    <g>
        <line x1="0" y1="0" x2="0" y2="3000" style="stroke-width:2;stroke:red;"/> 
{
let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
for $Year in $distinctYears
let $integerYears := xs:integer($Year)
order by $integerYears
return $integerYears
}
<text x="0" y="365" fill="red">
{
 let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
for $Year in $distinctYears
let $integerYears := xs:integer($Year)
order by $integerYears
return $integerYears   
}
</text>
</g>
</svg>
````

So I was trying to output the years with this and in the first set of curly braces it was only outputting the line and not the dates. So, I added a text element. This may be making it more complicated but I am not sure? Do I need the text element? Or is just the line element enough??

**Comment by laurenmcguigan** [comment]
is this where the $i variable comes into place?

**Comment by laurenmcguigan** [comment]
Has anyone else figured this out? I'm not sure what I missed? @mmm202 @jlm323 @mjb232

**Comment by mmm202** [comment]
I haven't I'm not even sure if what I did so far is right

**Comment by RJP43** [comment]
I am doing this right along with you guys, but by the looks of what Lauren has you may just want to put all of your calculations into global variables. And then when calling on those variables in the SVG make sure you use curly braces.

**Comment by laurenmcguigan** [comment]
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];

<svg width="500" height="3000">
    <g>
        <line x1="200" y1="0" x2="200" y2="3000" style="stroke-width:5;stroke:black;"/> 
{
let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
for $Year in $distinctYears
let $integerYears := xs:integer($Year)
for $i in (0 - $integerYears)
order by $integerYears
return $i
}

</g>
</svg>
```` 
So I tried a few different things and this is what I have come up with. 
And my out put looks like this:

````
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="3000">
<g>
<line x1="200" y1="0" x2="200" y2="3000" style="stroke-width:5;stroke:black;"/>
-1818 -1819 -1820 -1821 -1822 -1823 -1824 -1825</g>
</svg>
````

But it is still only showing a line. What do I need to add to the svg to make the dates show up at intervals of 365?

**Comment by laurenmcguigan** [comment]
can I put the dates in svg text individually? or is there a way of doing it all together?

**Comment by laurenmcguigan** [comment]
Okay that's not right either it supposed to say `for $i in (0 to something)` but I don't know what that something is...

**Comment by laurenmcguigan** [comment]
If I put 0 to 10 it's just outputting 10 of each year...??

**Comment by laurenmcguigan** [comment]
maybe this is closer?

````

<svg width="500" height="3000">
    <g>
        <line x1="200" y1="0" x2="200" y2="3000" style="stroke-width:5;stroke:black;"/> 
        <text x="0" y="365" fill="red">
{
let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
for $Year in $distinctYears
let $integerYears := xs:integer($Year)
order by $integerYears
return $integerYears
}
</text>
</g>
</svg>
````
I really don't know what to do

**Comment by ebeshero** [comment]
@laurenmcguigan Here's the problem: You are hand drawing the line, so you aren't plotting its length based on a calculation. 

You aren't outputting dates using any SVG elements for text, so they don't have any way to appear in your graphic, and try aren't aligned in any way with the line you drew by hand.

Think about what you need to do here: You need to plot a line that represents a *quantity* of years, and expand it by a factor of 365 (for 365 days; one pixel per day). Here's a hint: Plot your line based on the *timespan*, not the literal dates! Your line should be the length of (maxYear - minYear) * 365.

Then once you have the line plotted you work with each integer within that timespan. If your tinespan is seven years long, what do you need to do with each value of $i to convert it back into a date? What about adding it to the minYear?

**Comment by laurenmcguigan** [comment]
````
        <line style="stroke-width:5;stroke:black;"> 
        {
        let $distinctYears := distinct-values($letterDates)
        let $maxDistinctYear := max($distinctYears)
        let $minDistinctYear := min($distinctYears)
        return := ($maxDistinctYear - $minDistinctYear) * 365
        }    
            
        </line>
````
This is giving me an error. I'm not sure why

**Comment by laurenmcguigan** [comment]
how do I add x and y to that?

**Comment by mjb232** [comment]
see I have this, and when I try and return my `$years` there's error telling me that my `-` isnt supposed to be there. Do we need to put our variables in a `count` function?
````
let $distinctYears := distinct-values($letterDates)
let $max := max($distinctYears)
let $min := min($distinctYears)
for $distinctYear in $distinctYears
let $years := ($max - $min)* 365
return $years
````

**Comment by ebeshero** [comment]
@mjb232 make sure you turn the dates into integers. I bet that's the problem preventing you from subtracting. It's reading the dates as strings of text.

**Comment by mjb232** [comment]
Wait, no. Im dumb. I needed the `xs:integer` function. Guess I should have read the next sentence haha. @laurenmcguigan Could the `xs:integer` function that you need? I didnt see it in your code

**Comment by mjb232** [comment]
Also @ebeshero I ran my code using the proper integer function, but Im returning 8 items instead of just one. Is this an issue, or is that ok? my code looks like this:
````
let $distinctYears := distinct-values($letterDates)
let $max := max($distinctYears)
let $min := min($distinctYears)
for $distinctYear in $distinctYears
let $years := (xs:integer($max) - xs:integer($min))* 365
return $years
`````

**Comment by ebeshero** [comment]
@laurenmcguigan You removed your x1 and x2 and y1 and y2 attributes, and I don't know why you did that. All I was saying was don't draw the line by hand, but base it on calculations, so instead of writing numbers as attribute values, use curly braces and XQuery variables for your y variables. 

`<line x1="5" y1="0" x2="5" y2="{$variable}" style="whatevs;..."/>`

**Comment by ebeshero** [comment]
@mjb232 you are getting 8 values bc you are inside a for loop, which is saying, for each distinct year output something. You don't want that for loop just there...

**Comment by ebeshero** [comment]
Everyone-- when you get the point where you're outputting hashmarks and circles and text, you'll be outputting multiple SVG elements at once. You'll need to bundle those all together inside a single element or XQuery won't output it in a return statement: It can only output *one* thing in a return, and that *one thing* can be a group with multiple things inside it (like one table with lots of table rows and cells). You want to use `<g>` to hold your SVG lines and text and circle elements all together in one return.

**Comment by laurenmcguigan** [comment]
when I am trying to output the numbers is the x attribute in the text element supposed to have the {variable} this time?

**Comment by laurenmcguigan** [comment]
so I tried this

````
        <text x="0" y="{let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
for $i in (xs:integer($minDistinctYear) to xs:integer($maxDistinctYear))
for $distinctYear in $distinctYears
order by $distinctYear
return xs:integer($distinctYear)}" fill="red">

</text>

````

But I am just getting the dates repeated over and over

**Comment by ebeshero** [comment]
@laurenmcguigan you want the min and max distinct years, and you are getting them in your variables, but what happens next is way too complicated! You have two for loops now, one right after the other. That's not how you want to do this...

**Comment by laurenmcguigan** [comment]
````
        <text x="0" y="{let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
for $i in (xs:integer($minDistinctYear) to xs:integer($maxDistinctYear) )
return $i }" fill="red">

</text>
````
 Is this closer? I think somewhere in the $i you are supposed to multiply by 365 or is that somewhere else. Should it start at 0?

**Comment by laurenmcguigan** [comment]
okay wait so it is supposed to be 0 to something. But when I put in 

for $i in (0 to xs:integer($distinctYears)) it gives an error

**Comment by ebeshero** [comment]
@laurenmcguigan X positions are going to be static in a vertical (up and down) plot.

Your first for loop is the right idea, but do you literally want to plot from 1818 to 1823 as your actual Y values? Remember how you drew a line going down the screen from 0 to whatever? It's the same here. Work with the time span, not the literal years, to measure and calculate your y values. Well, you probably *could* plot from literal 1818 down, but you still need to factor in 365. I really, strongly urge you to think of this as a plot of a time span from year zero to year seven...or a span of 8 years, or whatever the difference is between maxYear and minYear. Make yourself a variable that simply calculates the difference, subtracts one from the other and maybe call it something like $yearspan. Then make another that spaces out the years by multiplying by 365 so you have a length for your line. You do NOT need to be in a for loop to plot that first basic line from point zero to point $timelinelength. 

The for loop (and you only need one) comes in when you plot the hashmarks and circles and text along the line, for $i in (0 to $yearspan) (which for now is 0 to 7). You calculate where each hashmark falls along the line by multiplying it by 365.

**Comment by laurenmcguigan** [comment]
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];

<svg width="500" height="3000">
    <g>
        <line x1="200" y1="0" x2="200" y2="
        {
let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
return (xs:integer($maxDistinctYear) - xs:integer($minDistinctYear)) * 365}" style="stroke-width:5;stroke:black;"/> 
   
       
   </g>     
       
<text x="0" y="3000" fill="red">

{let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
let $yearSpan := xs:integer($maxDistinctYear) - xs:integer($minDistinctYear)*365
for $i in (0 to $yearSpan)
return $i }

    
</text>

</svg>
````
So this is my whole thing and I STILL can't return points on the timeline. I'm so confused...

**Comment by mjb232** [comment]
@laurenmcguigan If im thinking about this correctly, our flowr statements are going to be used to define the points that a hash is supposed to appear. This means that we'd have to place our flowr in one of the x or y attributes. Now the part im confused about is where these statements belong, and whether or now we should be working in a `text` element or a `line` element, or two different elements. @ebeshero Am I thinking this through correctly?

**Comment by ebeshero** [comment]
Wow, Lauren! That's kind of impressive! You put a whole FLWOR inside those curly braces for the y2 attribute and it's DEFINITELY the right thinking, but also not the way I'd expected you'd do it... I bet it works, though...Let me take a look at your code in eXist. @laurenmcguigan

**Comment by mjb232** [comment]
@RJP43 @brookestewart @mmm202 How are you guys coming along? Any tips for us?

**Comment by laurenmcguigan** [comment]
@mjb232 
so like this:

````
<text x="0" y="{let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
let $yearSpan := xs:integer($maxDistinctYear) - xs:integer($minDistinctYear)
for $i in (0 to $yearSpan)
return $i * 365 }" fill="red">



    
</text>
````

**Comment by ebeshero** [comment]
@laurenmcguigan Okay--no it doesn't work. It's because of the positioning of the curly braces, and really there's a simpler way to do this. Write this part *before* you output your line, and think of your **whole line element** as your return, so like this:

````
let $distinctYears := distinct-values($letterDates)
let $maxDistinctYear := max($distinctYears)
let $minDistinctYear := min($distinctYears)
let $yearSpan :-= xs:integer($maxDistinctYear) - xs:integer($minDistinctYear)
let $timelinelength := $yearSpan * 365
return
`<line .... x1="whatever" y1="whatever" x2="sameasx1" y2="{$oneofyourvariables}"/>`
````
I think you were just confused about how to work with FLWOR statements and returns with SVG elements, and where to apply the curly braces. You need them whenever you invoke some XQuery, to hold a calculated value, for example, but you want to have a variable calculated already for you to return it...does that make sense?

**Comment by mjb232** [comment]
@ebeshero So where does that fit into the structure of the Xquery? Does it go inside of the SVG element and then inside its own g element?

**Comment by ebeshero** [comment]
@laurenmcguigan @mjb232 You really don't want to be putting the FLWOR statements inside an attribute value! Write out a FLWOR, and then write a *return* on the FLWOR that outputs an SVG element in its entirety. In your attribute value, simply reference the variable you need from one of your let statements.

**Comment by ebeshero** [comment]
@mjb232 @laurenmcguigan The architecture is featured in a big code block on the homework assignment, and I'll repeat it here:

````
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $countLetterFiles := count($letterFiles);
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when;
declare variable $letterYears := $letterDates/tokenize(string(), '-')[1];
<!--ebb: MORE GLOBAL VARIABLES To DEFINE MEASUREMENTS AND VALUES AS YOU KEEP WORKING-->
<svg>
   <g>
      <line x1="??" y1="??" x2="??" y2="??" style="??;??;"/>  
      
         {
         <!--ebb: FLWOR statements will go here, inside a pair of curly braces-->
         }
      
   </g>
   
</svg>
````

**Comment by ebeshero** [comment]
I don't know why you aren't using global variables the way we discussed in class and the way I showed you on the homework assignment. What's up with that?

**Comment by RJP43** [comment]
@mjb232 I finished just a bit ago and I guess my only real advice further than all that Dr. B. has been giving is to take the assignment very literally and move step by step remembering all of the ways we were returning multiple pieces of FLWOR statements in the XQuery assignments.  The parts of the assignment that are bootstrapped are less of what you want to the T and more of clues to how to get to the latter variables you will need to solve the tasks. Perhaps go back to the solutions for xQuery and Dr. B.'s SVG exercise 1 solution to get a better sense of everything and then literally work step by step though the assignment .

**Comment by RJP43** [comment]
Don't skim read the assignment and paste in the snippets that are bootstrapped. Try the pieces on for size and really understand what is being asked and think where makes sense to apply everything you already know about SVG and XQuery combined

**Comment by RJP43** [comment]
Whoops just realized I was being a little redundant with Dr. B. but my app for GitHub didn't refresh to show what she wrote.

**Comment by laurenmcguigan** [comment]
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];
declare variable $distinctYears := distinct-values($letterDates);
declare variable $maxDistinctYear := max($distinctYears);
declare variable $minDistinctYear := min($distinctYears);
declare variable $integer := (xs:integer($maxDistinctYear) - xs:integer($minDistinctYear)) * 365;
declare variable $yearSpan := xs:integer($maxDistinctYear) - xs:integer($minDistinctYear);

<svg width="500" height="3000">
    <g>
        <line x1="200" y1="0" x2="200" y2="{$integer}"/>
        </g>


<text x="0" y="3000" fill="red">


</text>

</svg>
````

So this is what I changed it to. But then how do I use the for loop. Can you define a for loop in  the global variables?

**Comment by ebeshero** [comment]
@mjb232 @laurenmcguigan In case it's more convenient here, I'm copying the whole architecture of the XQuery with SVG plotted in it. I wonder if you got confused by my telling you about the one global variable that holds an entire SVG file inside...but that's something you add at the very end, and it's a giant *global variable*, not a FLWOR.  

Look at how the SVG file is structured here. It's just like how we plotted HTML with XQuery: Put the things that hold the outer structure together on the outside, and then the FLWOR statements step through to help you handle repeating elements, in this case, each year in the timeline, or each stop in the span of years that measures your line.


````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $countLetterFiles := count($letterFiles);
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when;
declare variable $letterYears := $letterDates/tokenize(string(), '-')[1];
<!--ebb: MORE GLOBAL VARIABLES. . .-->

declare variable $ThisFileContent := 
<svg width="500" height="3000">
   <g transform="translate(30, 100)">
          <line x1="??" y1="??" x2="??" y2="??" style="??;??;"/>  
          
         {
         <!--ebb: FLWOR statements here, inside a pair of curly braces-->
         }      
   </g> 
</svg> ;

let $filename := "timeline.svg"
let $doc-db-uri := xmldb:store("/db/yourFolder", $filename, $ThisFileContent)
return $doc-db-uri
(: Output at http://dxcvm05.psc.edu:8080/exist/rest/db/yourFolder/timeline.svg :)    
````

**Comment by mjb232** [comment]
Aight this is what I have. I think Im getting back on track here.  
````
declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];
declare variable $distinctYears := distinct-values($letterDates);
declare variable $min := min($distinctYears);
declare variable $max := max($distinctYears);
declare variable $years := (xs:integer($max) - xs:integer($min));
declare variable $days := $years* 365;

<svg width="500" height="3000">
      <g  transform="(translate(100,50))">
          <line x1="0" y1="0" x2="0" y2="{$days}" style="stroke:black;stroke-width:5"/>
{
    for $i in (0 to $years)
    return <line x1="5" y1="0" x2="5" y2="{$i*365}"/>
}
      </g>
</svg>
````

**Comment by ebeshero** [comment]
@laurenmcguigan You're getting output now, right? 

The for loop is so you can plot a hash mark (and other things) for each year in the span of years. That's where you use `for $i in (0 to $yearSpan) ` but remember those are just going to be simple integers, between 0 and 7...and @mjb232 just posted, and YES, you're on the right track now. Whew!

**Comment by laurenmcguigan** [comment]
@ebeshero 

````

<text x="20" y="3000">
{for $i in (0 to $yearSpan)
    return $i
}   
</text>
````
so I added this and I'm returning 0 through 7.
Is it supposed to be in a text tag or another line tag. And am I returning them in the right place, or are they supposed to be within @y?

**Comment by laurenmcguigan** [comment]
@ebeshero  this is my output 

````
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="3000">
<g>
<line x1="200" y1="0" x2="200" y2="2555"/>
</g>
<text x="20" y="3000">0 365 730 1095 1460 1825 2190 2555</text>
</svg>
````

**Comment by mjb232** [comment]
Ok so I think I see where we got confused. We are thinking "We need a line, so lets create another line element similar to the first line we created", when in actuality we need to create several lines using flowr statements. So @laurenmcguigan you dont want a line element my itself but instead you want"
`{
statement 
statement
return <line/>
}` 
Then inside of this line, the coordinates (x and y) will be one of the statements you created above it. Does that help?

**Comment by laurenmcguigan** [comment]
@mjb232  what? haha

**Comment by laurenmcguigan** [comment]
````
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="3000">
<g>
<line x1="200" y1="0" x2="200" y2="2555"/>
</g>
<line x1="20" y1="0" x2="20" y2="0"/>
<line x1="20" y1="0" x2="20" y2="365"/>
<line x1="20" y1="0" x2="20" y2="730"/>
<line x1="20" y1="0" x2="20" y2="1095"/>
<line x1="20" y1="0" x2="20" y2="1460"/>
<line x1="20" y1="0" x2="20" y2="1825"/>
<line x1="20" y1="0" x2="20" y2="2190"/>
<line x1="20" y1="0" x2="20" y2="2555"/>
</svg>
````
 so here is my output which doesn't actually show anything in the browser...

**Comment by mjb232** [comment]
@laurenmcguigan maybe your lines need color/width

**Comment by laurenmcguigan** [comment]
ohh duh thanks @mjb232

**Comment by mjb232** [comment]
@laurenmcguigan So, did you figure it out then?

**Comment by ebeshero** [comment]
And you might want to mess with transform="translate(x, y)" on your outermost g element. And mess with your viewport. 
See this part of the homework: 
Setting the viewport and shifting things with transform="translate(x, y)" so you can see the full line:

**Comment by laurenmcguigan** [comment]
@mjb232  yes, but I am only getting lines right next to each other.

**Comment by mjb232** [comment]
@laurenmcguigan Just realized I did the same thing as you; I forgot to give my lines a style -__-

**Comment by laurenmcguigan** [comment]
@mjb232 but they are still just two solid lines next to each other.. I don't know where to go from there??

**Comment by mjb232** [comment]
@laurenmcguigan I see what you mean. We need to figure out how to make several of them appear. The issue isn't with the coordinates, but with our actual variables.

**Comment by laurenmcguigan** [comment]
@mjb232 it is with the coordinates

**Comment by laurenmcguigan** [comment]
@mjb232  you need to add `{$i*365}` to another coordinate

**Comment by RJP43** [comment]
Think of what kind of variables you could define thst could take place of the value for your y2 value. And and simply put return after the FLOWR statement but the variable you actually want retuned in place of the y2 value in a set of curly braces after the y2 equal sign.

**Comment by RJP43** [comment]
Well the y coordinates in general ... not just the y2

**Comment by RJP43** [comment]
I don't know if you guys got to that point but it's hard to read through all of the conversation so hopefully that was helpful to say ... in between my damn autocorrect cell phone typing

**Comment by laurenmcguigan** [comment]
So I tried doing this to add the date to the hashmark `{for $i + $minDistinctYear in (0 to $yearSpan)` like it said in the homework, but it's giving me an error.

**Comment by ebeshero** [comment]
a variable that simply holds `$i + $minDistinctYear` is smart, because it returns the year. Keep it simple. (I don't understand why you'd introduce a for loop here? Anyway, this code is a lot more complicated than it needs to be.)

Think about what you need a "for loop" to do. Do you *really* need one here? Or do you just want to add something to function in the existing for loop?

**Comment by brookestewart** [comment]
I can't get the dates either. I have a variable defined in the for loop as instructed in the homework and above, but I don't know how to get it to output the text?
