### ISSUE TITLE
svg 4

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#169]
I'm trying to return the stories in Decameron, and xquery it isn't letting me return anything. Right now it looks like this:

````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $Decameron := collection('/db/decameron/');
declare variable $stories := $Decameron//div/@type='novella';
return $stories
````
and I keep getting an error saying 
Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: $ [at line 6, column 8]

**Comment by RJP43** [comment]
@laurenmcguigan checkout your `$stories` variable right now you are asking to give you all the type attributes and that is probably where XQuery is throwing the error... I think what you want is the div **that has** the `@type='novella'` therefore you would need a predicate.

**Comment by RJP43** [comment]
also test it first in a let statement ... I think that is actually what the error is saying ... once you know it is getting you what you want then you want to make it a global variable.

**Comment by ebeshero** [comment]
@laurenmcguigan Don't forget the `tei:` prefix in front of your element names, too.

**Comment by laurenmcguigan** [comment]
SO I am doing this to try and get the count of persName in each individual day, but I am not getting the correct output.

````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $Decameron := collection('/db/decameron/');

let $days := $Decameron//tei:div[@type='Day']
for $day in $days
let $people := $days//tei:persName
let $countPers := count($people)
return $countPers
````
What am I doing wrong here

**Comment by ghbondar** [comment]
For starters, you are not actually using your range variable $day for anything.

**Comment by laurenmcguigan** [comment]
@ghbondar 
got it! Thank you!

**Comment by noobo** [comment]
Yay! :D
Well done!

**Comment by laurenmcguigan** [comment]
so this is what it looks like now
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $Decameron := collection('/db/decameron/');

<svg width="500" height="500">
    <g transform= "translate(30,100)">
<line x1="0" y1="0" x2="0" y2="300" style="stroke:blue; stroke-width:5;"/>
<line x1="0" y1="300" x2="300" y2="300"  style="stroke:blue; stroke-width:5;"/>
{
let $days := $Decameron//tei:div[@type='Day']
for $day in $days
let $people := $day//tei:persName
let $countPers := count(distinct-values($people))
return 
    for $i in (0 to 10)
    return
    <g>
    <rect x="{$i*30}" y="160" width="20" height="{$countPers*10}" style="fill:red;stroke-width:3;stroke:black;" />
    </g>
}

</g>
</svg>
````

And I am outputting each individual count of distinct persnames for each day, but the output is repeating over and over. How do I stop that?

**Comment by brookestewart** [comment]
I'm trying to graph the number of lines in each poem. I'm having trouble setting the interval for the x value on my graph. This is what I have: 
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
<svg width="300" height="400">
   <g transform="translate(50, 230)">
      <line x1="-1" y1="0" x2="300" y2="0" style="stroke:black;stroke-width:2"/>  
      <line x1="0" y1="0" x2="0" y2="-200" style="stroke:black;stroke-width:2"/>
{
let $dickinson := collection('/db/dickinson/f16/')
for $d in $dickinson
let $body := $d//tei:body
let $lines := $body//tei:l
let $countLines := count($lines)
let $xInt := ($countLines * 5)
return 
    <g>
        <line x1="{$xInt}" y1="0" x2="{$xInt}" y2="-{$countLines}" style="stroke:black;stroke-width:4"/> 
    </g>
}
</g>
</svg>
````
I tried setting `$xInt` as just a number, and that doesn't work. What I have now generates output, but it's not a consistent interval and some of the lines overlap. I know it's not correct, but it's the closest I was able to get. Does anyone have any ideas?

**Comment by laurenmcguigan** [comment]
Yeah, Basically I am having trouble with the x and y coordinates

**Comment by mjb232** [comment]
Im trying to count all the milestones in a Novella and Im having trouble figuring it out. Help?
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $dec := doc('/db/decameron/engDecameronTEI.xml');
declare variable $div := $dec//tei:div [@type="novella"];
declare variable $mile := $div//tei:milestone;
declare variable $divCount := count(distinct-values($div));
<svg width="5000" height="5000">
    <g>
    <line x1="0" y1="{$divCount*40+20}" x2="0" y2="0" style="stroke:black;stroke-width:5"/>
    <line x1="{500}" y1="0" x2="0" y2="0" style="stroke:black;stroke-width:5"/>
    {
        for $stories in (0 to $divCount)
        return
    <g transform="translate(0,20)">
    <rect y="{$stories*40}" width="{500}" height="10" style="fill:blue;stroke-width:2;stroke:black"/>
    <line y1="" x1="" y2="" x2="0" style="stroke:gray; stroke-width:3;"/>
    <text y="{$stories*40-4}" x="20"> Novella {$stories} </text>
    </g>
    }
    </g>
    </svg>
````

**Comment by laurenmcguigan** [comment]
I got y! just can't figure out x. keep trying different ways with the for loop, but it makes everything repeat.

**Comment by ebeshero** [comment]
@laurenmcguigan I think the problem is your double for loop!

**Comment by ebeshero** [comment]
That is why you are getting too much output repeated over and over: you are processing one loop for each day, and then inside each day running the integers from 0 to 10. You don't need to do both of those loops, do you?

**Comment by ebeshero** [comment]
@brookestewart Think about what you want to plot, step by step, across your X-axis. You want a count of the number of lines *in each poem*, so your count should only be appearing in your Y coordinates, not your X coordinates. Those should represent, evenly spaced, each poem in your collection. How many poems is that? (don't know? Use `count()`! )

**Comment by brookestewart** [comment]
@ebeshero I got it, thanks!

**Comment by ebeshero** [comment]
Yay! @brookestewart

**Comment by ebeshero** [comment]
@mjb232 I think you are on the right track, but you need a variable that reaches in, in each story `div` and counts your milestone elements...

**Comment by brookestewart** [comment]
My laptop is not working correctly, I can't open a new tab without it freezing. All I need to finish my graph is a text label on the left that goes up and down (sideways?). Since I can't search for it without my laptop freezing, would someone be kind enough to help me out with the writing-mode?

**Comment by brookestewart** [comment]
Never mind, I got it!

**Comment by ebeshero** [comment]
:+1:
