### ISSUE TITLE
Network Analysis Exercise 1

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#172]
@RJP43 @spadafour @brookestewart @nlottig94 @mmm202 @jlm323 @ghbondar @laurenmcguigan @mjb232 
I've made some small corrections and added a little more detail to [Network Analysis Exercise 1](http://newtfire.org/dh/NetworkExercise1.html), including a more fleshed-out sample of your XQuery structure with the two nested "for loops" and the "if(...) then ... else ..." structure. 

I've also added a suggestion in the "Using distinct-values()" section: You might want to grab a `count()` of the number of times each target node actually does appear with your source node, to use later on as an *"edge attribute"* (or an attribute on the shared-interaction) in Cytoscape, because you might want to use that to control the thickness of your edge-lines later.

**Comment by nlottig94** [comment]
@ebeshero I understand the "if(...) then... else...", but what I'm not understanding is how to get the same outcome with a collection of files, such as Dickinson, where you don't need all of the "if(...) then... else..."s.... This is what I have so far, but I'm not getting any output:
****
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";
let $Dickinson := collection('/db/dickinson/f16/')
let $apps := $Dickinson//text//body//l//app
let $rdgs := $apps/rdg
let $wits := $rdgs/@wit/string()
let $rep1 := replace(string-join($wits, ' '), 'var0', '')
let $rep2 := replace(string-join($rep1, ' '), 'var1', '')
let $rep3 := replace(string-join($rep2, ' '), 'var2', '')
let $witNames := tokenize($rep3, '\s+')
let $distWits := distinct-values($witNames)
for $d in $distWits
    let $pubs := $d[not(. = $d)]
    let $edge := $rdgs[$d = $pubs]
    let $edgeWeight := count($edge)
    for $pub in $pubs
    return
        concat($d, "&#x9;", $edge, "&#x9;", $edgeWeight, "&#x9;", $pub, "&#10;")
****

**Comment by nlottig94** [comment]
@ebeshero I am getting the distinct-values of the witnesses that I want before I did the first for loop.

**Comment by ebeshero** [comment]
@nlottig94 I took a look at your code, and tried taking out the second for-loop, and yes, you're getting a list of results for your $distWits variable. Now, notice that's a list of distinct values.
Your second for-loop doesn't actually make sense and really *can't* produce output, because you are saying, for each member of my list of distinct values, find when it is not itself! (That can never be.) What you need to do is make $pubs equivalent to the *other* publications represented in the same file with $d. You need to look up the file in which $d is sitting, and then locate all the other witnesses in that file. Make sense?

That said, good thinking here in that "string-surgery" work to output only the witnesses in your rep variables...Do you ever have more than var0, var1, and var2? I wonder if there's a simpler and less brittle way to do that string-surgery work in one step?

**Comment by nlottig94** [comment]
@ebeshero give me a minute and let me see what I can do.  I don't ever have more var0, var1, and var2.  And I was trying to find if there was some other way to do a replace and have all of those in one replace function, but I couldn't find anything.

**Comment by nlottig94** [comment]
Okay, @ebeshero, I tried this, but I keep getting an error that says "the sequence cannot be converted into a node set."

````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";
let $Dickinson := collection('/db/dickinson/f16/')
let $poemFiles := $Dickinson/*
let $apps := $poemFiles//text//body//l//app
let $rdgs := $apps/rdg
let $wits := $rdgs/@wit/string()
let $rep1 := replace(string-join($wits, ' '), 'var0', '')
let $rep2 := replace(string-join($rep1, ' '), 'var1', '')
let $rep3 := replace(string-join($rep2, ' '), 'var2', '')
let $witNames := tokenize($rep3, '\s+')
let $distWits := distinct-values($witNames)
for $d in $distWits
    let $pubs := distinct-values($witNames[. = $d]/ancestor::body//$witNames[not(. = $d)])
    let $edge := $rdgs[$pubs]
    let $edgeWeight := count($edge)
    for $pub in $pubs
    return
        concat($d, "&#x9;", $edge, "&#x9;", $edgeWeight, "&#x9;", $pub, "&#10;")
````

**Comment by nlottig94** [comment]
I was thinking that I may have to use my `$witNames` in there somewhere, so it doesn't catch the vars...

**Comment by ghbondar** [comment]
@nlottig94 your $wits variable is returning the xmlid value for the attribute, not the text. Is that what you want? Also, I think the error is coming from your use of string-join inside the replace-fcn.

**Comment by nlottig94** [comment]
@ghbondar yes, that is what I want because I'm trying to see how much the publications match up.  And I don't know why the string-join in the replace function would be a problem because it was outputting what I wanted to begin with...

**Comment by ebeshero** [comment]
@nlottig94 @ghbondar Nicole, you did well with grabbing all the witnesses in that first for-loop, so I didn't mean to throw a monkey wrench into this. But in case you ever have a var04 or a var06, for example, you might want to be able to use a regex so you don't have to make multiple variables that anticipate each number literally. I just checked in the Michael Kay book and it looks like you can use a regex instead of a literal number in your replace() function. If you've got the Kay book, check out p. 863. The example suggests we try this format, with caret and dollar-sign to signal the start and end of a regex:
````
replace($input, "^regex-to-match-here$",  "")
````
You can do capturing groups just like we do in the Find & Replace window in oXygen using (...)s, and capture them in the third argument with $1, $2, $3 (instead of our usual \1, \2, \3.

**Comment by ebeshero** [comment]
@nlottig94 More importantly, for now, let's just concentrate on getting your second "for loop" to work!

**Comment by nlottig94** [comment]
@ebeshero that's what I was trying to do.  But I can't figure it out.. I'm at work now, so I'll be back on around 8.

**Comment by nlottig94** [comment]
Okay, @ebeshero, I'm stuck :(

**Comment by nlottig94** [comment]
Okay, I tried this:
````
for $d in $distWits
    let $pubs := $d/ancestor::TEI//listWit/witness/@xml:id
    let $edge := $rdgs[$pubs]
    let $edgeWeight := count($edge)
    for $pub in $pubs
    return
        concat($d, "&#x9;", $edge, "&#x9;", $edgeWeight, "&#x9;", $pub, "&#10;")
````
I think I'm on to something, but I and getting an error saying that it can't convert #df16 into a node set...

**Comment by nlottig94** [comment]
I think it's the `#` in my witness ids, but I can't seem to get rid of them!

**Comment by nlottig94** [comment]
Okay, so I have figured out that it most definitely NOT the `#`. I created another variable after my first for-loop to find the substring-after the `#`, but after evaluating it, I'm still getting the same error just without the `#` before `df16`. Help?

**Comment by ebeshero** [comment]
@nlottig94 Okay, here's the problem: $d does not have an ancestor::* of any kind for you to locate on XPath! Remember why not?

**Comment by nlottig94** [comment]
I think it's because it's a distinct-value, so would I have to use `$wits`?

**Comment by ebeshero** [comment]
Right--it is a distinct-value, do it is just a string of text. And right, you need to map it back into the XML tree. Your variable `$wits` does look like your best option for that. Look at my simplified example with the `$treeWalker` variable in the homework assignment--that should help...but your case will be trickier: what part of $wit can you check to see if it has something equal to your $d?

**Comment by nlottig94** [comment]
`let $pubs := $wits[. = $d]/ancestor::TEI//listWit/witness/@xml:id`
@ebeshero this gave me output!

**Comment by nlottig94** [comment]
But, now I'm only getting a 0 for the second values of my lines...

**Comment by ebeshero** [comment]
Yay! Is it good output? I was thinking you might need `contains()` or `matches()` since your `@wit` attributes contain multiple values...As long as the @wit **contains** the $d string, you've got a match I. The XML tree, which is what we need!

**Comment by nlottig94** [comment]
![image](https://cloud.githubusercontent.com/assets/14095715/14237131/ab35f550-f9ed-11e5-9a71-f1a33dff0d74.png)
This is what part of my output looks like....

**Comment by nlottig94** [comment]
But I don't think it's correct..

**Comment by ebeshero** [comment]
So try reshaping your predicate so instead of `[. = $d]` you are using `[contains(., $d)]`. I think that'll get you more complete results...

**Comment by nlottig94** [comment]
@ebeshero I tried this:
`let $pubs := $wits[. = $d]/ancestor::body//app/rdg/@wit[not(. = $d)]`
and it seems to look better (except) for the zeros.
This:
`let $pubs := $wits[contains(., $d)]/ancestor::body//app/rdg/@wit[not(contains(., $d))]`
Seems to give me the same as the one with `[. = $d]`
My output looks like this:
![image](https://cloud.githubusercontent.com/assets/14095715/14237173/603d239c-f9ee-11e5-9045-43d0590cd224.png)

**Comment by ebeshero** [comment]
Hmmm. What is the variable that is outputting the zeroes? Let's have a look at it.

**Comment by nlottig94** [comment]
It's either `$edge` or `$edgeWeight` I think

**Comment by nlottig94** [comment]
````
for $d in $distWits
    let $pubs := $wits[contains(., $d)]/ancestor::body//app/rdg/@wit[not(contains(., $d))]
    let $edge := $rdgs[$pubs]
    let $edgeWeight := count($edge)
    for $pub in $pubs
    return
        concat($d, "&#x9;", $edge, "&#x9;", $edgeWeight, "&#x9;", $pub, "&#10;")
````

**Comment by ebeshero** [comment]
I think you aren't getting output either for $edge or $edgeWeight, and we need to rewrite those variables!

**Comment by ebeshero** [comment]
@nlottig94 Try rewriting $edge so it literally walks the tree *just the same way* that you do with $pubs, only stop on the tree at the point of the `<rdg>` *that holds* the `@wit` that doesn't contain $d!

**Comment by nlottig94** [comment]
Okay, let me try!

**Comment by nlottig94** [comment]
@ebeshero I tried this:
`let $edge := $wits[contains(., $d)]/ancestor::body//app/rdg[@wit[not(contains(., $d))]]`
and it's saying that the cardinalities don't match the function's signiture...

**Comment by ebeshero** [comment]
@nlottig94 Hmmm...okay, that makes sense, doesn't it. Let's think of what *one* condition constitutes a shared edge...Also I noticed in your output earlier it looks like you sometimes output multiple target nodes in the same line, which should not be happening...

**Comment by nlottig94** [comment]
@ebeshero yes, I noticed that too...how would I fix this??

**Comment by ebeshero** [comment]
@nlottig94 I may not be clear on this, so you tell me: What is an edge in your network? Is it being in the *same poem* with the other reading witnesses? If so, you want to **back up** in the tree: You want the `<body>` *that contains* the `<app>` that has the reading witnesses that aren't $d!

**Comment by nlottig94** [comment]
@ebeshero I was actually going to have the rdgs as the edges, but let me try what you said, just to see if I can get output...

**Comment by nlottig94** [comment]
@ebeshero That seemed to do something!!!  But i'm still getting two witnesses in my target nodes...

**Comment by nlottig94** [comment]
I lied!  there are still zeros as the second term....

**Comment by ebeshero** [comment]
@nlottig94 OK--if you do it your way it's a more complicated thing to try to visualize in a network graph: i can wrap my head around which *poems* are represented by specific editions. Your way would show us which lines or words in the poems are shared by those witnesses...Snips if text would turn constitute an edge. That's okay, too, but maybe if you want that let's try simplifying this so you reach back **not to the `<body>` but instead only back to the parent::rdg (it is the parent element, right? Attributes have a child relation to their parent element).

**Comment by laurenmcguigan** [comment]
@ebeshero , @mjb232  and I are working together on the homework  and this is what we have so far with the if else statements. Can you let us know if we are on the right track.


````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";
declare variable $doc := doc('/db/decameron/engDecameronTEI.xml');
declare variable $text := $doc//text;
declare variable $placeName := distinct-values($text//placeName/string())

let $edge :=
if ($placeName//ancestor::floatingText)
then "floatingText"
else if ($placeName//ancestor::novella)
then "novella"

````

**Comment by ebeshero** [comment]
@nlottig94 Aha! I think I see it...you are trying to find other pubs that do not match $d I the same rdg element, but that can't ever happen because the rdg always had your $d!  Instead, you need to reach up to the ancestor::app, don't you? And look for the *other* rdg elements that do not contain $d?

**Comment by nlottig94** [comment]
@ebeshero I don't think that's it. That's not really what I'm trying to do.  I'm just so confused with what and why things aren't outputting.

**Comment by ebeshero** [comment]
@laurenmcguigan @mjb232 Study your Decameron text...There is no novella element! But just study it with XPath in oXygen so you know what elements are holding the different levels of text.

**Comment by ebeshero** [comment]
@nlottig94 I'm sorry--I don't think I explained that very well. I meant, if you are trying to find the other witnesses in the **same rdg element** or the **same app grouping** you need to back up from your current position on the XML tree (the `@wit` that contains() $d) and back up in baby steps, parent to immediate ancestor. You jumped back to the ancestor::body, which contains lots of app and rdg elements, all of which contain witnesses that don't match $d. 

If you want to work with just the whole poems, to network what distinct witnesses are simply present in each, I think you could really simplify this XQuery a lot! You would just need to find out which distinct witnesses are present in the entire poem, and which others are present with them.

**Comment by ebeshero** [comment]
Folks, I'm turning in now! Early morning tomorrow. Help each other out, ok? You can do this!

**Comment by ebeshero** [comment]
@nlottig94 Here's a thought if you're working on this still: Think what it means for a witness to be just in the *same poem* with the other reading witnesses, regardless of where it is sitting, regardless of the immediate context in the parent rdg. Just find out *what* all the other values of @wit are, regardless of their immediate rdg context. In that case, it's simple. Reach up to the `<body>` *that contains* a descendant `@wit` containing $d, and then look down from `<body>` to find all the values of @wit that do not contain $d.

What seems hard here is, how to locate your target nodes reliably--when you go to look on the XML tree for all the other distinct witnesses, to locate them as not(. = $d). It's hard because you often have multiple values separated by a white space--so you actually need to tokenize all those on a white space, and locate all the tokens *that are not $d*. I am now wondering if `contains(., $d)` could be a problem if the witness is ever similar to other witnesses, containing the same characters. Maybe you do need to check precisely each little token with the `=` comparison operator.

So, without actually testing this in eXide, I think you want something like
````
for $d in $distWits
    let $pubs := distinct-values($wits[contains(., $d)]/ancestor::body//tokenize(@wit, " ")[not(. = $d)])

````
If I were making my edge be the poem itself, I would then just reach up and find the title of the poem up in the TEI header.  

The count() for your edge weight would be nearly the same as your $pubs variable, only replace the distinct-values() with the  count() function, to count the total number of times you mark the pub. But I am not sure whether that count() would really be very meaningful for your network. Why not? Because in reality, each publication does represent the whole poem in some way--we only mark it when it differs from Dickinson's manuscript. I don't think I would bother with a count() for that reason. 

Hope this helps! This is a tough little challenge, and I'm sorry things were confusing before!

**Comment by laurenmcguigan** [comment]
This is what I have right now, but I can't output it. 

````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";
declare variable $thisFileContent :=
string-join(
let $doc := doc('/db/decameron/engDecameronTEI.xml')
let $text := $doc//text
let $placeName := distinct-values($text//placeName/string())
for $p in $placeName

let $peers:=
if ($text//floatingText)
then distinct-values($placeName)
else if ($text//div/@type='novella')
then distinct-values($placeName)
else 

let $edge :=
if ($placeName//ancestor::floatingText)
then "floatingText"
else if ($placeName//ancestor::div/@type='novella')
then "novella"
else "frame"

for $peer in $peers
return
    concat($doc, "&#x9;", $edge, "&#x9;", $peer, "&#10;"))
````
But it is giving me an error saying: Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: null [at line 26, column 58]

Can anyone get to class a little early to help me fix this?

**Comment by nlottig94** [comment]
@laurenmcguigan, @RJP43 and I are here now

**Comment by nlottig94** [comment]
````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";

let $Dickinson := collection('/db/dickinson/f16/')
let $poemFiles := $Dickinson/*
let $apps := $poemFiles//text//body//l//app
let $rdgs := $apps/rdg
let $wits := $rdgs/@wit
let $rep1 := replace(string-join($wits, ' '), 'var0', '')
let $rep2 := replace(string-join($rep1, ' '), 'var1', '')
let $rep3 := replace(string-join($rep2, ' '), 'var2', '')
let $witNames := tokenize($rep3, '\s+')
let $distWits := distinct-values($witNames)
for $d in $distWits
    let $pubs := $wits[. = $d]/ancestor::body//app/rdg/@wit[not(. = $d)]/tokenize(., '\s+')
    let $edge := $rdgs[$pubs[$d]]
    for $pub in $pubs
    return
        concat($d, "&#x9;", $edge, "&#x9;", $pub, "&#10;")
````
@ebeshero So this is giving me an error, I know, but I cannot figure out how to find the parent rdg element of the `$pubs` variable.  I know this is what I want, but I can't figure out how to do it.  I'm stuck and I really can't get any farther.

**Comment by jlm323** [comment]
I fixed my xquery because I wasn't getting output before. My xquery now looks like this:
````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";
declare variable $ThisFileContent := 
string-join(
let $decamFile := doc('/db/decameron/engDecameronTEI.xml')/*
let $placeName := $decamFile//placeName
let $distPlace := distinct-values($placeName)
for $distP in $distPlace 
let $places := 
    if ($placeName[. = $distP]/ancestor::floatingText[@type="frame"]) then distinct-values($placeName[. = $distP]/ancestor::floatingText//placeName[not(. = $distP)])
    else if ($placeName[. = $distP]/ancestor::div[@type="novella"]) then distinct-values($placeName[. = $distP]/ancestor::novella//placeName[not(. = $distP)])
    else distinct-values($placeName[. = $distP]/ancestor::div[1]//placeName[not(. = $distP)])
    
let $edgeType := 
    if ($placeName[. = $distP]/ancestor::floatingText[@type="frame"]) then "floatingText"
    else if ($placeName[. = $distP]/ancestor::div[@type="novella"]) then "novella"
    else "frame"
    
let $edgeWeight := 
    if ($placeName[. = $distP]/ancestor::floatingText[@type="frame"]) then count($placeName[. = $distP]/ancestor::floatingText//placeName[not(. = $distP)])
    else if ($placeName//ancestor::div[@type="novella"]) then count($placeName[. = $distP]/ancestor::novella//placeName[not(. = $distP)])
    else count($placeName[. = $distP]/ancestor::div[1]//placeName[not(. = $distP)])
    
    for $place in $places
    
    return concat($distP,  "&#x9;", $edgeType, "&#x9;", $edgeWeight, "&#x9;", $place, "&#10;"));
        
let $filename := "milewski_networkEx1.tsv"
let $doc-db-uri := xmldb:store("/db/JessicaMilewski", $filename, $ThisFileContent, "text/plain")
return $doc-db-uri
(: Output at: http://dxcvm05.psc.edu:8080/exist/rest/db/JessicaMilewski/milewski_networkEx1.tsv  :)
````
But the only output I'm getting is this and I don't think it should be this small:
````
Florence	floatingText	3	Salerno
Florence	floatingText	3	Bologna
Bologna	floatingText	1	Florence
Monte Asinaio	frame	6	Florence
Monte Asinaio	frame	6	Pistoia
````

**Comment by ebeshero** [comment]
@jlm323 Hi Jessica! I took a look at your XQuery this morning, and I discovered the problem! I think you'll see it, too. Where you create each of your if (...) then statements, take a close look at what you're designating in "then" when you are looking into the novellas. Your "if" correctly identifies those as `div[@type="novella"]` but your "then" doesn't match. When I corrected that I returned the full output. (And that's suggesting to me that most of the place names must be mentioned in the novellas!)

**Comment by ebeshero** [comment]
@nlottig94 I think I got it to work! As I understand it, you want your nodes to be values of @wit, and your target nodes to be other @wit  shared within the same  `<rdg>` element. So your edge is the parent `<rdg>` element itself: a particular variant word or phrase. 

The tricky part of this is working with a tokenized list that breaks apart your `@wit` attribute and tests each value against the others to determine which witnesses appear together most often with a given variant. I rewrote some of you XQuery to simplify it  and just concentrated on the following:
* tokenizing your @wit attributes and only identifying the published witnesses (but you may want to consider including the manuscript variants as nodes too if you want
* identifying aspects of the shared connection: your *edge* is the `<rdg>` element itself, but you may also want to output edge attributes that yield a count of other attributes that appear in this rdg
* the target nodes as the *other* values in the tokenized list that aren't the current one. 

Here's the XQuery: and you may want to test it and tinker with it--you'll also need to turn it into a TSV file. I experimented a bit with doubling up on `string-join()` in the return, and I'm not sure how that'll affect your conversion of this into a file to save into eXist, but I think you'll figure it out! 
````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";

let $Dickinson := collection('/db/dickinson/f16/')
let $poemFiles := $Dickinson/*
let $apps := $poemFiles//text//body//l//app
let $rdgs := $apps/rdg
let $wits := $rdgs/@wit
for $wit in $wits
let $witNames := tokenize($wits, '\s+')[starts-with(., '#')]
for $witName in $witNames
let $edge := $wit/parent::rdg
let $poemTitle := $wit/ancestor::TEI//titleStmt/title
let $otherWits := $wit/tokenize(., '\s+')[starts-with(., '#')][not(. = $witName)]
let $countOtherWits := count($otherWits)
for $otherWit in $otherWits

return string-join(string-join(($witName, $edge, $poemTitle, $countOtherWits, $otherWit), "&#x9;"), "&#10;")

````

**Comment by nlottig94** [comment]
@ebeshero YES!!!  Thank you so much!!!  I did notice that the outside string-join() function that you experimented with, did not actually output with a line break.  So when I imported this into Cytoscape, I had one looooooooooong row of information!!  (like over 2000 columns!!), so I just used the concat() function, like you had in the assignment, and it worked fine!  I'm going to give this XQuery a look over to make sure I understand everything that you did, but if I have questions, would you be availablea little while after class tomorrow?  Again, thank you so so much!  I really appreciate the help!!!

**Comment by jlm323** [comment]
I fixed it and it's outputting correctly now!

**Comment by nlottig94** [comment]
@ebeshero I just noticed something...the XQuery is only catching `df16` as the source node...

**Comment by nlottig94** [comment]
As I'm looking at it now, though, this might be really useful!!  Because we are actually looking at the similarities between Dickinson's original lines and the published versions!

**Comment by spadafour** [comment]
Okay, I've fixed my code so I'm getting the output that I want, but I can't seem to add the code in to get all of my output in a web browser to save the file. Here's me code:

````
xquery version "3.0";
declare default element namespace "http://www.tei-c.org/ns/1.0";

string-join(
let $nellColl := collection('/db/Nelson/CSG_XML')
let $nellArts := $nellColl/*
let$placeNamesAll := $nellArts//text//placeName
let $placeNames := distinct-values($nellArts//text//placeName)


for $placeName in $placeNames

let $places :=
if ($placeNamesAll[. = $placeName]/@type='locRef') then distinct-values($placeNamesAll[. = $placeName]/ancestor::body//placeName[@type='locRef' and not(. = $placeName)])
else if ($placeNamesAll[. = $placeName]/@type='address') then distinct-values($placeNamesAll[. = $placeName]/ancestor::body//placeName[@type='address' and not(. = $placeName)])
else 'other'

let $placeRefEdgeType :=
if ($placeNamesAll[. = $placeName]/@type='locRef') then 'locRef'
else if ($placeNamesAll[. = $placeName]/@type='address') then 'address'
else 'something_else'

let $placeCountEdgeWeight :=
if ($placeNamesAll[. = $placeName]/@type='locRef') then count($placeNamesAll[. = $placeName]/ancestor::body//placeName[@type='locRef' and not(. = $placeName)])
else if ($placeNamesAll[. = $placeName]/@type='address') then count($placeNamesAll[. = $placeName]/ancestor::body//placeName[@type='address' and not(. = $placeName)])
else '0'

for $place in $places

return concat($placeName, "&#x9;", $placeRefEdgeType, "&#x9;", $placeCountEdgeWeight, "&#x9;", $place, "&#10;"));

let $filename := "nellOutput.tsv"
let let $doc-db-uri := xmldb:store("/db/queries/op", $filename, $ThisFileContent, "text/plain")
return $doc-db-uri
output at :http://dxcvm05.psc.edu:8080/exist/rest/db/queries/op/decOutput.tsv )
````

Any ideas what's going wrong here?

**Comment by spadafour** [comment]
I'm able to output a .tsv file from my code through XQuery, but how exactly are we supposed to view the output in a browser? Am I copying and pasting? I can't seem to get it.

**Comment by RJP43** [comment]
@spadafour I can see your tsv file here http://dxcvm05.psc.edu:8080/exist/rest/db/queries/op/nellOutput.tsv

**Comment by ebeshero** [comment]
@nlottig94 Oops! Sorry I didn't notice this earlier, but there was a typo in the code I posted for you here!
The error is in the line right after the first "for" statement. make sure $witNames is tokenizing $wit, not $wits!
````
for $wit in $wits
let $witNames := tokenize($wit, '\s+')[starts-with(., '#')]
````

If it's set to $wits, it won't do the tokenizing and just stall on the very first one. The `tokenize()` function requires you to work on jsut one node at a time, not the full list of nodes.
