### ISSUE TITLE
Network Analysis 2

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#173]
I think it may be because I'm on a mac, but I'm having a difficult time saving my output as a .tsv and opening it in cytoscape.

Is anyone else having this issue? And would anyone be willing to save my output on their computer and sending me the file to see if I can open it through cytoscape that way?

http://dxcvm05.psc.edu:8080/exist/rest/db/queries/op/myOutput.tsv

**Comment by RJP43** [comment]
@spadafour sure I can push it to the sandbox folder here in the Class-Hub then you can sync your repo and get it right out of your file directory

**Comment by spadafour** [comment]
awesome, thanks

**Comment by RJP43** [comment]
@spadafour ok is should be there now

**Comment by spadafour** [comment]
perfect, got it to load in. Thanks
