### ISSUE TITLE
Cytoscape upload

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/DHClass-Hub#174]
I can't upload my cytoscape session in Box, it says I don't have permission in either the folder from last semester or the new one, which I can't even open...

**Comment by nlottig94** [comment]
@brookestewart I'm having the same issue.

**Comment by ebeshero** [comment]
@brookestewart @nlottig94 I think I need to reset the Box permissions--will do when I come to class in a minute!

**Comment by ebeshero** [comment]
Fixed! I changed the permissions settings so you all can post now. Please upload your .cys sessions (as many as you'd like me to look at) into your Box folders.
