### ISSUE TITLE
PHP-Storm Info. please....

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#178]
@ebeshero here is an issue open to remind you to give us the info. on PHP-Storm.

**Comment by ebeshero** [comment]
So, following up on this a week later (sorry for the delay)-- PhpStorm is a code editor optimized for JavaScript and CSS as well as PHP--and for these technologies, especially JavaScript, it's got a better code editor than oXygen. (And oXygen is a lot better for anything with XML and angle-brackets syntax.) If you want to keep learning more coding related to this course and dig into more JavaScript animations and learn what PHP is all about (for dynamic server side operations) I highly recommend checking this out. It comes with tutorial access, too! 

Students get an absolutely free subscription to PhpStorm, together with lots of other nifty Jetbrains coding resources. Follow the links here for student complimentary downloads: https://www.jetbrains.com/phpstorm/buy/#edition=discounts
