### ISSUE TITLE
Regex Help!

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#18]
@ebeshero I am trying to find all of the Roman numerals in the Sonnets.  However, when I use [IXCLV]+ to find all of the Roman numerals, oXygen also highlights all of the lines that start with or have the letters I, X, C, L, and V in them, such as the lines that start with 'If' or 'Look'.  I was wondering if you could help me out here!  Thanks a million!

**Comment by ebeshero** [comment]
@nlottig94 Aha! Think of a strategy to eliminate those lines. You don't want a Roman numeral to follow with anything else but a Roman numeral. First of all, make sure you have selected "Case Sensitive" in the "Find/Replace" window (don't make the same mistake I did in class yesterday)! But it'll still pull all the cases where you have only *one* letter "I" in the text followed by anything else, so you need to develop a delimiter to prevent that...

**Comment by ebeshero** [comment]
@nlottig94 Think about what differentiates the lines that only have Roman numerals on them from the ones that start with a capital letter in the Roman numeral character set...

**Comment by nlottig94** [comment]
@ebeshero I tried [XCLIV][XCLIV]+, but this finds all of the Roman numerals except the ones that contain only one letter...Is there any way that I can indicate I want to find all I, L, C, X, and V's that are not  followed by lowercase letters?

**Comment by ebeshero** [comment]
@nlottig94 Yes, there's a way! Think about what is actually following the Roman numerals, and what makes this different from the line of text.

**Comment by ebeshero** [comment]
@nlottig94 Let me know if you want a stronger hint! But think about the *positioning in the document*: Those Roman numerals have a lot of *space* around them...right?

**Comment by nlottig94** [comment]
@ebeshero I think I found it!  I typed in [XCVIL]+</line>

**Comment by ebeshero** [comment]
@nlottig94 Well, the order of those letters inside the square brackets doesn't really matter to identify the character set. So if that made a difference it might be because of something you entered *afterwards*. You could enter that character without it showing in the box, but it's something probably best identified with a regular expression. I'm dropping all kinds of hints now!!!

**Comment by nlottig94** [comment]
@ebeshero I thought I would add \n to the end of the boxed characters, but it won't recognize it because of the line end tag.

**Comment by ebeshero** [comment]
@nlottig94 You're on the right track...Try the other character that includes "newline" as a possibility among other kinds of space.

**Comment by nlottig94** [comment]
@ebeshero  Okay, I tried the \s and it is still highlighting the I's in the document.

**Comment by nlottig94** [comment]
@ebeshero I tried the \s and it won't select the Roman numerals at all.  I am very stuck on this even after reading the Regex Intro multiple times.

**Comment by nlottig94** [comment]
@ebeshero I am able to use: ^([XCVIL]+)$  to find all of the Roman numerals BEFORE I wrap the lines if this helps any....

**Comment by ebeshero** [comment]
@nlottig94 Sorry I was away for an hour...Hope you figured it out! You're really close. Try designating multiple spaces, not just one.

**Comment by ebeshero** [comment]
@nlottig94 Also, I just realized before that I wasn't able to read your line earlier! You found your solution already, I think! Earlier when you posted, I couldn't see that you put  `</ line>` tags in your file--somehow I didn't see that in your comment when I read it. 

I hadn't anticipated you'd begin that way, though it's a great strategy. (Basically, there are lots of different ways to approach the assignment.) I was actually assuming you had not added any tags to your document yet. So I had you hunting for white spaces and newlines without realizing you'd already changed your document so those weren't there. You were right earlier--as long as you found a way to isolate only the Roman numerals, you have a solution! 
`[XCVIL]+</ line>` should work!
So should  `^([XCVIL]+)`

Don't forget (anyone reading this) to use the **`** character to help show coded lines and special characters in markdown when you post to GitHub!
