### ISSUE TITLE
T-shirts for Our Class

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#181]
@laurenmcguigan @mmm202 @jlm323 @mjb232 @spadafour @RJP43 @brookestewart @nlottig94 @ghbondar 

We want to make T-shirts for our class, and we now need everyone's help quickly. I'll need to place an order for T-shirt colors and sizes on Monday before 4pm, **so I'll need to hear from each of you by class time on Monday 4/11**. 
Note: **We'll buy shirts for all the new students**, but returning students will be asked to pay the production cost of a shirt, if you'd like one--somewhere between $10 and $15. 

Greg and I spent some time with the network graphs you plotted last week, and we opted for one that I made out of [a selection out of Lauren's place network graph from the Decameron](https://github.com/ebeshero/DHClass-Hub/blob/master/Network-to-TShirt/DecameronFlorentinePlaces_transp.png).  This will be the main design of the shirt, and when we go to Big Frog, we'll add the following somehow prominently on the shirt:
### newtfire.org

Big Frog has been terrific for working with us on small batches of shirts, and I've learned it's best to go there with my major graphic in hand (this one) on a transparent background, and work with them on the fonts and colors. They'll make a prototype shirt pretty quickly that I'll put up here when it's ready! 

For now, Big Frog just needs to know **what color(s) and sizes** we would like for our T-shirts. To give you an idea, I take an adult medium and Greg takes an adult large. We know we need to work with a light color for the colors to pop and so we aren't paying a lot extra for lots of ink. (Our shirts are made with ink on the cloth--not that nasty plastic-y stuff--so the ink is part of the fabric.) I'm thinking we might want light grey or pale blue shirts this time given the color range of this network plot!  Thoughts?

Here's the full list of T-shirt colors we can order from: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentcolor=51&cs=Sh

I'm thinking of these colors (and you might want to indicate a color you like: we can ask to order it in your size on Monday by 4pm):

* SAND: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=18

* LIGHT BLUE: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=64

* ASH GREY: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=50

Would you write me an e-mail or respond here with your preferred size and color? I'll place the shirt order on Monday and then we'll work on the design through the week, to plot our class info around the network graph!

**Comment by laurenmcguigan** [comment]
I would pick the ash grey! Also, I think I would wear an extra small, but if that is not available, small is fine!
On Apr 9, 2016, at 8:36 PM, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> wrote:


@laurenmcguigan<https://github.com/laurenmcguigan> @mmm202<https://github.com/mmm202> @jlm323<https://github.com/jlm323> @mjb232<https://github.com/mjb232> @spadafour<https://github.com/spadafour> @RJP43<https://github.com/RJP43> @brookestewart<https://github.com/brookestewart> @nlottig94<https://github.com/nlottig94> @ghbondar<https://github.com/ghbondar>

We want to make T-shirts for our class, and we now need everyone's help quickly. I'll need to place an order for T-shirt colors and sizes on Monday before 4pm, so I'll need to hear from each of you by class time on Monday 4/11. We'll buy shirts for all the new students, but returning students will be asked to pay the production cost of a shirt, if you'd like one--somewhere between $10 and $15.

Greg and I spent some time with the network graphs you plotted last week, and we opted for one that I made out of a selection out of Lauren's place network graph from the Decameron<https://github.com/ebeshero/DHClass-Hub/blob/master/Network-to-TShirt/DecameronFlorentinePlaces_transp.png>. This will be the main design of the shirt, and when we go to Big Frog, we'll add the following somehow prominently on the shirt:

Pitt-Greensburg
Digital Humanities
Coding and Data Visualization

###newtfire.org<http://newtfire.org>

Big Frog has been terrific for working with us on small batches of shirts, and I've learned it's best to go there with my major graphic in hand (this one) on a transparent background, and work with them on the fonts and colors. They'll make a prototype shirt pretty quickly that I'll put up here when it's ready!

For now, Big Frog just needs to know what color(s) and sizes we would like for our T-shirts. To give you an idea, I take an adult medium and Greg takes an adult large. We know we need to work with a light color for the colors to pop and so we aren't paying a lot extra for lots of ink. (Our shirts are made with ink on the cloth--not that nasty plastic-y stuff--so the ink is part of the fabric.) I'm thinking we might want light grey or pale blue shirts this time given the color range of this network plot! Thoughts?

Here's the full list of T-shirt colors we can order from: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentcolor=51&cs=Sh

I'm thinking of these colors (and you might want to indicate a color you like: we can ask to order it in your size on Monday by 4pm):

  *   SAND: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=18

  *   LIGHT BLUE: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=64

  *   ASH GREY: https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=50

Would you write me an e-mail or respond here with your preferred size and color? I'll place the shirt order on Monday and then we'll work on the design through the week, to plot our class info around the network graph!

**Comment by mjb232** [comment]
Im also down for ash grey and i will take a medium please!

**Comment by jlm323** [comment]
I like the light blue shirt. I'll take a size small.

**Comment by mmm202** [comment]
I would like the ash grey and extra small if available if not then small

**Comment by nlottig94** [comment]
Could I get a large in the ash grey, please :)

**Comment by RJP43** [comment]
I emailed you, but for the sake of keeping everything together I will take an ash grey 3XL. Thank you!

**Comment by ebeshero** [comment]
Orders are in and they say shirts will be printed on Wednesday!
