### ISSUE TITLE
Presentation Schedule Next Week

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#182]
@laurenmcguigan @jlm323 @mjb232 @mmm202 @RJP43 @spadafour @nlottig94 @brookestewart 
Each of you, would you respond to this and verify that you're okay with this presentation schedule in Oakland next week? Which of you will need rides,many which of you are willing to drive? (@ghbondar and I can take 2 or 3 of you, if we leave campus around 8:45am).

W 4/20  Emily Dickinson Team
              Decameron Team
             (one Obdurodon team)

F 4/22. City Slave Girls Team
        (two Obdurodon teams)

Is everyone available to participate in these presentations as slated? David needs to prepare text for posters this afternoon, so please respond quickly.

**Comment by laurenmcguigan** [comment]
What time would we be back on the 22nd? I have a study abroad meeting for Florence at 11am. I am good for Wednesday, but I would probably need a ride. @mjb232 said he could pick me up, but he would have to pick me up from my house because my sister needs the car at 12:30. Unless we would be back before then??

**Comment by ebeshero** [comment]
@laurenmcguigan David's class runs from 10 - 10:50am MWF, so probably it is best you don't come on F, if you need to be back at 11! But as long as you and Team Decameron are good for Wed., we'll be okay! 

We *could* put all three Greensburg groups on W, but then we wouldn't get to see any of their presentations, so I hope this schedule works so we have some shared feedback. For @RJP43 it's a tight turnaround from Thurs. eve capstone presentation to Fri. morning, but I hope @spadafour can help!

**Comment by RJP43** [comment]
@ebeshero I am fine with it.

**Comment by ebeshero** [comment]
@laurenmcguigan it takes about 45-50 minutes to drive between Oakland and Greensburg...you could probably return to Greensburg by 12:30, if you want to do that, but if you want to stomp around Pittsburgh a little, have lunch, etc, maybe you want a ride!

@ghbondar needs to be back for his 1pm class, so those riding with us either day have a way back to Greensburg by 1pm.

**Comment by ebeshero** [comment]
OK--I know @nlottig94 is better for W than F, so I will report this schedule to David. Keep us posted here about rides--if you need one, and where you'd need to be picked up if you are in the Greensburg area around 8:30am either day.

**Comment by brookestewart** [comment]
I was in class, so I was unable to answer on such short notice. I have class both days at 9:30 and 1. I could skip the first one if I have to, but it's going to be inconvenient. If it's mandatory to attend, I will need a ride.

**Comment by ebeshero** [comment]
@brookestewart These are our project presentations, and it's best if you and Nicole present your work together on Wednesday. (Since you are a two-person group, it's probably not nice to Nicole to make her present alone.) Let's work out a ride for you.

**Comment by ebeshero** [comment]
Everyone: Here's the full presentation schedule they're about to post, with our groups presenting on W and F. 

### 2016 UNDERGRADUATE RESEARCH AND CREATIVITY 
## Digital Humanities Undergraduate Project Showcase

#### M 4/18, W 4/20, F 4/22 @ 10 – 10:50 am
#### Cathedral of Learning G-27, Computer Lab Classroom

Students in Digital Humanities courses from two Pitt campuses join together to present their semester projects:

*  Pitt Honors College: Computational Methods in the Humanities (Prof. David J. Birnbaum)
* Pitt-Greensburg: Coding and Data Visualization (Prof. Elisa Beshero-Bondar)

M 4/18: **“The Klingon Hamlet: A Digital Humanities Compendium”** (Pittsburgh: Ryan Schroeder)
**“Jordanian Arabic: Spoken Grammar Variations”** (Pittsburgh: Amber Montgomery)

W 4/20: **“Emily Dickinson’s Poems: Variants in Fascicles 16 and 6”**  (Greensburg: Nicole Lottig and Brooke Stewart)
**“A Linguistic Analysis of Game of Thrones: A Song of Ice and Fire”** (Pittsburgh: Shannen Davis, Jerri Quenee, Lilija Riley)
**“Bocaccio’s Decameron: A Study of Places and Narrative Structure”** 
(Greensburg: Matthew Burch, Jessica Milewski, Lauren McGuigan, and Megan Mills) 

F 4/22:  **“Musicality of Phrase: An Analysis of Five Songs by Andrew Lloyd Webber”** (Pittsburgh: Allie Roos, Lauryn Morgan Thomas)
**“The Restoration of Nell Nelson and the Chicago Times’ Series: ‘City Slave Girls’”** (Greensburg: Rebecca Parker and Rob Spadafore)

Sponsors: [Pitt Digital Humanities Research Group](http://dhrx.pitt.edu)
[Pitt-Greensburg Center for the Digital Text](http://greensburg.pitt.edu/digital-humanities)

**Comment by brookestewart** [comment]
Nicole can give me a ride back to Greensburg, so I just need a ride down to Pittsburgh.

**Comment by RJP43** [comment]
@nlottig94 and I will be driving from the Plum Borough area (east of Pittsburgh) to Oakland on Wednesday and I will be hitching a ride with her and @brookestewart back to Greensburg before 1pm. However, Nicole is thinking she will not be able to go on Friday so I will likely drive myself down and back on Friday (again from the Plum Borough area, which is approx. 40 minutes from campus). If there are not enough people available to drive from Greensburg on Friday I would be willing to come to campus and take a group with me; however, I will not be able to drive back to Greensburg on Friday after the presentations.

**Comment by ebeshero** [comment]
@ghbondar and I can take people from Greensburg campus (or area) and return to campus by 12:30/12:45ish on W and F.

**Comment by nlottig94** [comment]
As @RJP43 said, I can bring anyone back to Greensburg on Wednesday if they need to be back before 1pm.
