### ISSUE TITLE
JavaScript Garden

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#185]
Here's a really helpful resource I just landed on today, called JavaScript Garden:
http://bonsaiden.github.io/JavaScript-Garden/
It claims to cover what's "quirky" about JavaScript, and I think its CSS is easy on the eyes and great for reading code snippets. The site editors say that visitors should come to the site with some basic understanding first, but I think the materials are quite accessible to us based on what we're covering in the DH coding classes! What I especially appreciate is that they give some really clear explanation to the particularities of JavaScript syntax: for example, _why_ we write and call variables and functions the way we do, and just _what_ JavaScript is doing with those double and triple comparison operators to "coerce" type comparison. It's a great read and since JavaScript periodically flummoxes me, I know I'll be revisiting it frequently!

**Comment by RJP43** [comment]
When investigating the option to random generate colors using javaScript @Ampzilla and I discovered [this interesting site](http://randomstringtocsscolor.com/) that randomly generate a hex value for strings of text.
