### ISSUE TITLE
Regex: If You Could Use it Outside <oXygen/>, Where Would You Use It?

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#19]
So, if you could use regular expression matching outside of `<oXygen/>`, where can you imagine using it? We actually can use regular expressions in lots of everyday applications, and perhaps you've used a version of regular expressions before. This is an Issues post designed to collect your ideas and see where we might apply this powerful technology elsewhere!

**Comment by spadafour** [comment]
I'd really love to use regular expressions in my google searches. Google offers key word searches, but getting super specific with search fields would be wonderful!

Here's a video about why that won't happen, though, as explained by Google webmasters:
https://www.youtube.com/watch?v=lYiTIDgejas

Basically, the huge amount of resources it would take to support this feature far outweighs the tiny user base interested in it.

**Comment by nlottig94** [comment]
Regex could really be useful in organizing documents only for myself, such as my capstone proposal.  This way, I could organize my thoughts after I have the initial draft done and then go back and see what needs to have a stronger argument or more supporting facts to it.  Overall, it would really help to organize my papers into some sort of outline form!

**Comment by KariWomack** [comment]
I could definitely use regular expressions in Library searches for research projects! It would make searching for specific topics and areas of interest soooooo much easier instead of having to shuffe manually through a lot of information.

**Comment by ebeshero** [comment]
Actually, you may have already used a form of regular expressions in Library searches if you have hunted for words and phrases in ECCO and EEBO for Prof. Greenfield's classes...The searches involve plugging in special characters to screen out mismatched characters when computer scans of old books and newspapers don't properly recognize particular blobs of ink or faded spots on the page as the right letter of the alphabet or the right punctuation mark. You learn how to match on *any alphanumeric* character, for example, to pull up better search hits!

Great examples so far! Keep them coming! :+1:

**Comment by ebeshero** [comment]
By the way, the process in which computer software scans an image, say a photo of a document, and *recognizes* text characters, is called *optical character recognition* or OCR, and it's comparable to speech-to-text translation software--converting some non-text media input into text output. These systems are hard to *train* (as we've many of us seen with talking into our mobile devices)! Could regular expressions help with problem text generated by such software? Think about how...or would such texts be too unpredictably error-ridden?

**Comment by CodyKarch** [comment]
It may seem like a bit of a stretch, but I was thinking that since Regex focuses on the meta-textual divisions of writing, it could be used for studying language evolution. There seems, to me, to be the difficulty of vocabulary changing, but in what I see, Regex is held more heavily on "alphanumerics" or "newlines" or "whitespace". From this, I mean that the grander disconnections among a text might actually help to illustrate the temporal connections as well.

**Comment by blawrence719** [comment]
I think that regex could be useful in my writing. I write a lot of poetry and think that regex could be used during editing for finding articles that aren't necessary or even finding repeated phrases that need to be changed. This could make the editing process a lot easier - I have one poem in mind where I manually changed the word "strawberry" to "blueberry" several times. It would've been easier to just find/replace these items.

**Comment by brookestewart** [comment]
I would like to be able to use it to organize titles of documents or songs in my music library. Sometimes there will be a title that has a space in the beginning and it will mess up the alphabetical order and such. It would make it so much easier if you could easily find those titles and remove the extra spaces. It seems like a trivial way to use regex, but it definitely gets frustrating trying to do each one manually.

**Comment by amielnicki** [comment]
Regex might be useful editing lengthy word, excel and powerpoint documents. I always have to work with these types of files at work and consistency is everything. If I change how something looks one place, the entire document has to match. If it was just a matter of writing some Regex, that would be so much easier!
