### ISSUE TITLE
Git Hub exercise 1: Adding Collaborators

### ISSUE THREAD

**Issue by msb81** [ebeshero/DHClass-Hub#190]
How do we know we've been add as a collaborator to Dr.B?

**Comment by ebeshero** [comment]
@msb81 Hi Madison! I just added you...

**Comment by ebeshero** [comment]
Everyone--"ping" me from this Issue when you are ready for me to add you as a collaborator on this DHClass-Hub. Use '@ebeshero' in your post to signal me directly.

**Comment by setriplette** [comment]
@ebeshero please add me as a collaborator!

**Comment by ahunker** [comment]
@ebeshero please add me as a collaborator

**Comment by ebeshero** [comment]
Done! Welcome @ahunker and @setriplette !

**Comment by jonhoranic** [comment]
@ebeshero Hoping this is the proper place to "ping." This is Jon Horanic asking to become a collaborator!

**Comment by ebeshero** [comment]
@jonhoranic I've just invited you!

**Comment by GitPitt-TutorialProfile** [comment]
@ebeshero can you add me as a collaborator please :)

**Comment by etj27** [comment]
@ebeshero  Oi, I'm a guy, add me as a collaborator.  Thanks senpai

**Comment by asf46** [comment]
@ebeshero im asf46, please add me :)

**Comment by jaketm** [comment]
@ebeshero im jaketm add me!!!!

**Comment by PPH3** [comment]
@ebeshero Can I climb aboard the mother-ship? PPH3

**Comment by JaredKramer40** [comment]
@ebeshero can you add me! JaredKramer40

**Comment by mjb232** [comment]
@ebeshero Hit me up yo!

**Comment by ebeshero** [comment]
You're already in, Matt!

**Comment by mjb232** [comment]
@ebeshero I just like feeling special is all

**Comment by ebeshero** [comment]
##Super Large Heading!!!
