### ISSUE TITLE
How I work with GitHub (steps recorded from class on 9/2/2016)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#193]
I switched to a Mac this summer, and didn't install the Desktop client at all when I installed Git. I just cloned my repositories inside the Mac command line terminal, and I configured my GitHub account there, too, in a few careful but quick steps. Here's [the Mac-specific documentation](https://help.github.com/articles/set-up-git/) I followed, which is really close to what you'd do on a PC in the Git Bash shell. The git commands are ALL the same in both environments. 

The key thing to me in working with GitHub is that **I always need to know where to find my files in the Finder and in the Terminal**. So I need to save them in a place where I can easily see them. 
- In the Finder, I just made myself a "GitHub" directory that lives inside "Documents." Inside the "GitHub" directory I clone each of my project repositories.
- In the Mac Terminal (command line shell), I can navigate to my directory from my computer's root by typing:
  `cd Documents/GitHub/`
  **cd means "change directories"** and here I am _stepping down_ into Documents and into GitHub. I usually pause there and take a look down at what I have inside, by typing **`ls`** (which means, list out what's inside this directory).
- If I need to **clone** a repository, I do so here, because then the new repository will sit as a _child_ inside my GitHub directory. I go to the git remote website and get its Download/Clone URL by copying it. 
  Then I type `git clone` and paste in the the URL after that. so it looks like this for our DHClass-Hub:

```
git clone https://github.com/ebeshero/DHClass-Hub.git
```

I hit enter, and watch the lines scroll away in the command line terminal as the repository clones itself on my local computer inside my GitHub directory. 

2) I interact with my local directory the way I would any other. I drag files into it using the Finder. I save files into it. And I check in with the remote repository to **pull** new files in. So this is what I do:
I open my Terminal, and I step down into my GitHub directory, and then down into the DHClass-Hub, and check that I am where I think that I am, **by typing `ls`.** The ls command **shows me the contents of the directory** in which I've positioned myself.  
- To make sure I'm in the right directory, the top level of the DHClass-Hub, I also check to see the directory name at the terminal prompt. Mine looks like this right now, and the key part is "DHClass-Hub":
  `gbg-wireless-pittnet-150-212-105-8:DHClass-Hub ebb8$`

Then to pull in any changes from the remote "mothership" repo, I type:

```
git pull
```

3) When I want to share my local files with the remote mothership and my collaborators, I need to **add**, **commit**, and **push** those changes. Here's how I do it:
- I make sure I'm in the DHClass-Hub repo at the top level
- Then I type:

```
git add .
```

The period means _all_-- add _all_ new files to be tracked by Git.
- If I type `git status` at this point, I see highlighted the new files I'm going to add! 
- Now, I need to **commit** those changes. I type the commit, and write a message, because Git _always_ makes me document my changes when I push to a remote "Mothership" repo:

```
git commit -m "I'm committing a picture of a llama to the DHClass-Hub Sandbox"
```
- Next I push the commit through, with this:

```
git push
```

And gears turn and lines of text whirl on the screen, and my file goes up into the remote Mothership repo! I always check on the web repository to see if my commit went through. 

That's how I do it.

**Comment by RJP43** [comment]
https://github.com/ebeshero/DHClass-Hub/blob/master/Git_BasicCommands.md

**Comment by Jamielynn92** [comment]
is this also to push the picture.. I did my repository but I'm sorta confused. thanks Jamie.

**Comment by ebeshero** [comment]
@Jamielynn92 Yes, you should be able to use this to push a picture, like we talked about in class. 👍
