### ISSUE TITLE
Discussion on Kirilloff and Other Passages

### ISSUE THREAD

**Issue by msb81** [ebeshero/DHClass-Hub#194]
Before this class, I really had no idea what digital humanities even was or what our class would even entail. In her essay, Kirilloff says how digital humanities is becoming an increasing subject of academic study, which I never knew. She also states how the relationships have changed between reader, scholar and the text itself. I never thought of these 3 things ever having a relationship but after she explained it I can now clearly see one.

**Comment by ebeshero** [comment]
@msb81 Aha! I see how I nearly didn't find your post! The rest of the discussion is going on over here: https://github.com/ebeshero/DHClass-Hub/issues/192

Want to repost over in that thread?

**Comment by msb81** [comment]
Could you please... I'm still trying to figure out github. Lol

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Sep 6, 2016 at 7:42 PM -0400, "Elisa Beshero-Bondar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@msb81<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fmsb81&data=01%7c01%7cmsb81%40pitt.edu%7ce9e82f0d4cd943ca766608d3d6af856a%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=1nYBE%2bOx1nm5bTCrKXtOt6nE0ot6n0JpnuM0lYUjT%2bM%3d> Aha! I see how I nearly didn't find your post! The rest of the discussion is going on over here: #192<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2febeshero%2fDHClass-Hub%2fissues%2f192&data=01%7c01%7cmsb81%40pitt.edu%7ce9e82f0d4cd943ca766608d3d6af856a%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=AUifkni50I3ZbI239YmNw88ylyAq66HV8Vw9RaH6V4g%3d>

Want to repost over in that thread?

-
