### ISSUE TITLE
Relax NG issue, and IDREF hashtag question

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#197]
I'm getting a syntax error on line, at the very bottom of my schema. Can anyone help me see why? I'm also really unsure about all the places where I put in parentheses to group up things--still not quite getting whether they need to be grouped.

start = epic
epic = element epic {front, \div+}
front = element front {mixed {commendPoem* | dedication* }}
commendPoem = element commendPoem {lg, type}
lg = element lg {type, lg*, line+}
type = attribute type {text}
dedication = element dedication {mixed {(persName+ | placeName)*}}
persName = element PersName {mixed {ref}}
ref = attribute ref {text} #How do I communicate that I want a hashtag in front of ref?
placeName = element placeName {text}
\div = element div {type, n*, lg*}
n = attribute n {xsd:int}
line = element line {mixed {(persName | myth | placeName | animal)*}}
animal = element animal {text}
myth = element myth {text}

**Comment by ebeshero** [comment]
@setriplette Hmmm. I'm not seeing an error with your schema. I pasted your text into a new Relax-NG Compact Syntax file and it looks to my oXygen as if all is well. Can you tell me more about the error you're seeing? 

To answer some of your questions:
* #How do I communicate that I want a hashtag in front of ref?
For that, you'll need to work with *regular expressions* (which we'll be learning a couple of weeks). A *regular expression* basically is a way of specifying a pattern of text, and if we use them in writing a schema, we can specify that we want a particular character followed by a symbol that indicates *any* character, or any alphabet character or a combination of letters + numbers.  (One of the fun things we're starting to learn about is how to distinguish different kinds of "text" in writing code.) In schema writing, what you'd be doing is essentially writing your *own* data-type by writing out a regular expression pattern that starts with a literal hashtag and is followed by some quantity of any character. If you want to explore ahead of our regular expressions unit, you can read more about how to write regular expressions (or "pattern facets") in Relax-NG here: http://books.xmlschemata.org/relaxng/relax-CHP-9.html 

* On grouping with parentheses, and using repetition indicators: I'll be concentrating a lot more time on this on Monday!

**Comment by ebeshero** [comment]
@setriplette On the hashtag question, you'll be interested in two datatypes:
xsd:id and
xsd:idref
I am reading up on this now, because it's not clear to me where the hashtag comes into the datatype definition for the idref! ... I'll keep posting as I read more.

**Comment by setriplette** [comment]
I did what you did and pasted what I had pasted into a new document. No error now. Could this have been an invisible characters thing?

**Comment by ebeshero** [comment]
Not sure, but I am glad it is working now! I'm reading up on ID, IDREF, and IDREFS (which is how you specify that you're okay with an attribute referring to *multiple* ids separated by whitespace. I want to take a look at how we poke hashtags around idrefs, because I'm having trouble finding examples of that...

**Comment by PPH3** [comment]
I know I have to code for my paragraph content {mixed {( etc, but when I do, I get an error reading "repeat line or data."


start = letter 
letter = element letter {author, salutation, p+}
author = element author {text}
salutation = element salutation {text}
p = element p {text}                     --when I code for this, I get the error
criticism = element criticism {text}
ref = attribute ref {"childe harold"| "pre-christian"| "christianity"| "non-jew
language = element 
religious = element religious {text}
figure = attribute figure {"iranian"}
muslims = element muslims {text}
philosopher = element philosopher {text}

**Comment by ebeshero** [comment]
@PPH I think we must be missing part of your code! Try using that markdown code with "tick marks" for showing code exactly as you've written it and paste it inside. Also, maybe push your code into Troubleshooting here on the DHClass-Hub so we can pull it in and take a look...!

From what I can see here, there ought to be an error on your line about the **ref** attribute, because your last value is missing a quotation mark and the closing curly brace, but I wonder if your code actually has that stuff... ? Show us the code that gives you the error on **p**: Might be how you're writing the `mixed{ }` part...

**Comment by PPH3** [comment]
Here's the whole code. The error occurred when I tried to code  within my "p" element. This is error free as I have it now, but I know I need to code for all of the other elements, attributes, etc. within my paragraph element line.


start = letter 
letter = element letter {author, salutation, p+}
author = element author {text}
salutation = element salutation {text}
p = element p {text}
criticism = element criticism {text}
ref = attribute ref {"childe harold"| "pre-christian"| "christianity"| "non-jew"| "greek"| "persian"}
language = element language {text}
category = attribute category {"latin"}
religion = element religion {text}
religious = element religious {text}
figure = attribute figure {"iranian"}
muslims = element muslims {text}
philosopher = element philosopher {text}

**Comment by ebeshero** [comment]
@PPH3 sorry for the delay! It sounds like you might need some help with how to write a rule for mixed content inside those paragraphs. Remembering your XML file, I think you had a pretty free-floating sequence of elements, so it wouldn't matter in what order they appeared. Also, you wouldn't necessarily want to demand that every one of these elements appear in a paragraph: they might or might not show up, right? So I'd group them using "or" pipes, and use an asterisk to say, *any* of these might appear, zero or more times. 

Notice how the curly braces nest when you use **mixed{ }** syntax:

````
p = element p {mixed{(criticism | language | religion | religious | muslims | philosopher)*}}
````

One more thing about **mixed{ }**: You really mean it for elements that sit alongside text. Keep the attributes on the p element out of the mixed soup, just to help distinguish them (this is for human readability of your schema. I always stick the attributes at the end. So, say I wanted to position an `@n` attribute on p, together with this mixed syntax we're working on. Here's how I'd do it:

````
p = element p {mixed{(criticism | language | religion | religious | muslims | philosopher)*}, n}
n = attribute n {xsd:int}
````

**Comment by ebeshero** [comment]
@setriplette At the end of the day I've learned that you actually can't make the rule that binds a hashtag to an xsd:IDREF in Relax-NG. There's a reason I've been doing that Schematron, the *other* schema writing language we'll be learning next month! Anyway, what you *can* do in Relax-NG is work with xsd:ID and xsd:IDREF (and its friend, xsd:IDREFS when you want room for a plural list of pointers back to an xml:id). 

Here's the monster list of xsd datatypes: click on each one to see what it's for and how it works: these are fun to define in a Relax-NG schema!
http://books.xmlschemata.org/relaxng/relax-CHP-19.html

**Comment by etj27** [comment]
In this assignment, as we are associating our Schema code and troubleshooting to solve problems, are we allowed to change some of the source material from the exercise we are doing the Schema for to make things easier?

**Comment by ebeshero** [comment]
@etj27 Yes, definitely DO change your original code. (Okay, you don't *have* to, but it's really a good idea, and we'll be happy to see you make changes!) That's half the fun of schema writing is coming up with a different way of writing your XML in the first place! 👍

**Comment by etj27** [comment]
@ebeshero That is great!  While writing the code I had come across some things that were in my way in the original code so I just on instinct changed it to make everything easier.  Also, just a random question, is the purpose of this activity to write a schema code that is errorless when you associate it to the XML document?  If so, then I've done that.

**Comment by ebeshero** [comment]
@etj27 The purpose is twofold:
1) To write a schema in good Relax-NG syntax (so you can use it to govern the coding of an XML file by "associating the schema", and
2) To make your XML writing more systematic, following rules that you yourself lay out to govern it--and that almost always involves altering the first XML you wrote!

**Comment by etj27** [comment]
@ebeshero Okie-dokie thanks for clarifying

**Comment by ebeshero** [comment]
So--to clarify this more (and not just for @etj27) : 
* As you're all writing the schema code, *before* you associate it with an XML file, you're trying to get the schema to "go green" in oXygen, to make sure you've written the rules correctly.
* *After* oXygen gives you the green light on your schema, you go to *associate your schema* with your XML file to make sure it works. At that stage, you may actually *want* to see some red error flags go off on your XML file: that tells you that your schema rules are firing and finding conditions that break the rules you defined. 
* When you see that, you want to try to solve the problems: either by changing the code of your XML or by refining your rules over in the schema. Ideally you conclude the exercise with a green box on both the XML and the Relax-NG. That will mean that you have *valid* XML according to the good rules that you have defined in Relax-NG.
