### ISSUE TITLE
Relax NG Issue

### ISSUE THREAD

**Issue by msb81** [ebeshero/DHClass-Hub#198]
Okay, so not to sound stupid or anything but I have no idea how to create my schema or how to group these together. I think I did it right by oXygen keeps telling me I have a syntax error... @ebeshero, I tried doing what you suggested to Dr. T and its not seeming to work for me. I've been looking at this code and I just can't seem to figure out what I keep doing wrong. Can you look at it for me? 

datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

element test { xsd:double }
start = root
root = element root
letter = element letter {introduction, startLetter, dialogue, conclusion}
introduction = attribute introduction
background = attribute background
quote = element quote
date = element date
dialogue = attribute {speaking, girl1, girl2, man, government}
narrorator = element narrorator

**Comment by ebeshero** [comment]
@msb81 It looks like you haven't finished defining some of these rules, in particular for:
* introduction
* background
* quote
* date
* narrorator  (and don't you mean "narrator" here? You probably don't want to spell it that way in your XML!)

To define the content of each of these, you need a statement inside curly braces. Here is an example of a complete rule, if your introduction is an *element* that contains *one or more **p** elements inside*:
introduction = element introduction {p+}

Here's another example: If your element *narrator* has only text inside (and no more elements), you might define that like so:

narrator = element narrator {text}

Things get more complicated when you have an element that can contain text as well as other elements . That's when we pull out the **mixed{ }** syntax which you should read about on the tutorial. We have some examples of that in the file we worked on in class on Friday--pull it in on your GitHub and take a look. Hope that helps!

**Comment by msb81** [comment]
Well now the syntax error is gone, but now its telling me I can't have this type of content in the prolog. 

datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"
element test { xsd:double }
start = root {text}
root = element root {text}
letter = element letter {p+}
introduction = element introduction {p+}
background = attribute background {p+}
quote = element quote {p+}
date = element date {p+}
startLetter = element startLetter {p+}
dialogue = element dailogue {p+}
speaking = attribute speaking {p+} 
girl1 = attribute girl1 {p+}
girl2 = attribute girl2 {p+}
man = attribute man {p+}
government += attribute government {p+}
narrator = element narrator {text}

**Comment by ebeshero** [comment]
@msb81 I usually delete the first two lines that come by default in the Relax-NG code: the one on datatypes and the element test, so I start with a blank slate. I don't know if that's causing your prolog problem or if it's just some white space, but try making the file just start with your word "start".

WARNING: You are also going to notice some serious problems with this when you associate with your XML: Did you ever define `p`?  Usually `<p>` is an element, so does it make sense for it to be the content of an attribute? Not only do you need to write the rules, but they need to suit your XML. It's fine to edit your XML, by the way--you'll probably want to make some changes to both the XML and the schema file!

**Comment by ahunker** [comment]
@ebeshero I'm having some issues with my Relax NG as well. I have the error "repeat of 'string' or 'data' element" regarding the fourth line (form = attribute form). I'm not quite sure what this means and how to fix it. Help would be greatly appreciated.

start = element gazpacho_recpie {ingredientList, method}
ingredientList = element ingredientList {ingredient+}
ingredient = element ingredient {form*, unit*, n*}
form = attribute form {mixed {("chopped"* | "liquid"* | "granulated"* | "spice"*)}}
unit = attribute unit {mixed {("6cups"* | "0.25cups"* | "1cup"* | "1-2Tbsp"* | "2Tbsp"* | "1tsp"* | "1Tbsp"* | "2tsp"* | "6drops"* | "2cups"*)}}
n = attribute n {xsd:int}
method = element method {step+}
step = element step {n+}

**Comment by setriplette** [comment]
@ebeshero I think the trouble is with putting mixed content inside an attribute rather than an element. Is that right? An attribute shouldn't have a lot of text, just your designated values, like say
`<ingredient attribute="chopped">tomato</ingredient>

**Comment by ebeshero** [comment]
@setriplette @ahunker Yes, that's right! The problem is the use of **mixed{ }** syntax in that line. We wouldn't use **mixed{ }** for attribute values because that really isn't mixed content. Mixed content is when we have an element that contains *text that surrounds other elements*, sort of a text "soup" or "salad" with crunchy element nuggets floating around inside! (It's dinner time...) ;-)

So here, pull the mixed content out, and just define your list of attributes and I think you'll solve this problem.

**Comment by ahunker** [comment]
I have removed the mixed {} and am still getting the same error in the same place.

start = element gazpacho_recpie {ingredientList, method}
ingredientList = element ingredientList {ingredient+}
ingredient = element ingredient {form*, unit*, n*}
form = attribute form {"chopped"* | "liquid"* | "granulated"* | "spice"*}
unit = attribute unit {"6cups"* | "0.25cups"* | "1cup"* | "1-2Tbsp"* | "2Tbsp"* | "1tsp"* | "1Tbsp"* | "2tsp"* | "6drops"* | "2cups"*}
n = attribute n {xsd:int}
method = element method {step+}
step = element step {n+}

Am I still not defining my attributes correctly?

**Comment by ebeshero** [comment]
@ahunker Well, you only expect to ever have *one* attribute, not zero or more of it. So I'd remove the repetition indicator on one of your attribute values. Does that solve it?

**Comment by ebeshero** [comment]
@ahunker Defining attribute values is usually easier than defining element contents, because attribute values are simply a string of text, whereas element contents are sometimes a mix of elements and text, and sometimes we want to set the internal elements in a certain order, *and* set attributes on the element. Once you step into an attribute rule, your choices are generally to define specific strings of text (as you're doing here), or to define a datatype (like for a date or an integer) with something like xsd:date or xsd:int, so those rules are usually a little more straightforward to write (no repetition indicators necessary)!

**Comment by ahunker** [comment]
I am all green and good to go now, thank you for your help!

**Comment by ebeshero** [comment]
@ahunker Huzzah!
