### ISSUE TITLE
RegEx: Links to Answers for Assignment 1 and Assignment 2

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#20]
http://dh.obdurodon.org/regex-assignment-01.xhtml (Assignment 1)

http://dh.obdurodon.org/regex-assignment-02-answers.xhtml (Assignment 2)

If you just want to look at the Obdurodon Site for examples and tutorials go to http://dh.obdurodon.org/

**Comment by ebeshero** [comment]
Thanks, Becca!
