### ISSUE TITLE
Cool Projects We've Seen

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#203]
This one: [YouTube Comments Study] (http://pacific.pitt.edu/dhds/youTube/index.html)

**Comment by laurenmcguigan** [comment]
I actually really like this project, and liked it last semester as well. If we choose not to continue with Decameron, I think I would be interested in adding to this project. I think it would be interesting to look at some other videos and analyze them. In particular, I think it would be cool to look at coming out videos to compare the negative and positive reactions. The only difficulty with this is that we would nee to mark-up all the comments, which would be very time consuming, but I am into it. 

The only thing I am not sure about is how to include their theme with the news articles, but if someone has an idea on how to include that with coming out videos or other sensitive content, let me know what you think!
