### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#204]
Hi everyone! So I came across this question while I was grading and was wondering if anyone could figure out a solution for it. I'm not even sure if this is possible or not, but if you have time give it some thought and let me know if anyone has an answer for it:

So say you are writing a Relax-NG for a letter coded like this:

```` 
<head>
           <recipient> Professor B </recipient>
          <address> 123 English Lane, PGH PA, 15555 </address>
          <date when="2016-09-14"> September 14th, 2016 </date>
</head>
````
SO, say you are coding a bunch of letters and you want to say that the elements inside `head` (@recipient, @address, @date) can appear in any order, BUT there HAS to be AT LEAST ONE recipient, there HAS to be ONE address BUT no more than ONE, and there could be ZERO OR ONE date. What would be the Relax NG for this? OR Perhaps we have to wait for Schematron to do this?

**Comment by jonhoranic** [comment]
@laurenmcguigan  Hey its me, the one that keeps finding the really (and I mean **REALLY**) strange work-arounds in the Relax-NG schema. I set up the three elements with the specific conditions you asked for, then I used pipes, a whole lot of pipes!

`head = element head {(recipient+, address, date?) | (recipient+, date?, address) | (address, recipient+, date?) | (address, date?, recipient+) | (date?, address, recipient+) | (date?, recipient+, address)}`

Here is the full schema, copy this in and associate it. Then you can mess with the order number combinations and check to see if this crazy work-around is stable.

`start = head
head = element head {(recipient+, address, date?) | (recipient+, date?, address) | (address, recipient+, date?) | (address, date?, recipient+) | (date?, address, recipient+) | (date?, recipient+, address)}
recipient = element recipient {text}
address = element address {text}
date = element date {when, text}
when = attribute when {xsd:date | xsd:gYearMonth | xsd:gYear}`
