### ISSUE TITLE
Can't attach my homework files to CourseWeb

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#207]
It is saying my xml document is a security threat. @RJP43 did the same thing happen to someone else? What was it?

**Comment by ebeshero** [comment]
@setriplette @RJP43 This last happened to @ahunker , and the problem was surprising! It was actually because she used an element named `<script>` in her XML, and CourseWeb thought it was a malicious active script! (Yeesh...) So if you used `<script>`, change the name of that element. (Use find & replace to do it...)

**Comment by setriplette** [comment]
No script. I'm pasting my schema below so other problems can be identified.

````start = frameTale
frameTale = element frameTale {front, \div+, source*}
front = element front {author*, bookTitle, tableContents, dedication}
author = element author {persName+}
persName = element persName {ref?, type?, text}
type = attribute type {"myth" | "animal" | "novella"}

ref = attribute ref {text}
bookTitle = element bookTitle {mixed {(persName | bookTitle | placeName)*}}
tableContents = element tableContents {divTitle+}
divTitle = element divTitle {text}
dedication = element dedication {mixed {persName*}}
\div = element div {type, divTitle, (frame | story)*}
frame = element frame {(p | authorIntrusion)*}
authorIntrusion = element authorIntrusion {(p | s | text | floating)*}
#I'm really struggling with coding authorial intrusions bc they are stretching my hierarchies. They can be outside or inside p and s. They also overlap floating! Also, was this a moment for mixed, and if so, what parts are in the mix and which are out? Help! 
p = element p { (s | authorIntrusion | floating)* }
s = element s {mixed {(persName | placeName | floating  | emotion | bodyFeeling | bookTitle | authorIntrusion)*}}
# s for this text is sentence-like units. Because I've set off the dialogue as floating text, not every s is a full grammatical sentence.
placeName = element placeName {type?, text}
floating = element floating {genre, (speaker | writer)?, gender?, mixed {(p | s | line | persName | bookTitle | emotion | bodyFeeling)*}}
line = element line {mixed {(persName | emotion | bodyFeeling | placeName |bookTitle)*}}
writer = attribute writer {text}
gender = attribute gender {"m" |"f" | "nonBinary"}
speaker = attribute speaker {text}
emotion = element emotion {text}
bodyFeeling = element bodyFeeling {text}
genre = attribute genre {"citation" | "dialogue" | "letter" |"poem"}
story = element story {(p | authorIntrusion)*}

source = element source {text}
#If I were using this in the project I would have xmlids assigned to the persNames, but I did not code quite that deeply for now.
````

**Comment by RJP43** [comment]
Hmmm maybe the attribute value nonBinary ? Not really sure. You can email me your files if you cannot get them into courseweb. Email them to Gmail though cause Pitt email blocks attachments on same basis as courseweb. Rjp396@gmail.com

**Comment by RJP43** [comment]
Actually might be the source element. Could try changing that and/or nonBinary attribute value.

**Comment by ebeshero** [comment]
File size won't be the problem--Did either of @RJP43 's suggestions work?

**Comment by setriplette** [comment]
No, it didn't work. The problem was on the xml and not the relax ng, which was where the word "nonBinary" was. I deleted source on a separate try and it still had the error.

**Comment by ebeshero** [comment]
Right--we figured you showed us the RelaxNG as an overview of your XML, which is what CourseWeb is choking on. So, if changing the XML works, I think we've figured it out, right?

**Comment by ebeshero** [comment]
@setriplette Looks like we only have the Relax NG file, so I take it you need to change the XML. Use Find & Replace to change that nonBinary word. And if that doesn't work, I think we ought to talk to the CourseWeb people about this problem--it's starting to crimp our coding style!

**Comment by RJP43** [comment]
Unresolved, but since the homework is in and we are aware of this issue I am closing this!
