### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#209]
Hi, I was going to get started on the TEI exercise and try and use the things you guys put in as examples but the links lead to nothing, they are broken  (error 404).  

Is there a way to fix them so I can use them as a reference to know what to do?  Thanks!

**Comment by ebeshero** [comment]
Yikes--thanks for the heads up! I'll get on that. I'm surprised the links are broken!

**Comment by ebeshero** [comment]
@etj27 The links on our Markdown page here on the DHClass-Hub work: here's a direct link: https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/Cheese-Straws-Exercise/TEI-Reference.md

That's in the Class Examples --> Cheese Straws Exercise directory here. 

I think the problem must be on my syllabus page so I'll go check that.

**Comment by ebeshero** [comment]
@etj27 I've now repaired the broken links, so you can take a look at some sample TEI files now. Sorry for the confusion and thank you very much for the alert!

**Comment by ebeshero** [comment]
@etj27 I need to make one more repair--the link is broken on the newtFire syllabus too. I'll post here when I've repaired it, but in the meantime you can at least access the sample files from the DHClass-Hub.

**Comment by ebeshero** [comment]
@etj27 All links are updated and should work now! Let me know if anything else looks amiss. I'm closing this issue, but if you see a link not working, please reopen it.
