### ISSUE TITLE
RegEx:  9/28 In-Class Example Working Code

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#21]
\n[A-Z]{2}.+?: --- getting 174 results

**Comment by CodyKarch** [comment]
I had ^\w+ *\w*:\n.+ and found 173. (don't forget the space after \w+)

**Comment by CodyKarch** [comment]
Here is one person and speech that mine didn't pick up: PIERSON (OFF-MIKE):
What's that? Because of the parenthesis

**Comment by brookestewart** [comment]
\n[A-Z]{2,}[A-Z?] found 174 results

**Comment by rCarls** [comment]
^.+\:\n this finds all the speakers' names and, apparently, the one line of text that ends in a colon.

I can get it to grab all of the speech afterwards as well, as long as it is one paragraph. Some of the speeches are more than one paragraph, however. The string for that is ^.+\:\n.+

**Comment by spadafour** [comment]
\n[A-Z (A-Z-)]+:\n    nets me 174

**Comment by amielnicki** [comment]
`^[A-Z \s -]+[() A-Z -]+:$`   found 174 results

**Comment by KariWomack** [comment]
[A-Z]+\s?[A-Z]+:  got 176 results...

**Comment by RJP43** [comment]
Dr. B. working RegEx

Find: \n[A-Z]{2}.+?:
Replace: </sp><sp>\0
