### ISSUE TITLE
Office Hours -- week without Dr. B.

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#215]
Hey everyone (@msb81 @JaredKramer40  @setriplette @jonhoranic @PPH3 @ahunker @etj27 @laurenmcguigan @mjb232), 

I will be on campus every day (starting today) while @ebeshero is away just in case anyone needs any extra help with anything DH. Generally, I can be found in the upstairs lounge of FOB or the library. Use this issue to ping me for one-on-one meetings and to check for updates of where I am, on campus, any given day. I am here for you so feel free to meet with me. You can also email me (rjp43@pitt.edu).

**Comment by RJP43** [comment]
Where I am today (2016-09-22):

        11-12:15  FOB upstairs Lounge (meeting with @PPH3 around noon for brief status check)
        12:15-1:30  Library (meeting with @msb81 to help with RegEx Exercise 1)

**Comment by RJP43** [comment]
Hey everyone (@msb81 @JaredKramer40 @setriplette @jonhoranic @PPH3 @ahunker @etj27 @laurenmcguigan @mjb232),

I will be in the library at the charging workstations (a.k.a. the long tables on the other-side of the stairs on the first level) from 1-3 today available to help anyone with RegEx, Git, or Project stuff.  I can stay longer if anyone needs me to; just ping me here if that is the case.

**Comment by RJP43** [comment]
@JaredKramer40 @PPH3 @setriplette @jonhoranic @ahunker @etj27 @msb81 

I wanted to remind all of you that you can review the [RegEx exercise 1 solution](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/RegEx-Exercises/RegEx_Exercise1-Sonnets_Solution.md) as well as the [steps we took in class on Friday to markup the Lovecraft novel](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/Regex_upConversion/Lovecraft-novel/StepsConvert-TheShunnedHouse_HPLovecraft.md) if you find yourself struggling with [RegEx Exercise 2](http://www.newtfire.org/dh/RegexExerciseBlithedale.html). You, of course, should post a new issue here on GitHub with any specific concerns/problems; we are here to help.  
  
As I mentioned in class on Friday, most of our units from here on out and all of our exams will have [Solutions Posted here](https://github.com/ebeshero/DHClass-Hub/tree/master/Solutions) to GitHub so you should check there frequently. 

I am available for individual meetings every day next week; please let me know if you need any extra help!

**Comment by RJP43** [comment]
@msb81 @JaredKramer40 @setriplette @jonhoranic @PPH3 @ahunker @etj27 @laurenmcguigan @mjb232 

I am holding office hours today from now (10:40AM) until 2:30 in library study room 168. Please stop by if you want help installing your FTP client and accessing your PSC account. I am available for consult on RegEx, Git, and project work as well. I can stay later if need be; please just let me know!

**Comment by RJP43** [comment]
Class Example Link: http://www.cervantesvirtual.com/portales/miguel_delibes/obra-visor-din/peribanez-y-el-comendador-de-ocana--0/html/ff82a608-82b1-11df-acc7-002185ce6064_1.html

**Comment by RJP43** [comment]
[A-ZÉÁÑÍÚ]

**Comment by RJP43** [comment]
@msb81 @JaredKramer40 @setriplette @jonhoranic @PPH3 @ahunker @etj27 @laurenmcguigan @mjb232 Great job today deciding on first project team meetings. I wanted to remind everyone to please download an FTP client and go through the process listed out on Courseweb to setup your PSC account. I will be on campus tomorrow to help anyone that gets stuck!

**Comment by RJP43** [comment]
@msb81 @JaredKramer40 @setriplette @jonhoranic @PPH3 @ahunker @etj27 @laurenmcguigan @mjb232 Hey everyone I will be on campus today from now (11AM) til around 2. If you need help getting your FTP client and PSC account setup for class on Friday or want to ask questions about your homework I am happy to help.

Just a reminder if you are having a specific issue with RegEx please post an issue. We are seeing a lot of homework exercises coming in with questions and uncertainties written in the margins that we could jump on to solving as a community here on GitHub. Trust me if you are asking the question there is another student likely asking the exact same question. 

Okay, I am in library study room 166A till around 12:20 then I will be down in our McKenna classroom for the Lovecraft team meeting from 12:30-1ish. I will return to the library after that meeting; feel free to ping me in this issue if you would like to meet up!

**Comment by RJP43** [comment]
@msb81 @JaredKramer40 @setriplette @jonhoranic @PPH3 @ahunker @etj27 

Hey everyone!

Looks like most of you have not submitted anything for RegEx Exercise 4 yet. I encourage that if you are having a problem with your expressions to please post an issue so I can help. I am online currently trying to get back your graded RegEx Exercise 3 assignments so I should be able to respond pretty quickly to any questions. 

Happy Coding :)

Feel free to email me with any questions about FTP clients and PSC login issues!

**Comment by msb81** [comment]
Becca did you get mine?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Sep 29, 2016 at 8:50 PM -0400, "Rebecca Parker" <notifications@github.com<mailto:notifications@github.com>> wrote:


@msb81<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmsb81&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=WfWNGuDQ3kyfMP6t5OSEBVq%2FH2HvZ2COWWaHOeiboMA%3D&reserved=0> @JaredKramer40<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJaredKramer40&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=%2BHGi%2FuAOH%2BkzR7%2Bvase%2B5VDVzh1pgcKG0OWinYQCbGg%3D&reserved=0> @setriplette<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsetriplette&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=uJ2DwVtqLYDTzUcVS8DGIjY0qJR6Vwl4AzGmDW9Z9ac%3D&reserved=0> @jonhoranic<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonhoranic&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=bhLdGv%2FWgDY%2B9nnG1s5gg5CmdwO5KvlJmikk65Rh09g%3D&reserved=0> @PPH3<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPPH3&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=b%2FqdcofI1KskKMWRh3DJ5ia9Hga5r57CPshLS%2Bm04Vw%3D&reserved=0> @ahunker<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fahunker&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=zF%2B%2BGKZiwuv20SCQfAxswefuRW9nvawkt9tKHOjTejA%3D&reserved=0> @etj27<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fetj27&data=01%7C01%7Cmsb81%40pitt.edu%7Cd598556b917645fccae908d3e8cbc8ee%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=9ZAgSL53THev5Gq4gNa72fsp8Dcgn7ZQZkG1utR5ASo%3D&reserved=0>

Hey everyone!

Looks like most of you have not submitted anything for RegEx Exercise 4 yet. I encourage that if you are having a problem with your expressions to please post an issue so I can help. I am online currently trying to get back your graded RegEx Exercise 3 assignments so I should be able to respond pretty quickly to any questions.

Happy Coding :)

Feel free to email me with any questions about FTP clients and PSC login issues!

-

**Comment by RJP43** [comment]
@msb81 Yes looks like you have submitted. Thanks, Madee!
