### ISSUE TITLE
Question concerning Regex requirements

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#216]
Just a quick question about the assignment.  In the requirements its said that the document needs ,"each sonnet should be its own element, each line should be tagged separately, and the roman numerals should be encoded in a useful way" I've done everything there but I noticed that there is a difference in the example of what it should look like.  I noticed that the entire thing is wrapped within the element <sonnets>  but it isn't specifically asked for us to group all of the sonnets under 1 element.

Are we required to do that?  Cuz if not I'm done (puppy eyes)

**Comment by ebeshero** [comment]
@etj27 If I am understanding you clearly, you did the major important thing, which is to wrap each *whole* sonnet it its own element. That's key to the assignment. Wrapping the entire sonnet sequence is just a matter of tacking on a root element of some kind, or really doing something that doesn't need autotagging with Regex. Now, if you saved your file as `.xml`, then closed it, reopened it in oXygen you can make sure it's well-formed, and if it is, voila! You're done. Your code does not have to look exactly like our model, as long as you covered the bases of the assignment.

**Comment by RJP43** [comment]
@etj27 if you want you could upload both your steps and XML to courseweb  or put just your XML file in the sandbox and I can take a look to let you know if you met each of the requirements.

**Comment by RJP43** [comment]
@etj27 I just saw your submission and it looks like with the Regular Expressions you used you completed what the assignment was asking. My only concern is that you did submit your steps in a `.docx` format and I hope that doesn't mean you were using Word to write those up. Looks like the expressions all came in clear this time; however, in the future, we ask that you turn in `.txt` files containing your steps to avoid auto-correct issues.  Thanks!
