### ISSUE TITLE
Upconverted War of the Worlds transcript

### ISSUE THREAD

**Issue by rCarls** [ebeshero/DHClass-Hub#22]
@ebb8 The files are up. I would've had them up a few hours ago but I have this unfortunate habit of falling asleep right when I get home from school. Hope it's all up to snuff.

peace

**Comment by ebeshero** [comment]
@rCarls Actually, I don't think your files were actually pushed through to GitHub! The last commit I see is Becca's notes after class yesterday. Make sure you commit first (with a commit message) and then sync--was that the problem?
