### ISSUE TITLE
Trouble with HTML

### ISSUE THREAD

**Issue by msb81** [ebeshero/DHClass-Hub#221]
Hey guys! I am working on our assignment due for monday and every time I try and open my web browser, only my text inside my body elements come up. Can anyone help me figure out whats wrong? Thanks so much!

**Comment by RJP43** [comment]
@msb81 Can you push your site pages to your personal webpage github repo. and we can try to help you troubleshoot?

**Comment by RJP43** [comment]
Others can find Maddee's personal repo here: https://github.com/msb81/my_page

**Comment by msb81** [comment]
I actually figured it out... Lol. Thanks anyway Becca!!!
