### ISSUE TITLE
How to align images/gifs/whateva

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#222]
Hi, what is the code and where do you put it for aligning images and or gifs?
I have tried codes I've seen online in both css and xhtml but neither really seem to work at all.  I don't need to know it but it would be nice to know!

**Comment by RJP43** [comment]
@etj27 well that all depends on what you mean by aligning it? You want it centered or what? Make sure you push your files to your personal github page.

**Comment by ebeshero** [comment]
@etj27 Hi Evan! Have you tried CSS float and clear? You want to try those while also adjusting the width properties of your image. Here's a good tutorial with some examples: http://www.w3schools.com/css/css_float.asp
One thing to experiment with is setting relative widths on portions of your document via percentage values: So, try setting portions of your document in HTML `<div>` and/or `<section>` elements, and setting those up to have relative widths of say 50% and 50%. Then set a float property to have those sit next to each other and take up the full width of the screen. 

You might also want to experiment with CSS position properties, which work more absolutely to "pin" stuff where you need it on the page: http://www.w3schools.com/css/css_positioning.asp 

One thing I usually do to control the **size** of images on a page is to give those an absolute pixel value (px) in width (and the image resizes on the page proportionally based on the width value you give it.) I experiment with pixel values until the image size comes out about right in the browser window. 

Depending on what you're trying to do, you maybe want to control the "white space" around your images and text: check out the CSS box model:  http://www.w3schools.com/css/css_boxmodel.asp

It'll help if you post your code so we can get a sense of what you're trying to do and suggest something specific...
