### ISSUE TITLE
Tips on min and max

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#225]
I've got permission from Dr. B to share with you an example that she shared with me. This is relevant to question 4b on Xpath 4:

> Find the longest and shortest div elements of this type (that contain the word "GitHub") in the document. How long and short are they? Hint: You will need to use min(), max(), and the string-length() function here, as well as some complex predicates.

First, string-length (). This lets me count the characters in a span of text. For my example, I'm going to work on the element item because it is far simpler than the homework.

`//item/string-length(.)`

Gets me the length of each span of text between  `<item>` and `</item>`

If I want to find the item with the longest string-length, I need to use max()

If I do this

`max(//item/string-length(.))`

I get 2186, the length of my longest string. But what good is that?

This thing of beauty, on the other hand, actually navigates to that longest item, i.e., the string where the string length is equal to the max string length. I suspect this is math but I have not died from it yet.

`//item[string-length(.)=max(//item/string-length(.))]`

Now, if I want to make my xpath report the length of the longest item, I just add a path step at the end

`//item[string-length(.)=max(//item/string-length(.))]/string-length(.)`

And yay, I get to 2186 by a different road.

The key things to remember about this for me were:
- when you do your homework, everywhere I've put "item", you're going to put the path steps that navigate to the thing you want to find. (hint: with the super-complicated xpath (or is it an argument?) you used in the question above. Copy and paste is your friend)
- max and min wrap things like distinct-values does
- string length is a path step, as in `//item/string-length(.)`

**Comment by RJP43** [comment]
Also, I took notes from class on Wednesday and dropped them into class-examples. So check [that](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XPath/XPath-StringFunctions.md) out if ya feel stuck. And of course, post an issue with any specific questions.
