### ISSUE TITLE
Help Me With The Voyage Regex

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#23]
I have my books, and chapters marked, but I'm not sure how to pick up the beginning of paragraphs without the Chap. of chapter or the BOOK of book (AND include the square brackets with dates). Anybody?

**Comment by ghbondar** [comment]
Perhaps try using the double line-breaks /n/n ?

**Comment by ghbondar** [comment]
... for the paragraphs that don't begin with a square bracket, that is. Most of the paragraphs _do_ begin with a square bracket.

**Comment by CodyKarch** [comment]
That helped me pick up square bracket paragraphs, but I can't seem to grab paragraphs that don't have brackets.

**Comment by ghbondar** [comment]
Did you try searching for a double line-break? \n\n
Perhaps a double line break following a punctuation mark and before a word:
\.\n\n\w

**Comment by CodyKarch** [comment]
I was able to capture all the paragraphs with \n\n[A-Z]\w|\n\n\[  but my problem now is.. that when I try to place in the tags, all the paragraphs smash together and I loose some of the alphanumerics starting my find Regex.

**Comment by CodyKarch** [comment]
Excuse me: \n\n[A-Z]\w|\n\n\[

**Comment by CodyKarch** [comment]
OMG. There is a slash before the end square bracket, but it won't appear in these comments.

**Comment by ghbondar** [comment]
If you are losing the break between the paragraphs, it is because you have them selected when you hit replace. Make sure you either add them back or preserve them when you replace.

**Comment by ebeshero** [comment]
@CodyKarch Did you figure out how to preserve space between the paragraphs? Think about how you create your capturing group(s)! Yes, in markdown in the GitHub comments, we need to designate literal code characters a special way, in between "tick marks": It's the top left key on your keyboard under the Esc key: **`** You want to wrap any code or weird characters inside `weirdStuff Here!` tick marks like that.

**Comment by CodyKarch** [comment]
I was able to keep the breaks between paragraphs, but I overlooked the text and noticed that there were interlocking tags. Thus, I'm going to try and find the beginning and the end of the paragraphs, instead of simply the beginning.

**Comment by brookestewart** [comment]
I'm not able to keep the spacing between the paragraphs. Nothing I try seems to work.

**Comment by ebeshero** [comment]
If you are designating spacing with \n or \n\n that should be something you can use in a capturing group. But the numerical repetition indicators in curly braces don't work, so I think you won't be able to put \n{3} in a replace because you'll get literal characters in your replace. \n\n should work though.

**Comment by ebeshero** [comment]
The same kinds of things you did with the Blithedale exercise will work here too!
