### ISSUE TITLE
stuck on XSLT exercise 2

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#231]
Okay, so it's been a while since I have done xslt, and lists are complicated, so here is where I am stuck.  I am posting this now in the hopes that someone will see this early tomorrow. Here is what I have, but I am not getting anything close and I am pretty sure I have stuff repeating. I think where I am getting stuck is when to start a new template rule with match versus when to use select. I know we talked about it in class, so I was trying to find the example of the one we did in class here on github, but under class examples and xslt the one from Friday's class isn't there. Anyway, here is what I have. 

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
    xmlns="http://www.w3.org/1999/xhtml"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0">

    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>

    <xsl:template match="/">
        <html>
            <head><title>Digital Mitford</title></head>

            <body>

                <ol><xsl:apply-templates select="//listOrg"/>
                </ol> 
                <ul> <xsl:apply-templates select="//org"/></ul>

            </body>
        </html>

    </xsl:template>

    <xsl:template match="//listOrg">
        ,

        <li><xsl:apply-templates select="//head"/></li>


    </xsl:template>

    <xsl:template match="//org">

        <li><xsl:apply-templates select="//orgName"/>
        </li>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by RJP43** [comment]
@laurenmcguigan 
First remember you use an XPath pattern in your xsl:template match and you navigate the tree in your xsl:apply-templates select . So you will want to remove your leading slashes on all of your matches. If you're are thinking about how XSLT works similar to Schematron -  xsl:template match is to rule context as xsl:apply-templates select is to assert/report test. 

Okay so your stylesheet starts out looking good: you match on the document node (with the single slash) and setup your HTML tags.  Now you run into a problem after your `<ol>` tag. It makes sense that you call on (with your `xsl:apply-templates select="//listOrg"`) the content of the `<listOrg>` inside the HTML `<ol>`; however, then you are also dropping your unordered list in there right after the ordered list. In reality, the `<ul>` will only appear inside of the `<li>`s of your ordered list.  So to do this (and this is in step 2 on the assignment although it may be confusing) you create the `<ul>` inside of the `<li>` in your `<xsl:template match="listOrg">` This is a matter of determining the one-to-one versus one-to-many setup we discussed in class. 

So in your match on the document node the only thing you know happens one time is the `<ol>` element and you select a portion of the document everything in the `<ol>` is going to work with (`//listOrg`). Then in your next match you say: Okay XSLT up above I said spit out all of the contents of listOrg now I need to match on what I had you spit out and tell you exactly what I want you to do. In this match (on listOrg) you will say in every `<li>` first spit out all of the descendant head elements in `<li>` elements and with each of those also give me a `<ul>` . And in that `<ul>` spit out (xsl:apply templates select) all of the descendent `<org>` elements. Then in your next xsl:template match you tell XSLT to match on what you spit out in your last xsl:apply templates and through the descendant orgName elements into `<li>` elements there. 

This is how I think of this conceptually and hopefully it helps: the `<xsl:apply-templates>` elements throw some nodes out into space and say would someone please process these? and the various `<xsl:template>` elements (with the match attributes) sit around watching nodes fly by, and when they match something, they grab it and process it. So your first xsl:apply-templates say HEY process the contents of listOrg and then your match does that. Then within that match you say HEY someone process these descendant `<org>` elements and your next match does that. 

Now there is something else to be careful with. The only place the double slashes will work to get into the descendants of the source node is in the match that matches on the source node. If you try to just use the double slashes in the xsl:apply-templates selections in other matches you will either get no results or enter a loop (pending on where you try this).  In those selections, you will need to say from here or from this point (as in whatever is being matched) reach down and get me the descendant such-and-such element. Remember self or the `.` says okay XPath take it from this specified point. Now the nice thing is in your xsl:apply-templates we only ask you to grab children at each level so you can avoid using the self-notation by just writing the child element without any slashes at all and you will get the same result. This is similar to our Schematron in-class [game results example](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/Schematron/Example-fromTutorial/gameResults.sch) where once we made the context be parent element (`<gameResults>`) we were able to call on children elements (`<first>` `<second>` etc) without any leading hierarchy slashes.

**Comment by ebeshero** [comment]
@laurenmcguigan Thanks for reminding me that I didn't push our class example from Friday! I  just pushed some repairs to that file and added lots of comments to talk about how we use the `@select` attribute inside `<xsl:apply-templates select="//setPathFromMatchNode"/>`. It's posted now in Class-Examples in the XSLT folder so you can pull it in together with its source and output files, or view it online here: https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/XSL-to-HTML-sample.xsl 

@RJP43 is right to warn you about LOOPING when you start a `@select` attribute with those double slashes! My example from class contains a template match that uses the **dot notation**: `<xsl:apply-templates select=".//path/down/fromThis/context"` so you indicate you start from HERE (the self axis). There's a better way to write this, really, though you have to type a little more:

````
<xsl:template match="somePattern">
        <xsl:apply-templates select="descendant::path/down/fromThis/context"/>
</xsl:template>
````
If you always use the full axis name, you don't have to remember the dot and you're actually being more precise. So this is really the recommended practice. Just say **`descendant::`** and your meaning will always be perfectly clear and precise.

**Comment by laurenmcguigan** [comment]
Okay, so I think I have this figured out, but I am having trouble with the Xpath part and I am not sure why. So when you xpath to get the head element like this //listOrg//head it grabs the head elements, but when I output it into xslt it outputs the first head 3 times. I'm confused. 

This is what I have now, for the beginning, am I correct that this is a problem with xpath?

````
    <xsl:template match="/">
        <html>
            <head><title>Digital Mitford</title></head>
            
            <body>
                
                <ol><xsl:apply-templates select="//listOrg"/>
                </ol> 
                
               
            </body>
        </html>
        
    </xsl:template>
    
 
    <xsl:template match="listOrg">
  <li><xsl:apply-templates select="//head"/></li>
        <ul><xsl:apply-templates select="/org"/></ul>
    </xsl:template>
````

**Comment by ebeshero** [comment]
@laurenmcguigan The problem is with your @select attributes in your second template rule, on BOTH the two `<xsl:apply-templates/>` elements. Review my comment just before this about why you need to use either the "dot" notation or the "descendant::" axis designation to see why that's likely causing the problem here.

**Comment by laurenmcguigan** [comment]
@ebeshero @RJP43  I think I finally got it! Thank you for all your help. I think I am just a little confused still on the difference between two slashes // and descendant:: . Perhaps we could go over it in class tomorrow?
