### ISSUE TITLE
xslt 2

### ISSUE THREAD

**Issue by PPH3** [ebeshero/DHClass-Hub#232]
Any suggestions with getting started?  Also, the title is not transferring to html but other things have, just by me messing with some elements.

**Comment by ebeshero** [comment]
@PPH3 see https://github.com/ebeshero/DHClass-Hub/issues/231

**Comment by ebeshero** [comment]
@PPH3 Also, do a git pull on the DHClass-Hub, and pull in the revised and corrected and commented examples from Friday's class. That should help!
