### ISSUE TITLE
Course Web thinks my xsl file for assignment 4 is a security threat

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#235]
So I can't attach my xsl file to courseweb and GitHub will not allow me to post my entire length of code here.  once I get to my 2nd template it changes the code

**Comment by etj27** [comment]
<xsl:template match="head">
        <span class="headLine"><xsl:apply-templates select="descendant::headLine"/></span>
        <xsl:text>&#xA;</xsl:text>
        
        <span class="newspaperTitle"><xsl:apply-templates select="descendant::newspaperTitle"/></span>
        <xsl:text>&#xA;</xsl:text>
        
        <span class="seriesTitle"><xsl:apply-templates select="descendant::seriesTitle"/></span>
        <xsl:text>&#xA;</xsl:text>
        <span class="date"><xsl:apply-templates select="descendant::date[@when]"/></span>
        <xsl:text>&#xA;</xsl:text>
        <span class="byline"><xsl:apply-templates select = "descendant::byline"/></span>
        <xsl:text>&#xA;</xsl:text>
       
       
    </xsl:template>

**Comment by etj27** [comment]
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    
    
    <xsl:template match="/">
        <html>
            <head>
                <title>HTML Transformation of 1888-07-30 Nelson Article</title>
            </head>
            
            <body>
                <h1>Chicago Times </h1>
                <h2>CITY SLAVE GIRLS</h2>
                <h3>Nell Nelson</h3>            
                <h3>Monday Morning, July 30, 1888.</h3>S
                <h4><xsl:apply-templates select="//head"/></h4>
                <h4><xsl:apply-templates select="//articleBody"/>
                <xsl:apply-templates select="//dialogue"/>
                    <xsl:apply-templates select="//company"/>
                </h4>
            </body>
        </html>
    </xsl:template>
    
      <xsl:template match="head">
          <span class="headLine"><xsl:apply-templates select="descendant::headLine"/></span>
          <xsl:text>&#xA;</xsl:text>
          
          <span class="newspaperTitle"><xsl:apply-templates select="descendant::newspaperTitle"/></span>
          <xsl:text>&#xA;</xsl:text>
          
          <span class="seriesTitle"><xsl:apply-templates select="descendant::seriesTitle"/></span>
          <xsl:text>&#xA;</xsl:text>
          <span class="date"><xsl:apply-templates select="descendant::date[@when]"/></span>
          <xsl:text>&#xA;</xsl:text>
          <span class="byline"><xsl:apply-templates select = "descendant::byline"/></span>
          <xsl:text>&#xA;</xsl:text>
         
         
      </xsl:template>
      
     <xsl:template match="articleBody">
         <span class="articleBody"><xsl:apply-templates select="//articleBody//workingConditions[@category=(//toneElements/category[@tone='good']/@id)]"/></span>
         <span class="femVoice">
             <xsl:apply-templates select="//dialogue/femVoice"/>
         </span>
         <span class="nellVoice">
             <xsl:apply-templates select="//dialogue/nellVoice"/>
         </span>
         <span class="mascVoice">
             <xsl:apply-templates select="//dialogue/mascVoice"/>
         </span>
         <span class ="company">
             <xsl:apply-templates select="company[@name='identified']"/>
         </span>
     </xsl:template>
    
      <xsl:template match="unclear">
          <span class="unclear"><xsl:text>[missing word(s)]</xsl:text>
          </span>
      </xsl:template>
  </xsl:stylesheet>

**Comment by etj27** [comment]
Aha, i put my code into notepad and then cody pasted it.  That seems to work

**Comment by etj27** [comment]
[XSL 4.txt](https://github.com/ebeshero/DHClass-Hub/files/558598/XSL.4.txt)

Just in case, I'm doing random stuff

**Comment by RJP43** [comment]
@etj27 please just email me your submission to rjp396@gmail.com

**Comment by RJP43** [comment]
@etj27 just come to class and we will handle it.
