### ISSUE TITLE
How to change background color in SVG

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#243]
Hi, it's not 2am and I'm posting. WHAT?

So I finished the first exercise i have a graph and what not but I was trying to come up with a way to style the web page even more so i thought that they obvious solution would be to use CSS but there doesn't appear to be a place in any section of SVG where it accepts the link to the styling.  Can you link a CSS directly to SVG or is there some other way to go about it?

**Comment by ebeshero** [comment]
@etj27 Hi Evan! Great question. In our projects SVG is usually embedded on an HTML page, literally set inside it much the way you position an image. Then you write CSS on the HTML and you can add style to SVG elements in the CSS file. But SVG also typically sets styling inside its own attributes. It is kind of a grey area how best to control the styling, whether inside the attribute or in a separate CSS file. 

So I just looked this up, and YES, you can link CSS to your SVG file. Here's how:
https://www.smashingmagazine.com/2014/11/styling-and-animating-svgs-with-css/#styling-svgs-with-css

Thinking about your projects: A separate CSS file is basically so you can hold all your styling for multiple webpages and/or SVGs in one place, and update it once to update the style everywhere. If SVG is only being used one time on one page, the styling it needs might be just fine set inside its attributes. But if you are playing with the same kinds of styling on similar SVGs across your project, we should look into setting the style in a linked CSS.

**Comment by ebeshero** [comment]
@etj27 So, pullimg from that article I linked: If you want to try associating a CSS file, try adding your version of this line (modified with your file name and the relative file path)  to the top of your file:

`<?xml-stylesheet type="text/css" href="style.css"?>`

**Comment by ebeshero** [comment]
@etj27 By the way, we'll be setting SVG in an HTML page in a homework coming up, so this is a good moment to preview the process and consider the options. Sara Soueidan writes the best stuff I've seen on the web about styling SVG  for browsers on its own or within HTML--so here's one more resource by her on SVG-in-HTML: http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
