### ISSUE TITLE
JavaScript Example: searchHide

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#248]
Here's a neat example I adapted from code one of you submitted for JavaScript Exercise 1. We'll take a look at it in class today: 

Run the JavaScript in the browser here:
http://htmlpreview.github.io/?https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/JavaScript/searchHide/playListEx.html

Look at the files here:
https://github.com/ebeshero/DHClass-Hub/tree/master/Class-Examples/JavaScript/searchHide

**Comment by ebeshero** [comment]
@setriplette @JaredKramer40 @RJP43 @laurenmcguigan @ahunker @mjb232 @PPH3 @jonhoranic @etj27 
I fixed what I broke on the JavaScript example in class today! The links above now lead to functional code, and you can pull in the DHClass-Hub to play with it locally. I completely removed the event listener from the HTML file, so the JavaScript in the separate file controls everything. 

Now, I didn't add code to step down into the `<a>` element, but let's experiment with that next!

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
