### ISSUE TITLE
mfw I read JavaScript Ex 3

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#250]
![](https://68.media.tumblr.com/6934ebb1f802de9c063fb2f373204b0b/tumblr_mqembnrTue1rqfhi2o1_250.gif)

**Comment by ebeshero** [comment]
@etj27 You know we're only working on[ JavaScript Ex 2](http://newtfire.org/dh/JavaScriptExercise2.html) for tomorrow, right? There's a reason that JavaScript Ex 3 is scheduled over a long break!
