### ISSUE TITLE
Help with Java script 2

### ISSUE THREAD

**Issue by PPH3** [ebeshero/DHClass-Hub#251]
Don't know how to start this. Aside from my ignorance of Java script, our group doesn't have any HTML done (I'm a big part of that void), so I don't know what file to use plus I simply don't know Java script. Any insight would be appreciated.

**Comment by ebeshero** [comment]
@PPH3  I'm marking the JavaScript Ex 1 assignments right now, looking in web directories. DId you submit something there? If you did, I'll be responding to it shortly.

 If you don't have a project HTML file, try writing up something with a few paragraphs for the Eldritch project that holds some information in '<span>` elements, and give them some attributes so you have a range to work with, like `<span class="person">...</span>`, and `<span class="place"> ...</span>`. Give yourself a few different spans to work with that you can grab hold of in JavaScript and CSS.

To understand how to write JavaScript as a sequence of events, look at the examples we've posted here on the DHClass-Hub, starting with the intro examples. Study our code in the tutorial, as well, and come back here with questions as you go!

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
