### ISSUE TITLE
T-Shirts --- Sizes Please!!!

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#254]
Notes about the t-shirts:
a) Ink is applied to the fabric (so there's nothing plastic-y in the application).
b) We can order these in any combination of the available T-shirt colors (so they don't all have to be the same color):
c) The design would work on four different T-shirt colors, and those colors have official names that I need to ask about, but for our purposes, let's call them in order from left to right in the proof image:

gold,  grey, natural, and green
(Yes, that counts as an array of colors, and if we were counting in JavaScript we'd call that 0) gold, 1) grey, 2) natural, and 3) green. ;-)

Here is the [proof](https://cloud.githubusercontent.com/assets/4014518/11314432/822bb9c8-8fb3-11e5-9803-1e8607100160.jpg).

Please provide your size and color in this issue.

**Comment by mjb232** [comment]
Large- grey!

**Comment by laurenmcguigan** [comment]
small-gold

**Comment by RJP43** [comment]
All: Here are some suggested fonts we might try for "Digital Humanities" on our shirt: 
![fonts](https://cloud.githubusercontent.com/assets/4014518/11320033/59f969b6-905b-11e5-8f1f-a9414cece316.jpg)

Preferences?

**Comment by RJP43** [comment]
Other possible colors: https://www.alphabroder.com/cgi-bin/online/webshr/prod-labeldtl.w?sr=G200&currentColor=51

**Comment by setriplette** [comment]
large green!

**Comment by ahunker** [comment]
Medium - Grey

**Comment by jonhoranic** [comment]
medium-grey

**Comment by JaredKramer40** [comment]
medium   grey

**Comment by msb81** [comment]
Large grey please!

**Comment by etj27** [comment]
Large Grey -  XXX CAMGIRL STREAMING

**Comment by ebeshero** [comment]
Pat Herron: Medium green

**Comment by ebeshero** [comment]
We picked up the T-shirts this evening! Bringing them to class tomorrow...

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
