### ISSUE TITLE
Trouble uploading files

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#255]
@RJP43 Coursweb won't let me upload my xslt for the javascript assignment. It says there is a security issue. Should I just email it to you?

**Comment by laurenmcguigan** [comment]
And should I email you the other files too or put the rest on courseweb?

**Comment by RJP43** [comment]
@laurenmcguigan  yea just email from a non-pitt email to my Gmail rjp396@gmail.com 

Or if @ebeshero sees this she can change your box status so you can upload to the folder we send your graded assignments back in

**Comment by RJP43** [comment]
You can either email them all to me or just the problematic files. I can get the others from either place easily.

**Comment by laurenmcguigan** [comment]
sent! It should be coming from my gmail account
