### ISSUE TITLE
Project Teams and their GitHub Repos:

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#258]
Here's where to find each of our team projects this semester. Each of you, please leave a comment on at least one other team's repository Issues page, offering a response to each team's presentation and project as you can see it thus far. (There's an issue page open on each project repo to collect your feedback.) Thanks for all your hard work!!! 

Eldritch (H. P. Lovecraft): http://eldritch.newtfire.org
Repo: https://github.com/PPH3/Eldritch
@etj27
@PPH3 -- Project Leader
@mjb232

theGraveyard: http://graveyard.newtfire.org
Repo: https://github.com/jonhoranic/theGraveyard
@JaredKramer40
@laurenmcguigan
@jonhoranic -- Project Leader

Lope de Vega: http://lope.newtfire.org
Repo: https://github.com/setriplette/golden_age
@setriplette -- Project Leader
@msb81
@ahunker

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
