### ISSUE TITLE
Help Me With The Pygmalion

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#26]
Hey, I am trying to tag the square brackets, but everything I have tried doesn't work. Any hints or suggestions?

**Comment by ghbondar** [comment]
can you find the square brackets ok in the text using regex?  `\[` and `\]`  seems to work.

**Comment by nlottig94** [comment]
I used `\[.+?\]` to find all of the stage directions in the document!  Hope this helps!

**Comment by CodyKarch** [comment]
Wow... Sorry, I kept trying those, and it wouldn't work. Now I realize that I needed to turn the Dot Matches All on. Silly mistake. Thanks.
