### ISSUE TITLE
Finals Week -- Instructors' Office Hours

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#260]
@ahunker @msb81 @setriplette @JaredKramer40 @laurenmcguigan @jonhoranic @etj27 @mjb232 @PPH3 

As you are wrapping things up this week for your Final Project's deadline (Thursday at 11:59PM), @ebeshero and I want to be available as much as possible to meet with project teams and individuals that need help. Come to this issue for our available times during this final week. This will also be a good place to ping us if you want to reserve a specific time. 

**Monday 12/12:** 
Becca is in from 11 - 4 Location: outside of Cassell Hall 205 (Meeting with Eldritch Team at 2 in McKenna)
Dr. B is in from midday onward... (office: FOB 204).

**Tuesday 12/13**
Becca is in from 12 - 7 Location: Library Study Room 166B (Meeting with Matt)
Dr. B arriving around 10am and around until 3 pm in office, FOB 204. (Giving an exam at 3:15).  

**Wednesday 12/14**
Room Reserved: **FOB 138: noon to 4pm**
Becca is in from 11 onward Location: Meeting with Eldritch team around 12:30 in FOB 138 & Meeting with Lope team around 1:30 in FOB 138 & Meeting with Lauren (hopefully whole Graveyard team) around 3 in FOB 138
Dr. B arriving around noonish--has a meeting in the early afternoon; likely available later afternoon.

**Thursday 12/15**
Room Reserved: **Cassell 205: 1 - 5pm**

Good luck with Finals! Happy coding!

**Comment by RJP43** [comment]
**Monday 12/12**

I am available 11-4

**Comment by RJP43** [comment]
@setriplette what time on Wednesday are we meeting for mapping and where?

**Comment by setriplette** [comment]
My exam ends at 12:30, and Maddie and Audrey and I are having lunch at the cafeteria for a final project meeting. Join us, and then we'll go map somewhere.
@msb81 @ahunker make sure you have coordinates for us by then so it goes fast. I have to leave for home at 5ish, but I think we can get done well before that (I hope).
Also everybody take a look at the website now and make an issue if I need to do anything to your pages.

**Comment by RJP43** [comment]
@laurenmcguigan looks like you got both your SVGs done, but we could meet to tweak some things and fit the graphs on pages with some descriptive text. What time do you want to meet Wednesday morning?
