### ISSUE TITLE
Add New GitHub User Names Here! 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#263]
Leave a comment here with your user name, so I can add you to our DHClass-Hub.

**Comment by jonhoranic** [comment]
Example post:

Heyo, I am @jonhoranic, beam me up!

**Comment by ajnewton1** [comment]
@ajnewton1 is my username!

**Comment by bsf15** [comment]
@bsf15 is my username.

**Comment by ebeshero** [comment]
Welcome @bsf15 @ajnewton1 !

**Comment by ebeshero** [comment]
Here's what happens if we're asking a question. It's always helpful to POST YOUR CODE:

````
<measurement>(about 1 teaspoon)</measurement>
                <measurement quant=".25">1/4 cup</measurement>
                <liquid>red wine vinegar</liquid>
                <measurement>1/4 cup</measurement>
````

**Comment by ebeshero** [comment]
If you just want to type a LITTLE code, try this: `<code>stufff</code>`

**Comment by jonhoranic** [comment]
Control+K auto inserts brackets for links. Just place the url inside or you can add them manually via type or by clicking the button that looks like a chain.

**Comment by Samantha-Mcguigan** [comment]
@Samantha-Mcguigan

**Comment by jonhoranic** [comment]
Here is an example link to a .gif image (this works with image files too).

Ex. What troubleshooting code looks like. [http://i.imgur.com/fSV89.gif](url)

**Comment by ebeshero** [comment]
camelCase

**Comment by ebeshero** [comment]
camel_case

**Comment by ebeshero** [comment]
Welcome @Samantha-Mcguigan !

**Comment by gretchenuhrinek** [comment]
gretchenuhrinek here!

**Comment by gretchenuhrinek** [comment]
@gretchenuhrinek here! @ebeshero

**Comment by ebeshero** [comment]
@gretchenuhrinek I've just added you! Huzzah! Welcome to the DHClass-Hub!

**Comment by ebeshero** [comment]
@ajnewton1 Looking through the comments, I just noticed your avatar--it's perfect! ;-)

**Comment by ajnewton1** [comment]
@ebeshero I tried to think of a pic that would make sense but also make you think of the purpose too!

**Comment by ebeshero** [comment]
Everyone has now completed GitHub Ex 1, so I'm closing this issue.
