### ISSUE TITLE
file conventions for naming course web documents error

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#269]
I was going to upload my xml file and relaxNG file and the page says a Relax-NG Schema file must end with .rng. However, at the moment my Schema file ends with .rnc and both have the little green square saying there is no errors but when I change it to end in .rng and change the xml file to run a new validation with the renamed file, it says there is an error and the square is red. Is this okay or do I have to change something in my schema or xml file? Thank you for your help!

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Oops! Your file extension is correct: `.rnc` is the correct extension for compact syntax. I'll go correct my error in Courseweb! Sorry for the confusion!

**Comment by Samantha-Mcguigan** [comment]
Sounds good thank you for your help!

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I'm trying to spot where we made the error, and having trouble. Is it in our Relax NG tutorial? I don't see it on Courseweb...

**Comment by Samantha-Mcguigan** [comment]
No, it is under the page titled "File Conventions for CourseWeb Assignments" on newtfire

**Comment by ebeshero** [comment]
Thanks, @Samantha-Mcguigan. I've just repaired it!
