### ISSUE TITLE
Regex Exercise

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#273]
I am not sure if you mentioned this already but I 'tried' to do the regex exercise and I went to turn it in but there is no link to turn it in in CourseWeb. Were we not supposed to do it?

**Comment by RJP43** [comment]
@ajnewton1 glad you got a start on Regex... @ebeshero will be giving a more indepth introduction to Regex today and the exercise is technically due on Monday. When I get my computer fired up I will add the upload point to courseweb and you can upload your assignment, but you may find you want to edit it after getting more regex experience in class today. Huzzah for being on the ball!

**Comment by ebeshero** [comment]
@ajnewton1 Right--Regex Ex 1 is absolutely not due until Monday! (Remember, the text in the right column on the syllabus is the homework assignment the next class period.)  Glad you're eager to get back to coding! ;-)
