### ISSUE TITLE
Regex exersize  3 PYGMALION discussion

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#275]
Hi everyone, I thought I would start a discussion thread for us to help each other with the regex homework for Friday. I was working on it and just had one question so far:

There is a line after the PREFACE TO PYGMALION. that reads: 
A Professor of Phonetics. 

I don't know what to tag this as. Is it a stage direction? A character?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan It's a subtitle, basically a secondary title for the whole play!

**Comment by ebeshero** [comment]
Yay for starting a thread! 👍
