### ISSUE TITLE
XPath exercise 1

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#277]
I was just finishing the first XPath exercise and the directions said we would need to use not() for one of the questions but I did not seem to use it anywhere and still get the answers I needed. Did anyone use this and if so for which question?

**Comment by RJP43** [comment]
Hey @Samantha-Mcguigan you are right that the not() function isn't necessary to complete this assignment. Thanks for pointing this out in the instructions for us to fix. @ebeshero

**Comment by ebeshero** [comment]
Corrected and posted! :-)
