### ISSUE TITLE
Path Exercise 2

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#279]
Im really having a tough time trying to figure out the 2nd question. Ive been trying for hours and I am really getting frustrated.. PLEASE HELP!

**Comment by RJP43** [comment]
These latitude measurements you've just looked up are all held inside paragraphs, or the <geo select="lat"> element. What would you add to the previous XPath expression to return the paragraphs that hold latitude measurements in Book I? Give your complete XPath expression here.

Lets try rewording the question... @ajnewton1 first step down so you are only looking at the descendants of Book 1. Then get the paragraphs **that have** descendant lat. coords.

**Comment by ajnewton1** [comment]
This is what I have so far
//div[@type="book"][1]//p/geo[@select="lat"]

**Comment by RJP43** [comment]
Great so far, so notice your expression is getting you the children lat coords of the paragraphs ... instead of the slash after p how could you change the expression so you are grabbing the paragraphs **that have** lat. coords

**Comment by RJP43** [comment]
You want the last step ( as in the slashes that are saying where you are stepping to next ) to land on the paragraphs so you need to filter the paragraphs by grabbing only paragraphs with lat coords instead of stepping to down another step to those lat coords

**Comment by ajnewton1** [comment]
Ahhhh, I think I got it!
//div[@type="book"][1]//p[geo[@select="lat"]]
Thank you so much @RJP43, my frustration is gone now

**Comment by RJP43** [comment]
Bingo! Nice work!
