### ISSUE TITLE
How Do We Get Our HW To Newtfire?

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#28]
I'm lost at how we are supposed to get our xhtml and css onto the supercomputing space.

**Comment by RJP43** [comment]
@CodyKarch have you downloaded winSCP or something similar?

**Comment by RJP43** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/10271920/76d230bc-6ae6-11e5-9518-93bae3745ce0.jpg)

**Comment by RJP43** [comment]
once in the file transfer program find your xhtml and css files on your local drive then copy them (in winSCP you can just drag them) into the publicHTML folder of your PSC userID folder. Make sure you put the css and the xhtml both inside this folder so that they stay associated.

**Comment by CodyKarch** [comment]
Thank you! I had to get used to the practice of these transfer applications, but I got it!

**Comment by spadafour** [comment]
I can't seem to be able to access the ...server? I'm on a mac. I've downloaded Fetch, host name: unixs.cssd.pitt.edu, user name: spadafor (that's the one we're using, right? The one we were assigned?), connect using SFTP, entered my passoword. No luck so far. I was able to log in during class on Friday.

**Comment by spadafour** [comment]
okay, I solved it. The pitt guide says to use units.cssd.pitt.edu as the host name. I swapped that out for dxcvm23.psc.edu and I'm in.
