### ISSUE TITLE
XPath exercise 3

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#280]
I have been working on this for hours and I can not get past trying to find all the attributes

//*/..[@*] seems to grab a bunch of different elements
//@* gets a bunch of yes and false

I have tried a thousand different things and I just can not figure it out!

**Comment by ebeshero** [comment]
Hi @Samantha-Mcguigan! Your second expression is correct and as you click on the results, notice they are stopping on just the attribute part of each tag. Scroll through the results in the results window--are those attribute values?

**Comment by Samantha-Mcguigan** [comment]
Thank you for your help, I was just really confused because when I tried to click on the results in the results window it wouldn't bring me to it in the document like it usually does. Thank you for your help!

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I'm back on campus and actually in my office at last! I'll be in class from 2:30-3:45, but if you're around and still stuck, pop by either before 2:30 or after 3:45! 

Here's something worth noticing about the attribute axis. You switch over to it, as you did, just with the symbol `@`, and you can make deep steps from the document node through the entire tree looking ONLY at attributes just with `//@type`, `//@n`, `//@select`, etc, or if you don't know the attribute names and just want every single one, `//@*` . When you click on those results, you should see highlights in the document. But if you switch over to get the names of the attributes using the `name()` function, you're actually going to step OFF the XML tree to return those names. So those results won't let you click on the document any more!

**Comment by Samantha-Mcguigan** [comment]
What time will you be in you office till after 3:45?

The only thing I am getting stuck on now is 2.f. I want to grab just the elements of all the elements with attributes but when I use //@*/parent::* it grabs something diffrent than just the direct element of elements with an attribute

**Comment by ebeshero** [comment]
I should be back at around 3:45!

**Comment by Samantha-Mcguigan** [comment]
@bsf15 @Samantha-Mcguigan @ajnewton1 @gretchenuhrinek

Just as PSA if any of you guys were getting stuck on question 2, I was confused because even though I was putting @* in the search box I was still getting elements that didn't seem to have any attributes but I talked to Dr. B and there are HIDDEN ATTRIBUTES on some of the elements, meaning they have attributes but you can not see them in the file. 

I hope this helps!

**Comment by ajnewton1** [comment]
I can't seem to get question 3b. I feel like I have most of it but I just can't get it to have more than 2 latitudes. This is what I have so far (//p[geo[@select="lat"]])[1]

**Comment by bsf15** [comment]
Currently, I am stuck on question 3. I'm having issues with placing the comparison operators to indicate more than 1 or more than 2 latitude attributes and/or the placeName element. 

For example, I've managed to develop an XPath expression for part A of question 3 that is finding me the last paragraph within the whole text that has a latitude attribute in it: //p[geo[@select="lat"]]/last()
I've tried putting in a variety of comparison operators in different places, but no matter what I am doing I keep getting errors. 
I think the closest I got was by using: gt 1 before the last //p[geo[@select="lat"]] gt 1/last()
Or at least that was making the most sense for me, but I am clueless about whether I am even using the right comparison operator ( I've tried &gt;1, >1, and gt 1) and where I would even put the operator for it to compare the right thing as I have pretty much dropped every variation of it in every logical place within the expression for me. 
I thought maybe it was just an issue for part A of question 3, but as I came up with the rest of the answers, I was pretty much getting what I needed except for more than 1 or 2 of latitude attributes and Place Names. So, I am definitely not getting something about using the greater than operation.

**Comment by ajnewton1** [comment]
@bsf15 I am having the same problem

**Comment by ajnewton1** [comment]
count(//p[geo[count(@select="lat") gt 2]])
I was playing around and got this but it gives the answer of 0

**Comment by Samantha-Mcguigan** [comment]
Hi guys, you do have to use the count function but you do not want to count the paragraphs, just the latitude statements.

Arron is close but take the first count out at the beginning , and since you want the first one you need to put something else at the very end

**Comment by ajnewton1** [comment]
Thanks @Samantha-Mcguigan , I am working on 3a which is why I have the last function. I have this so far but don't understand what is wrong. (//p)[geo[count(@select="lat") gt 2]][last()]

**Comment by ajnewton1** [comment]
Wait, I figured it out, thank you!

**Comment by Samantha-Mcguigan** [comment]
your welcome! also @bsf15 if you want to get the first, last, etc. of anything you want to put your whole search in parenthesis ( ) and after put which one you want in brackets [ ]. Also for the greater than and less than stuff you want to use the count function and put what you want to count in parenthesis ( ) and the entire statement with count in brackets. So, if you wanted to find the first paragraph that had more than one latitude statement, for example you first want to go to all the paragraphs:

//p

then all the paragraphs that have latitude measurements

//p[geo[@select="lat"]]

then all the paragraphs that have more than one latitude measurement by using the count function and gt

//p[count(geo[@select="lat"]) gt 1]

* if you are looking for paragraphs that have latitude measurements greater than 2 you just change the number after gt to 2

then the first paragraph that has more than one latitude measurement by putting the whole expression in ( ) and following it with [1] like we do to find the first book, first chapter, etc

(//p[count(geo[@select="lat"]) gt 1])[1]

*if you wanted the last paragraph with all of this you just put [last()] at the end instead of [1]

I hope this helps! Just typing this all out helped me understand!

**Comment by bsf15** [comment]
@Samantha-Mcguigan  Thank you, that helped so much! Using the count function never occurred to me and the grouping with the parentheses makes so much sense! I think I finally got it! Thanks again!

**Comment by Samantha-Mcguigan** [comment]
It also helps me to think of the brackets [ ] as the words "that has" or "that contains" so a paragraph "that contains" a geo element "that contains" a select attribute with a latitude tag would read
//p[geo[@select="lat"]]

Sorry for saying so much but I've been working on this for hours and I didn't want you guys to have the same problems that have been driving me crazy!

**Comment by ebeshero** [comment]
Yay--this is exactly how the GitHub discussion is supposed to work! 👍
