### ISSUE TITLE
Schematron exercise 2

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#283]
I'm having trouble on the first question about white spaces in elements this is what I have so far and I've tried a few different things:

    <pattern id="elements">
        <rule context="tei">
            <report test="starts-with(., ' ')">No leading white spaces inside any element</report>
        </rule>
        </pattern>

I'm am getting no results in my xml. Does the rule context need to equal "tei:element" I've also tried putting //* as the first thing inside starts-with but that does not seem to work either. Any ideas?

**Comment by Samantha-Mcguigan** [comment]
I think the problem I am having is that I am grabbing the text inside an element rather than the element itself. I am having the same problem with the second question. I have this so far:
        <rule context="tei:person">
            <assert test="contains(., @xml:id) and contains(., @sex)">person elements must contain xml:id and sex attributes</assert>
        </rule>
It is creating way too many errors, about 73 I think, even if they have both the sex and xml:id attributes. How do I make it grab the element itself?

**Comment by Samantha-Mcguigan** [comment]
i think the problem I am having is that I am grabbing what is inside an element rather than the element itself for both the first and second question. This is what I have so far for the second question:
      <pattern id="personAttributes">
        <rule context="tei:person">
            <assert test="contains(., @xml:id) and contains(., @sex)">person elements must contain xml:id and sex attributes</assert>
        </rule>
        
    </pattern>
I am getting way to many errors with this, 73 I think and it is giving an error even to the elements that have both sex and xml:id attributes. Any one know how to fix this?

**Comment by Samantha-Mcguigan** [comment]
i think the problem I am having is that I am grabbing what is inside an element rather than the element itself for both the first and second question. This is what I have so far for the second question:
    
    <pattern id="personAttributes">
        <rule context="tei:person">
            <assert test="contains(., @xml:id) and contains(., @sex)">person elements must contain xml:id and sex attributes</assert>
        </rule>
    </pattern>

I am getting way to many errors with this, 73 I think and it is giving an error even to the elements that have both sex and xml:id attributes. Any one know how to fix this?

**Comment by ebeshero** [comment]
Hi @Samantha-Mcguigan! Your code for the first question is close! Look at your `<rule context="tei">': It looks like you set the TEI namespace prefix but didn't follow up with the element name. Otherwise your assert test is just right!

**Comment by RJP43** [comment]
@Samantha-Mcguigan 

Frist I am gonna paste the question here for easy reference:
`We want to close up extra white spaces that our editors inevitably type at the start of their elements. Write a Schematron rule that checks for leading white space inside any element. (That is, raise a warning when an element starts with a white space.) Hint: you may want to look at the starts-with() function, one of the family related to contains().`

Okay so for number one and what you have above is very close. Remember in class today @ebeshero mentioned that your rule context will not be an xpath expression in the sense that you do not need to walk the tree. Otherwise your * will work to get every element, and everything else in your assert looks good.

**Comment by Samantha-Mcguigan** [comment]
@ebeshero @RJP43 
 For the first question I don't know what to put after tei: I've tried tei:element and that does not seem to work either?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan For the second problem, think about how we use `contains()`. It is about the text inside an element, NOT for checking to see if an attribute is present. What you need here is simpler: Just test that the attribute is there!

**Comment by RJP43** [comment]
@Samantha-Mcguigan so further explanation on #1 what you had first thought with `//*` is smart and as you know in the XPath window gets you all of the elements. See if you can write the rule out as an XPath expression and then figure out what piece needs to be context to grab all of the things you need and then use your starts-with portion in the test.

**Comment by RJP43** [comment]
@Samantha-Mcguigan Let's take it in parts ... what is the XPath expression you can use to get all of the elements where a white space starts the text inside the element.

**Comment by ebeshero** [comment]
@RJP43 is being a little cryptic. ;-). You know you need the tei: prefix, but don't know what elements to match on, which calls for the *. Just go ahead and put the two together!

**Comment by ebeshero** [comment]
I think what's weird here is the namespace notation. As @RJP43 said, you're **right** about that * . But it needs to be prefixed, that's all!

**Comment by ebeshero** [comment]
Moving my comment on 2. here for ease of reference:
@Samantha-Mcguigan For the second problem, think about how we use `contains()`. It is about the text inside an element, NOT for checking to see if an attribute is present. What you need here is simpler: Just test that the attribute is there! How would you do that in the XPath window? (Remember, what you put in the predicate there just lifts out and goes into the test attribute in Schematron.)

**Comment by Samantha-Mcguigan** [comment]
Okay so I think I got the first question, I put the asterisk * after tei: and it seems to be getting everything that has a space as the first thing after the element tag and got 12 errors. 

But for question 2 I took out the contains( ) which leaves:

<assert test="@xml:id and @sex">
  
but it is not getting any errors so I typed //person into Xpath and scrolled through them all but they all seem to have both attributes so I manually took one out and got an error message! So it is working there just were not any errors.

Thank you for your help

**Comment by Samantha-Mcguigan** [comment]
Okay so I think I got the first question, I put the asterisk * after tei: and it seems to be getting everything that has a space as the first thing after the element tag and got 12 errors.

But for question 2 I took out the contains( ) which leaves:

<assert test="@xml:id and @sex">

but it is not getting any errors so I typed //person into Xpath and scrolled through them all but they all seem to have both attributes so I manually took one out and got an error message! So it is working there just were not any errors.

Thank you for your help

**Comment by Samantha-Mcguigan** [comment]
Okay so I think I got the first question, I put the asterisk * after tei: and it seems to be getting everything that has a space as the first thing after the element tag and got 12 errors.

But for question 2 I took out the contains( ) which leaves:

<assert test="@xml:id and @sex">

but it is not getting any errors so I typed //person into Xpath and scrolled through them all but they all seem to have both attributes so I manually took one out and got an error message! So it is working there just were not any errors.

Thank you for your help

**Comment by Samantha-Mcguigan** [comment]
Okay so I think I got the first question, I put the asterisk * after tei: and it seems to be getting everything that has a space as the first thing after the element tag and got 12 errors.

But for question 2 I took out the contains( ) which leaves:

assert test="@xml:id and @sex"

but it is not getting any errors so I typed //person into Xpath and scrolled through them all but they all seem to have both attributes so I manually took one out and got an error message! So it is working there just were not any errors.

Thank you for your help

**Comment by Samantha-Mcguigan** [comment]
Okay so I think I got the first question, I put the asterisk * after tei: and it seems to be getting everything that has a space as the first thing after the element tag and got 12 errors.

But for question 2 I took out the contains( ) which leaves:

`assert test="@xml:id and @sex"`

but it is not getting any errors so I typed //person into Xpath and scrolled through them all but they all seem to have both attributes so I manually took one out and got an error message! So it is working there just were not any errors.

Thank you for your help

**Comment by ebeshero** [comment]
That's a good start! 👍  And yes, that's how we test project schematrons, too: take out some code to break it and get the rule to fire. :-)

**Comment by Samantha-Mcguigan** [comment]
So I was trying to do question 4 on my own but I've been stuck on it for 3 hours now. This is the question: 

Sometimes our editors don’t capitalize proper names! Check that all TEI forename, surname, and placeName elements, as well as any persName elements that hold text and do not wrap around forename and surname elements start with capital letters (you can do that with one rule).

The only thing I can get any results for is  
```
<pattern>
        <rule context="tei:surname">
            <assert test="matches(., '[A-Z]')"></assert>
        </rule>
    </pattern>
```
but this only gets the surname elements that do not have a capital letter. I believe all the forenames, surnames, and placeNames are inside a persName element so my guess is that is what I should put in the rule context but I really have no idea..

**Comment by Samantha-Mcguigan** [comment]
Wait I think I got it using report instead!

**Comment by Samantha-Mcguigan** [comment]
I'm not sure how to use tokenize for the sixth question. This is what I have so far

```
    <pattern>
        <rule context="tei:death">
            <let name="tokens" value="for $w in tokenize(., '-+')[1] return substring-after($w, '')"/>
            <assert test="every $token in $tokens satisfies $token $w gt </assert>
        </rule>
    </pattern>
```

I'm just kind of guessing here I don't really know what I'm doing. I'm not sure where to put the predicate that indicates the first token. I'm also not sure if I need the substring-after and if I do I don't know what to put inside it. Also for the assert part, I think at the end after $token I am supposed to put that the death date is greater than the birth date  but I son't know how to write that since I've only defined the tei:death element and not the birth element. Please help!

**Comment by Samantha-Mcguigan** [comment]
i think this may be closer but im still not getting any errors

  ```
      <rule context="tei:person[tei:death]">
            <report test="/tei:death/@when[tokenize(., '-+')[1]] lt /tei:birth/@when[tokenize(., '-+')[1]]"></report>
        </rule>
```

**Comment by Samantha-Mcguigan** [comment]
okay I think I got it i have:

   ```
 <pattern>
        <rule context="tei:person[tei:death]">
            <report test="tei:death/@when[tokenize(., '-+')[1]] lt tei:birth/@when[tokenize(., '-+')[1]]">birth dates must come before death dates</report>
        </rule>
    </pattern>
```
the only problem is that it is putting the error message on the <person> element. Is that okay or is there a way to change this?

**Comment by Samantha-Mcguigan** [comment]
For question 6 I have:

   ```
 <pattern>
        <rule context="tei:person[tei:death]">
            <report test="tei:death/@when[tokenize(., '-+')[1]] lt tei:birth/@when[tokenize(., '-+')[1]]">birth dates must come before death dates</report>
        </rule>
    </pattern>
```
It is working but the only problem is that it is putting the error message on the <person> element. Is that okay or is there a way to change this?

**Comment by ebeshero** [comment]
Hi @Samantha-Mcguigan ! Looks like we were all asleep as you were working! You may want to get the rule to fire on the tei:death elements (where a human can see a problem better) instead of the whole tei:person elements. To do that, you change the rule context. Whatever the `@context` is set on establishes what highlights when your message fires. Of course you then have to change the XPath of your `@test` and you can totally do that. If your `@context` is either `tei:birth` or `tei:death` you can **reach over** to check the other one by using the appropriate XPath axis to find a sibling in one direction or the other.

That said, good work with the tokenize() function and how to grab the first of three--BUT two problems: 
1) your evaluation isn't actually comparing the tokens, is it? Notice you've tucked the whole token inside a predicate, so you are literally comparing the entire `@when` *that has* a string that can be tokenized. 
2) there's no literal + sign in any of the dates as far as I know, and the string you put in as the second argument of `tokenize()` is a *literal* piece of text and not a regex. So I am not sure you are really breaking tokens off, since there's no `-+' combination I can see! Just break on the hyphen `-` by itself. And (as I said) make that one first part of the token after you break it off be in the *destination* of your XPath (not a predicate filter).

**Comment by Samantha-Mcguigan** [comment]
@ebeshero So I changed it to:

```
        <rule context="tei:death">
            <report test="tei:death/@when/tokenize(., '-')[1] lt following-sibling::tei:birth/@when/tokenize(., '-')[1]">birth dates must come before death dates</report>
        </rule>
```
but it is not firing and I'm not sure why. I think I may be using the following-sibling wrong but I never used it before so I'm not really sure.

**Comment by RJP43** [comment]
@Samantha-Mcguigan Does birth every come after death (or as the following-sibling to death)?
Try running this XPath first `//death/following-sibling::birth`. How could you switch this around or use another axis (perhaps preceeding-sibling) to fix your rule?

**Comment by RJP43** [comment]
@Samantha-Mcguigan Also, since your rule context is the death elements does it make sense to test for `tei:death/@when` that would look for death elements that are children of death elements. Instead I think you want self there.

**Comment by Samantha-Mcguigan** [comment]
So now I have this:

```
        <rule context="tei:death">
            <report test="tokenize(@when, '-')[1] lt preceding-sibling::tei:birth/tokenize(@when, '-')[1]">birth dates must come before death dates</report>
        </rule>
```
and it is grabbing the same things as my last expression but grabbing the death dates. Is this better?

**Comment by RJP43** [comment]
@Samantha-Mcguigan okay so my brain hurts because **math** but would making sure the death date value is less than the birth date value result in a later death date than birth date?

**Comment by RJP43** [comment]
@Samantha-Mcguigan ok scratch my brain fart from above. Yea that should work since it is a report.

**Comment by RJP43** [comment]
@Samantha-Mcguigan is it firing?

**Comment by Samantha-Mcguigan** [comment]
it is firing I am getting 3 items but it would not fire for a birth or death date that had the an attribute other than when such as `@notAfter` or `@notBefore` is that okay? would I need to make a different rule for those?

**Comment by nlottig94** [comment]
@RJP43 I wish I was on my own computer and could try this exercise on my own!! :(

**Comment by Samantha-Mcguigan** [comment]
okay last question I'm on I have:

```
   <let name="si" value="doc('http://digitalmitford.org/si.xml')//@xml:id"/>
    <pattern>
        <rule context="@ref/@resp">
            <let name="tokens" value="for $w in tokenize(., '\s+') return substring-after($w, '#')"/>
            <assert test="every $token in $tokens satisfies $token = $si">
                Every @ref and @resp after the hashtag must match an xml:id defined in the list in this file!
            </assert>
        </rule>
    </pattern>
```

a minute  ago I was getting a few errors but now it is giving me something that is saying there is an error reported by XML parser??

**Comment by ebeshero** [comment]
Hi Sam— I didn’t see this on GitHub but it’s in my e-mail—did you spot the error? I think it’s the rule @context: You’ve set it on @ref/@resp, and the forward slash (/) doesn’t make sense to the parser! You can change that to a vertical pipe (|) to indicate either @resp or @ref attributes as your context! 

Dr. B

**Comment by ebeshero** [comment]
Hi Sam— I didn’t see this on GitHub but it’s in my e-mail—did you spot the error? I think it’s the rule @context: You’ve set it on `@ref/@resp`, and the forward slash (`/`) doesn’t make sense to the parser! You can change that to a vertical pipe (`|`) to indicate either `@resp` or `@ref` attributes as your context! 

````
   <let name="si" value="doc('http://digitalmitford.org/si.xml')//@xml:id"/>
    <pattern>
        <rule context="@ref/@resp">
           . . .
        </rule>
    </pattern>
````

**Comment by Samantha-Mcguigan** [comment]
Sorry I deleted the post because I just decided to do two different rules  and change the `context`  from` @ref` to `@resp` and just turn it in because my brain was melted and I forgot you could use ` ( | )` so I just changed it and resubmitted it .

**Comment by jonhoranic** [comment]
Ok, I have two questions to finish up, this being 4 and 7 which I am pretty sure are correct in form but I cannot get them to fire properly! As asserts they grab ALL the strings in the tested=" " space, and as reports they grab nothing at all. Currently they are set up to be reports, just so my screen is not crazy red when I check the file. Should I post these here? Or is there a need to redact any of the content as to not give the problem away?

**Comment by ebeshero** [comment]
@jonhoranic Well, can you post some partial, or tell me a little more?

**Comment by ebeshero** [comment]
@jonhoranic All I can tell from your post is that your rule context is probably fine (since you can tell when the rules are firing via assert tests). But your `@test` is the problem: it's getting too much and not isolating the problem!

**Comment by jonhoranic** [comment]
@ebeshero Here is what I have for question 4, perhaps that might be my issue, in trying to find what is not capitalized I might just be grabbing too much. Take a look:

```` <!-- #4 -->
    <pattern id="capitalization">
        <rule context="all the tei:namespaces I need seperated by pipes">
            <report test="starts-with(., '[A-Z]')">Explination.</report>
        </rule>
    </pattern>````

**Comment by ebeshero** [comment]
@jonhoranic Yes, I think you're right, and you want to change that report to an assert! Assert basically lays out how things *ought* to be. But report is an alarm bell: report when this condition happens! You don't want to be raising an error when things are properly starting as they should with capital letters...

**Comment by jonhoranic** [comment]
@ebeshero Now, as soon as I do so, it is instead flagging names with starting capitals, making the result total jump up in the hundreds. I know that should not be occurring but I cannot figure it out without breaking form of the rule.

**Comment by jonhoranic** [comment]
@ebeshero The same thing is occurring in question 7, and my contains are looking for pound-signs '#' or whitespaces  ' ' to kill two birds with one code. It catches way more then it reasonably should when I make it an assert.

**Comment by ebeshero** [comment]
@jonhoranic Aha! I see the problem! You are treating the function `starts-with()` as if it were like `matches()` and can contain a regex! It's not so...`starts-with()` is kin to `contains()`, so it's pulling literal strings, and NOTHING but square brackets at the start of those names is going to satisfy your test now! ;-)

**Comment by ebeshero** [comment]
@jonhoranic So, one way you can get the versatile and marvelous `matches()` function to match on the start or the end of a thing is to use ^ or $, just the way we used them in autotagging to find the starts and ends of lines. Here they find what's at the start or end of an element's text node or attribute value.

**Comment by jonhoranic** [comment]
@ebeshero Interesting, I am gonna try to mess with this and see what I come up with, is there an example of how ````matches()```` is set up in one of our tutorials?

**Comment by ebeshero** [comment]
@jonhoranic I've been modeling it in class, so I think there's an example or two in the Class Examples -> Schematron folder here on DHClass-Hub. But see also the [XPath Functions We Use Most](http://dh.obdurodon.org/functions.xhtml) page on Obdurodon. 

matches() is set up like contains() and its friends, so that second argument is wrapped in a pair of quotes when it's referencing a string of text.

**Comment by jonhoranic** [comment]
@ebeshero That worked for number 4, but my attempts to get this to work with 7 are baffling because I just used the same form to fix the problem is not working for this one:

 ````<pattern id="no_poundSign">
        <rule context="@xml:id">
            <report test="contains(., '#') or contains(., ' ')">
                Explination.
            </report>
        </rule>
    </pattern>````

**Comment by jonhoranic** [comment]
@ebeshero I even tired changing those with `starts-with()` and `matches()` and it is the same odd result.

**Comment by jonhoranic** [comment]
@ebeshero I think I have it working now, I am going to try to finish this up for turn in.

**Comment by ebeshero** [comment]
@jonhoranic Sorry--looks like the night crew was sound asleep for the last part, but I'm glad you've found a way to repair your code!
