### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#285]
I was looking through my computer and it says that my computer is being shared with law-rnc-ice-1. I am not sure what this means and I am a little scared. Is this something with eXist ?

**Comment by ebeshero** [comment]
@ajnewton1 I don't think this has to do with eXist, since you're using it as an online service, and it's not reading your computer. (You're reading files on a remote computer when you work in our PSC installation of eXist.) 

The issue I described in class was if you install eXist-db locally, where you might inadvertently set up your computer as a data port for someone else to access. I've never had a problem with this either--and I think it would only work if you set up your computer to be a server, and people knew how to access your local installation of eXist remotely. The way you're accessing eXist is not like accessing someone else's wifi or network. 

Now the question is, what **is** happening? Where are you seeing the message that your computer is being shared?

**Comment by ebeshero** [comment]
Also, where are you with your computer? Are you part of a household network?

**Comment by ajnewton1** [comment]
I am at my house which I think is weird because I never have seen this before. 
<img width="761" alt="screen shot 2017-03-01 at 5 54 23 pm" src="https://cloud.githubusercontent.com/assets/24962219/23485152/38d2a416-fea8-11e6-9a83-e17f537e1389.png">

**Comment by ajnewton1** [comment]
as you can see it is in the bottom left corner. I can't delete it or remove it at all. I am currently reading articles to see what is going on

**Comment by ebeshero** [comment]
Hmmm. I'm on my mac in my house right now, and I'm definitely part of a household network here. Let me see if my screen looks similar.

**Comment by ebeshero** [comment]
Yep...I have the same thing here, only it's not a surprise to me. Here's how my Finder 
<img width="769" alt="screenshot 2017-03-01 17 57 51" src="https://cloud.githubusercontent.com/assets/4014518/23485254/af25d048-fea8-11e6-8d18-068937722dfe.png">

**Comment by ajnewton1** [comment]
Interesting. Maybe my father did something and hasn't told me about it. Ill have to ask him about that. Thank you

**Comment by ebeshero** [comment]
So, basically in my house, I'm sharing with my husband's computer, named "noobo", and WordHoard is a shared network drive that Greg and I have in our house. Now, I can click on these and retrieve files.

**Comment by ebeshero** [comment]
I'm noticing that when I click on "noobo" it won't connect, because we didn't configure that. But WordHoard is a network drive we made in the house to store stuff we might both need to access from different computers. And that opens up okay.

**Comment by ajnewton1** [comment]
Now I went on my computer and turned all the sharing that was on to off and it is still there. Would this be something that I would need to accept or would that computer just automatically come up as 'Shared'

**Comment by RJP43** [comment]
So I have something similar on my windows computer where I can see other computers and devices on a shared home and some other networks I have configured sharing with. What is interesting is even when I am not connected to a network the shared folders (linked computers and devices) still appear (albeit non-clickable) in my file directory. If all of your sharing settings are shut off you shouldn't be concerned that any other computer on any networks you connect with are  accessing your computer. One thing you can try to do is forget all wireless networks and then just reconnect to your home Internet and see if it is still there. If not then it's likely a device or computer or some shared file from somewhere else you have connected to (perhaps at school).

**Comment by RJP43** [comment]
*shared file folder

**Comment by ajnewton1** [comment]
Thanks for the help! I am pretty sure it is coming from my fathers work computer
