### ISSUE TITLE
Project Midterms (due by F 3/17)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#287]
@ahunker @jonhoranic @bsf15 @Samantha-Mcguigan  @ajnewton1 @RJP43 
Your Midterm exam is to do the following for your projects: 
1) **Schema Design:** Design clear and well-documented schemas in Relax NG and Schematron to guide and manage the team's markup for your project. (Bri and Audrey should meet with Dr. B about preparing an ODD schema, with embedded Schematron rules, for their TEI.)  
2) **XML Markup**:  Complete a substantial amount of XML coding (this to be determined within your project teams, but try to complete over half of the markup you need for your projects.) Check and correct this code with help from your project schema.
3) **Website Development**: Produce some new substantial pages on your team's website, indicating what you are accomplishing and what you aim to produce by the end of the semester.

**Comment by ahunker** [comment]
Will the Hamilton Project require a Relax-NG since we're using TEI?

**Comment by ebeshero** [comment]
@ahunker No, but see our note to you and @bsf15 : Let's make an ODD file for your project, where we streamline the TEI to just what you all need to use. It's easy to edit and add elements and constrain attributes from the TEI, but we'll want to have a meeting together to create it. The ODD generates your Relax NG schema by paring down from the giant TEI Relax NG schema. And you poke your Schematron rules into it. We'll show you how! (We could get started on this tomorrow if we have time.)

**Comment by ebeshero** [comment]
@ahunker The easiest start for you will be, probably, the ODD that @setriplette and I worked out for the lope project last year! Here it is in the goldenAge GitHub repo: 
https://github.com/setriplette/golden_age/blob/master/ODD/goldenAgeODD.odd 

Basically we need to walk through the TEI modules together and decide which modules you don't need, and within those, which elements you want to keep. Then we work on attributes and attribute values. At this point, if you and @bsf15 have a good idea of how you're marking your files, we're in a good spot for developing this. Because the TEI is so huge, ODDs are the best and most human-readable way to customize the schema you want that best fits your project!

**Comment by ebeshero** [comment]
@ahunker @bsf15 Thinking about timing: If you'd rather have a schema running quickly write now and not wait for us to meet to develop your ODD, you can write Schematron to do things like constrain your attribute values (typically stuff we do with Relax NG), as well as the other kinds of checking we more typically do with Schematron (like check for sequences, white space issues, etc). Survey your markup so far and think about what kinds of things you need to catch most right now to locate errors!
