### ISSUE TITLE
Project Presentations at Cathedral of Learning: Friday April 14 (2017)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#292]
Can we all be available to go to Pitt-Oakland, the Cathedral of Learning, to join our sibling DH course in project presentations on **Friday April 14**? If we can all do this, we'll have a chance to share our work with the other students and get feedback from each other. Presentations and responses will be worth credit toward your course projects. 

Presentations will follow a format traditional in Digital Humanities: the lightning talk! Each project team will present a "lightning talk" of about 5 minutes, followed by 5 minutes of questions. Ideally you present the most important features of your project. We'll follow up with a response period on project GitHub repositories--asking everyone to comment on each other's projects in the following week with advice for final project development.

Respond here to indicate whether you can make it, or if you have conflicts, and whether you will need a ride. 

I can write a letter to your profs excusing you for the day-trip to Pittsburgh if you need it. 

@RJP43 @jonhoranic @ahunker @Samantha-Mcguigan @ajnewton1 @bsf15

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I will be able to make it and I can also give rides, I have 4 extra seats in my car.

**Comment by ajnewton1** [comment]
@ebeshero Do you know what time we will be leaving and what time we will be done?

**Comment by ebeshero** [comment]
@ajnewton1 I'd recommend leaving Greensburg around 8:30am, which dodges the morning rush hour traffic AND gets you to Oakland comfortably early (just before 9:30). (You could leave somewhere between 8:30 and 8:45, really).

Our sibling class begins at 10am, in a ground floor computer classroom in the Cathedral of Learning. It's over at 10:50am, so you can easily return for afternoon classes. (When I regularly commuted to that class, I was easily able to get lunch and return to Greensburg for a 1pm class.)

**Comment by ajnewton1** [comment]
@ebeshero I should be able to make it

**Comment by ahunker** [comment]
I, unfortunately, can't make it :(

**Comment by jonhoranic** [comment]
Checking with the family, they are really unsure about how we are going to manage the range of events in April in order to kick start the theatre season (and bring some revenue into the house), so I am going to have to say I will not be able to attend.

**Comment by RJP43** [comment]
I'll be there, and I can give rides from the Plum/Monroeville/Murrysville/Delmont area.

**Comment by ebeshero** [comment]
@jonhoranic I will need to be back for our American Lit class on Friday afternoon 4/14 at 2pm. If you go and return to Greensburg with me by early afternoon for class, does that make a difference for you?

**Comment by jonhoranic** [comment]
@ebeshero I am still unsure, I will miss all my other classes that day and I will also be juggling things on top of that which has me worried overall. If we were closer to that date, I would be better prepared. I would hate to commit to this to have to bail out for something I could have planned around. I will try talking with the family again and see if I can at least get something concrete.

**Comment by ebeshero** [comment]
@jonhoranic With @ajnewton1 and @Samantha-Mcguigan present, that will help if you really can't make it. Not to complicate matters, but it might make sense for *you* in particular to be excused from classes that day to make a conference presentation: Remember, of course, that on the same day, after the DH class, Gabi Keane (from Obdurodon's [Victorian Ghost Stories](http://ghost.obdurodon.org/) project) is trying to get the Sigma Tau Delta DH panelists (you, me, Pat, Becca) together to discuss [Eldritch](http://eldritch.newtfire.org) and your [Graveyard](http://graveyard.newtfire.org) projects together with her project (like our practice run ) at their Undergraduate Literature Conference. It would be wonderful to bring you all together that day to present, and I am sure my colleagues would understand (and take some pride in) your absence to participate in both the Oakland DH class and the Undergraduate Lit conference that day. I would really like you to have a chance to present your fine work this semester if it's at all possible.

**Comment by RJP43** [comment]
**Ride Arrangments to Pitt-Oakland's Cathedral of Learning**

@Samantha-Mcguigan driving to and from Greensburg with @bsf15 @jonhoranic @ajnewton1 @PPH3 leaving at 8:30 AM Smith Hall Parking Lot   
  
@rjp43 driving to and from Plum leaving at 8:45 AM  
  
@ebeshero and @ghbondar will already be on site

**Comment by PPH3** [comment]
I will be driving myself to the conference. Samantha, thank you for the offer.

**Comment by ajnewton1** [comment]
I will be driving myself as well. I am not able to stay for the GOTHIC presentation because I have to work.

**Comment by ebeshero** [comment]
Just copying this location info into this issue so we have it here, too:
**DH class lightning round presentations** will be from 10:00–10:50 in CL G-27 (Cathedral of Learning ground floor computer lab classroom)

**Humanities/Lit. Conference GOTHIC presentation** will be from 11:00-11:50 in CL 501 (Cathedral of Learning)

**Comment by Samantha-Mcguigan** [comment]
im leaving my house now ill should be there in 20 min

**Comment by RJP43** [comment]
I just made it to the Cathedral. I parked in the Soldiers Memorial Parking Garage on the lower 3rd level. I'm sitting outside the cathedral by the fountain ... I can wait here for others since the classroom is a little weird to find if you've never been here.

**Comment by RJP43** [comment]
Aaron is with me now in front of the Cathedral and informed me street parking is free due to the holiday weekend.

**Comment by RJP43** [comment]
@bsf15 @Samantha-Mcguigan @jonhoranic @ajnewton1 

Here is the link to respond to the Oakland projects:
http://dh.obdurodon.org/course-projects.xhtml
