### ISSUE TITLE
JavaScript and DHTML class resources

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#299]
I'd like us to take a look at this "DHTML" tutorial today in class:
http://w3schools.sinsixx.com/dhtml/default.asp.htm

**Comment by RJP43** [comment]
Here is a link to the information to grab HTML elements using the CSS querySelectors:
https://www.w3schools.com/jsref/met_document_queryselector.asp
The list of possible CSS Selectors can be found here: 
https://www.w3schools.com/cssref/css_selectors.asp


Also, here is a list of javaScript events:
https://www.w3schools.com/js/js_events.asp
