### ISSUE TITLE
Stacey is throwing sand at me in the sandbox! 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#3]
This hurts my eyes! Waaaah! Make her stop!

![image](https://cloud.githubusercontent.com/assets/4014518/9452586/1d391800-4a83-11e5-9058-252807dc54c9.png)

**Comment by setriplette** [comment]
I am going to take my bucket and go home.

**Comment by ebeshero** [comment]
No fair!

**Comment by ebeshero** [comment]
We are declaring the sandbox a peaceful zone of orderly construction, where castles are built.
