### ISSUE TITLE
General XPath question

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/DHClass-Hub#30]
I'm not sure what we're trying to find/select. For example, in the question "What XPath would find ONLY the chapters in the file?" are we trying to select the whole chapters or only the chapter headings?

**Comment by ebeshero** [comment]
@brookestewart You want to find the whole chapters, not the chapter headings. (We'd have specified "chapter headings" if we wanted you to find a heading instead.)

**Comment by nlottig94** [comment]
@ebeshero Is there a link to upload our answers in CourseWeb?

**Comment by ebeshero** [comment]
@nlottig94 Ah! Thanks for reminding me. I've just posted the upload link in Courseweb.

**Comment by nlottig94** [comment]
I am having trouble understanding the second question for the XPath Exercise 2. Could someone explain it to me?  I go the first question with no problem!:
These latitude measurements you've just looked up are all held inside paragraphs, or the `<geo select="lat">` element. What would you add to the previous XPath expression to return the paragraphs that hold latitude measurements in Book I?

**Comment by nlottig94** [comment]
If it helps, my expression for the first question is: `//div[@type="book][1]//geo[@select="lat"]`

**Comment by ghbondar** [comment]
Nicole, you are on the right track. The question is asking you to retrieve the geos that are inside p-elements. Think about how you can filter your search to only those specific p-elements that contain the geo-select-lat attributes.

**Comment by nlottig94** [comment]
Thank you @ghbondar !  I got through it!

**Comment by noobo** [comment]
Great! Wee figured that rephrasing the goal might help. 😁
