### ISSUE TITLE
JavaScript: Testing Your Code

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#302]
If anyone is having a difficult time going back and forth between oXygen files and seeing what your code looks like on the web (like I do), check out [CodePen](https://codepen.io). It is free and easy to use. You don't need to create an account or anything but to get started all you have to do is hit the drop down menu titled 'Create' and then click 'New Pen'. Your good to go

**Comment by ebeshero** [comment]
ALSO, let's try using the Console view in Developer tools on Chrome.
