### ISSUE TITLE
Class T-Shirts: Sizes and Colors please!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#303]
I've just phoned Big Frog (a wonderful T-shirt company in Greensburg) and revived our Spring Coding and Data Visualization T-Shirt orders from last year--they are pretty spectacular! I had one large ash grey left in my office, which I've photographed and pushed to the repo here: https://github.com/ebeshero/DHClass-Hub/blob/master/T-Shirt-Designs/TShirt_CDV_Network.JPG

Big Frog has been terrific for working with us on small batches of shirts, and they can quickly process shirts for our little group of 5. For now, Big Frog just needs to know what color(s) and sizes we would like for our T-shirts. To give you an idea, I take an adult medium and Greg (the other half of the Bondars) takes an adult large. We know we need to work with a light color for the colors to pop and so we aren't paying a lot extra for lots of ink. (Our shirts are made with ink on the cloth--not that nasty plastic-y stuff--so the ink is part of the fabric.) Last year we decided on light grey, sand, or pale blue shirts given the color range of the network plot we were featuring. 

These are the colors in which we printed our shirts last spring--and they are ideal so the network graph "pops" on the shirt: :-) 

[SAND](https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=18)
[LIGHT BLUE](https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=64)
[ASH GREY](https://www.alphabroder.com/cgi-bin/online/webshr/prod-detail.w?sr=G200&currentColor=50)

**Would you quickly respond here with your preferred size and color?** I'll place the shirt order as soon as I've heard from all of you, and if that's by tomorrow (Thursday 4/6) we should easily be able to pick up the completed shirts by early next week. And yes, you should wear your new shirt (with your "eye-code" button) to present from your project next Friday 4/14 when we are in Pittsburgh together! 
Thanks, everyone!
@Samantha-Mcguigan @ajnewton1 @ahunker @bsf15 @jonhoranic

**Comment by ajnewton1** [comment]
Adult M and Sand for me please!

**Comment by jonhoranic** [comment]
Medium - Grey (just like last time!)

**Comment by Samantha-Mcguigan** [comment]
small and sand

**Comment by ahunker** [comment]
Medium and light blue

**Comment by bsf15** [comment]
Medium and light blue

**Comment by ebeshero** [comment]
I've placed the order! Thanks everyone! :-) Should have the shirts by Monday!
