### ISSUE TITLE
JavaScript Exercise 3 

### ISSUE THREAD

**Issue by bsf15** [ebeshero/DHClass-Hub#305]
I've been trying to walk through the assignment myself, but I feel like I am stuck because I am unsure if I am going in the right direction and I was thinking that maybe I needed to implement elements of css or javascript into the html/svg/xquery I have going on to maybe start seeing things come together, but I didn't want to do more of the coding if what I have currently is incorrect because then I assume I would just have a bunch of little mistakes as opposed to just fixing the ones I maybe have now. 

I know I am not seeing my line that is meant to represent all the recipient's letters and what I have started of a checkbox is not really coming together as it is firing out a bunch of names and nothing else. 

I am just lost if I am even moving in the right direction with this code or if my mistakes are just depending on further code from the javascript or css elements, if that makes sense.

This is my code so far: 

```
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0";    
declare namespace htm="http://www.w3.org/1999/xhtml";

declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];
declare variable $distinctYears := distinct-values($letterDates);

declare variable $minDY := xs:integer(min($distinctYears));
declare variable $maxDY := xs:integer(max($distinctYears));
declare variable $years := $maxDY - $minDY;
declare variable $years_space := $years* 365;

declare variable $recipLetters := $letterFiles[descendant::tei:titleStmt/tei:title/tei:persName/@ref];
declare variable $distRecips := distinct-values($recipLetters);



declare variable $recipDates :=$recipLetters//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/string();
declare variable $maxRecip := max($recipDates);
declare variable $minRecip := min($recipDates);

declare variable $letterRecipients := $letterFiles/descendant::tei:titleStmt/tei:title/tei:persName/@ref;
 declare variable $distLetterRecips := distinct-values($letterRecipients);
 declare variable $si := doc('http://digitalmitford.org/si.xml');


 <htm:html>
    <htm:head>
    <htm:title>Mitford Letter Timeline</htm:title>
    </htm:head>
    
    <htm:body>
    {
for $r in $distLetterRecips
let $recips := $letterFiles/descendant::tei:titleStmt/tei:title/tei:persName/@ref = $r
let $names := $si//tei:person[@xml:id = tokenize($r, '#')[2]]/tei:persName[1]
return 
 <htm:input type="checkbox" id="{$r}">{$names}</htm:input>
    }
    <htm:div type="svg">
    
    <svg width="3000" height="500">
   <g transform="translate(30, 100) scale(.7, .7)">
   <text x="25" y="-25">Timeline of Letters to Specific Correspondents in the Digital Mitford Collection</text>
      <line x1="0" y1="30" x2="{$years_space}" y2="30" style="stroke:black;stroke-width:20"/>  
       {
           for $i in (0 to $years)
    return
        <g>
            <line x1="{$i*365}" y1="25" x2="{$i*365}" y2="50" style="stroke:black;stroke-width:5"/>
         <text x="{$i*365}" y="10">{$minDY + $i}</text>
         <circle cx="{$i*365}" cy="50" r="{count($letterDates[contains(.,$minDY+$i)])div 2}" stroke="black" fill="aqua" stroke-width="3"/>
         </g>
        
         }
         {
             for $d in $distRecips
             let $selectRecipLetter := $letterFiles[descendant::tei:titleStmt/tei:title/tei:persName/@ref/string() = $d]
             let $letterDates := $selectRecipLetter//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/string()
             let $minDate := min($letterDates)
let $maxDate := max($letterDates)
let $earliestDate := format-date($minDate, '[d]')
let $latestDate := format-date($maxDate, '[d]')
let $earliestYear_Integer := xs:integer(tokenize($minDate, '-')[1])
let $latestYear_Integer := xs:integer(tokenize($maxDate, '-')[1])
let $earliestDay_Integer := xs:integer($earliestDate)
let $latestDay_Integer := xs:integer($latestDate)
let $earliestLetter := ($earliestYear_Integer - $minDY)* 365
let $latestLetter := ($latestYear_Integer - $minDY)* 365
return
    <g>
         <line x1="{$earliestLetter + $earliestDay_Integer}" y1="30" x2="{$latestLetter + $latestDay_Integer}" y2="30" style="stroke:aqua;stroke-width:4"/>
        </g>

         }

</g>
</svg>
</htm:div>
</htm:body>
</htm:html>
```

**Comment by ebeshero** [comment]
@bsf15 I wanted to reply to this last night but I fell asleep early! Before I go into eXide to take a closer look, I see two interesting things:
1) Your master line isn't going to have ANY deviation on X. It starts and ends at the same value. And the y is moving up from 25 to 50, so I imagine what you'd see is something over to the right that goes up a little bit (a little tiny line). Here's what you have:
````
<line x1="{$i*365}" y1="25" x2="{$i*365}" y2="50" style="stroke:black;stroke-width:5"/>
````
and I think you mean for `@x1` to be set at the starting point for your line, at 0, right? If you are plotting a line horizontally, the two y values should be the same. 

2) This is probably not an issue, but worth noting: You're using an @scale on the SVG `<g>` element holding `transform=translate()`, and I'm not sure how that's working. I think it's a neat idea to make the graph maybe 7/10s as big as it would be, but it's different from how we were controlling dimensions with the viewbox on the svg element. I wonder if it's behaving unpredictably? We might just try removing that to see how it affects the output.

Does that catch the problem?

**Comment by ebeshero** [comment]
Oops! I'm looking at your code now in eXide and I see the problem is not what I thought... I'm editing the above post...!

**Comment by ebeshero** [comment]
@bsf15 AHA!!!! I found the error that was preventing your SVG lines to output with x1 and x2 values. It was way up near the top, in your global variables. You have:
````
declare variable $recipLetters := $letterFiles[descendant::tei:titleStmt/tei:title/tei:persName/@ref];
declare variable $distRecips := distinct-values($recipLetters);
````

When we actually look at the output of `$distRecips`, we get entire letters, not the `@ref` attributes on the persName in the titleStmt on each letter. You didn't use that variable when you output your HTML checkboxes, but you *did* use it down in the SVG, and since it's going letter by letter, that is why your loop is so much too big! So you need to fix that global variable:

````
declare variable $recipLetters := $letterFiles/descendant::tei:titleStmt/tei:title/tei:persName/@ref;
declare variable $distRecips := distinct-values($recipLetters);
````
And then your $distRecips will give us distinct values of letter recipients the way it's supposed to!

**Comment by ebeshero** [comment]
@bsf15 Once you're getting good output, you're going to want to output `@id` attributes on the `<g>` that hold letter recipient lines (about which see the assignment), so you can match them up with the `@id` on your HTML `<input>` checkbox elements, and you'll be ready to write the CSS / JavaScript portion.
