### ISSUE TITLE
Friday April 14: Travel and Presentations in Oakland 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#307]
See (and scroll down) https://github.com/ebeshero/DHClass-Hub/issues/292

**Comment by RJP43** [comment]
@bsf15 @ajnewton1 @Samantha-Mcguigan @jonhoranic @PPH3 @ebeshero 

Here are the details for Friday Presentations:

DH class lightning round presentations will be from 10:00–10:50 in CL G-27 (Cathedral of Learning ground floor computer lab classroom)

Humanities/Lit. Conference  GOTHIC presentation will be from 11:00-11:50 in CL 501 (Cathedral of Learning)
