### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#308]
Presentations were great today! Everyone did a fantastic job! For those of you unaware, I submitted an app for the Pitt Mobile App Challenge and it would be really awesome if you all could vote for it. It is called BookHunter (more information on the web if you're interested) and all you have to do is follow this link https://appchallenge.pitt.edu and toggle the 'Code It' button and then scroll down and click on BookHunter to vote (it is the little white circle with blue circle inside). It would be very helpful. Thank you all and again, everyone did a great job today.

**Comment by ebeshero** [comment]
Presentations were definitely impressive--thank you everyone! And I have just voted for your BookHunter app, @ajnewton1 !

**Comment by jonhoranic** [comment]
@ajnewton1 Voted, and thank you for all the work you put into the newsAnalysis project. I think we made a good impression at main campus and with a bit of fiddling I think our working iteration of the project will be complete shortly.

Equal thanks too @Samantha-Mcguigan for being another awesome project assistant and for driving the carpool, and to @bsf15 for being part of the carpool party (and extra points for presenting on your own!).

To celebrate, I am going to post this little relax jam [here](https://www.youtube.com/watch?v=f7wkRET0hbo). RATATAT is one of my favorite modern instrumental groups, adding rock and chiptune themes into their overall experimental sound (matched by equally experimental music videos). It is repetitive in a sense, but never really _feels_ like it. I see it as a zone out piece, which is great when tackling stressful assignments. But hey, at this point of the semester, I think we can all use a little bit of stress relief! 

Enjoy some downtime this weekend when you can guys.
