### ISSUE TITLE
Website Layout: CSS Flexboxes

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#310]
As you're working on project websites, you're likely going to want to lay out portions of your pages side by side and up-and-down. You might want to try a multi-box layout, or to orient some components of your page next to, above, and below one another in a way you want to control. If you're finding yourself wanting to have more control over layout, you should take a look at **flexbox** properties in CSS.
Here are a couple of good sites to check out flexboxes:

https://internetingishard.com/html-and-css/flexbox/

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes

@ahunker You were asking me about something like this a while ago, and this is a better answer than I gave you then! 
@ajnewton1 @bsf15 @Samantha-Mcguigan @jonhoranic @RJP43

**Comment by ebeshero** [comment]
I have to say, I really like [this "Interneting is Hard" site](https://internetingishard.com/html-and-css/) for its explanations of CSS for responsive web design (that is making your site responsive for all kinds of monitors, including mobile devices). It's a great crash course and reference: https://internetingishard.com/html-and-css/

**Comment by ajnewton1** [comment]
Apple Users: To inspect you webpage with Safari. Go to <Safari> <Preferences> <Advanced> and then toggle the <Show Develop menu in menu bar> to on. Then to inspect your webpage. You can either (A) right click and click <Inspect Element> or (B) go to <Develop> <Show Web Inspector>. Also, a cool feature is to look what your page would look like on a mobile device/ tablet. Go to <Develop> <Enter Responsive Deign Mode> and then you can play around from there. It is pretty neat and a quick and easy way to see what is going on on all platforms.

**Comment by ajnewton1** [comment]
I've been struggling to find a good and easy way to make a website and its contents adjust when the window screen becomes bigger and/or smaller. Good News! By setting your `div`, `img`, `video`, etc. to have a `height: 100vh; width: 100vw;`, you are able to adjust your window to fit the content on any screen. For more information on the `vh vw`, I found a decent [site](https://snook.ca/archives/html_and_css/vm-vh-units) that you can look at. Happy Coding!

**Comment by ebeshero** [comment]
@ajnewton1 Thanks for this recommendation! `vh` and `vw` units are good to try because (at least as I understand it) they consider the units of available height and width on the screen you're using. I'd like to spend some time experimenting with these in context with the CSS flex boxes we were testing a bit this past semester--to see whether we'd want to use them together, or separately!
