### ISSUE TITLE
Finals Week Project Meetings

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#311]
@Samantha-Mcguigan @jonhoranic @ajnewton1 @bsf15 @ahunker @RJP43 
List when and where you'll be meeting in Finals Week:

Aaron, Jon, and Sam: 12 pm Mon. **at FOB 131**

Bri and Audrey: 12:30pm Tues. **location to be determined**

**Comment by Samantha-Mcguigan** [comment]
I'm by FOB 131 do I need to get a key?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Punch in the code to get the key. It is an increasing sequence of odd numbers.

**Comment by Samantha-Mcguigan** [comment]
Never mind john is here

**Comment by bsf15** [comment]
@ahunker 
Just wanted to confirm if we are still meeting tomorrow at 12:30 in the little lobby area inside FOB (that place where we were sitting last time before heading into the room for digital humanities)?

**Comment by ahunker** [comment]
@bsf15 The meeting is still on. I'll see you around 12:30 in the lobby area inside FOB

**Comment by RJP43** [comment]
@bsf15 @ahunker @Samantha-Mcguigan @ajnewton1 @jonhoranic I am on campus in the FOB faculty/staff lounge if anyone wants to meet and get any help with project stuff. I plan to leave campus around 4, but I am willing to stay longer if anyone needs me. Let me know :)

**Comment by RJP43** [comment]
@Samantha-Mcguigan @jonhoranic @ajnewton1 -- Is the New Analysis team meeting today? If so, when and where? I'd like to join you. 

@ahunker @bsf15 -- Is the Hamilton team meeting again this week? If so, when and where? Let me know if I can be any help.

**Comment by ahunker** [comment]
@RJP43  and @ebeshero  Bri and I are on-campus finishing up Hamilton. We're in Cassell Hall if you're able to join us.

**Comment by RJP43** [comment]
@ahunker ... I can head over shortly!

**Comment by ebeshero** [comment]
@ahunker @bsf15 and @RJP43 I'm at home, but ping me if you need help!
