### ISSUE TITLE
DH student-mentor meeting 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#315]
@jonhoranic @ajnewton1 @ghbondar I've just sent an e-mail, but thought this might be a faster way to reach everyone: Can we get together for a meeting at, say, 11am on Friday 5/19? There are some things we can be preparing well in advance to get ready for coordinating the DH classes at Greensburg and Oakland this fall, and Jon and Aaron, you two are going to be the knowledgeable authorities--most in the know about Greensburg operations: the Oakland instructors are going to rely on your experience, especially with all things GitHub but also with newtFire assignments, too, and we should maybe take a little time now to plan ahead. 

If you're not available on Friday, let me know when you're free between Wed. 5/17 and Mon. 5/22. I'd like @ghbondar to be present, since he'll be teaching the Oakland course this fall.

**Comment by ajnewton1** [comment]
I will be able to meet Friday at 11am

**Comment by ebeshero** [comment]
Great, thanks @ajnewton1 ! Why don't we meet down in FOB 131 (the Center for the Digital Text)?
