### ISSUE TITLE
Adding Hub Collaborators

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#316]
My username is @quantum-satire. @ebeshero please add me as a collaborator to this DHClass-Hub.
(I hope I am doing this correctly!)

**Comment by ebeshero** [comment]
Huzzah! Yes you are! Welcome to GitHub, Ally!

**Comment by ebeshero** [comment]
@jonhoranic @ajnewton1 This is Ally Hall, who's joining our class thus fall and getting a head start by doing the GitHub assignments early! Welcome to our coding hive!

**Comment by ebeshero** [comment]
@quantum-satire I have just sent you an invitation that I believe went to your email.

**Comment by quantum-satire** [comment]
@ebeshero I accepted the request, thank you!

**Comment by zme1** [comment]
My username is @zme1. Please add me as a collaborator to this repo! @ebeshero

**Comment by ebeshero** [comment]
Hi Zack! Happy to...stay tuned a moment...

**Comment by pab124** [comment]
@ebeshero please add me as a collaborator to this DHClass-Hub

**Comment by ttb11** [comment]
@ebeshero please add me as a collaborator.

**Comment by jub45** [comment]
@ebeshero Please add me as a collaborator to this DHclass-Hub

**Comment by BMR59** [comment]
@ebeshero please add me as a collaborator

**Comment by ebeshero** [comment]
Yay! I'm adding people now...Welcome! Give me a minute or two...

**Comment by Blangzo** [comment]
@ebeshero , Please add me as a collaborator.

**Comment by ebeshero** [comment]
@Blangzo @BMR59 @jub45 @ttb11 @pab124 Welcome! I've just sent each of you invitations to the repository. Check the e-mail you used to create your account and accept the invitation! :-) Also--who are you people? We'll be chatting away on the DHClass-Hub, and our Greensburg class will be joining after 10:30, so this is a good moment to introduce yourselves and say hello! :-)

**Comment by tal80** [comment]
Hello, this is Tylar Lyons. My username is Tal80. Please send me an invitation @ebeshero. Thank you!

**Comment by miam1997** [comment]
Hi my name is Mia, add me as a collaborator. I am @miam1997

**Comment by flowerbee1234** [comment]
Hi, this is Liz Laughlin. Please add me as a collaborator. My name is @flowerbee1234

**Comment by alexfell06** [comment]
This is Alex Fell, my username is alexfell06. Please add me as a collaborator.

**Comment by Jamielynn92** [comment]
hi, my name is Jamie add me  as a collaborator. My name is @Jamielynn92

**Comment by ajnewton1** [comment]
![lolgato-funny_cat_pictures_174](https://user-images.githubusercontent.com/24962219/29878618-07d10904-8d71-11e7-8cd5-bc7213d705e1.jpg)

**Comment by ebeshero** [comment]
@jonhoranic Hi Jon! Show the pikachu face!

**Comment by ebeshero** [comment]
@quantum-satire Hi there, Ally!

**Comment by kes213** [comment]
Hi, can you please add me as a collaborator? @kes213

Kaylee Stinebiser

**Comment by jonhoranic** [comment]
Just going to leave [this](http://i0.kym-cdn.com/photos/images/original/000/674/495/6ff.gif) here...

**Comment by Jamielynn92** [comment]
pika pika pikachu

**Comment by ajnewton1** [comment]
New people! Check your emails and accept the invite! @miam1997 @Jamielynn92 @kes213 @alexfell06 @tal80 @flowerbee1234

**Comment by ghbondar** [comment]
@Blangzo @BMR59 @jub45 @ttb11 @pab124 
Hey, Pittsburghers! Welcome to GitHub and our DHClass-Hub/HIVE! Please post here and introduce yourself, and/or create a new Issue with a brief bio.

**Comment by Jamielynn92** [comment]
how do I add collaborators? I've looked through GitHub, but it seems my eyes cant find it. @ebeshero @ajnewton1 @jonhoranic

**Comment by ebeshero** [comment]
Hi @Jamielynn92 : Across the top of your GitHub repo on the web, do you see the "Settings" tab? Click on it.
* Then along the left panel on the Settings page, find "Collaborators" and click on that.
* You should be prompted for your GitHub password, I think as soon as you click.
The next screen should look like this:

<img width="948" alt="screenshot 2017-08-31 18 19 00" src="https://user-images.githubusercontent.com/4014518/29947785-77446750-8e79-11e7-97ae-295ef3cff94b.png">

You should be able to look me up (if you'd like to add me as a collaborator)--but you need to know my GitHub name, which is ebeshero (the same way you "pinged" me here).

**Comment by ebeshero** [comment]
Huzzah! You've just done it. Well done, @Jamielynn92 ! :-)

**Comment by Jamielynn92** [comment]
Thank you. The screenshot helped a lot. I kept going to the other 'settings' and I got confused.

Yay!
Jamie.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ttb11** [comment]
Hi, my name's Tyler Bokan and I study Linguistics and French at Pitt's Oakland campus.

**Comment by ebeshero** [comment]
Welcome! 👍

**Comment by Jamielynn92** [comment]
So I'm confused on how to push a file. I think I'm getting my commands confused.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ebeshero** [comment]
@Jamielynn92 Want to open a new issue on this? This one is getting pretty crowded--and was pretty much just to get us started with adding collaborators to the DHClass-Hub. I imagine lots of people are going to be experimenting with git this weekend, so it'll help to have a new Issue just on pushing files... When you post a new issue, tell us what's going on and where you're confused by the sequence of commands.

**Comment by Jamielynn92** [comment]
I will. I'm gunna try and do it tomorrow. But I may need a bigger break down of the steps. Just need a lil more information. I tried to write it down as well, but sometimes I feel like 10 second tom and forget.

Ps sorry for the late message. I worked late and finally remembered that you emailed me.

Jamie d.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mof11** [comment]
my username is mof11, @ebeshero please add me as a collaborator

**Comment by ebeshero** [comment]
Welcome @mof11 ! I've just added you--and you'll receive an e-mail message from GitHub (via me) to accept my invitation to this repo.
