### ISSUE TITLE
Free online Python modules this summer

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#317]
@jonhoranic @ajnewton1 @quantum-satire  (and anyone else following DHClass-Hub): I'm taking the free parts of an online introduction to Python this week, as it's required for an institute I'm part of this month (July). So this is going to be my 4th of July Holiday fun... I thought maybe you might want to take the class along with me. @RJP43 just took it (she's part of the institute too), and she says it won't be hard for us newtFire folks! :-) So, if you'd like to take a 13-part series of online tutorials along with your prof., how about giving this thing a go? I'm thinking, since it's all in a web interface, it'll be like a video game... https://www.codecademy.com/learn/python

Note: this is in Python 2, and the stuff we've started doing with projects in this class (as in with the "synset" lookup in Wordnet for the [Eldritch project](http://eldritch.newtfire.org), for example) has been in Python 3. That's okay, because the differences are small and predictable--the point of the online class is to get us thinking about the kinds of things we can do with Python and thinking programmatically (as in expressing stuff you want to do in little steps). For @ajnewton1 , I bet a lot of this will be review! And one of our goals, by the way, is to find some good method for web scraping, since this is often something students want to try in our course projects! **SO...who's in with me?** I'll be starting it this afternoon (4 July)...

Happy 4 July, by the way!!!  And we'll continue to use Python 3 via Anaconda Python for newtFire projects when we use it for real. I'll send install instructions if you like. But we won't need to install anything for this set of web modules.

**Comment by quantum-satire** [comment]
I have yet to try out Python myself so I'll try taking this course to get familiar with it!

**Comment by ebeshero** [comment]
Yay! Thanks, Ally!

**Comment by ebeshero** [comment]
To see the complete set of lessons available, click on the "Syllabus" tab. We're supposed to take the whole thing: 

1
Python Syntax
2
Strings and Console Output
3
Conditionals and Control Flow
4
Functions
5
Lists & Dictionaries
6
Student Becomes the Teacher
7
Lists and Functions
8
Loops
9
Exam Statistics
10
Advanced Topics in Python
11
Introduction to Classes
12
File Input and Output
