### ISSUE TITLE
Job for a Coder in CA

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#318]
If you've taken our DH class(es), you are well qualified to apply for this job in Santa Clara, CA and other positions like it. The starting salary is between $58,000 and 85,000 per year! 

http://www.simplyhired.com/job/NgSU8xdRpSJqoQmbcP3yZqXshC0tyephpzAFZAG_sDjpgYiwk5y7Dg

**Comment by ajnewton1** [comment]
@ebeshero Wow! Thats awesome
