### ISSUE TITLE
Greensburg DH Student-TA Meeting Friday 8/26

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#319]
@jonhoranic @ajnewton1 
* Are either of you free to meet me sometime this Friday August 26? (If so, about when are you free?)
* Check your Pitt e-mail for updates on the course development for this fall--and please respond to that message with times you want to set for office hours! 

More shortly about changes to web server access...

**Comment by jonhoranic** [comment]
@ebeshero 
I should be free 11:00am/noon-time. If that needs bumped back or moved forward let me know.

As for setting office hours, after my Modernism class ends (MWF 1:00-1:50) the rest of my day will be open until 4:30(ish).

**Comment by ebeshero** [comment]
Thanks @jonhoranic--that's very helpful! I'll see you around 11am, then, and let's meet at my office (FOB 204)>  @ajnewton1 I know you can't make it, and that's okay. Jon and I will take a look through some preliminary class prep, including setting up Courseweb... and we'll bring you up to speed later online!
