### ISSUE TITLE
Problem with the Distinct-value function.

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#32]
Hey, so it seems that every time I use this function, my entire xml editor crashes and I have to fight it a bunch to get it working again? If anyone has an idea, let me know...

**Comment by ebeshero** [comment]
@CodyKarch I am not sure what is going wrong here! If it's a bad XPath expression, oCygen should just give you an error message and quit processing. I wonder if it's something else: are you running some high memory processing applications in the background? If it's happening a lot, you might just reinstall oXygen--but why don't you show this to one of us--see if you can reproduce the crash where we can look at it together?
