### ISSUE TITLE
How to line-wrap text w/o prettyPrint

### ISSUE THREAD

**Issue by ghbondar** [ebeshero/DHClass-Hub#323]
Sometimes you will want <oXygen/> to wrap text, but you won't want to use prettyPrint, which will permanently add white spaces to the beginnings of the lines of your document. 

**One way to temporarily toggle the line-wrap on and off for your document is to use cntl-shift-Y** 

Try it! It will be your new Best Friend.

**Comment by ebeshero** [comment]
And for those of us on Macs, toggling line-wrap is Command-Shift-Y.
