### ISSUE TITLE
Difficulty find historical letters!

### ISSUE THREAD

**Issue by tal80** [ebeshero/DHClass-Hub#324]
How can I locate the historical letters needed to complete our homework?

Thanks!

**Comment by ajnewton1** [comment]
Here the link [http://dh.newtfire.org/XMLExercise2.html](url)

You can locate the options you have under the 'Options:' heading

**Comment by ajnewton1** [comment]
dh.newtfire.org/XMLExercise2.html

**Comment by ajnewton1** [comment]
[dh.newtfire.org/XMLExercise2.html](url)

**Comment by ebeshero** [comment]
I just quickly repaired the link! :-)
(Here's how to write links in GitHub's markdown syntax for the Issues tickets): 
`[text to be linked](http://i.am.a.link.html)`
