### ISSUE TITLE
What's due for next Wed. 9/6

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#327]
Up to this point, I've been announcing in class what's due for next time--so in case you haven't been in the habit of looking, please make sure you check the right-hand column of [the syllabus page](http://dh.newtfire.org/CDASyll.html#d2017-09-01), which tells you what you need to be doing next. It's a long weekend (yay!--happy Labor Day)! Since we have a little time to work with, we've scheduled a few things to help get you thinking about and accustomed to the new technologies we're working with. I'm just copying the three assignments for next Wednesday right here, with a little bit of added commentary, as we're all kind of "moving in" to the DHClass-Hub and trying to get used to the strange new worlds of git and code.

1. **[Git Exercise 2](http://dh.newtfire.org/GitExercise2.html):** Some of you may have completed this already, but install Git on your home computers and practice with the git shell commands we showed you today. You should be cloning your personal repo and the DHClass-Hub on your machines. REMEMBER:
-  ****Pull from remote before you start changing your local repo!**  Always to a `git pull`** from our DHClass-Hub every time you want to work with files in here--it's a busy place and lots of us will be changing files in this repo regularly!  
- Also, here's [a handy short list of git commands that I regularly use](https://github.com/ebeshero/DHClass-Hub/issues/193).  
- When you need help, post an issue here!  
- It's quite likely that you'll run into difficulties at some point with merging your local repo with a remote that you share with others, and we'll likely see issues with *merging* this week as we're working together. You know you have a problem if git won't let you push your commit, or won't let you complete a pull, and opens a strange new window asking you to write a message. What to do? Try following [our advice on dealing with merges here](https://github.com/ebeshero/DHClass-Hub/issues/92) and scroll down to the post where I show some git commands for dealing with the "vim editor".  

2. **XML exercise 3:**  
    - Review our feedback on your XML coding exercises so far and submit revisions if we asked you to. 
     - Mark up **a text of your choice** (any genre; manageable but reasonable size; foreign languages welcome). Work on applying attributes with your elements, and doing so in a careful and systematic way. Really, it's up to you--choose something interesting to practice XML coding and submit that on Courseweb for XML Ex 3.

3. **[Reading and Discussion Post here on DHClass-Hub](https://github.com/ebeshero/DHClass-Hub/issues/325)**: We've been doing lots of hands-on work, but this is a good moment to read more about what we're doing! These readings will give you some perspective on the origins of XML markup, and some serious issues with it that are worth thinking about! This will give us a chance to have the Pittsburgh and Greensburg DH classes join together in a shared discussion. And it'll get you used to writing in GitHub issues using [simple markdown](https://guides.github.com/features/mastering-markdown/) for formatting.

Thanks, everyone! See you online here on the DHClass-Hub! 
@alexfell06 @ajnewton1 @Blangzo @BMR59 @flowerbee1234 @gabikeane @ghbondar @jonhoranic @jub45 @miam1997 @kes213 @pab124 @quantum-satire @ttb11 @tal80 @zme1

**Comment by quantum-satire** [comment]
@ebeshero Was the Reading and Discussion post required? I went back to reply to another comment to fully complete the assignment but I haven't seen anyone else respond yet.

**Comment by ebeshero** [comment]
@quantum-satire Yes indeed, it's one of the required homework assignments due by tomorrow morning. I guess people are taking their time on the reading...? ((crickets chirping...)) I imagine there will be more activity later this evening.

**Comment by quantum-satire** [comment]
@ebeshero I hope so! That's odd that no one has added anything else yet though, it's on the syllabus!

**Comment by ebeshero** [comment]
Sometimes the first discussion is delayed like this...The reading is a bit involved and the three-day weekend probably didn't help matters. Let's see how this evolves! You shouldn't worry about making a second post until at least a few other people have responded.

**Comment by quantum-satire** [comment]
Alright! I'll keep an eye on it and I'll probably come in early tomorrow to make a response if that's alright!
