### ISSUE TITLE
The Lo-Fi Manifesto

### ISSUE THREAD

**Issue by gabikeane** [ebeshero/DHClass-Hub#329]
[The Lo-Fi Manifesto](http://kairos.technorhetoric.net/20.2/inventio/stolley/)
I just read this very cool digital article for my Composing Digital Media class.  I agree with most of what Stolley has to say here, and it can very easily be applied to our course's goals and eventual outcomes.   This class is very lo-fi, which is part of what makes it so useful. Hope you enjoy!

**Comment by ebeshero** [comment]
Numbers 4 and 6 of the manifesto are especially close to the beating heart of this course. Thanks for posting this, @gabikeane !
