### ISSUE TITLE
Pittsburgh & Greensburg DH Class Directories

### ISSUE THREAD

**Issue by ghbondar** [ebeshero/DHClass-Hub#333]
PITTSBURGH Instructors, Students, and Class Projects:
[@ghbondar](https://github.com/ghbondar) = Greg
Portuguese WhatsApp: [https://github.com/BMR59/Portu-WhatsApp](https://github.com/BMR59/Portu-WhatsApp)
[@BMR59](https://github.com/BMR59) = Brandon
[@pab124](https://github.com/pab124) = Patrick
[@ttb11](https://github.com/ttb11) = Tyler
[@zme1](https://github.com/zme1) = Zac

90s-rap: [https://github.com/Blangzo/90s-rap](https://github.com/Blangzo/90s-rap)
[@Blangzo](https://github.com/Blangzo) = Wesley
[@mof11](https://github.com/mof11) = Monica
[@amk231](https://github.com/amk231) = Angela

TurkishUrum: [https://github.com/ttb11/Urum](https://github.com/ttb11/Urum)
[@jub45](https://github.com/jub45) = Justin
[@gabikeane](https://github.com/gabikeane) = Gabi

**Comment by ebeshero** [comment]
And here is the Greensburg group:

@ebeshero = Elisa
@jonhoranic = Jon
@ajnewton1 = Aaron
@Jamielynn92 = Jamie
@quantum-satire = Ally
@flowerbee1234 = Liz
@tal80 = Tylar
@kes213 = Kaylee
