### ISSUE TITLE
Help with Relax NG Homework (Due 09/13)

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#335]
I'm having some trouble with debugging my XML code after associating my Schema with it. I uploaded the code [here](https://github.com/ebeshero/DHClass-Hub/tree/master/Troubleshooting/Relax_NG_troubleshooting) as Dr. B asked to do earlier in class today (hopefully this is what you meant!) I'm conitnuing to get the `element "___" not allowed anywhere; expected the element end-tag or text` issue again as on the last assignment, but I don't have the `element` set as an `attribute` and I allowed `text` to be in the elements necessary for `text` to be in. The answer is probably obvious--I'm just tired. I am able to have elements within elements in my XML document, correct? I'm also planning on adding more elements to the letter for markup, but I wanted to start with fewer elements to worry about before adding anything else.

**Comment by ebeshero** [comment]
@quantum-satire Yes--that's what we'd like you to be doing--pushing your code into the Troubleshooting directory. (We can pull it in locally to take a close look that way.) I'm doing that now...

**Comment by ebeshero** [comment]
I left some detailed comments to help you debug, @quantum-satire , and pushed it back into the [Relax NG directory you set in Troubleshooting](https://github.com/ebeshero/DHClass-Hub/tree/master/Troubleshooting/Relax_NG_troubleshooting). Hope this helps! Pull this in to open it up locally.

**Comment by quantum-satire** [comment]
@ebeshero Thank you so much! I'll pull it in locally tomorrow and get to work again!

**Comment by Jamielynn92** [comment]
how much schema should there be? I'm doing the star spangled banner and I haven't over done a lot of the xml for it? does it matter?

**Comment by gabikeane** [comment]
The length of the schema depends on the complexity of the hierarchy, but for RelaxNG assignment 2, you should try to build on what you did last time.  So hopefully your second schema will be more complex and longer than your first.

**Comment by Jamielynn92** [comment]
I'm doing a whole new one. I put it in troubleshooting if you want to look at it.

**Comment by gabikeane** [comment]
sorry, by build i mean build on your skills.  I can take a look during my office hour today.

**Comment by ajnewton1** [comment]
@Jamielynn92 I put comments in your [RelaxNG](https://github.com/ebeshero/DHClass-Hub/blob/master/Troubleshooting/Relax_NG_troubleshooting/downey_09_13_xml_05.rnc) code. I hope this is helpful to you. Let me know if you need more explaining on certain things.

**Comment by Jamielynn92** [comment]
@ajnewton1 I added my letter xml/schema to the troubleshooting. I think that one was a lil easier to code. ill try the other one another time.

**Comment by ajnewton1** [comment]
@Jamielynn92 First of all, your beginning line on your .rnc file is barely incorrect. It should read ````start = Letter```` It is not a lowercase 'letter' because in your .xml file, your start tag is ````<Letter>````

**Comment by Jamielynn92** [comment]
I thought so.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajnewton1** [comment]
@Jamielynn92 Stay tuned for further updates on your [code](https://github.com/ebeshero/DHClass-Hub/commit/5fd86844cec1235414e659ba70b40d0bda01a0f5)

**Comment by ebeshero** [comment]
@Jamielynn92 Just wanted to say--I took a peek at your homework submission and it is SO MUCH BETTER! You might laugh when you see how easy it'll be to repair from here. You're *definitely* learning this. 👍
