### ISSUE TITLE
Cloning Error

### ISSUE THREAD

**Issue by BMR59** [ebeshero/DHClass-Hub#336]
Well, I've accidentally cloned the DHClass-Hub into an existing DHClass-Hub repo that I have on my computer. How should I go about fixing that?

**Comment by ebeshero** [comment]
@BMR59 Did you clone it so the files are inside your existing repo? If so, I would just delete the new directories you cloned. You can do that in your shell or terminal by positioning yourself a directory above the one in which you cloned the unwanted extra DHClass-Hub, and use the command `rm -r DHClass-Hub` to remove all the unwanted directories. 

If you accidentally delete both repos, just clone the DHClass-Hub again.

**Comment by ebeshero** [comment]
@BMR59 Did you fix your situation with cloning the DHClass-Hub inside itself? Take a look and let us know if your local repo is okay! @ghbondar or @gabikeane  can take a look tomorrow if need be.

**Comment by BMR59** [comment]
@ebeshero Yes! After everyone's help I got it situated and I've been playing around with it. Thank you so much!

**Comment by ebeshero** [comment]
Huzzah! I shall close this issue now. 👍
