### ISSUE TITLE
XPath3

### ISSUE THREAD

**Issue by KariWomack** [ebeshero/DHClass-Hub#34]
Having sooooo much trouble with returning parent elements in XPath. I keep coming up with errors and I don't know how to even begin to find where I'm going wrong. I've checked the readings and examples, but they are not helping. HHHHHHHHEEEEEEEEEEEEEELLLLLLLLLLPPPPPPPPPPPPPPP MMMMMMMMMMMMEEEEEEEEEEEEEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by brookestewart** [comment]
I find it helps to start very broad, then work your way to the more specific things. For example, for question 3 c.:
Now, how would we write XPath to find the very last paragraph in Book 2 that contains more than 1 latitude record?
First, find all of Book 2. Then add on to find the paragraphs that contain more than one latitude record. From here, it should be simple to find the very last paragraph that contains that information. I also found that grouping everything before the `[last()]` function works without error.
Hope this helps!

**Comment by RJP43** [comment]
Great advice @brookestewart ... that is exactly how I work through XPath think simple and don't over complicate... XPath is very literal!! @KariWomack did Brooke's advice help you at all? Do you have a more specific problem you could share. Perhaps give us the expression you are trying and we can walk through exactly what your expression is saying versus what you want it to say. It often works out that when you write out what you are looking for and how you are attempting to do it you see where your mistakes are being made.
