### ISSUE TITLE
Problems Submitting TEI Exercise Pt 1 on Coursweb

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#340]
I'm trying to submit my TEI file on Courseweb, but it keep saying this: 

> You can't attach the following files. They may contain a security threat: stinebiser_TEIexPt1_9-18, stinebiser_TEIexPt1_9-18 Please fix the files and re-attach them OR attach a ZIP of the files.

What should I do to fix this so that I can turn the assignment in? 

Thank you!

**Comment by ghbondar** [comment]
Hmmm... it looks like @ajnewton1 was able to submit ok. Did you have any problems uploading, Aaron?

**Comment by ajnewton1** [comment]
Make sure it has the .xml file extension on it. If it does and still won't submit, then just put it in its own folder and zip it.

**Comment by ebeshero** [comment]
@kes213 If none of that works, let us know--we can have you submit it via Box (where we return your graded homework files).
