### ISSUE TITLE
Document Analysis part 2 

### ISSUE THREAD

**Issue by Jamielynn92** [ebeshero/DHClass-Hub#341]
So, I'm confused on how to do this part. I know we started it in class, but I don't think I fully grasped this part. I probably have to write notes again, but its a little confusing on how to do this.

**Comment by ebeshero** [comment]
@Jamielynn92 I was evasive of drafting a TEI Header for my first projects for a while, but the easiest way for me to learn how was to read http://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html , especially the early parts of it, to wrap my head around what kinds of information go in. Now, our assignment isn't terribly elaborate, but you *do* have information about the source documents, and one thing you may want to do is write up something descriptive to go inside a `<sourceDesc>`: (What kinds of source material are you working with?) Also, you want to identify authors and at least yourself as the editor, preparing the digital edition of this document!
