### ISSUE TITLE
Project Teams

### ISSUE THREAD

**Issue by gabikeane** [ebeshero/DHClass-Hub#342]
### 90's Rap Music: [https://github.com/Blangzo/90s-rap](https://github.com/Blangzo/90s-rap)
Monica ( @mof11 ) and Wesley ( @Blangzo ) 

### Portuguese WhatsApp: [https://github.com/BMR59/Portu-WhatsApp](https://github.com/BMR59/Portu-WhatsApp)
Brandon ( @BMR59 ) and Patrick ( @pab124 ) and Tyler ( @ttb11 )

Deferred to Spring 2018: ### Turkish-Urum 
Justin ( @jub45 )

**Comment by jonhoranic** [comment]
## Greensburg

### AC/DC - Edison vs Tesla
Ally, Aaron, Jamie

### Harlem Renaissance Poetry/History
Kaylee, Tylar, Liz

**Comment by ajnewton1** [comment]
##Greensburg
Keeping the tradition alive!
Here are the final results

![fullsizerender](https://user-images.githubusercontent.com/24962219/30651383-8c1119e2-9df3-11e7-9118-edec80804ea3.jpg)

**Comment by ghbondar** [comment]
Attn: @djbpitt
