### ISSUE TITLE
Configuring your SSH keypair to work with the SFTP client

### ISSUE THREAD

**Issue by pab124** [ebeshero/DHClass-Hub#344]
So, I've been trying to do this last step for a little while now. I've had no problems following the instructions thus far and I believe that I've done everything correctly. So now I'm just trying to set up the FileZilla and I run into a problem with step #4 under the heading: "Once in the browser window, search for ******" whatever the file name is. When I do this, it says nothing has matched my search. I'm not sure if I'm doing this wrong or whats up, so any help would be appreciated.

**Comment by ebeshero** [comment]
Hi @pab124 ! Sorry! I've just edited that step in the instructions this morning to add a bit of clarification. What you're doing here is browsing to your new `.ssh` file directory, and you might be told by FileZilla that it can't open files at this location (or something to that effect). If that happens, step out of the Settings window and go back to the main FileZilla file menu--and click on Server. Under server select "Force showing hidden files". Then go back and try to locate that .ssh directory.

Your directory is located (if you used the default location when you set it up) one step below your home location. On your bash shell you can always get there by typing just `cd `  (cd + space) , and you can see what directory that is by typing `pwd` (or print working directory). If you have to use the browse option in FileZilla to find it, you may want to see the full file path.
