### ISSUE TITLE
Web Development

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#345]
While you're coding over the weekend, here's an image to keep you sane

![deing1pw0aamfj- jpg-large](https://user-images.githubusercontent.com/24962219/30768591-de980f50-9fd7-11e7-9124-a3c07102f3a0.jpeg)

**Comment by jonhoranic** [comment]
@ajnewton1 Interesting! I can oddly relate...

**Comment by quantum-satire** [comment]
This is actually hilarious. I want one!
