### ISSUE TITLE
Problem pulling from GitHub

### ISSUE THREAD

**Issue by ghbondar** [ebeshero/DHClass-Hub#347]
@Blangzo is having difficulty pulling from his GitHub repo. ![mintty_2017-09-23_20-54-49](https://user-images.githubusercontent.com/14024762/30778379-9ba1e056-a0a2-11e7-9416-1af4cf6e43c8.png)

**Comment by ghbondar** [comment]
@Blangzo When in doubt or peril type
`git status`

**Comment by ebeshero** [comment]
@Blangzo and @ghbondar As Greg says, run `git status` on your repo and let us know what it says. I think something might have been buggy with Vim, which is an ancient text editor attached to everyone's shells--and it's an editor that opens if you need to resolve a merge conflict by sending a report--you'll likely need to use it once or twice later and we'll walk you through it. In this case, I doubt this message is anything nearly as terrible as it sounds--so let's see what `git status` tells us about the state of your repo!

**Comment by Blangzo** [comment]
![mintty_2017-09-23_21-50-40](https://user-images.githubusercontent.com/24595610/30778647-3258e70a-a0a9-11e7-9a1c-2c7dbaeb46ce.png)
I had to restart git bash because it wouldn't let me type into it

**Comment by ghbondar** [comment]
@Blangzo try
`git push`

**Comment by Blangzo** [comment]
![mintty_2017-09-23_21-50-40](https://user-images.githubusercontent.com/24595610/30778688-2b2f9c2a-a0aa-11e7-8d27-344e4e968fc4.png)

**Comment by ghbondar** [comment]
@Blangzo is that the same screenshot? I don't see any difference. If pushing didn't work, try:
`git add -A
git commit -m "informative message here"`

**Comment by Blangzo** [comment]
![mintty_2017-09-23_21-57-59](https://user-images.githubusercontent.com/24595610/30778707-8a56a4c8-a0aa-11e7-842d-d63dd85da1d4.png)
Oops, sorry. That was the same screenshot

**Comment by ghbondar** [comment]
@Blangzo this looks good. Try:
`git pull` again
or maybe a 
`git status` ??

**Comment by ebeshero** [comment]
@Blangzo Also, go look at the web home of your repo on GitHub and take a look--your push should be there.

**Comment by Blangzo** [comment]
![mintty_2017-09-23_22-04-09](https://user-images.githubusercontent.com/24595610/30778727-1a75d3b2-a0ab-11e7-8057-11aa697a3fb4.png)

**Comment by ghbondar** [comment]
Please add @ghbondar as a collaborator on your repos, also.

**Comment by Blangzo** [comment]
I already did.

**Comment by ghbondar** [comment]
Ok, good, though I seem to be having problems with my notifications :/
It looks like your problem is solved?

**Comment by Blangzo** [comment]
I'm not sure what the vim.exe.stackdump is. Do you know?

**Comment by ghbondar** [comment]
It is just a crash log... you can delete it if you can find it...

**Comment by ghbondar** [comment]
You might want to add, commit, and push your web files, also, from the looks of it.

**Comment by Blangzo** [comment]
Ok, sounds good. Thank you!!

**Comment by ghbondar** [comment]
If hope it continues to work! See you on MOnday!
