### ISSUE TITLE
XPath 4

### ISSUE THREAD

**Issue by amielnicki** [ebeshero/DHClass-Hub#35]
I need some clarification on part of the assignment... I have the entire thing done except for number 2:

2) a) Which 'div' elements contain references to 'homework'? How many results do you return?

b) Can you figure out how to retrieve the immediate parent element containing the word "homework"? (Hint: it involves looking for any element below the div and then its text() node, since we need the element whose *text* contains the word "homework.")

What exactly are you looking for in part A? The names of the @type associated with each div? I think if that question gets answered, it will clear up part B too.

Thanks!
@ebeshero @RJP43 @ghbondar

**Comment by ghbondar** [comment]
2a. is pretty straight-forward (you should find 18 divs that contain "homework").
2b. involves identifying the parent of the element whose text-node has "homework". (you should retrieve 9 results).

**Comment by nlottig94** [comment]
I was having the same issues.  I got the first expression, but I can't get the last expression.  I tried: `//div[contains(., "homework")]/..` but it is giving me 11 results instead of 9...

**Comment by ghbondar** [comment]
The trick is to refer to the text-node containing "homework", first.
@nlottig94

**Comment by ghbondar** [comment]
Your XPath is finding the parent of the div, not the parent of the element, that contains "homework".
@nlottig94

**Comment by nlottig94** [comment]
I figured it out!  Thanks!

**Comment by spadafour** [comment]
I am still completely lost on 2b. Are we using `text()` in this? How do we refer to specific text if we cannot place actual text within `text()`?

This is the closest that I got:
`//div[contains(., "homework")]/parent::*[contains(., "homework")]`

**Comment by ghbondar** [comment]
Getting closer, now how about using text() as part of the element tree with a predicate, such as:
`text()[contains(., 'homework')]`
@spadafour

**Comment by ghbondar** [comment]
That way you only have to search for the homework once.
