### ISSUE TITLE
FileZilla Setup Issue

### ISSUE THREAD

**Issue by mof11** [ebeshero/DHClass-Hub#353]
Link to troubleshooting page:

https://github.com/ebeshero/DHClass-Hub/blob/master/Troubleshooting/felix_terminal_screenCap.png

I was able to set up my SSH keys for the newt fire server without many major issues, but I seem unable to link the SSH keys to the newtfire server after opening a new session, and this is the most recent attempt in the screenshot above.

**Comment by ebeshero** [comment]
Hi @mof11 . You're including too much in the ssh-copy-id line. What you need is just:

```
ssh-copy-id username@firebellies.newtfire.org 
```
But there's a more serious problem. You've now posted your keys in public view on our GitHub repo. You should delete them and start over. I'm sorry, but the key generation part isn't hard, and it's important you understand *why* we're using these keys in the first place. You never want to be sharing them in public view(!!)

**Comment by ebeshero** [comment]
@mof11 Looking more closely at your screen capture, you are apparently located in your `.ssh` directory, and I think that's the reason your first (correct) attempt at the `ssh-copy-id` command didn't work. So, climb *up* just one level with `cd ..` And try the command again. I think it'll work this time.

**Comment by mof11** [comment]
Okay I will!!! Do you have any advice on how to delete the keys that I already made before trying again?

**Comment by ebeshero** [comment]
@mof11 Position yourself above the directory (stay in that "home" spot) and use `rm -r .ssh` to delete the .ssh directory . Hope that helps!

**Comment by mof11** [comment]
@ghbondar here: @mof11 is still having this problem. We deleted the old .ssh folder, created a new one, made a new set of keys, and moved above the .ssh folder, but now when we try:
`ssh-copy-id mof11@firebellies.newtfire.org`
we still get the following error:
`-bash: ssh-copy-id: command not found`

**Comment by mof11** [comment]
@ghbondar  here: Ah, ha! First we needed:
First, ensure authentication works with 
ssh username@firebellies.newtfire.org 
I think we've got it now :D
