### ISSUE TITLE
Regex Exercise 2 Paragraph Tags

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#356]
Hi everyone, 

I'm having trouble getting the <p></p> tags around the paragraphs in the novel. I removed the three or more spaces, but when I try to put the paragraph tags in like we learned in class, it puts them in halfway through sentences and in other weird places. 

First I did this: 

`Find box: ^.+?\n\n`

It selected only the last lines of the paragraph instead of the entire line. 

I tried using just .+?\n\n as well, trying to get it to select everything. It didn't work either. 

This is my screen: 
<img width="960" alt="regex_issue_pic" src="https://user-images.githubusercontent.com/31480908/31034746-5d22ecb8-a533-11e7-895c-5cfbe3bd61ee.PNG">
And as you can see, it put the paragraph tags where they weren't supposed to be. 

I thought the first thing I tried to do was what we learned in class, but it just didn't work. What am I doing wrong?

**Comment by ebeshero** [comment]
@kes213 Remember the difference of marking "Dot matches all"? Try it here...When you have 
```
.+
```
that makes a "greedy match", but the question mark afterwards says "Don't be greedy" and match **just** up to the next pattern...

**Comment by ebeshero** [comment]
@kes213 If you set "Dot matches all", and work with the *non-greedy* match (using the ?), you can re-do that Find as we did it in class today.

**Comment by kes213** [comment]
Okay, I tried that, and I got it to select the entire paragraph, but when I hit "Replace," nothing happened except the addition of the <p> tags at the beginning of the document, even though all of the paragraphs were selected. 

<img width="960" alt="regex_problem_pic" src="https://user-images.githubusercontent.com/31480908/31046503-8c5d5182-a5c7-11e7-8e28-985c5ccaccdb.PNG">

**Comment by kes213** [comment]
Before I hit the replace all button, all of the paragraphs were individually highlighted.

**Comment by ebeshero** [comment]
@kes213 Aha! I had to pull this up on my own computer to see what was going on. It's actually an issue with your first capturing group, the part you have in parentheses. So, what you posted has this:
```
(.+)?(\n\n)
```
And when you hit **find all** with that capturing group in place, you're back to matching on the entire novel--we can see that in your screen capture too (there's just one result--the whole document). 
Try *moving* that right parenthesis over just one character--evidently you need to make sure you include the `?` in the capturing group for the *non-greedy* matching to hold when you do the find & replace.

I just tested this on my computer and that made the difference!

**Comment by ebeshero** [comment]
It's interesting to think about why the positioning of those capturing groups matters here! The computer evidently reads these from the inside-out, so it's kind of like grouping when we were writing Relax-NG:  The computer looks at what's inside the parentheses first of all, and if our  `?` is on the outside `(.+)?`, the meaning changes from *a non-greedy match up to the first instance of the regex pattern we designate*, to zero-or more instances of `.+` , which of course is the whole document when we've got Dot-matches all set.

**Comment by Jamielynn92** [comment]
@ebeshero So I'm still confused on what to do. i've tried to do that paragraphs and they ended up marking every line with a <p></p> instead of just the paragraph itself.

**Comment by ebeshero** [comment]
@Jamielynn92 Do you have Dot matches all selected?  NOTE: I just added the tic marks around your angle-bracket code above so it would show here.

**Comment by ebeshero** [comment]
@Jamielynn92 Tell us what regex patterns you're trying, too.

**Comment by Jamielynn92** [comment]
![screenshot 19](https://user-images.githubusercontent.com/31480905/31060206-5445d5a0-a6dd-11e7-9900-3c0b606dedd7.png)
what I have so far.

**Comment by ebeshero** [comment]
@Jamielynn92 If you're only searching for the `^`, you're going to find *every* new line, and that's not going to help you locate where the paragraphs separate from each other. How can you find the paragraph breaks? (How are they different from lines inside the paragraph?)

**Comment by Jamielynn92** [comment]
I'm not sure how to write that without screwing it up. what about ^(.+)$
I tried looking it up, but the wording is confusing yet again.

**Comment by ebeshero** [comment]
@Jamielynn92 You probably don't want `^` and `$` here...why not? B/c that's a way of isolating *every single line* in the document. Remember, `^` just flags the start of a line, and `$` flags the end of it. Don't cling to those.

**Comment by Jamielynn92** [comment]
I don't know what I'm doing. I'm trying to, but as of now its too complicated. I don't know which combinations to put to make it work.

**Comment by Jamielynn92** [comment]
![screenshot 20](https://user-images.githubusercontent.com/31480905/31060297-371905f4-a6df-11e7-8e82-ce50b21a1b96.png)

**Comment by ebeshero** [comment]
Keep experimenting! You know how to find newlines--and how to find multiple in a row, so keep playing with that! But understand that `^` and `$` isolate single lines--so that is why you are having trouble using them to grab whole paragraphs. You really do NOT want to use those for this. Remember how we marked "Dot matches all" to run over multiple lines, but we also used the `?` to tell it "don't be greedy" and match only up to the next thing we designate? 

The assignment page explains that non-greedy matching really clearly--if you're having trouble reading it, slow down and read it out loud--the explanation there will really help you, I promise!

**Comment by ebeshero** [comment]
@Jamielynn92 I'm looking at the assignment and realizing that it's guiding you to locate the paragraph breaks a little differently than the way we did it in class. In reality there are a few different ways to grab those paragraphs--and really all you need is to locate the single thing that separates the paragraphs from each other. (You don't even need to match on whole lines to get them or any text at all.) All you need is to grab hold of the two newlines in a row that separate every block of text, right? And once you find them, you can write a replace that uses our "close-open" strategy: Where you see the start of one paragraph, you have **also** found the close of the preceding paragraph...so close-open with your replace!

**Comment by Jamielynn92** [comment]
so what I find \n\n and replace it with </p><p>? cause I think I tried that and it didn't do anything?

**Comment by ebeshero** [comment]
@Jamielynn92 We can't see your angle-bracket code here until you wrap it in those tic marks (top left key on your keyboard: ```

**Comment by Jamielynn92** [comment]
```</p><p>```

**Comment by ebeshero** [comment]
Yep... That should work. I'd actually even put one of your `\n` characters back just to keep them on separate lines. (You'd want to use a capturing group in the Find (using parentheses), and refer to it with \1 in your replace.)

**Comment by Jamielynn92** [comment]
![screenshot 22](https://user-images.githubusercontent.com/31480905/31060438-e9426412-a6e1-11e7-92dc-6fb3f01766aa.png)

**Comment by Jamielynn92** [comment]
![screenshot 23](https://user-images.githubusercontent.com/31480905/31060750-bcb852d0-a6e6-11e7-8da6-cf1d22cddeca.png)
so I took a lil break from staring at my screen, and I read the paragraph part again, and I got this.. I got the paragraphs but they are all mushed together... how would I get them to do it themselves without having to do them all manually?

**Comment by ebeshero** [comment]
@Jamielynn92 Yay! You got the paragraphs! Sounds like you want to put a hard return (or newline) back in between the paragraphs to make it look prettier. (You don't have to do that, but you can!) Try matching on the pattern you just made. What do we see? close-paragraph-tag, one newline, open-paragraph tag. So try matching on that in your find...
And for the replace...well, use your *capturing group* savvy. Try capturing that newline character in a pair of parentheses `(\n)`, and then **refer** to it in your replace, **twice**. You'll want to keep your paragraph tags, too--so be sure to put **them** in capturing groups, too. (keeper-1)(keeper-2)(keeper-3), to refer to with \1\2\2\3 .

I'm trying not to give **too** much away here...but see if that's a strong enough clue.

**Comment by Jamielynn92** [comment]
now I'm having trouble with the chapters. ive tried a few combinations but I'm getting way to many results.

**Comment by ebeshero** [comment]
Remember, literal matches on specific words are perfectly legal in regex matching!

**Comment by mof11** [comment]
Yes same here, I am trying to isolate the roman numerals in each chapter by doing ^[IVX]+$ but it not only highlights the chapters but other lines that started with I or V that are not relevant to the chapters. This was mentioned on the Regex Tutorial on Newtfire, but how do you only highlight the roman numerals? 
![screen shot 2017-10-01 at 9 50 27 pm](https://user-images.githubusercontent.com/31665019/31061784-a40a3396-a6f2-11e7-9e69-181826917b14.png)

**Comment by ebeshero** [comment]
@mof11 Remember that `^` and `$` are just flags for the start and end of a line. When the Roman numeral does not appear at the start or the end of the line, you wouldn't want to set these around them.

**Comment by ghbondar** [comment]
@mof11  It also looks like you need to tell your search when the Roman numeral has ended. What symbol indicates this?

**Comment by kes213** [comment]
@ebeshero I got it all figured out. Thank you for your help!

**Comment by ebeshero** [comment]
Great, @kes213 ! 👍  I'm re-opening this issue, though, since others are now referring to it and commenting here. (See? The issues you open start helpful comment chains. Thank you!)

**Comment by mof11** [comment]
@ebeshero @ghbondar So I was able to narrow it down to 38 matches when I modified the search a bit. However, I still got a few unwanted lines in my search. I tried adding the period (the symbol coming right after the roman numeral) with the brackets but it did not really do anything. here is what I got now: 
![screen shot 2017-10-02 at 12 02 10 am](https://user-images.githubusercontent.com/31665019/31063935-828cc270-a705-11e7-9047-0a247f9b2427.png)

**Comment by ebeshero** [comment]
@mof11 I'm confused looking at your screen shot, because the file over which you are running the search evidently *already has* chapter tags in it. I'm also confused about your placement of these tags: shouldn't a chapter title be included *in* the chapter it's part of?  

Did you tag *some* of the chapters but not all? If so, I'd recommend back-tracking to a point before you tagged some of these. You should be working on catching *all* the chapters in one search and replace. 

Next, remember that when you search for a period it's a reserved regex symbol--the dot. Dot matches any character, so your search isn't really matching *only* the periods. You need to escape any reserved regex symbols like this using a backslash, as in `\.` 

When you write a character set using square brackets as you are properly doing for the Roman numerals, remember that this matches *just one* character, so you need to use a repetition indicator when you have one or more of these. 

Finally, the assignment sheet would have you matching paragraphs first, and then chapters. It looks like you're doing this from the "outside in" instead of the "inside out"? (It doesn't appear that you've tagged the paragraphs at this point.) That's okay, but might be making you a little more work when you finally do go and tag the paragraphs.

**Comment by Jamielynn92** [comment]
![image](https://user-images.githubusercontent.com/31480905/31109827-7e379b2a-a7d0-11e7-9d13-afaded13e187.png)
@ebeshero  @ghbondar  @ajnewton1 
I'm trying to redo this and I'm stuck on doing the roman numerals.. I many ways but cant isolate just the roman numerals. I need a hint on how to write it. ive even tried to search for it but none have helped.

**Comment by ghbondar** [comment]
@Jamielynn92 It looks to me like you are not "escaping" the period when you search. Instead, you are using it as a "dot". Remember, if you want to search for a literal period, you need to use `\.`
Doing that gets you `[IVX]+\.` which is not perfect, but you can easily remove the extra/false tags with a later search and replace. You can even add a `.+` to select the whole line.
Goodnight! -.-

**Comment by tal80** [comment]
<img width="1431" alt="screen shot 2017-10-03 at 7 20 06 pm" src="https://user-images.githubusercontent.com/31480833/31153579-f5d002b8-a86f-11e7-9e4d-0ae08e79e466.png">

I am stuck here trying to wrap the selected in <title></title> tags, but I cannot figure out how to make it go to the end of the line.

Thanks for the help!

**Comment by ebeshero** [comment]
@tal80 You've got the first part, which is what distinguishes the heads of chapters. You can use the dot `.` to help keep going to the end of the line, but here you'll want to *shut off* "Dot matches all" so it doesn't continue matching over all the lines in the document. You could match up to the close paragraph tag (since you're going to want to change that anyway).

**Comment by tal80** [comment]
<img width="1311" alt="screen shot 2017-10-03 at 7 30 39 pm" src="https://user-images.githubusercontent.com/31480833/31153855-629122a0-a871-11e7-9d93-ccf42141d41b.png">

Still having trouble. This is confusing. I have been trying since Sunday but keep getting caught up...

**Comment by ebeshero** [comment]
@tal80 There's some text in between the Roman numerals and the closing `</p>`, so you want to match on it. Like I said, the `.` could be your friend here to keep the rest of the match pretty simple. How would you match one or more of "any character" before that closing `</p>`?

Here's something else: You found those Roman numerals, which is important! That's the hardest thing to match here. Think about how you want to work with that Find once you do match the full line. Sure, you want to wrap it in a `<title>...</title>` element, but don't you *also* want to wrap the whole chapter in its own element, too? Just like you wrapped the paragraphs, you can also wrap the whole chapter up in a container element, so your structure would be like this:

```
</chapter>
<chapter><title>III. TITLE HERE</title>
     <p>.....</p>
     <p>.....</p>
     <p>......</p>
   ...[more paragraphs]...
  </chapter>
  <chapter><title>IV. TITLE HERE</title>
```
    When you find the **beginning** of a container, you've found the **end** of the previous container. That's our "close-open" model.
