### ISSUE TITLE
Pygmalion Regex Speech Tagging

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#357]
I'm having some trouble getting oXygen to recognize all of the speeches made by the characters. I input `^([A-Z]{2,}\s*[A-Z]*.+)(\n\n)` and it picked up some of the speeches, but not all of them for some reason. There aren't any visible differences between the ones that are marked and those that aren't, which is why I am a little mystified.
![screen shot 2017-10-02 at 3 48 35 pm](https://user-images.githubusercontent.com/28074589/31096136-31ba61d4-a789-11e7-8ab6-5f487a3ff9b9.png)

**Comment by quantum-satire** [comment]
I just realized the difference--there are extra `\s` breaks which need to be included in the input.

**Comment by ghbondar** [comment]
@quantum-satire Remember that `\s` matches any white-space character, including new lines, and not just space characters.

**Comment by ghbondar** [comment]
@quantum-satire ...after all, a 'space' is just another character. Why not include it with the other characters that you are searching for inside the brackets?

**Comment by ebeshero** [comment]
@quantum-satire @ghbondar Indeed: experimenting with character sets will be a big help here! @kes213 was asking about this after class, too:  You'll notice that there are several kinds of characters that may be included in a character name: these may include hyphens (THE PARLOR-MAID), white spaces, periods (inside the name, not just at the end of it, as in MRS. HIGGINS and MRS. HIGGINS.). 

It may help to know that you can put a range as well as a grab bag of special characters inside your character sets: '[A-Z.- ]+` might catch a few more of these...

**Comment by quantum-satire** [comment]
@ebeshero @ghbondar I went ahead and submitted the assignment after some more tinkering--I attempted to input `[A-Z.- ]+` in several different ways but it repeatedly told me that it wasn't a valid expression (I believe it was because of the period, which I also attempted to cancel out with `\.` but still would not work). Sorry for such a late response--and thank you for your help!

**Comment by ebeshero** [comment]
@quantum-satire @ghbondar I see my mistake in my post above! You were right that there was something wrong in my expression. I had `[A-Z.- ]+` and of course that won't work! The period is okay to include in a character set, but the hyphen has a special regex meaning there, and so *the hyphen* is the character we need to escape with a backslash. If you want to, feel free to give it another try!

**Comment by Jamielynn92** [comment]
I cant figure this out. ive tried different possibilities but this one is hard

**Comment by Jamielynn92** [comment]
its not catching all the speeches and I've tried the above example from allys screenshot but mines not working.

**Comment by ebeshero** [comment]
@Jamielynn92 Ally's first screen capture wasn't right--and she modified it because that `\s*` she used was matching newline characters (too many kinds of white space). See if you can match a lot of them (even if you don't get them all), and try building this in stages--you don't have to get it all at once. What do you notice about the speaker's names? What kinds of characters do you see?

**Comment by Jamielynn92** [comment]
The beginning letters are all capitalized.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ebeshero** [comment]
@Jamielynn92 Yes--just about all of them (with like one or two little exceptions), but let's run with that...you want to start there: How much can you match with capital letters?

**Comment by Jamielynn92** [comment]
@ebeshero  I'm not completely sure on how to type it out. I've tried finding an example, but there are none to look at as a reference cause we've done different ones that don't go off each other. so trying to think of tags is complicated.

**Comment by ebeshero** [comment]
@Jamielynn92 I'm going to give you the same Giant Hint I gave @quantum-satire , only this time I won't make a mistake in my hint the way I did earlier. So, you know how you can catch a character range with `[A-Z]` to get any capital letter? Well, you can actually put *more* characters inside the special character set. What you put inside the `[ ]`set is kind of like rolling the dice: you could get ANY one of whatever you set in there. Some of those names (a LOT of them) have white spaces, like `MRS. HIGGINS`. Some of them have periods inside, too (like `MRS. HIGGINS` again), so you can add literal periods and white spaces in the set, too. (We showed you some of this in class on Monday with the "War of the Worlds" script example.)  And some of the names have a hyphen inside, but you have to escape the hyphen b/c it means a range when it's inside a character set.

**Comment by ebeshero** [comment]
@Jamielynn92 So here's something to try: See if you can add some stuff that's part of the names (white spaces and periods at least) into your character set, and match on one or more or two or more of those: See what you turn up...

**Comment by ebeshero** [comment]
@Jamielynn92 Bottom line: what we're looking for is a serious try at catching those speakers: We know this one is a challenge! If you don't get them all in one try, that's okay, too! You can catch a LOT of them that look the same way in one pass. And you can do another Find & Replace to look for more that have slightly different content. There's no need to get them all in one Find & Replace pass--and in fact, that might not be the wisest approach. 

In Real Life when we do this work on projects, we typically have to do this kind of work in multiple passes--there's no shame in that!

**Comment by Jamielynn92** [comment]
I just keep hitting multiple walls. and all the different symbols, I just don't understand how to place them. I need a better example. and there are none out there. My brain doesn't work that fast, at least not yet.

**Comment by ebeshero** [comment]
@Jamielynn92 So here's what I'm saying in a nutshell:
Character set: `[  ]`  (holds a range like A-Z or single characters (like Roman numerals), or literal periods or punctuation or anything you need, and it means, by itself, just one of *whatever's* inside.

Repetition indicator: + (means one or more)
* (means zero or more) 
? (means zero or one)
{2} means exactly 2
{3} means exactly 3
{2,} 2 or more  {3,} is 3 or more,  etc.

One of the really neat things you can do is put a whole bunch of symbols into a character set: 
1) Try this: `[A-Z]+` and you don't get enough b/c you only get the capital letters. 
2) So, try this: Add a period! `[A-Z.]+`  Do you get some more?
3) Well there are white spaces, so add a literal spacebar into that set: `[A-Z. ]+` Do you get a few more? 
What if you change the repetition indicator so you get two or more? 
Keep fussing with it and see if you can get a LOT of them. 

If you don't get them all, try and see what's missing. You could just get them in another round of Find & replace, or you could try to add something new to your current Find.

**Comment by Jamielynn92** [comment]
![screenshot 27](https://user-images.githubusercontent.com/31480905/31159860-16acc4d8-a89a-11e7-8499-6fc3d2068b54.png)

**Comment by ebeshero** [comment]
@Jamielynn92 One more thing--if you start catching some of these, with periods, you'll probably find the ends of sentences and the starting capital letter inside the speeches. So, how do you get this? Well, you maybe need to make sure your *starting* pattern (with the period and white space) is followed by at least *two or more* capital letters... you may want to make a second character set to make sure you catch only stuff that *starts and ends* with capital letters.

**Comment by ebeshero** [comment]
@Jamielynn92 I was just typing you a hint on how to do that...and you DID it ! Congrats! 👍

**Comment by Jamielynn92** [comment]
but I ended up with Capital Letters that I don't want.

**Comment by ebeshero** [comment]
Ahh I see.. You got "A Professor..." Yes. You just need to match on **two or more** capital letters in a row in your second character set. You currently are matching **one or more**.

**Comment by ebeshero** [comment]
@Jamielynn92 In one of my solutions I put three character sets in: One to get one or more of the capital letter or period or white space or etc, one to get two or more capital letters in sequence, and then just one seeking a period or a white space.. There's a few different ways to catch these!

**Comment by Jamielynn92** [comment]
![screenshot 28](https://user-images.githubusercontent.com/31480905/31160077-aebf8886-a89b-11e7-8471-520de0826f61.png)
okay so ive captures most of them but some don't have periods after it.. should I go through and put one or is there another way?

**Comment by ebeshero** [comment]
@Jamielynn92 Yay! You worked it out this far...bet you can do one last thing to match zero or one period... There's a couple of ways you could do that.

**Comment by ebeshero** [comment]
And think about your replace: Once you found the speakers, have you found their speeches, too?

**Comment by Jamielynn92** [comment]
I have not. I haven't been able to fully match the speakers to move on to the speeches. and I am aware of how late it is too. Sorry for it being so late as well.

**Comment by ebeshero** [comment]
@Jamielynn92 You're really close. Finding the speakers is the hard part here, and you're nearly through it. In fact you've got most of it. You could knock out most of them now, and catch the rest with the literal period at the end in another pass.

**Comment by ebeshero** [comment]
I'm happy you've got this far...I'll check in in the morning!

**Comment by Jamielynn92** [comment]
well I might stop for now and try again when I get to the school, I'm usually there early. I need a fresh mind set.

**Comment by mof11** [comment]
@ebeshero Hi so I am working on the third Regex hw and running into a few problems. For the speakers, I was able to include all the capital letters of the speaker names but I was including the first letter of the sentence which I do not want. I did find ^([A-Z. ]+\.[A-Z.\s ])+[A-Z]+ and then when I tried to do ^([A-Z. ]+\s.[A-Z. ])+ it did not capture all of them such as "MRS. PEARCE" with no period at the end because the [] next to the name. Then I went ahead to see if I could get the speech part down in the meantime to see if I could get the formula for it (after I submitted the <sp> tags in) and what I did was </sp>([A-Z,a-z,\'\.\-\?\:\;\! ]+) however i do not want to include the </sp> tag in when I am trying to highlight the speeches from the speakers. Here are some screenshots below: 
![screen shot 2017-10-05 at 5 02 32 pm](https://user-images.githubusercontent.com/31665019/31252788-58eae094-a9f0-11e7-9d93-aae083b88458.png)
![screen shot 2017-10-05 at 5 06 54 pm](https://user-images.githubusercontent.com/31665019/31252795-601e22a4-a9f0-11e7-87ac-b0619b898995.png)

Sorry if my explanation is confusing above and I will try to be clear if it is! Thanks so much!!

**Comment by ghbondar** [comment]
@mof11 Feel free to use multiple searches to tag the speakers incrementally, first some, then others, changing your search each time.

**Comment by ghbondar** [comment]
@mof11 try search for cap letters with a space followed by the [ 
maybe [A-Z]{3,} \[
... I am on my phone so my suggestions are limited

**Comment by ghbondar** [comment]
`[A-Z]{3,} \[` ... It lost my slash @mof11

**Comment by mof11** [comment]
@ghbondar okay thank you!! I did that and it really helped, however, the [ was replaced as well when I added my replacing tag which I think I do not want to do (even though the document says it is still valid). Also I am still having trouble with including the whole <sp> tag around speakers with names such as MRS. PEARCE because the tag only isolates the MRS. part . Here is a screenshot below. 
![screen shot 2017-10-05 at 8 40 02 pm](https://user-images.githubusercontent.com/31665019/31258523-ac023288-aa0d-11e7-975d-fe9aea9dd843.png)

**Comment by ghbondar** [comment]
@mof11 Yes, if you select text, you are either going to delete/replace it, or you need to enclose it in ( ) and preserve it using \1 (or \2 or \3 etc) in the Replace line. If you can find and tag the MRS. so it's
`<sp>MRS.</sp> PEARCE` 
just do a second Find/Replace to remove the extra tag and place it at the end.

**Comment by ghbondar** [comment]
@mof11 The [ ] are pseudomarkup that indicate stage directions in the script, not part of the XML (so oXygen doesn't care). However, you can use those [ ] to tag that text as stage directions *hint*hint*

**Comment by mof11** [comment]
@ghbondar oh yes I was not preserving it correctly for the second capture group ([). And for some reason that was not working for the MRS. PEARCE, it kept saying String Not Found. So I did this instead and hope this is still okay. 
![screen shot 2017-10-05 at 9 19 44 pm](https://user-images.githubusercontent.com/31665019/31259228-37764232-aa13-11e7-974c-5eca8e5554e5.png)

**Comment by ghbondar** [comment]
@mof11 As they say, 'many RegEx roads lead to Rome' so as long as you're not doing it manually line-by-line, that's the main thing.

**Comment by ghbondar** [comment]
@mof11 Please remember to turn in your work on Pygmalion.
