### ISSUE TITLE
Xpath exercise 1 help..

### ISSUE THREAD

**Issue by Jamielynn92** [ebeshero/DHClass-Hub#359]
Help... not sure how to start this.

**Comment by ghbondar** [comment]
@Jamielynn92 um... with a `//` in the XPath window in the upper left corner of oXygen?? ...I'm sorry, but you need to be more specific. What have you tried so far?

**Comment by Jamielynn92** [comment]
![screenshot 29](https://user-images.githubusercontent.com/31480905/31255569-839d1b58-a9fb-11e7-8032-ced7e738c587.png)

**Comment by Jamielynn92** [comment]
okay. so I've made it to number four on #1. I cant figure out how to isolate book 2. I've a few ways but I still get all three books.

**Comment by Jamielynn92** [comment]
nevermind I figured it out.

**Comment by Jamielynn92** [comment]
so I'm on question 2. and I'm wondering are the h1/h3 the chapters?

**Comment by Jamielynn92** [comment]
or I should ask how do you want that written out? as an xpath expression or what they would be called in sequence?

**Comment by Jamielynn92** [comment]
@ebeshero

**Comment by ghbondar** [comment]
@Jamielynn92 if you are see h1 and h3-elements, you must be looking at the html mark-up, instead of the xml. For question #2, yes, your answer should be written as an XPath expression.

**Comment by Jamielynn92** [comment]
for the homework or the outline. that was a lil confusing.. not sure how lol.
