### ISSUE TITLE
Dates in XPath

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#36]
I don't understand how to do 5b on the homework. I honestly don't even know where to start and the hints on the assignment aren't helping. So far all I have is my output of all of the dates as: //date/@when/format-date(xs:date(.), '[FNn] [MNn] [D] [Y]')

**Comment by nlottig94** [comment]
You need to find exactly what you want in `@when` before you tell XPath what to output...

**Comment by RJP43** [comment]
Consider that `format-date()` will also be useful in defining what exactly you want from when , but first you need another function! One that says I only want the `@when` that contain blah, blah, blah

**Comment by RJP43** [comment]
The rest of what you have @blawrence719 makes sense in saying how far down you want to go before explaining the `contains()` with `//date/@when`  but you need to go further in the `@when` before saying how you want to output your results (which also looks good!) just like @nlottig94 suggests

**Comment by blawrence719** [comment]
i'm still not sure how to go further down in @when since all it contains is numbers without it being output into something else. I'm sorry if this is simple, I'm just not getting it.

**Comment by RJP43** [comment]
What I have seen with questions posed in this issue by @blawrence719 and through text messages with @nlottig94  the stumbling point on question 5B  is when you want to go further into the `@when` attribute by saying you want the `@when` dates that `contain()` the whole date (using the format-date function with the dot being inside of that inner format-date function and a character/text node that grabs Fridays ... it is easy to forget where you are in your XPath when you are drilled down all the way into the `format-date ()` function that you haven't completed what is required in the `contains ()` function. Don't forget [the examples from class](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XPath/XPath-InClassNotes_10-14Parker.md) and notice the format for contains contains(.,"text") remember the dot is the anchor or the place holder saying search from here for whatever is coming after the comma and for this question the dot is specified in the drilling down into the specifically formatted date.  Very basically your steps are go way down in and find all the dates (specifically styled like blah blah) in `@when` that contain text indicating Fridays and then output the resulting Friday dates formatted however you like. HOPE THIS HELPS ! Think simple and think in steps!

**Comment by brookestewart** [comment]
I honestly don't know what the question is asking us to do... are we working with the dates in the attribute value? or the actual text? I'm so confused... 
Would I be correct in assuming that we're to find the Friday dates first, then go from there?

**Comment by brookestewart** [comment]
This is what I have, I'm not sure if it's what the question is asking, but there's a Wednesday in there that I can't get rid of. `//date[contains(.,"F ")]/@when/format-date(., "[FNn]/ [M]/ [D]/ [Y]")`

**Comment by RJP43** [comment]
so you are on the right track but you want to combine these two functions... think how you would incorporate `format-date()` into the `contains()` function also be careful with format-date you have the function setup not exactly how its supposed to be remember the example from the assignment `//some-XPath-here-that-leads-to-the-dates-you-want/format-date(xs;date(.), '[FNn]/ [MNn]/ [Dwo] / [YWw')` also look back at what I said to the other Brooke about the dot we typically see in contains is being replaced with the `format-date()` function's dot. @blawrence719 or @nlottig94 care to hint to @brookestewart where she is confusing things?

**Comment by RJP43** [comment]
Simplify your thinking of what you want. Remember you want to drop down as deep as you can before you start telling XPath what you want to pull out. 

This way of thinking might help: Very basically your steps are go way down in and find all the dates (specifically styled like blah blah) and grab those . that contain text indicating "Fridays" and then output the resulting Friday dates formatted like this (your choice in format).

**Comment by RJP43** [comment]
@nlottig94 you have a really great sense of explaining the parts of `format-date()`care to give some input explaining what @brookestewart has versus what she would want to have? Perhaps just by giving the clear explanation of the different parts of the `format-date()` function that she is representing we can get a clearer sense of what would make sense to keep or not when combining it with the `contains()` function.

**Comment by RJP43** [comment]
the question is asking that you go into the when attributes of date and you grab all of the dates (that are formatted in a specific way) that contain Fridays (some kind of text to indicate Fridays) and then output the dates in a format of your choice. Be careful of where you are stepping further `/` and where you are saying take this from this point `.`

**Comment by brookestewart** [comment]
I'm still having a lot of trouble. Is this correct so far? `//date[text()[contains(., "F ")]]/@when`

**Comment by ghbondar** [comment]
Try including the when-attribute earlier in you search tree, such as `//date/@when`. You can either use the contains-fcn. as a predicate, or you can add it to the tree as well. However, within the contains-fcn., you are doing more than simply referring to the preceding steps in the hierarchy `the .`. 
Instead, the haystack that you need to search through consists of formatted dates as `xs:date`, so use them in the contains-fcn: 
`contains(format-date(xs:date(.), '[whatNeedleDoYouWantToFind]')` 
@brookestewart
