### ISSUE TITLE
Neat stuff: A sample of spoken Urum

### ISSUE THREAD

**Issue by jub45** [ebeshero/DHClass-Hub#361]
So I was browsing through some youtube videos, looking for some sources for the Turkish-Urum project and I stumbled across this gem of a video: an elderly woman speaking in Urum and telling a fairy tale. This will be an excellent source for documenting phonetic/phonemic variances between Turkish and Urum! Right off the bat I can understand about half of what she's saying.
https://www.youtube.com/watch?v=SyCGgat4Rwo

**Comment by ghbondar** [comment]
@jub45 Neato! Remember that  it is essential for our course projects that the material is in the form of an electronic text that can be marked up and manipulated. Now, as this project may overlap with your work in other courses in which you are doing the translations, that's fine, but remember that the **Midterm evaluation of your project is due on October 23**, by which time you will need to have a **solid start on marking-up texts, with a developed schema, and a structured website**.

**Comment by jub45** [comment]
I have already found several good TEI tags that will be useful for the project markup <s>, @lemma, <m> and other tidbits from section 17 of the TEI website. The purposes of this video will only be to compare certain sound environments within known cognate sets between Turkish and Urum for the eletronic text, so that I can incorporate (or try to incorporate) those comparisons within the markup. From a comparative linguistics standpoint, this kind of info is one of the 'Holy Grails' for those doing research among somewhat disparate languages within the same family.

**Comment by ghbondar** [comment]
Excellent!
