### ISSUE TITLE
confused on Xpath exercise 2. 

### ISSUE THREAD

**Issue by Jamielynn92** [ebeshero/DHClass-Hub#362]
I've trying to find these geo markers, but I seem to be missing something. I'm not quite sure how to find them. But everything ive tried so far hasn't worked. I couldn't find the geo by scrolling down. but didn't find any, so I'm confused.

**Comment by ebeshero** [comment]
@Jamielynn92 How would you jump down the tree looking for an element if you don't know where it is? We told you the element name is `geo`. If you don't remember how to write an XPath expression after the long weekend, please review our ["Follow the XPath" tutorial](http://dh.newtfire.org/explainXPath.html).

**Comment by Jamielynn92** [comment]
I have looked it over. I still am missing what tree elements to use. and how to write them. Its harder than the last homework I think.

**Comment by ebeshero** [comment]
Well, you're working with the same file you used for last week's exercise. Go take a look at your homework to review how you found Book 1, for example. Also, I just pushed the [solutions to XPath Exercise 1](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/XPath_Exercises/XPath-Ex1.md), which might help for you to review how you located things last week.

I am not sure I understand the issue--I think you're trying to find the `<geo>` elements in the first place, and when I don't know how to find an element like that, I simply jump down the tree to see where it is, using the descendant axis from the root, to jump down and find all the`<geo>` elements wherever they are.

**Comment by ebeshero** [comment]
@Jamielynn92 In other words, write a really simple XPath expression just to get started and help you see where these elements are. (Outline view and scrolling won't help in a gigantic document like this.) Then build on it to refine it to respond to the homework questions. Hope that helps!

**Comment by Jamielynn92** [comment]
I looked over the answers you posted and looked at mine, and I didn't get any of the same answers.

**Comment by ghbondar** [comment]
@Jamielynn92 Sometimes, there are many different XPath-expressions that will get the same result, and it can be useful to study and experiment with the differences. Hopefully, your results were similar to ours. If not, break down the syntax or "grammar" of your answers to restate what your XPath actually is actually searching for.

**Comment by Jamielynn92** [comment]
@ghbondar I have tried. I keep getting errors with every attempt I've done. I even tried the ones from the answers posted on here. and those don't even work.

**Comment by Jamielynn92** [comment]
![screenshot 34](https://user-images.githubusercontent.com/31480905/31355543-b8da83cc-ad08-11e7-9f60-ded8efff8096.png)
I keep getting this pop up.

**Comment by ghbondar** [comment]
@Jamielynn92 Your search returned results for me, so the syntax is ok. Try downloading and opening a fresh copy of the file. I cannot replicate your error :(

**Comment by Jamielynn92** [comment]
![screenshot 35](https://user-images.githubusercontent.com/31480905/31356193-2eada910-ad0b-11e7-92a3-51f0622e32dc.png)
ugh.. It doesn't want me to get this.

**Comment by mof11** [comment]
@ebeshero @ghbondar Im stuck on the third question. How do you include two different kinds of attributes in the same expression. So far I have //body/div/div[@type="book"][3] but I want to add that I want only the first chapter that contains the latitude reading. How do I go about this? Thanks!

**Comment by quantum-satire** [comment]
@Jamielynn92 It looks like your XML file is the issue rather than the XPath expression you're trying to run. Delete that extra <respStmt> element you have there and it should fix it!

**Comment by quantum-satire** [comment]
@mof11 I think you can continue further down the tree and specify the second attribute that way, since the attribute `@select="lat"` isn't on the same level as `@type="book"`, but a child. Does that make sense?

**Comment by Jamielynn92** [comment]
![screenshot 36](https://user-images.githubusercontent.com/31480905/31364018-4f7f2a86-ad30-11e7-9a40-efa1077ff5eb.png)
@quantum-satire

**Comment by quantum-satire** [comment]
@Jamielynn92 The problem continues with your XML document! Do a find/replace with to get rid of & and replace with &amp;. This should fix your problem!

**Comment by Jamielynn92** [comment]
it worked. i replaced it the &amp;

**Comment by quantum-satire** [comment]
@Jamielynn92 Awesome! See if your expression works now.

**Comment by Jamielynn92** [comment]
it did.

**Comment by mof11** [comment]
@quantum-satire thank you I got it!!

**Comment by quantum-satire** [comment]
@mof11 Glad to hear it!!
