### ISSUE TITLE
Simple XPath Functions: not() 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#363]
For number 5 in XPath Ex 2, you'll want to try an XPath function, and we may not have modelled this for you on Friday. In case we didn't...a function **wraps around** a part of an XPath expression, and delivers some useful information. Say you want to find which paragraphs or `<p>` elements in a document do NOT contain any descendant quotes or `<q>` elements. We'd use the `not()` function our predicate filter to help us find this, like so:
```
//p[not(descendant::q)]
```

Make sense? Give it a try on the homework! :-)

**Comment by pab124** [comment]
I have a question about using this on the homework. I understand how you can use the not() function to find elements that do not have a certain characteristic, but how then, within the same xPath expression, do I state that the same element MUST have this other characteristic?

**Comment by ghbondar** [comment]
@pab124 The Not-fcn is a way of testing for absence, in effect. A normal XPath search is looking for a 'positive' case. If you are comparing specific values, you can use eq, or other comparisons, as you can see at the end of "[XPath Functions we use most](http://dh.obdurodon.org/functions.xhtml)"

**Comment by pab124** [comment]
@ghbondar I guess I should rephrase my question maybe. I was wondering how I could include multiple +/- features into a single expression. In some of the reading, I saw the 'and' operator and I was curious if I can use this to introduce multiple clauses, like arguments, into a single expression in addition to a not() function: something like "it must contain this, this, **and** _not_ this"

**Comment by ghbondar** [comment]
@pab124 Multiple predicates is one way to do this *hint*hint*

**Comment by jub45** [comment]
Having similar issues with this exact question. I can answer questions 1-4, but I am having quite a rough time getting xpath to differentiate between p's that contain one value but _not_ the other.

**Comment by ghbondar** [comment]
@pab124 @jub45 While we did see multiple-predicates in class, we did not go over _nested_ predicates, where you can use a value with a predicate, say a `geo[select="lon"]` as the contents of another predicate further constraining another element, such as a paragraph `p`
