### ISSUE TITLE
Problems with #5 for Xpath assignment 2

### ISSUE THREAD

**Issue by jub45** [ebeshero/DHClass-Hub#364]
As the title suggests, I am having a tough time figuring out this one. Obviously I am wrong, but I would figure that if in a string such as `//p[not(descendant::geo[@select='lat'])]`, that:
1. Search all p's that don't contain a descendant geo with the attribute equal to 'lat'. 

I have tried a boatload of combinations using the not function, using booleans and using multiple predicates with no luck (I however did manage to make the editor go crazy a few times).

**Comment by gabikeane** [comment]
I've just tried to recreate your issue.  I got 910 results (910 paragraphs) out of about 1004 total.  Can you give me more details about what is wrong?
