### ISSUE TITLE
Oxygen Outline View

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#367]
Hi everyone, 

Somewhere along the line, I lost the outline view in my XML documents in oxygen. How do I turn it back on? 

Thanks.

**Comment by ebeshero** [comment]
@kes213 On the menu bar across the top of oXygen, go to Window --> Show View. And on the long drop-down list (in alphabetical order), find Outline.

**Comment by kes213** [comment]
@ebeshero thank you!
