### ISSUE TITLE
Intro to XPath Functions: Class Notes

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#368]
I drafted some notes for today's class to help with thinking about how to write XPath functions. This contains lots of examples and explanations of why some functions are "wrapped" with the function going at the start, and why some functions sit at the end of an XPath expression, as they respond to each and every node.  These are posted in a Wiki page here on our DHClass-Hub, and I hope they're helpful as you're working on XPath 3 and 4! 
https://github.com/ebeshero/DHClass-Hub/wiki/An-Intro-to-XPath-Functions

@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213

**Comment by quantum-satire** [comment]
Thank you for this!!
