### ISSUE TITLE
A Helpful Explaination of Basic XPath

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#37]
If this is an aid to anybody, here you go: `https://en.wikibooks.org/wiki/XPath/Basic_Syntax` I found a source with the most basic information of XPath. I wish it had more on the topic though.

**Comment by ebeshero** [comment]
@CodyKarch That's a good, quickly readable survey of the basics, and probably helpful as a review! I recommend working with the Michael Kay book for looking up anything--and use Kay together with webpage resources you find like this. Kay is really the leading authority on the specifications for XSLT and XPath--he wrote *The Book* on XPath and XSLT--and you can find just about anything working from the index of his book. I find myself *reading* Kay to get a sense of *how* things work with an XPath function, for example, and then I look up for more examples of how that function is used online, sometimes at the w3schools site.
