### ISSUE TITLE
XPath 3 

### ISSUE THREAD

**Issue by flowerbee1234** [ebeshero/DHClass-Hub#370]
I am doing pretty well on this one, at least I think so, but when I go to type in the expression discussed in class, I keep getting errors. I am on #1 of the third section, because I decided to redo it. Here's my expression:

(//p [count(geo[@select="lat"])gt 1] last()))

Am I writing it wrong? Why does this not work for me? 
:(

**Comment by ajnewton1** [comment]
The last function should be in square brackets like ````[last()]````

**Comment by flowerbee1234** [comment]
Thank you for getting back to me! It gave me 11 results, though, instead of one. :/

**Comment by ajnewton1** [comment]
Simple fix! Check to see where your parenthesis are

**Comment by flowerbee1234** [comment]
I have them around my [last()] expression

**Comment by flowerbee1234** [comment]
I mean after it. Like [last()])

**Comment by ajnewton1** [comment]
Try to move it around to different places

**Comment by flowerbee1234** [comment]
It worked!! Thank you so much. I may need more help (probably will).

**Comment by flowerbee1234** [comment]
Now for this next one, I used the expression (//p[1] [count(geo[@select="lat"])gt 2]), which didn't bring up any answers. But when I changed it to gt 1, I got two results

**Comment by flowerbee1234** [comment]
Never mind the last post, I figured it out all the way up to number 4. I am getting the first half of the expression right but the second half wrong.

**Comment by flowerbee1234** [comment]
Wait, never mi

**Comment by ebeshero** [comment]
Sounds like you’re building it up from small pieces...that’s the right idea! How is it coming?

**Comment by flowerbee1234** [comment]
I figured it out! That's why I closed the issue. I'm finally on the last question so I deleted the issue.

________________________________
