### ISSUE TITLE
XPath Exercise #2A issues

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#371]
Hi, 

I'm working on this question within the exercise: 

> Which 'div' elements contain references to 'homework'? How many results do you return?

Looking at the Xpath: Functions with Strings Wiki on this git hub, I think I need to use the contains() function here . . . so here's what I tried: 

`contains(//div, "homework")`

I received an error that said "a sequence of more than one item is not allowed in the first argument of contains()." 

Is this the correct function to use? Am I using it correctly? 

Thanks!

**Comment by ajnewton1** [comment]
It is the right function but you are using it wrong. You would want to go down to the div first before you find what it contains. 
````//div/contains("homework")````
That wont work because you need two arguments inside the function. What is the special character that refers to _self_?

**Comment by kes213** [comment]
Should I use the . character??

**Comment by ajnewton1** [comment]
Actually, thats wrong -- sorry. You would want the ````div```` to contain the ````contains()```` function... if that makes sense. But yes, you would want to use the '.'

**Comment by kes213** [comment]
I tried this: 

//div[contains(., "homework")]

It seems like it's pulling up every div element, even the ones without "homework" in it.

**Comment by ajnewton1** [comment]
Are you sure? It looks like I am getting 18 results on the code that you just posted. What is in your return window?

**Comment by kes213** [comment]
I got 18 items as well. Maybe I was just missing something when I scrolled through my results. Thanks!

**Comment by ebeshero** [comment]
@kes213 @ajnewton1 Actually, you're *both* correct. What Kaylee is rightly noticing is how deeply the `contains()` function runs. This will match on ANY div that has the text string "homework" inside its children or deep descendants. That is why we keep tinkering with the expression in the later homework options...to drill down more precisely to the actual parent of the precise text() node that contains the "homework" string!
