### ISSUE TITLE
Website Issues

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#372]
Here's an issue for all you website lovers. I am working on [War of Currents](http://newtfire.org/warofcurrents/index.html) and I am trying to use javascript to show a title that is hidden. Right now on the website, the title is hidden below 'Insert Graphic Text' and above the menu bar. What's supposed to happen is that once the user scrolls past 1px, the title shows. It's not working and I cant find what's wrong with it!! 
I even did it on [JS Fiddle](https://jsfiddle.net/ajnewton1/660ewnwm/) and it works! So I am very confused on what is wrong with my code.

**Comment by ebeshero** [comment]
@ajnewton1 Interesting that it works on the JS Fiddle--and thanks for posting it: I can see what you're trying to do! When I load your page in the web browser and open up Developer Tools in the browser, I am seeing errors on the lines in the JS where you attempt to change the className value. The error is "cannot set property className of null"-- and what that indicates is basically that it can't change a className when it can't **find** the element in the first place. I think that In the browser, the JavaScript isn't locating your element with `@id = "myID"` so I'd work on checking that first!

**Comment by quantum-satire** [comment]
@ajnewton1 I pulled all of the files from the repo you uploaded and ran them locally on both Safari and Chrome to test if it could be a browser incompatibility issue (which I don't think is the case). I then looked at the page with developer tools on Chrome and saw the same issue @ebeshero had mentioned--it looks like you set `myID` to equal `War of Currents`, but also set the class to `class="title hide"`. Could it be that the title's function will only be true if the ID is set to `class="title hide"`?

**Comment by ajnewton1** [comment]
Thanks @ebeshero and @quantum-satire but I figured it out! I changed some stuff around and it finally works!!

**Comment by ebeshero** [comment]
@ajnewton What was it that you fixed? Was it adding a function init() on load of the window?

**Comment by ajnewton1** [comment]
Actually I don't think thats what fixed it. I tried that at first and it didn't do anything. 

````
window.onload = init;

function init() {
    scroll();
}

function scroll() {
    var y = window.scrollY;
    if (y >= 111) {
        document.getElementById("id").className = "show"
    } else {
        document.getElementById("id").className = "title"
    }
};

window.addEventListener("scroll", scroll);
````
What I did was I changed some stuff in CSS and HTML and also took out the global variable that I declared in JS. It seems a lot simpler than what I expected!

**Comment by ebeshero** [comment]
@ajnewton1 Interesting! I'm glad you got it working, and the main page on warofcurrents looks great!
