### ISSUE TITLE
Xpath 4 Issues

### ISSUE THREAD

**Issue by flowerbee1234** [ebeshero/DHClass-Hub#373]
Hi, guys. I just started to look at the homework, and I am already very confused. I know that, in order to find the list of authors, I would need to use the name () string, but I'm not sure where else to go from here. I also have been looking in my textbook, but it hasn't really helped :/

**Comment by ebeshero** [comment]
@flowerbee1234 `name()` is the function we use to get a list of *element* names...I don't think it's going to help you to return a list of the authors inside the `<bibl>` elements. Just do a simple XPath to look at all the `<bibl>` elements first, and look at the results...I think that'll help you get started!

**Comment by flowerbee1234** [comment]
I am still pretty stuck. Here's what I've got so far.
//xs:string (bibl)

But they're not separated by semi-colons. I'm not sure how to do that.

**Comment by ebeshero** [comment]
@flowerbee1234 Really, all I meant was just look inside `//bibl` . Just take a look at what elements are nested inside. `<author>` is simply an element inside `//bibl`.  That's all you need to start. Afterwards you want  a function that reaches in and grabs the contents of the author elements, and bundles them together. Hint: look at `string-join()`, and look at our wiki: we went over this one in class on Wednesday!

**Comment by ebeshero** [comment]
@flowerbee1234 Here's the wiki where we recorded examples of lots of string functions on Wed.: https://github.com/ebeshero/DHClass-Hub/wiki/XPath:-Functions-with-Strings

**Comment by ebeshero** [comment]
@flowerbee1234 Here: just look at this in your XPath window:
```
//bibl/author
```
See? And use the `string-join()` to put those contents together with a `;` separator. Remember how the `string-join()` function takes two arguments? The first is the XPath that lands on the elements you want to work with. The second is just a little piece of text you designate as a separator, inside quotation marks.  `string-join(XPath-to-here, ";")` (if `;` is your separator). Look at the results when you do that, and you'll see how string-join works.

**Comment by flowerbee1234** [comment]
Thank you! Here's what I've got so far
string-join(//author/normalize-space(), ;)
So close, but the semi-colon part is throwing me off. I'm looking up how to use semi-colons in this

**Comment by ebeshero** [comment]
@flowerbee1234 What you need are just quotation marks around your separator: ";" 
Otherwise silly XPath thinks your semicolon is an element name! It's pretty literal.

**Comment by flowerbee1234** [comment]
Ugh finally!!! Thank you so much

**Comment by ebeshero** [comment]
Somehow I think you might have gotten lost in the Michael Kay book...am I right? Maybe scan the wiki and XPath Functions we use most pages first....There's a part on this assignment where we'll send you to look at some passages in Kay and you'll get a better sense, I think, of how to work with the book there.

**Comment by flowerbee1234** [comment]
Yeah that's exactly what happened! So sick of screens! Lol anyways thank you again. I'm hoping I get better at this.

**Comment by ebeshero** [comment]
You will! I was pretty awful at it myself at first...the first times you learn how to write the functions are the hardest!

**Comment by flowerbee1234** [comment]
Now I am totally stuck with the MMDDYY question. I am thinking maybe it involves xsd:int, but I'm not sure, and I've been looking on the wiki page for help

**Comment by ebeshero** [comment]
@flowerbee1234 That's not on the wiki page. It's also **mostly** modeled for you very literally on the assignment sheet. It's unusual code and part of the idea for *this* part of the assignment is to show you something interesting! Just try out the code I'm giving you on the assignment sheet, and read what I'm saying closely. Also, remember you have until tomorrow night to finish this--so if you're tired and your eyes are buggy, it might help to just sleep on it. :-)

**Comment by flowerbee1234** [comment]
Unfortunately I work until 10 tomorrow and have class all day so I won't have much time to work on this. But thank you again for all your help!!

**Comment by ebeshero** [comment]
@flowerbee1234 Okay, what I said just now was about number 5, the `format-date()` function. You might be stuck a little earlier...?

**Comment by flowerbee1234** [comment]
I was actually fine up to this point. Now I'm stuck again, but I'll try that!

**Comment by ebeshero** [comment]
If you're stuck on 3b., just look at the attribute values and how they're formatted first. Take my hint in the assignment page.

**Comment by flowerbee1234** [comment]
//div//date[contains(., "F")]//format-date 

This is what I have

**Comment by flowerbee1234** [comment]
I just saw your last comment. Let me try that

**Comment by ebeshero** [comment]
@flowerbee1234 You're right, actually, for returning the Friday dates on the syllabus, but you do not need the `//format-date`. You've got this.

**Comment by flowerbee1234** [comment]
I can't figure it out! I've been stuck on the same one for awhile now, and it's just not happening

**Comment by ebeshero** [comment]
@flowerbee1234 You got this part: run this (if you haven't already): ` //div//date[contains(., "F")]` 
It's part of the code you posted just now, but you just had too much at the end of it.

**Comment by ebeshero** [comment]
@flowerbee1234 The next bits are just looking at the attribute on `<date>`, and running our old friend `string-join()` again.
