### ISSUE TITLE
Xpath #4 Help

### ISSUE THREAD

**Issue by ttb11** [ebeshero/DHClass-Hub#374]
I'm stuck on 4b. Whenever I use the string-length() function all that comes back is thousands of zeros.

I've tried a bunch of different things but nothing is giving me the results I need.

**Comment by ebeshero** [comment]
@ttb11 string-length() needs to be called on each node separately—it is taking a measurement of the number of characters at each stop on the XML tree. So if you want to return the string-length() of each p element, you would set the function to call after you stop on each p, like so:
‘//p/string-length()‘
Does that help? Some functions must be called one by one to return separate results. Others wrap around the entire path and calculate a single result from many nodes.
