### ISSUE TITLE
Schematron Ex 1 help: sum(), count(), and number()

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#375]
Here's a little guidance for the first Schematron Exercise. For this, you need to make sure you're understanding the difference between **sum()**, **count()**, and **number()** to write good Schematron rule tests: 
    * We use **sum()** when we have numbers as content inside elements or attributes and we want to add up all those numbers. 
    * We use **count()** when we want to get a count of the number of times we see something in a document, like the number of times we see `@name` attributes with the contents "Mexico".  (How would you count that?)
    * We use **number()** really only when we have to tell Schematron to evaluate numeral contents inside an element or attribute, to make sure it's reading a literal number and not text. We only need to use this when we're making sure a number sitting inside an element or attribute is greater than/less than/equal to/ (etc) a particular value. It's only used to reformat each individual node when you need to do that. You may not need to.

Interestingly, we've never had to use **number()** before taking the **sum()** of the numbers inside a repeating element. We've only needed to use it when we have to *compare* the literal contents of an element to something else. The result of a **sum()** or a **count()** is already a number, so it doesn't need to be reformatted with **number()** when you're trying to see if it's greater than 0 or less than 100, etc.
Hope that helps!

**Comment by Jamielynn92** [comment]
This is using the Dhclass xml right?

**Comment by ebeshero** [comment]
@Jamielynn92 No--it's a really simple XML file inside the assignment: http://dh.newtfire.org/SchematronExercise1.html 

You just copy and paste the simple XML file into oXygen to get started.

**Comment by Jamielynn92** [comment]
The link for exercise 2 isn’t working.

**Comment by ebeshero** [comment]
@Jamielynn92 Thanks, and I know--I took it down to rewrite it this weekend. You're working on Schematron 1 for now...don't worry about 2 yet.

**Comment by Jamielynn92** [comment]
I’m stuck on how to try to compare the percentages.

**Comment by ebeshero** [comment]
@Jamielynn92 Much depends on the context of your rule, I think. What are you trying?

**Comment by ebeshero** [comment]
(I just deleted some old comments in here about Schematron Ex 2--that link should be back now)

**Comment by ebeshero** [comment]
@Jamielynn92 Remember how you could write a predicate in XPath to find all the paragraphs that had more than 2 of something? This is a *little* like that, only the predicate turns into a test for your rule. Want to share some code?

**Comment by Jamielynn92** [comment]
I tried looking up how to write them but I’ve been staring at it puzzled on how to write it.

**Comment by ebeshero** [comment]
@Jamielynn92 Which part? 
```
<pattern>
	<rule context=" ">
		<assert test=" "> </assert>
	</rule>
</pattern>

```
or

```
<pattern>
	<rule context=" ">
		<report test=" "> </assert>
	</rule>
</pattern>
```

**Comment by Jamielynn92** [comment]
Top part.

**Comment by ebeshero** [comment]
@Jamielynn92 Ummm, I probably just gave away the answer.

**Comment by ebeshero** [comment]
@Jamielynn92 Except of course the element names in the tutorial are different... but see how the syntax is working?

**Comment by ebeshero** [comment]
@Jamielynn92 Because we're using all the same element name, you need to find a different way to distinguish the elements holding the votes.

**Comment by ebeshero** [comment]
@Jamielynn92 I deleted a couple of my comments, just looking back at the assignment. What we're asking is a little different than the example in the tutorial, and that's probably why you're puzzling a bit. What we're asking about the percentages is: "Write a Schematron rule that fires an error when any location’s voting percentage sits outside of the 0 to 100 range. There should be no negative integers and no integers greater than 100. "

So, you want to compare each value to make sure it is greater than 0, and less than 100, basically.

**Comment by ebeshero** [comment]
@Jamielynn92 You aren't comparing the values with each other here, but you are comparing each one to 0 and 100.  I think you will need to use `number()` here to make sure Schematron reads the contents of each element as a number, and you need comparison operators. You can also use a boolean "and" in your test, to make sure the value is greater than something *and* less than something.

**Comment by Jamielynn92** [comment]
Would I put xsd:int or percentage?

**Comment by ebeshero** [comment]
@Jamielynn92 I don't think you need either one, really. You may just need `number()`. The values are just supposed to be greater than zero and less than 100, and that rule you write will make them legal as percentage values.

**Comment by ttb11** [comment]
How do you get the schematron linked to the xml file? Just by linking it like you would a schema?

**Comment by ebeshero** [comment]
@ttb11 Yes--it's the same way you'd associate a Relax-NG file. In oXygen, go to Document -> Schema -> Associate schema, and select your file. oXygen should recognize it as a Schematron file, and generate the appropriate schema line on your XML file.

Once you've associated it, test it and make sure your rules are working the way you want them to!

**Comment by ttb11** [comment]
Okay, thank you! For some reason it couldn't find my file but I changed the name and it worked.

**Comment by Jamielynn92** [comment]
![Image](https://i.imgur.com/MVKCa3F.jpg)

**Comment by Jamielynn92** [comment]
Did I name these right?

**Comment by ebeshero** [comment]
@Jamielynn92 Whoa! You didn't need to write a Relax-NG schema for the Schematron file. We provided you with a Relax-NG file for the simple XML file you are testing, the one we listed in the assignment sheet that just records vote percentages for trip destinations to Spring Break.

You don't need to be writing any new Relax NG rules, and you don't need to write Relax NG rules for the Schematron file.

**Comment by Jamielynn92** [comment]
Which xml? I’m so confused.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ebeshero** [comment]
@Jamielynn92 What you should have open on one screen is the simple XML file we gave you in the assignment. You don't even need the Relax-NG file open. We showed you that just so you could see how *differently* Schematron works, because you can just write some custom rules to be more specific than Relax NG can be. 

It looks like you pasted the simple XML file into your Schematron file. That's not how Schematron works. It needs to be a separate file from your XML. Save that simple little file, the stuff in the `<results>` element, in a **separate** XML document. Open that in the other window in tile view.

You're writing Schematron to help you make sure that the numbers in the simple XML file add up to 100.  And you're making sure that none of the values are less than 0 or greater than 100.

**Comment by pab124** [comment]
@ebeshero I read all the discussion you've posted so far about using the sum, count, and number functions and I think I've used them correctly. The problem I'm having now is, like you mentioned before, identifying each individual <place> tag. I figured it would be important to note that their attribute values are different, but I can't seem to recall how to individualize them. Could you point me in the right way?

**Comment by ebeshero** [comment]
@Jamielynn92 Here is the simple XML file I am talking about. 
```
<results>
    <place name="NYC">34</place>
    <place name="Mexico">24</place>    
    <place name="Rome">30</place>
    <place name="London">12</place>
</results>

```

You have somehow pasted that tiny XML file in your Schematron file. That's not where it goes. Schematron is written as a separate file with schema rules, and you **associate** that file with your XML file. It's just like the way you write Relax NG in a separate file from the XML, and associate the schema.

**Comment by ebeshero** [comment]
@pab124 You have a decision to make about where to set the `@context` of each of your rules. Since this XML file is so simple you could choose your context to be the root element (`<results>`) or the child elements `<place>`. If you wanted to make a separate rule for each place, you could probably do that by referring to the element with its attribute, but you may not really want to control each element one by one. Instead, you could try to set a context rule on the `<place>` elements generally, like so:

```
<pattern>
    <rule context="place">
           <assert test="something-to-do-with-the-self-node">Your message here!</assert>
   </rule>
</pattern>
```
Now, you could write that rule from the **point of view** or `@context` of the results element, but you'll just make reference the place element as the child of `<results>` when you do that. Either way would be fine, so long as your rules work. It's up to you!

**Comment by Jamielynn92** [comment]
![Image](https://i.imgur.com/ehR8l9G.jpg)
Is that better?

**Comment by ebeshero** [comment]
@Jamielynn92 YES. Now, let's take a look at your rule. Your rule is always going to test "true", no matter what is happening in that XML file, because it is literally saying, "Tell me when 100 is greater than 0." That isn't too helpful for testing the numbers inside the `<place>` elements in that XML file, is it?

**Comment by ebeshero** [comment]
@Jamielynn92 You have a choice to make between whether you want your rule to be an `<assert>` or a `<report>`. The `<assert>` statement defines the way things **ought to be** in the XML file, so when you write a `@test` attribute on `<assert>` the `@test` value is the condition you want to be ideal and perfect for the XML elements. 

You want all those place elements to add up to 100.
You want each of those elements to be greater than zero, and less than 100.
(You want a few other things, too, but let's just start there...)

**Comment by ebeshero** [comment]
@Jamielynn92 Go up to the top of this issue and take a look at my hints about `sum()`, `number()`, and `count()`, now. This should start to make more sense as you're looking at the simple XML file you're working with.

**Comment by ebeshero** [comment]
So, you want a sum() that equals 100.
You want the number() in each element to be greater than 0, and less than 100 (so no one sneaks in values like -50 and 150)
You want the total count() of the elements to always be 4, so someone doesn't sneak in an extra option.

**Comment by ebeshero** [comment]
And lastly, and maybe @pab124  this is what you were asking about, you want a way to tell if the @name attributes ever repeat. (So if someone were cheating on representing the votes, they might make `@name` values be set to "NYC". What's a way we can find out the count of different values used? We'd combine two functions for this...and you've done it before on the XPath homework.

**Comment by pab124** [comment]
@ebeshero your first comment definitely helped with the problem I was having. As for the last question, I didn't realize until now that I was completely misunderstanding it and your help there greatly clarified that. Thank you very much, I think I've got it now.

**Comment by Jamielynn92** [comment]
I didn’t get it all but I can’t stare at the screen anymore. I’ll try again in the morning before class.
