### ISSUE TITLE
Missing Class: XSLT Orientation

### ISSUE THREAD

**Issue by KariWomack** [ebeshero/DHClass-Hub#38]
I am currently on the Fall Arts Trip in Boston, posting from my hotel room, and obviously will be missing class tomorrow. Is it possible for someone to fill me in on any important notes I miss during class? If not I'll just figure it out, but if you could, it would be really helpful. Thanks!!!

**Comment by ebeshero** [comment]
@KariWomack You should probably make some time to meet with one of us instructors when you're back. You'll be back on Tuesday (when Tuesday is Monday), right? If you have some time to meet that day (or maybe right after class), let's do that. In the meantime, you'll need to concentrate on learning XSLT, so concentrate on the [Introduction to XSLT] (http://newtfire.org/dh/explainXSLT.html) material . [The first XSLT assignment](http://newtfire.org/dh/XSLTExercise1.html) is something to get you started working with the XSLT debugger view in oXygen, so we hope this gets you oriented. Give this a try and as you have questions, post here, okay? We'll keep an eye out for you!
