### ISSUE TITLE
Issue with FileZilla

### ISSUE THREAD

**Issue by ttb11** [ebeshero/DHClass-Hub#381]
I can't find my website on FileZilla to put files into.

**Comment by jonhoranic** [comment]
@ttb11 
Which website are you referring to? Are you looking for your personal or project site folders? Once I know which one, I can point you in the right direction!

**Comment by gabikeane** [comment]
@ebeshero Tyler was recently added to the Whatsapp group and does not have permissions to upload to their newtfire site.  Could you give him permissions for us please?  Sorry, I think this just slipped all our minds when we switched him over!

**Comment by ebeshero** [comment]
@gabikeane @ttb11 Oops! Sorry we missed that, Tyler! I have now just added you to the WhatsApp group, so you should be able to access the project directory on our newtfire web server now. Let us know whether you can get in now!
