### ISSUE TITLE
Portu-WhatsApp

### ISSUE THREAD

**Issue by ttb11** [ebeshero/DHClass-Hub#382]
I changed groups for the project and don't have permission to upload stuff onto the Portu-WhatsApp page through FileZilla.

**Comment by ebeshero** [comment]
@ttb11 I think you do, right now-- I added you to the Portu-WhatsApp group on my server. Can you try right now and see if you have access?

**Comment by ebeshero** [comment]
@ttb11 Please report back here after you have tried again to access the site via FileZilla. You may need to close a current FileZilla connection and establish the connection to the newtfire server again. Please respond.

**Comment by ttb11** [comment]
I tried and it gave me the same message "Error: /var/www/html/newtfire/portu-whatsapp/index.html: open for write: permission denied
Error:        	File transfer failed"

**Comment by ebeshero** [comment]
@ttb11 Ah! I see the problem...you're a member of the group, but I bet no one but the original owner of the index.html file has access to it right now. (The permission settings permit only the first owner of the file to write over it.) Let me get in and change that...give me 5 minutes...I'll report back when you should try again! (In the meantime, can you upload a different file to the space, other than index.html?)

**Comment by ttb11** [comment]
@ebeshero I tried to upload an image into the image folder but I got the same "permission denied" message.

**Comment by ebeshero** [comment]
@ttb11 Thanks for that info, Tyler--I'll check the ownership and write access of the directory.

**Comment by ttb11** [comment]
Okay thank you!

**Comment by ebeshero** [comment]
@ttb11 This is strange: I'm a member of your group as well, and I can see very clearly you are a member. I just uploaded an image successfully to your group's web space. **You** should definitely be able to do so as well. I wonder if you are attempting to access the wrong directory? What directory path on newtfire are you attempting to access?

**Comment by ebeshero** [comment]
Okay--it looks above as if you're okay. The directory should be: 
/var/www/html/newtfire/portu-whatsapp

**Comment by ebeshero** [comment]
@ttb11 I will reset permissions on the index.html page, but this is about all I can do.

**Comment by ttb11** [comment]
I'm on the right directory but I'll try to see what else I can do to get it to work

**Comment by ebeshero** [comment]
@ttb11 Okay--I've just done a couple of chmod commands to modify permissions in that area...give it a try now?

**Comment by ttb11** [comment]
Okay it's working now! Thank you!

**Comment by ebeshero** [comment]
Huzzah!

**Comment by ttb11** [comment]
Okay actually just kidding. The index was updated and I uploaded an image but I can't upload over the html files.

**Comment by ttb11** [comment]
Okay wait actually all that I was able to do was to upload the index.html

**Comment by ebeshero** [comment]
@ttb11 Sorry about the delay-- I needed to change the permissions *recursively* on that directory named "website" inside portu-whatsapp. You should be able to upload inside that directory now--**however** I am not sure why your team is using a separate directory named "website": that is going to complicate matters for building your project! (your website URL for those files has to be like so: http://portu-whatsapp.newtfire.org/website/html/Analysis.html  

I'm not sure why it makes sense to use that directory anyway. Would you all want to just reorganize all that and scrap the "website" directory?

Anyway, the entire team now has access to the directory **inside** the "website" directory now--and it didn't before. Give it a try now. And sorry I wasn't able to respond until so much later.

**Comment by ttb11** [comment]
No problem! Thank you, it's completely working now!
