### ISSUE TITLE
XSLT 4 Question

### ISSUE THREAD

**Issue by pab124** [ebeshero/DHClass-Hub#384]
I decided to start a little earlier on this assignment. My question is related to the css part of the assignment. I'm having difficulty getting any of the css values to apply to the newly created `@class` values. I did the whole transformation that created new `<p>` elements with different class values so that there are several to differentiate between. Also, I know that my css is associated correctly because I'm able to write a css property for the body element and change the entire text to blue for instance. Did I skip over a step or something or did I just not form the new element tags correctly?

**Comment by ebeshero** [comment]
@pab124 Take a look at this page if you haven’t already: http://dh.obdurodon.org/class-and-span.html. It models the HTML and css for span elements with ‘@class‘ attributes...does that help?

**Comment by pab124** [comment]
@ebeshero I've been looking at that page in combination with a few others, and I've tried matching whats on the page exactly (as in changing the class value to 'good' for a moment, just to try out exactly what was there). But, I still cannot get the CSS to apply. I wrote a css property causing `<h1>` elements to become green and then wrapped  my `<p class="headline">` elements in `<h1>` to see if that would work and it does. But that isn't doing what I'm really supposed to.

**Comment by ghbondar** [comment]
@pab124 Patrick, besides our sample css from class today, go to the [sample results file](http://newtfire.org/dh/1888-07-30_XSLTresults.html) linked from the assignment sheet. Rt-click on that to view the source code and the [link to its css file](http://dh.newtfire.org/nelsonStyle.css). Maybe this will help.

**Comment by ebeshero** [comment]
The idea of linking that is so you can see how someone else wrote CSS to go with the output of this assignment. It does sort of give everything away, but the point more to help you review CSS so you can go and adapt it. It also shows you how you can refer to elements with multiple different class values and style them similarly if you choose to do that. I feel sure that there must be some syntax issue with your code @pab124, but we don't know what it is without seeing a sample of it.

**Comment by pab124** [comment]
@ebeshero @ghbondar I'm going to a TA's office hours today, so hopefully they'll be able to look at it a little bit and see where I'm going wrong. Thank you for your help in the meantime.
