### ISSUE TITLE
GitHub Repo Previews of HTML and Some SVG Files

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#389]
Prepend this to the GitHub address of your code file: **http://htmlpreview.github.io/?**

For example, here's a file pushed to DHClass-Hub Class Examples: https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/FunWithSVG.svg

And here's how we can preview how it would look when served on a website: 
http://htmlpreview.github.io/?https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/FunWithSVG.svg

**Comment by ghbondar** [comment]
Here is the file with more shapes:
[https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/FunWithSVG_moreShapes.svg](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/FunWithSVG_moreShapes.svg)

[http://htmlpreview.github.io/?https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/FunWithSVG_moreShapes.svg](http://htmlpreview.github.io/?https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/FunWithSVG_moreShapes.svg)

**Comment by ebeshero** [comment]
And here's a web link to our slide show helping to introduce SVG today! https://www.slideshare.net/ebbondar/svg-81556046

@ghbondar
