### ISSUE TITLE
XSLT Example from Friday's Class

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#39]
I've just made some repairs to the stylesheet we ran in Friday's class, added some comments to the file, and pushed it here to Class Examples on GitHub: https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/ForsterChPlaceList-Model.xsl 

Sync your GitHub and find the ForsterGeorgComplete.xml file in the [Class Examples --> XSLT folder](https://github.com/ebeshero/DHClass-Hub/tree/master/Class-Examples/XSLT) together with this XSLT file. You may wish to open them in oXygen, run the transformation, and to study the output. You may want to tinker with the template rules a bit as you're learning about how XSLT works.

I have also updated our "Explain XSLT" Tutorial with a few repairs so that our output isn't munged HTML! Remember: Always, always save your output and reopen it in oXygen to make sure it is valid and well-formed, because the XSLT results window in oXygen won't tell you this on its own.  

@amielnicki @CodyKarch @ghbondar @RJP43 @KariWomack @nlottig94 @blawrence719 @brookestewart @spadafour @rCarls

**Comment by nlottig94** [comment]
Closing for Spring 2016.
