### ISSUE TITLE
Math in SVG

### ISSUE THREAD

**Issue by Blangzo** [ebeshero/DHClass-Hub#390]
When I was writing the code for the SVG assignment, I noticed its similarities to other coding languages and tried to code the same way. One thing that I attempted to do was basic arithmetic operations with the SVG code.

For example for the first rectangle in the assignment, we want a rectangle that begins has a height of 404 and reaches the x axis at the bottom. To do this I would expect to be able to write this:

    <rect width="75" height="404" style="fill:rgb(0,0,255);stroke-width:1;stroke:rgb(0,0,0)" x="75"
        y="500-404"/>

Notice, that I set the y attribute as "500-404".  This is because I set my x axis at y=500 and want my rectangle to begin 404 above it. This however does not work. When I try to run this either in w3schools online IDE or in Oxygen, there is an error. Oxygen outputs the message that the attribute "y" of the element <rect> is invalid. 

    <rect width="75" height="404" style="fill:rgb(0,0,255);stroke-width:1;stroke:rgb(0,0,0)" x="75"
        y="96"/>

This works. Its the exact same except there is no arithmetic performed in the attribute. Is there any way to do math in this way?

In other languages such as java and python, this functionality was used to allow objects to change/move. The attribute could be set as an arithmetic operation of 1 or more variables that would change. It would not surprise me if this were not possible in SVG since there are other ways to make objects change/move.

**Comment by ebeshero** [comment]
Hi @Blangzo ! We're going to be making calculations just like this next week, but only in XSLT that *writes* SVG output. To my knowledge, there's not a way to handle calculations in SVG attributes, but XSLT handles them well. We'll be setting variables in XSLT next week that help us to adjust the size of graphs based on variable input XML, such as, say, to extend an X axis based on how many poems we have in a collection, and extend a Y axis based on the maximum count of something in each chapter. When we compose SVG using XSLT, we've got a lot of flexibility for controlling outputs.

This brings to mind a general observation about how people tend to produce SVG: Often we build it from a program (whether with XSLT or Python, for example) and set basic parameters for what we want, depending on what input we're supplied. And when SVG gets complex (say for retracing a map image with lots of curves and shapes) that process is usually automated by computer programming. We're going to be writing some XSLT code that responds well to XML source texts next week to help us output flexibly sized graphs and visualizations based on what XML input we provide.

**Comment by kes213** [comment]
You're method of subtracting the values before plugging them into SVG worked for my first bar, but not the second bar, for some reason. I've done the same thing, but the bar is way below my X axis. 

Here's what I have for my horizontal x-axis:

`<line x1="50" y1="600" x2="600" y2="600" stroke="black" stroke-width="5"/>`

And here's my second bar: 

 `<rect x="300" y="535" width="100" height="535" stroke="purple" stroke-width="5" fill="yellow"></rect>`

My first bar has a y value of 196, and that bar is sitting perfectly on the x-axis, so I'm confused why this one isn't working.

**Comment by ebeshero** [comment]
@kes213 Ah! Take a look at your height attribute on your new rectangle. You have the right positioning for your bar to be begin being plotted. But the height value has to go *down* the screen from the top of the bar by a set number of units. The `@height` wouldn't match your `@y` value, but instead it's a literal difference, a literal measurement.  

It should be the difference between where you draw the top of the rectangle, and the X axis. Does that help?

**Comment by kes213** [comment]
@ebeshero Yes, I think I got it figured out.

**Comment by Blangzo** [comment]
@ebeshero I realized that I never thanked you for your response even though its been over a week. Thank You!! Your general observation was something that I hadn't thought about when I tried to do math within svg attributes themselves, but does make a lot of sense.
