### ISSUE TITLE
SVG Exercise 3 X-axis Labels

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#395]
I'm assuming that my problem is related to what I'm selecting on my `@select` attributes in the code below, so hopefully someone can steer me in a better direction. 

I already have my X and Y axes set up with the Y-axis hashmarks and labels. My Xspacer and barWidth variables are defined as well higher up in my XSLT document.

```
 <xsl:for-each select="//fs[f[@select='Yes']]/f">
            <xsl:variable name="xPos" select="descendant::string * ($Xspacer + $barWidth)"/>
         <!-- X-axis Labels -->
             <text x="{$xPos}" y="10" text-anchor="end" writing-mode="tb" fill="black"><xsl:value-of select="descendant::string"/></text>
         </xsl:for-each>
```

This code is my attempt at labelling the X-axis with the questions. I know I need to output the <string> elements somehow. In my output, the new <text> elements aren't even showing up, so I'm assuming that the issue is how I've Xpath-ed, or perhaps what I've selected. 

How should I adjust this to get my labels to work?

**Comment by ebeshero** [comment]
@kes213 First, check and make sure: Do you have the TEI namespace defined as xpath-default-namespace up in the XSLT root element? (Be sure to paste that in from the assignment page, because without it, the TEI elements from the source XML won't be read). I'll take a closer look at your code here in a minute...

**Comment by ebeshero** [comment]
@kes213 Now I'm taking a closer look! There are a couple of issues here:
* One problem is  with how you're defining your `$xPos` variable: That needs to be a number, and it needs to be spaced across the X axis just as you've been doing in previous assignments. Here, though, you're reaching into the `<string>` element in the XML source document, which isn't a number at all. It won't make sense for the computer to try to multiple a string of text by numbers--it's almost certainly giving you an error when you try to run this.

* Here's a more basic issue: Let's take a look at what you're processing with your `<xsl:for-each>` loop. That's supposed to cycle through each portion of the source XML that holds information about each survey question together with its response counts. You've set that to look inside each:
`<xsl:for-each select="//fs[f[@select='Yes']]/f`

But if we do that, we land on each of the internal parts of the questions: it's 55 separate items. There are only 12 survey questions that have "Yes" responses, so we should be looping through for-each just 12 times. Let's back up an XPath step in your `@select` so you're doing that: 
`<xsl:for-each select="//fs[f[@select='Yes']"`

It may help to look at one whole XML element (the `<fs>` element) that contains a sample survey question, just to think about the data you need to reach, so I've just pasted it in below. 
```
     <fs type="QandA">
               <f name="question">
                  <string>Are there stairways from the windows outside?</string>
               </f>
               <f name="response" select="Yes" n="350"/>
               <f name="response" select="No" n="318"/>
               <f name="response" select="Blank" n="148"/>
            </fs>
```
As you move forward with this, one of the differences between *this* code and the code from *Alice in Wonderland* that we just processed is that we're holding all the raw data for survey counts inside attributes. You aren't going to be counting anything, then. Instead, you need to turn these raw numbers into percentages. You should write variables to do that: You'll need a variable that takes the `sum()` of all the @n attributes inside each `<fs>` element that'll get you your total. The`@n` on a "Yes" divided by that sum() total * 100 gets you a percent value.  (You didn't ask about this, but I'm just posting it here as a reminder of why we need to stop on the `<fs>` element: It **binds** all this information together, almost like a bound book with pages inside.

**Comment by ebeshero** [comment]
@kes213 To deal with the issue of the `$xPos` variable, you just need something that will return the `position()` number in the for-each loop you're processing, and that works exactly as you've done it in the last assignment.

**Comment by ebeshero** [comment]
@kes213 On spacing across the X axis: see the comment I just added to our posted solution to SVG Ex 2: https://github.com/ebeshero/DHClass-Hub/commit/de71e1edc86c78ed910afacd11ef736d20832771

**Comment by kes213** [comment]
Thank you! I will tamper with this shortly and let you know if I still have problems with it.

**Comment by kes213** [comment]
I'm closer but not quite there. 

I have better output now as far as my SVG file is concerned, because I can see the new <text> elements with the questions inserted in them, but they aren't showing up on my table when I open the SVG outputted file locally. 

I drastically enlarged the viewport, the height and width, and then both at the same time to see if the questions were just out of my view, but I still couldn't see them. 

Here's my new code on my XSLT file:

```
<xsl:for-each select="//fs[f[@select='Yes']]">
            <xsl:variable name="xPos" select="position() * ($Xspacer + $barWidth)"/>
             <xsl:comment>What is the value of $Xpos> 
             <xsl:value-of select="$xPos"/></xsl:comment>
         <!-- X-axis Labels -->
             <text x="{$xPos}" y="10" text-anchor="middle" style="font-family:sans-serif;font-size:20px;writing-mode:tb" fill="black"><xsl:value-of select="descendant::string"/></text>
         </xsl:for-each>
```
I'm super confused.

**Comment by ebeshero** [comment]
@kes213 It's good you can see the question string in the output code, but I wonder why the output isn't working. I'm going to tinker with the `<text>` element code you supplied here, but my first instinct is that you might want to move the "fill" property into your `@style` attribute in case it's being ignored. I'm going to take a closer look shortly...

Meanwhile, can you try to plot some bars on the graph? Also, one thing you might try is outputting just the Questions by `position()` number, just to see if *those* short strings are visible in the output.

**Comment by kes213** [comment]
I've just tried to put bars the graph, but I'm having trouble even getting the <xsl:comment> on my scratchpad to come through on the output with my value of the percent for each question.

**Comment by ebeshero** [comment]
@kes213 Make sure you position the `<xsl:comment>` inside your `<svg>` element on the XSLT stylesheet. Don't try to set it above or below that element, or you won't see it in the output. (Is that the problem?)

**Comment by kes213** [comment]
I've just pushed my XSLT file to my personal repo in case you need it. 

I got the questions to appear on the SVG and the <xsl:comment> is coming through, but all of the values are 0. I think it might have something to do with the way I've set up my <xsl:when> and <xsl:otherwise> elements?

**Comment by ebeshero** [comment]
@kes213 I'm going to take a look right now...stay tuned!

**Comment by kes213** [comment]
@ebeshero Thank you, I appreciate it! I feel as though I'm just on the brink of understanding; I just can't quite get there on my own. 

I'm on my way into class now, but I'll get back to the assignment once the chaos of class, my commute home, and dinner passes.

**Comment by ebeshero** [comment]
@kes213 Aha! I discover the problem. You have:
```
<xsl:variable name="YesCount" select="descendant::f[@select='Yes']/count(@n)"/>
```
However, you don't want to be using the `count()` function here! (There's really nothing to count: there's only one `@n` attribute on the element.) We used `count()` to count the number of times Alice's speeches were marked in *Alice in Wonderland*, but we wouldn't want to use it here, because we already have survey results. We just need to deliver the value of the `@n` attribute itself, not get a count of it. So just amend that to:
```
<xsl:variable name="YesCount" select="descendant::f[@select='Yes']/@n"/>
```
and you'll have the literal number to work with! Hope that helps.

**Comment by ebeshero** [comment]
@kes213 There's one other problem: It's with how you were calculating your `$TotalCount` variable. You had positioned the `sum()` in a place where it was being calculated on each `@n` separately, instead of including all of them in one calculation. You had:
```
descendant::f/sum(@n)
``` 
And that would mean the sum() was being taken on each separate `@n` where it doesn't make sense. Instead, you need the `sum()` function to wrap around the whole expression, to "walk the tree" and return one result. Once you do that, you get actual good results! Make sense?

**Comment by kes213** [comment]
Yes, I got it! Thank you!
