### ISSUE TITLE
My Talk about Student Projects: TEI 2017 Conference

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#398]
I'm giving a talk at the [TEI 2017 Conference](http://hcmc.uvic.ca/tei2017/index.php) and it features some gorgeous, intricate projects our students have worked on,  and it goes something like this:
http://bit.ly/TEI_Repurpose .

Navigate my slideset by hitting the space bar, or using the right and down arrows on your keyboard. The last set of slides is about @BMR59 and team's [Portu-WhatsApp project](http://portu-whatsapp.newtfire.org/) this fall, b/c we're [currently in conversation](https://github.com/BMR59/Portu-WhatsApp/issues/4#issuecomment-343933242) about their TEI markup!

@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213 @djbpitt

**Comment by ghbondar** [comment]
@ebeshero This looks great! Can I take your class? ;-D
