### ISSUE TITLE
Javascript Exercise 1

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#403]
Can someone tell me why this isn't working? 

```
window.addEventListener('DOMContentLoaded',init,false);
            
function init() {
    alert('Welcome! The page loaded!');
    }
    var buttons = document.getElementsByTagName("button");
    var button = buttons[0];
    button.addEventListener('click',show_hide,false);
    
function show_hide() {
    var p = document.getElementById("paragraphToToggle");
    if (p.style.display == "block") {
        p.style.display = "none";
    } else {
        p.style.display = "block";
    }
}
    
function show_hide() {
    var p = document.getElementById("paragraphToToggle");
    if (p.style.display == "none") {p.style.display = "block";}
    else {p.style.display = "none";}
    }

```

Also, I should say that I'm having to plug my code into https://codepen.io/pen/ to try to work with it because, as @ajnewton1 and @jonhoranic saw in class on Friday, my computer won't read JavaScript programs, even if the code is 100% correct. That's an entirely other problem, though.

**Comment by ajnewton1** [comment]
It looks like you closed your first function early. Try moving you end curly brace right before `function show_hide()` like this
````
function init() {
    alert('Welcome! The page loaded!');
    var buttons = document.getElementsByTagName("button");
    var button = buttons[0];
    button.addEventListener('click',show_hide,false);
}
````

**Comment by kes213** [comment]
Awesome, that worked! Thanks! @ajnewton1

**Comment by ajnewton1** [comment]
@kes213 Also, I see that you have an unnecessary step in your code. In your first function
````
function init() {
    alert('Welcome! The page loaded!');
    var buttons = document.getElementsByTagName("button");
    var button = buttons[0];
    button.addEventListener('click',show_hide,false);
}
````
I believe you could just say 
````
function init() {
    alert('Welcome! The page loaded!');
    var buttons = document.getElementsByTagName("button");
    buttons[0].addEventListener('click',show_hide,false);
}
```` 
and it still should work the same.

Just for fun, you could say ````buttons[0].addEventListener('dblclick',show_hide,false);```` or ````buttons[0].addEventListener('mouseover',show_hide,false);```` just to see how different events work.

**Comment by ebeshero** [comment]
@kes213 When you get a chance, try this page in your browser, and let me know what happens when you mouse-over the underlined words on it: http://digitalmitford.org/getLetterText.php?uri=1819-05-16_MWebb.xml 

I suspect you just need to activate a setting in your browser: let's take a look at 
* https://www.enable-javascript.com/
* https://support.microsoft.com/en-us/help/3135465/how-to-enable-javascript-in-windows
