### ISSUE TITLE
T-Shirts! sizes and colors, please!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#406]
**It's time to do our class T-shirt orders!**  I'm posting the proofs we used last fall, but NOTE: we're going to change the lettering, so this represents BOTH **Pittsburgh AND Greensburg** this fall as a special FALL 2017 issue celebrating the union of our classes. 

Here is the [proof](https://cloud.githubusercontent.com/assets/4014518/11314432/822bb9c8-8fb3-11e5-9803-1e8607100160.jpg) (but we're changing the lettering to **"Pittsburgh and Greensburg" around the newt**.) 

Notes about the t-shirts:
a) Ink is applied to the fabric (so there's nothing plastic-y in the application).
b) We can order these in any combination of the available T-shirt colors (so they don't all have to be the same color):
c) The design would work on four different T-shirt colors, and those colors have official names that I need to ask about, but for our purposes, let's call them in order from left to right in the proof image:

**gold, grey, natural, and green**
(Yes, that counts as an array of colors, and if we were counting in JavaScript we'd call that 0) gold, 1) grey, 2) natural, and 3) green. ;-)

**Please provide your preferred size and color in this issue.**

@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213 @djbpitt

**Comment by ebeshero** [comment]
If everyone responds by this afternoon (Wed. 11/29) that would be perfect for me to place orders.

**Comment by zme1** [comment]
I would love a grey medium shirt!!

**Comment by ebeshero** [comment]
NOTE: I'm on the phone with the T-shirt people, and they order shirts for printing on Thursdays and Mondays--once the shipment arrives, they're ready to print quickly. It would be perfect if I could send our list off by tomorrow morning! :-)

**Comment by gabikeane** [comment]
grey medium also please!

**Comment by amk231** [comment]
Ill take a green small! Thanks :)

**Comment by tal80** [comment]
Tylar Lyons, medium green T-shirt

**Comment by flowerbee1234** [comment]
I will take a medium natural! Thank you!

**Comment by Blangzo** [comment]
I'd like a gray large please! Thanks!

**Comment by BMR59** [comment]
I'll take a green medium, thank you !

**Comment by ttb11** [comment]
medium gray please thanks!

**Comment by mof11** [comment]
I would like a gray medium please! Thank you!

________________________________

**Comment by ebeshero** [comment]
Note: the frog in the background isn't part of the shirt--it's just the logo of the "Big Frog" T-shirt company we work with. Here's one more image:

![tshirtproof2fa2017](https://user-images.githubusercontent.com/4014518/33393055-dea7d156-d50b-11e7-8cc3-22dda850ae4b.jpg)

**Comment by quantum-satire** [comment]
I'll take an L in natural color please!

**Comment by kes213** [comment]
I'll take a medium green.

**Comment by ajnewton1** [comment]
Ill take a Large grey

**Comment by jonhoranic** [comment]
I have a collection of these going so far, let's mix it up a little!

Medium, green for this round!

**Comment by ebeshero** [comment]
Okay! I've submitted the order! Thanks everyone! :-D We'll have these by early next week.
