### ISSUE TITLE
Toggling css with Javascript

### ISSUE THREAD

**Issue by ttb11** [ebeshero/DHClass-Hub#410]
One day in class we saw an example from the Pacific Archives where checkboxes highlighted text. Would someone be able to tell me the link to that website? Thanks.

**Comment by ghbondar** [comment]
@ttb11 @ebeshero Here ya go!
[http://pacific.pitt.edu/InjuredIsland.html](http://pacific.pitt.edu/InjuredIsland.html)

**Comment by ttb11** [comment]
Thank you!
