### ISSUE TITLE
Adding DHClass-Hub Collaborators 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#412]
Add your GitHub username here, and I will add you as a full collaborator on this DHClass-Hub.

**Comment by alexfell06** [comment]
Hey, this is Alex Fell, my username is alexfell06

**Comment by setriplette** [comment]
Hi, I'm Stacey Triplette, username setriplette

**Comment by garrettjoiner** [comment]
Jello, this is Garrett Joiner. Handle is @garrettjoiner

**Comment by ebeshero** [comment]
Quick demo of markdown!
 # GIANT HEADER
## Smaller Header

*italics*
_also italics_
**bold**

`tick marks or backticks--NOT APOSTROPHES for a literal string of code`
`<element att="value">....</element>`

CODE BLOCK: (use 3 back-ticks in a row above and below so you don't disrupt formatting of a block of code you paste in):
```
<root>
     <element>...</element>
</root>
```

**Comment by MarkTheShark01** [comment]
Howdy, it's Mark Raschiatore, and my username is @MarkTheShark01

**Comment by ebeshero** [comment]
Welcome new class! :-D

**Comment by dorothealint** [comment]
Hi! I'm Dorothea Lint.  My username is @dorothealint

**Comment by Pomilui** [comment]
Hello, Code vets and code newbs.  This is Nicholas Pcsolar.  My (not very recognizable) username is @Pomilui , and I will update it later (I was hesitant to change it after reading the warning messages about forwarding pages or something).
