### ISSUE TITLE
Discussion about RNC schemas

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#416]
I'm starting the thread because I don't see one up here yet!  I have all green at the end but I hate my schema because it is NOT universal!  I'm sure there could have been a better way to do it. 
So first question - Is there a data type for consecutive alphabetical letters like there is integers?  I used those to mark one attribute and I don't see it on the list!  Am I missing it or did I just learn a way not to try to designate items in a series?
And question number 2 - I did the schema for a play, is it better to use the universal "text" in the actor's names or is it better to make this one more document specific to prevent misspellings and characters that are not on the accepted list or is there a more advanced way to do schemas to facilitate adapting a universal one?  I'm sure this comes up for every attribute but I was wondering what the usual form is.

**Comment by jonhoranic** [comment]
@dorothealint 
1. To my knowledge, I do not believe the xs:string datatype does just that. However, I am not fully sure of the proper use of that datatype and how it differs from the "text" designation.
2. This is depended on the context in which you would apply your schema. You could generate a schema that will only function on one file with all the ID names listed out, which can be useful for something large/complex. At the same time, you could also take a "one-file" schema and adapt it, for example: if you have actor names listed you can associate it with a similarly marked-up file and ADD those to the list with pipes. The last option is to just refer "text" and it will cover anything text based placed within, and though you will not be able to control exact spellings it will simplify the schema code overall.

**Comment by ebeshero** [comment]
@dorothealint and @jonhoranic Great questions! In reading about xs:string ([here](https://www.w3schools.com/xml/schema_dtypes_string.asp)) I'm thinking it's not exactly what you're seeking: it seems to permit alphanumeric characters as well as returns, tabs, various white space characters--and probably the reserve word "text" is equivalent (setting just a text node). 

Datatypes basically define *types* of "string data", as in integers or dates or decimals, and we can think of these as patterns of characters that when defined a computer knows how to recognize and format. I think setting a datatype won't tell the schema how to organize that data in sequence. For that we'll learn a different kind of schema code called Schematron (based on XPath which we'll learn later)--which has the power to evaluate sequences and make comparisons and calculations. 
 ( @djbpitt Do you know a way to do this in Relax NG? )

That said, as you are thinking about fine-tuning your schema to adapt it for a larger project (to use it for more than just the one XML file you're testing here), you may want to think about setting the text node of an element or an attribute value to a precise number of characters. So if you have in your XML:
```
<stageDir type="a">....</stageDir>
<stageDir type="b">....</stageDir>
<stageDir type="q">...</stageDir>
```
you can set those as *specific* values so you're only allowed to use `"a" | "b" | "q"` but maybe the character you use doesn't matter, and you want to just make it so you're only allowed **one letter** in the value. For that, you might want to play with a Relax NG **facet**. Take a look at [this chapter in Eric Van der Vlist's online Relax NG book](http://books.xmlschemata.org/relaxng/relax-CHP-8-SECT-1.html#relax-CHP-8-SECT-1.2) and see if this gives you some ideas! Here's the whole book's contents: http://books.xmlschemata.org/relaxng/page2.html .  Note that the examples are often in XML syntax followed by our compact syntax. Happy hunting!

Those of you returning to the course (@quantum-satire @setriplette  @jonhoranic)  might be interested to see that you can use regular expression patterns to define contents of elements and attributes, too!

**Comment by djbpitt** [comment]
See also http://eric.van-der-vlist.com/blog/2005/01/07/562_relax_ng_text_versus_data/. Eric is the author of http://books.xmlschemata.org/relaxng/. Uche is a regular contributor to the XSLT discussion list, to which you can (= should) subscribe (see <https://www.mulberrytech.com/xsl/xsl-list/> for information).
