### ISSUE TITLE
Sample Project Proposal: Your Project Name here

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#426]
1. **Open a new issue** here on DHClass-Hub with a (tentative) name for your project, and write up a description of what you propose. This should be a project that involves XML markup to investigate a research area of interest. Ideally, make your proposals by Friday 1/26 (or over the weekend). **Add a Label** indicating this is about **projects** (using the dropdown menu of labels available here). 

2. **Each of you must comment on at least one other student's proposal** and leave some suggestions, commentary, etc. 

Notes on Project Proposals:
*  The project must involve something we could study and visualize from our markup more effectively with computers than with human reading and description alone. Try to identify a source of texts to mark up. 
* Base texts: Where can you access and retrieve these? It's easiest of there are "base texts" already available in some online form, as in plain text or something we can "scrape" from the web. Project Gutenberg and WikiSource are good sources for literature, for example. We can also handle OCR (optical character recognition) at our Center for the Digital Text using ABBY Finereader on sources where print (or image of print) is all that's available and you can't copy and paste the text. Think about whether the material you want to investigate with XML is under copyright and what issues that might raise. 
* For ideas, here are other student projects completed in this course: http://dh.newtfire.org/studentProjects.html and in our sibling course in Pittsburgh: http://dh.obdurodon.org/course-projects.xhtml

**Comment by setriplette** [comment]
I am working on the Lope de Vega project [lope.newtfire.org](url) in which I compare women's speech to men's across several plays. Last year I looked at what portion of two plays' speeches were uttered by women and began some preliminary work on identifying what people talked about in the plays. I want to expand the project up to eight or more plays and come closer to answering the question of what men v. women talk about across the corpus. I have been running plain text versions of the play through voyant and generating wordlists, which has helped me add to the topics I knew I should look at from reading traditional criticism. Many critics have made it a habit to remark Lope's relatively progressive outlook on women, but my graphs lead me to question that. Women speak less often than men (this is true even if they are the title character), and I believe that I am going to find that the topics they talk about are limited. I think I'm going to find that men speak more often of real people and places (referencing the exterior world), violence, justice, honor, and money, while women talk about family, gender roles, and the domestic world (words like house, pot, hearth, broom, etc). The trick will be defining these semantic fields well enough to code single words.

**Comment by ebeshero** [comment]
Hi @setriplette ! Can you redo this post as a **new issue** here, so that each proposal can receive its own set of comments? I meant this one just to be a sample proposal post!

**Comment by ebeshero** [comment]
Thanks, @setriplette ! I'll delete these...
