### ISSUE TITLE
Lope de Vega project (ongoing)

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#427]
I am working on the Lope de Vega project [lope.newtfire.org](url) in which I compare women's speech to men's across several plays. Lope is the most famous Spanish playwright of the Golden Age (turn of the seventeenth century), and about half of his 400 extant plays are available in some kind of machine-readable form. Last year I looked at what portion of two plays' speeches were uttered by women and began some preliminary work on identifying what people talked about in the plays. I want to expand the project up to eight or more plays and come closer to answering the question of what men v. women talk about across the corpus. I have been running plain text versions of the plays through voyant and generating wordlists, which has helped me add to the topics I knew I should look for from reading traditional criticism. Many critics have made it a habit to remark Lope's relatively progressive outlook on women, but my graphs lead me to question that. Women speak less often than men (this is true even if they are the title character), and I believe that I am going to find that the topics they talk about are limited. I think I'm going to find that men speak more often of real people and places (referencing the exterior world), violence, justice, honor, and money, while women talk about family, gender roles, and the domestic world (words like house, pot, hearth, broom, etc). The trick will be defining these semantic fields well enough to tag single words.
My play choices for this year are three with women's names in the title, indicating the main character, three that reference male main characters in the title, and (possibly) three whose titles do not indicate the gender of the main character. Some of my choices are famous, but most I haven't ever read. I wanted to make sure I wasn't just recapitulating my own received knowledge, so I chose some new-to-me objects. I expect them to surprise me. All the texts I will be working with are in Spanish.

**Comment by quantum-satire** [comment]
One of the things I look for as a science journalist is the fact behind a statement. As you parse the plays by Lope I find it interesting that women are not portrayed in as "progressive" a light as critics claim he writes them in. I see this type of claim (and others similar to it) happen by fans of writers quite often and I feel that this is an important aspect to show! There is added difficulty to working with this project however, as it is all written in Spanish. Is there a way for individuals to contribute to the project if they aren't fluent in the language?
