### ISSUE TITLE
Analysis of the Graphic Novel--Alan Moore's "Watchmen"

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#428]
I enjoy the heck out of comics and comic art. Some day, I’d like to get around to creating my own comic, and I often find myself pulling apart the numerous aspects of well-written comics   in order to benefit from what they can teach me about the artistic craft and of writing as a whole. I'd like to explore this parsing of comics in a systematic way for this project.

I completed Dr. B’s Science Fiction course last semester and found I’d really enjoyed the works we covered. _Watchmen,_ written by Alan Moore and illustrated by Dave Gibbons, was one of my favorites, and I want to take another look into the story to analyse the text. Alongside the main story lines and chapters, there are documents written by the characters that provide further insight into the fictional timeline that _Watchmen_ takes place in. Though at first I considered looking at a few comics Moore had written, I decided that tackling only one would provide a more thorough analysis (and give a team ample time to actually complete the work--it's easy to run out of time depending on the size of the group and each individual's capabilities and strengths).

Using [Comic Book Markup Language (CBML)](http://dcl.slis.indiana.edu/cbml/)—a TEI-based markup language specifically catered toward comics and graphic novels—we can delve into the literary value the story holds and compare it to the visual value that readers are able to see on their own. I can picture the network analysis of overarching themes mentioned within the text or between the characters with the amount of times their names were mentioned and who was speaking them. There's a lot we can do with this, and I know (from painful experience!!!) that having this set, singular source of text will allow us to bypass a lot of the collection stages some projects may need to go through.

I realize not everyone has read this graphic novel, so I'm also open to ideas for other comics in place of _Watchmen._ This could be a really unique take on markup for the DH courses thus far and I can see it being a fun project to work on!

Thanks to Dr. B for showing me CBML!

**Comment by dorothealint** [comment]
I've never read the comic, but I'd be willing to read anything for one of these projects.  This sounds interesting!  You already have a timeline to extract and it intrigues me that you say each of the characters has written documents.  It sounds to me like there might be additional network analysis possibilities such as using the syntax of each character's writing to analyze them and why they are part of certain events based on specific words, sentence length, etc.  This sounds like a neat project!

**Comment by jonhoranic** [comment]
@quantum-satire There is a good deal of material to draw from in _Watchmen_, and I wonder if you simplified this idea to focus on a network of character interactions via plot points we could make some neat graphs! I think we would need a larger group, or more time if we wanted to look at a broader "content window", but if the project starts small it does give it chance to grow in later semesters!

For other comic ideas, looking at a one off issue of his or a somewhat smaller work like _Batman: The Killing Joke_ could prove interesting and more manageable for our class. Other works that come to mind: _Maus_, _Footnotes In Gaza_, any of the Neil Gaiman's extended works  (or crossovers with Moore).
