### ISSUE TITLE
XSLT 2

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#43]
I'm attempting to do the second xslt assignment, but I'm not getting anything in my output window except for my h1. I tried to follow along from the in class example as closely as I could while sticking to the assignment of which lists were ordered or unordered, so I'm not exactly sure where I went wrong. I pushed my file into the troubleshooting folder. I was able to understand what was going on in class, but I am completely lost on my own. I'm unsure when I'm supposed to be matching things and what exactly I should be matching and I don't understand how to make them output into a list.

**Comment by nlottig94** [comment]
Okay, I put an example up under the class examples earlier.  It's the lottig_10-20_extraPractice.  It may be of some help!

**Comment by RJP43** [comment]
@blawrence719 I also pushed Dr. B.'s files from class today to reference. Let's think very simply of what we want. We want an organized list of the the types of organizations and inside that we want unorganized lists of all the organization names. I am going to take a look at your file in troubleshoot now, but I wanted to first make it clear what exactly you should be looking for.

**Comment by RJP43** [comment]
Ok so from what I see you are matching, but you aren't selecting. Inside of your list items you need to specify exactly what you want the XSLT to grab!

**Comment by blawrence719** [comment]
Thank you @nlottig94 and @RJP43 both helped a lot, I think I figured it out!
