### ISSUE TITLE
Project Proposal: Analysis of Uses of Horror in Stephen King's IT

### ISSUE THREAD

**Issue by MarkTheShark01** [ebeshero/DHClass-Hub#434]
My project proposal will focus on looking at the different horror elements used the the book IT by Stephen King. 
IT is perhaps one of my all time favorite stories ever made, if not overall. Just the mere thought of an entity from an unknown world terrorizing people by changing into what they fear most is haunting just to think about. 
Since there are many ways in which horror is used, and the different references that are made to the time period it is set in, which is the 1950's, we can look at how these methods are effectively used, and see if there are any 50's references put in as well, such as movie references, or maybe even to different celebrities that were alive at the time. 
The document can be used to mark up any people, places, movies, or different elements of horror, such as tension, discomfort, and the ever famous jump scare.

**Comment by ebeshero** [comment]
@MarkTheShark01 This isn't an easy text to access online--*It* doesn't seem to be free. But...may I suggest a twist on this proposal? The movie scripts made of King's work, such as *The Shining* are readily available: see http://www.dailyscript.com/scripts/shining.html 

Here's the IT script: http://www.script-o-rama.com/movie_scripts/s/stephen-king-it-script-transcript.html 

There will be others... Does this suggest some possibilities?

**Comment by ebeshero** [comment]
By the way, in the next unit in the course we'll work a bit with the radio script of Orson Welles' *The War of the Worlds*: http://www.sacred-texts.com/ufo/mars/wow.htm and the plain text of H. G. Wells' 1898 War of the Worlds novel is also readily available and free of copyright issues: http://www.gutenberg.org/cache/epub/36/pg36.txt 

The readily availability of these texts might make for an interesting project...maybe? What think you? @MarkTheShark01

**Comment by quantum-satire** [comment]
I'm a huge fan of King. A lot of his _short stories_ are either free or in public domain from what I remember, it's been a few years since I read them. This may be something to consider if you want to run with this...

**Comment by jonhoranic** [comment]
@MarkTheShark01 Some of King's content can be frustratingly difficult to use or even get hold of. However he has SO MANY different works and there exist SO MANY MORE adaptions/parodies/homages that you could represent.

As a way of dodging the copyright issue, perhaps you can take a broad look at the possible connections that exist within or around his work (narrative similarities, publication information, medium of media, actor/narrator relations, etc.) to plot a system of commonalities. This is the sort of networking we can do in this part of the course! 

Now, it does not need to be EVERYTHING as that would be a project much larger then the time/work frame of our class! We could focus on a small selection, of just one work, to show the possibilities of this project and perhaps leave it open for future development!
