### ISSUE TITLE
Project Teams

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#435]
## [Rick and Morty](https://github.com/dorothealint/Rick-and-Morty)
★ @dorothealint and @quantum-satire

## [Overholt Diary](https://github.com/alexfell06/Overholt-Diary)
★ @alexfell06 and @garrettjoiner

## [Akira Manga](https://github.com/Pomilui/Akira_Page)
★ @Pomilui and @MarkTheShark01 

## [Lope de Vega](https://github.com/setriplette/golden_age)
★ @setriplette 

_Let me know if there are any corrections!_

**Comment by jonhoranic** [comment]
![proposalsspring2018](https://user-images.githubusercontent.com/21690665/35632872-dec12e08-0675-11e8-8ab5-7fa85b6902dc.jpg)

**Comment by setriplette** [comment]
Lope de Vega project: https://github.com/setriplette/golden_age

**Comment by alexfell06** [comment]
Overholt Diary project: https://github.com/alexfell06/Overholt-Diary

**Comment by Pomilui** [comment]
Akira Manga/Anime project:  https://github.com/Pomilui/Akira_Page

**Comment by dorothealint** [comment]
Rick and Morty project [](https://github.com/dorothealint/Rick-and-Morty)

**Comment by dorothealint** [comment]
Rick and Morty project https://github.com/dorothealint/Rick-and-Morty

**Comment by Pomilui** [comment]
I guess I'll add a link in the comments, too.  Akira Project:  https://github.com/Pomilui/Akira_Page
