### ISSUE TITLE
Fix Git Clone Instructions on Explain Git Shell Tutorial

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#437]
Git clone is complicated and misleading because you don't need to name a file path.  If you choose a different name than the online repo for the folder, it will create errors.

The error is in the [How to Clone an Existing Repo section](http://dh.newtfire.org/explainGitShell.html#cloning).

**Comment by RJP43** [comment]
@ebeshero I have sent a pull request with this minor edit to the newtfire web development repo. Thanks, @dorothealint !

**Comment by ebeshero** [comment]
@dorothealint I posted @RJP43 's correction! Thanks, both of you, for the speedy debugging! :-)
http://dh.newtfire.org/explainGitShell.html#repo
