### ISSUE TITLE
Regex Miniscule Steps

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#439]
Hey, all.  

   I'm stuck on the first Regex assignment.  I got to the part where I added `<p></p>` to all of the lines, but I can't figure out matching chapter titles.  I searched several combinations to bring up the beginning of the chapters in the body, but each produced no results.   Do I search `^<p>IVXLD</p>$`  or a more/less than that?   Thanks.

 -Nick #
P.S.  I think I did the `<p>` step before doing the `\t`  or `sp+` step

Edit:  PING!  
@ebeshero @jonhoranic @alexfell06 @MarkTheShark01 @dorothealint @Pomilui @garrettjoiner @quantum-satire

**Comment by ebeshero** [comment]
@Pomilui Use those tick marks around your angle-bracketed code in the markdown on this issue so it'll show up: ` `<p></p>` `

**Comment by ebeshero** [comment]
@Pomilui You want to use the square brackets to create a character set like so:
`[IVXLC]` 
Basically the square brackets are regex for "choose one of whatever is inside me". If you add a repetition indicator of some kind afterwards, you can pull up whatever you designate. Remember in class how we set the repetition indicators? They can be more specific than what you used in Relax NG schemas. For example if you want exactly 2 of something in a special character set in which the special characters could be either A, B, or C, you'd write: 
`[ABC]{2}`
And if you want 2 or more, you'd write:
`[ABC]{2,}`

**Comment by Pomilui** [comment]
Welp.  I found all but the first chapter lines using `<p>[IVX\.]{2,}`, but I'm unsure if I can replace (or just add?) what I found with the `<title></title>` tags.
 I searched the following with no results `[IVX]{2,}</p>$` 

Should I try replacing the beginning `<p>` with `<title>` then replacing the `</p>`?

**Comment by quantum-satire** [comment]
You can replace both `<p>` and `</p` at the same time! Remember the use of grouping... placing parentheses `()` around the group you'd like to keep.
