### ISSUE TITLE
No instructions for FTP Client to access NewtFire?

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#440]
Hey, all.  

  Just a heads up that I did install SSH Secure Shell, but I don't see any instructions in the Coursweb Announcements section about setting it to access web content.  See you all in class tomorrow.  

  - Nick

**Comment by ebeshero** [comment]
@Pomilui Oops! Thanks for the heads up! I need to set up everyone's web space before I make that announcement, and I should have remembered/noticed it's on deck for tonight. Thanks for setting up the SSH client and stay tuned...I'll see if I can get this set up for our crew tonight!

**Comment by ebeshero** [comment]
@Pomilui and all: I'll set up everyone's web directory access on the newtfire server tomorrow, and we'll defer this little assignment for the weekend.

**Comment by ebeshero** [comment]
Just finished setting up everyone's accounts--Let's see if everyone can access your webserver space in the morning!
