### ISSUE TITLE
Regex...am I ahead of myself?

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#442]
Yes I am.  Because I have no idea what I'm doing with this, I just know it worked.
\&(?!.*"the but not stuff")
without the quotes

I found it but can somebody tell me why it works?

Regex Ex 2
@ebeshero @jonhoranic @quantum-satire

**Comment by ebeshero** [comment]
@dorothealint I'm scratching my head and squinting at the expression here, trying something of it on the Forster Voyage file for Regex 2. I'm mystified mainly by the ampersand. When I search on that, naturally I find all the ampersands (which is exactly what I'd expect). I'm not sure what you're trying to match here? (Tell us more!)

**Comment by dorothealint** [comment]
I don't want to give away the homework if this is a solution. I submitted mine. It's the first search for the &. All are already converted but 2. If you don't write a 'but' expression, you will double replace the ones that are already converted so they will read \&amp;amp; right?

**Comment by dorothealint** [comment]
I just looked at my original post. Should read with a \\ in the front

**Comment by ebeshero** [comment]
@dorothealint There's a simpler way to find lone ampersands: search on the character followed by white space. The two in the document are actually attached to right angle bracket (`>`) characters, and while I think they probably shouldn't be there (they seem to be part of some tags we didn't fully remove), they aren't going to break the XML in their current state...

That said, I'm mystified by what turns up in hunting for `\&?!.*` turns up. When I search for *just* that, I return 25 hits, all strings that begin with an exclamation point, and I don't return any ampersands. As far as I can see the ampersand doesn't have any special meaning in regex, so it doesn't need to be escaped. I return the same 25 items when I don't use that backslash in front. The expression literally means "find zero or more &'s followed by exactly one exclamation point, and then zero or more of any character. 

Adding parenthetical grouping as you've indicated here changes the behavior of the question mark, so it would be something you search for literally: exactly one ampersand followed by exactly one question mark and exactly one exclamation point, then zero or more of any character. I don't seem to be able to get any results when I do that...I'd like to see the expression you used, but I can wait! That said, there's a simpler way to search just for unattached ampersands, and simpler is always easier to repeat later!

**Comment by dorothealint** [comment]
It brings up any \& inside a string of characters unless it is followed by amp;

**Comment by ebeshero** [comment]
Aha! Sorry I was being dense! The `.*` in the expression threw me off, and I thought I was looking at a parenthetical capturing group. I see now that you have cleverly applied the *negative lookahead* using `(?!stuff)`

**Comment by ebeshero** [comment]
@dorothealint The negative (and positive) lookahead is a pretty powerful tool! I'm glad you found your way to it. Okay, but try looking up `&(?!amp;)` by itself...same results, I think?

**Comment by ebeshero** [comment]
When you said "the but not stuff" above, I was thinking of `[^!]` which would find any character that is not an exclamation point. (sigh)

**Comment by ebeshero** [comment]
For those following this, read more about **lookahead** and **lookbehind** here: https://www.regular-expressions.info/lookaround.html  These are fun expressions to experiment with--we'll play with some in class on Monday!

**Comment by dorothealint** [comment]
Yep! Same result. Now I don't know why I put the extra in. I've always called them "but not" searches. I'm sure that's not the technical term for them in any program. Lol

**Comment by ebeshero** [comment]
It makes sense... You want to find a thing **as long as it doesn't have the stuff after the ?! in it**. One thing that is worth playing with is whether/how you can use that format with capturing groups...(you actually can)...

**Comment by ebeshero** [comment]
And by the way, there are many roads to Regex Rome. Your solution works and is impressive because you applied negative lookahead! Bravo! :-)  One thing I like about this is that you turned up those "greater than" escape characters which are attached to broken span elements. I don't know how those got there, but we scraped this document from a messy source and had to do some serious text "cleaning" to spruce it up for XML up-conversion. In real life, I'd destroy those broken span element tags. (Don't worry about it here.)

**Comment by dorothealint** [comment]
I don't think the 2 that didn't already have the amp; after them weren't followed by white space so that didn't work. Which is how I ended up here. Because if you just searched \\& and replaced, on all 48 of the others it would read \&amp;amp; after the replace and I didn't like that.

**Comment by dorothealint** [comment]
This was all before I ever converted from text to xml. So I had no idea what those would do after conversion!

**Comment by ebeshero** [comment]
Yep. Those two were `&gt;` which translates into the special escape character `>`. Those wouldn't have hurt the XML on the other side of the up-conversion, but they'd look sloppy. I'd probably replace them with nothing! :-)

**Comment by dorothealint** [comment]
Many roads to Regex Rome! :-D :-D :-D

**Comment by ebeshero** [comment]
And yes, you were right **not** to replace `&amp;` , because it is already the special legal escape for the `&` in XML.
