### ISSUE TITLE
Regex Replace

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#446]
@ebeshero @jonhoranic  @Pomilui @quantum-satire

Hey, all.

 I've capture the epilogue and that goofy **** line before it (with dot matches all) with this crazy long search:  `(^<p>[\s]{5,}[\*]{5,}</p>)/?.*^(<p>[A-Z][a-z].+?</p>)`

  What could I do to replace or add some <epilogue> tags to only the second part that I found (2nd parenthesis)?  Thanks.  

 - Nick

**Comment by ebeshero** [comment]
@Pomilui Congrats on your skillful location of the Epilogue! I'll quickly note that your use of the **character set** [ ] is going to look for **either** 5 or more \ characters **or** * asterisks: it works, but you can either write it as `[*]` OR as `\*` to get a literal asterisk and escape the regex indicator.

Now, as for your actual question: how would you replace or add tags in the second part: It looks like you've matched on **the first** paragraph in the Epilogue following the long chain of asterisks...What would you like to do with it? Do you want to wrap the Epilogue in its own section? You could probably set down a start-tag to indicate the epilogue begins there using this regex find. Do you want to replace the asterisks with an XML start-tag to mark the start of the epilogue? You could simply do something like:
`<epilogue>\2` 
to set a start tag right there, and set down your second capturing group right after it. Does that work?  For the end tag, there's nothing wrong with scrolling to the end of the document to set it in the appropriate place by hand.
What else would you like to do here?

**Comment by Pomilui** [comment]
@ebeshero I'd like to, indeed, delete the *** line and add <epilogue> tags to at least the beginning and the end of the paragraph.  I do have the ENTIRE EPILOGUE and the *** line captured.  Maybe that's over-capturing?

**Comment by ebeshero** [comment]
@Pomilui If you've captured what you're looking for, that's the key. (There are many roads to Regex Rome!) Sounds like you've got this under control?

**Comment by Pomilui** [comment]
@ebeshero I can't seem to simply add the `<epilogue>' tags at the beginning or the end.  I'm pretty much looking up ways to search, trying them and trying again 9-10 times before I get what I want, but I don't know how to add in what I want without deleting everything.  I'm far from confident in Regex :(

**Comment by ebeshero** [comment]
Hmmm. Maybe I misread what you're capturing here. Tell me if I understand right: You found the epilogue with: `(^<p>[\s]{5,}[\*]{5,}</p>)/?.*^(<p>[A-Z][a-z].+?</p>)` 

To me, that looks like you captured this structure in your **first** capturing group, right? 
```
<p>*************</p>
```
What comes after it....ahhh, I see the issue. 
You must be matching  most of the epilogue with `.*` that I see in the middle...
Then in what's currently your **second** parenthetical capturing group is getting the very last paragraph in the epilogue, right?

To **keep** the part you want (in the middle), you need a new capturing group--or just to widen your second capturing group to contain the stuff you want to keep. Use those parentheses, and then reference them in your replace. Does that make sense?

**Comment by ebeshero** [comment]
So...you began with this:
```
(^<p>[\s]{5,}[\*]{5,}</p>)/?.*^(<p>[A-Z][a-z].+?</p>)
```
Try **adjusting** that second set of parentheses like so:
```
(^<p>[\s]{5,}[\*]{5,}</p>)(/?.*^<p>[A-Z][a-z].+?</p>)
```
And then if you use 
```
<epilogue>\2</epilogue>
```
that might work out a little better! What say you? @Pomilui

**Comment by Pomilui** [comment]
![aragorn](https://user-images.githubusercontent.com/35349892/35892877-475bbf14-0ba3-11e8-8ded-f4b28a718f20.jpg)

I say, "That worked!"  It kept the <p> tags and everything.  Thanks!  Might try the rest of the play now, as that's practically all I've done so far.  I can get the "plot" parts with (<p>[A-Z][a-z].+?</p>) as it goes from Uppercase to lowercase in 2 letters.

**Comment by ebeshero** [comment]
Huzzah! and Coraggio! Go boldly on and regex your way around those boxes. Remember the "clo-pen" strategy as you go! If you find the **beginning** of a thing you find the **end** of the previous thing. And one more trick: If you **highlight** only a portion of the document, you can run regex find & replace on JUST the section in which you are searching. Notice in the Find & Replace oXygen window that you can set "Scope" on "Only selected lines". **Be careful with that**--sometimes you want to run searches over the whole document, but you may want to just isolate certain parts sometimes.
