### ISSUE TITLE
Your Webspaces and Your GitHub Repos, via Your SFTP Client

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#447]
I posted this just now on Courseweb, but decided to copy it here, too! 
*******
In class today we made sure you could access your web space on the NewtFire server, but you now need to go home and repeat the process--make sure that your server space is something you can easily find and locate later with your SFTP client (FileZilla, WinSCP, or Fetch) on each of the computers where you do your work. Just like we started out with rounds of GitHub practice, part of your **"Mindful File Management"** experience involves connecting your local GitHub directories to your SFTP clients that reach the web server. That way you can be building your website in GitHub (to work out the coding), and post the files to build your website in your server spaces on newtFire. Set up your SFTP client to save locations for each website you're working on. SO--here is what you need to set up, and the locations you need to find:

## Finding your space in the worldwide web:
1) **Your Personal Website** (just yours individually): Digital Studies students will build a personal profile here! Set your client so it saves a profile or site connection for accessing your personal GitHub repo on your local computer, and the newtFire server directory on the other:

**Local GitHub repo**: Find the filepath to it! You can do that by opening it up in your Bash Shell or Terminal, and when you reach the repository, enter pwd (for print working directory): and you'll see your filepath. Or, browse to it in your File directory. Set your client so you can save your profile.
 
**NewtFire Space**: Your web files will go inside the public_html directory. That's located on NewtFire in **/home/yourUserId/public_html**

Your personal site *could* aspire to be as fancy and cool as Ally's: <http://www.newtfire.org/~quantum-satire/> , but you could also just play around with CSS and include images and tables and various HTML structures like [this simple site with cool Alaska photos](http://www.newtfire.org/~blawrenc/) made by a recent graduate.  For Friday, you're just getting started with building things, so your site doesn't have to be beautiful yet, but try to make it functional!  NOTICE how we want you to include CSS as a separate file instead of writing it into the HTML page. That's really important--we didn't go over how to associate a `.css` file with your .html file in class, but it's just a line of code and we show you how to write it and where to place it in our CSS tutorial. 

2) **Your Project Site:** Your team can start playing with making starter pages or "placeholder" pages for now as you're starting your projects. Make a separate profile (or bookmark) in your SFTP clients to find your project space easily. Here's how to find what you need: 

**Local GitHub Repo for the Project:** (Have you joined and cloned your Project Repo on your local computer? This is a good moment to make sure you've done that. Clone it into your GitHub directory so it's a "next-door neighbor" to your clone of the DHClass-Hub and your Personal Repo, and be careful NOT to clone inside those other repos.) Get the filepath (use pwd in the shell or browse to it. 

**NewtFire Project space:** These are directories designed to be shared with a team, and they're located in a different part of the server from you personal home space. Here's how to find your project space:
**/var/www/html/newtfire/yourProjectDirectory**

## Working on your websites: It all starts with index.html
There is an **index.html** page inside your personal **home/public_html** folder, and inside your project directory folder too. Start by modifying that, but don't change its name--the index.html is a conventional filename as the root start page of a web folder. You can build other pages and write hyperlinks to link them, as you'll see on the examples sites above. (Try viewing the page source in your browser to see how these were built!) 

NOTE: Local links to files on your web server space are **relative** (that is, relative to your site): If you want to show images on your page, or you want to link to another .html page in your web space,  these **need to be transferred into the public_html space on the NewtFire server**. They could sit in the same folder on the web server, you just give the file name: `<img src="songbird.png"/>`. Or you can make an images directory to put all your images inside, and step down into it like so: `<img src="images/songbird.png"/>`. That's relative because it's made **relative** to the public_html directory on NewtFire in your webspace.
**Absolute links** go outside to other sites, and you need the full website address starting with `<a href="http://web.address.whatever/file.html"` for these to work. 

Happy site building! Remember to shout out on the DHClass-Hub issues if you get stuck!
Dr. B

**Comment by Pomilui** [comment]
Ok.  I've started working on my index.html file, but I'd like to complete the "Finding your space in the worldwide web:" section.  In FILEZILLA,  I see my folder on the newtfire server and my .ssh and public folders.  I also added bookmarks in FILEZILLA to the Nick_Page (my personal Git Repo) folder on my PC, Akira_Page folder on my PC IN GLOBAL BOOKMARKS.  

   What else do I need to do?

**Comment by ebeshero** [comment]
This is great, @Pomilui ! Now, you can start a basic workflow. Make a modification on your website, by sending a file over to newtFire in FileZilla. AND go over to your bash shell, and push your changed local file over to your GitHub repo. You'll have achieved the ideal GitHub and Web Server synchrony of the spheres!

**Comment by ebeshero** [comment]
@Pomilui You should be all set now to modify your index page on the <http://akira.newtfire.org> site! Remember to push your new files over to GitHub, which will serve as backup for your site files.
