### ISSUE TITLE
Linking CSS page

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#448]
How do you write the link to the CSS page?  I created one, I have it in the folder with the index file in the mypage git repo but where do I find how to write the line of code to link it in the index page?  I viewed the corresponding CSS but I have no idea how to "take note of how we linked our CSS with this page".

**Comment by ebeshero** [comment]
@dorothealint We're suggesting in the homework page that you "View page source" on the homework HTML page itself, so you can see the HTML `<head>` element and how it contains the link to the CSS file. On that page it looks like this: <view-source:http://dh.newtfire.org/HTMLExercise1.html>
Look inside the `<head>` element for the `<link>` element. See it?
