### ISSUE TITLE
HTML Assignment #1

### ISSUE THREAD

**Issue by alexfell06** [ebeshero/DHClass-Hub#449]
Hey everybody,

So I just read through the Explain HTML and Explain CSS guides, and I'm still pretty confused on how to actually start the HTML assignment 1. If anybody could point me in the right direction that would be great, thanks!

**Comment by Pomilui** [comment]
@alexfell06 @ebeshero @quantum-satire @jonhoranic 

 Hey, Alex.  I started by (finally) connecting to the newtfire server in Filezilla.  A start would be connecting to newtfire.org through Filezilla or whatever you're using and downloading your index.html file OR SIMPLY making a new HTML file in Oxygen and copying and pasting what Dr. B put in the "Explain HTML" page.

**Comment by ebeshero** [comment]
@alexfell06 Hi Alex--In class on Wednesday I was concentrating on making sure you could connect to your web spaces, and I didn't concentrate on actually writing the HTML and CSS files. Let's just start with a simple HTML file. I saved an `index.html` page in your personal webspace on newtFire: here: http://newtfire.org/~agf33/  
You can see that very simple page on the web, but it's being driven by HTML code. Can you use your SFTP program (FileZilla or WinSCP or whatever you're using) to download that file from your public_html folder on newtFire? You should set things up so you can download it into your personal GitHub repository space, and then make edits there. You can transfer it back to the web server with your SFTP program. You can *also* push the code to your personal GitHub repo and be able to save all of its versions. (That's the workflow we recommend as your build your personal and project sites--and you probably saw my post about that.)

Okay, so for HTML Ex 1, you pretty much need to explore how to write HTML, and for that we're giving some basic instruction in the Explain HTML guide. See if you can add things like lists and tables to the site--you'll need to look up how to write the code. You can view that code in the web browser locally as you're working, too! If you're on a PC, use CTRL + O on a web browser and browse for the HTML file on your computer to see how your edits look!  

For writing CSS, that's something you write in a separate file to control the styling--the font you want to use, background colors, etc. We use a `<link>` element up in the HTML `<head>` to attach a CSS page to an HTML page. Try some really basic things to see if you can change a background color or font--but if you're confused about CSS, we'll go over it in class tomorrow morning. Let us know where you're stuck...

**Comment by ebeshero** [comment]
@alexfell06 (and all)-- I've added a few links to my post here--hope this helps! Again, let me know where you're stuck.
