### ISSUE TITLE
Help Meee!!!!

### ISSUE THREAD

**Issue by KariWomack** [ebeshero/DHClass-Hub#45]
How do I stop the xsl from grabbing the <note> elements within the <org> elements. Also, if someone could remind me how to attach what I have so far to GitHub so you can see what Im doing, that would be great. Havent had to push files in a while, don't remember how.

**Comment by ghbondar** [comment]
It sounds like you are retrieving elements at the wrong level of `<xsl:apply-templates>` ...  without knowing exactly what you are trying, perhaps try getting those elements at either an earlier or later application of `<xsl:apply-templates>`. Also, I think you can attach/upload files just by drag-and-dropping into the web app, if not through pushing from the desktop app: [testupload.txt](https://github.com/ebeshero/DHClass-Hub/files/17283/testupload.txt)

**Comment by KariWomack** [comment]
The web app says it doesn't handle this kind of file, and I still don't know how to push from the desktop. Some instruction on that would b nice, even if for future reference.

**Comment by ebeshero** [comment]
@KariWomack Here's our instructional material on GitHub all linked in one place: [the main ReadMe on the DHClass-Hub](https://github.com/ebeshero/DHClass-Hub): Review this so you remember how to push files to GitHub. (You need to do this for project work, too, as well as some of the upcoming homework assignments, so it's important you remember how to clone, sync, and push new files to GitHub). https://github.com/ebeshero/DHClass-Hub

**Comment by ebeshero** [comment]
@KariWomack We have pushed lots of XSLT files into this GitHub over the past few days, so we know that the desktop client handles this file. Be sure to save your file with the `.xsl` file extension. I wonder if that could be the problem?

**Comment by ebeshero** [comment]
@KariWomack As to how to get XSL to select and process only what you want: think of how you're setting up your template rules: Do you need to write a new template rule(s) to process the deep descendant element content differently? Or do you think you might use the `@select` on `<xsl:apply-templates/>` to filter out the stuff you don't want to process?
