### ISSUE TITLE
XPATH EX 1 

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#451]
@ebeshero @jonhoranic @quantum-satire 

Hey, all.  I'm stuck on the 4th (last) set of questions for the 1st XPATH exercise.  

I found book 1 with `//div[@type = "book"][1]`  but I'm unsure of where to go from there.  stepping down through the children  doesn't work.  Any help would be appreciated.  Thanks.

 - Nick

**Comment by quantum-satire** [comment]
When you're stepping down to find the children, what are you typing? This looks correct so far!

**Comment by Pomilui** [comment]
I'm typing `/` but I tried `/child::placeName` with no luck

**Comment by ebeshero** [comment]
@Pomilui Those placeNames are deep descendants--probably great-grandchildren of the books...you want to leap down to those.

**Comment by Pomilui** [comment]
@ebeshero That's what I figured.  I'll try again.

**Comment by Pomilui** [comment]
@ebeshero  ah!  /descendant::placeName works.  now to count
