### ISSUE TITLE
XPATH Ex 3 Stuck Halfway

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#455]
@ebeshero @jonhoranic @quantum-satire 

  Hey, all.  I'm stuck on 2 d of this exercise:  finding the parent elements of all the attributes in the body 

`//body//attribute::*/parent::*` returns over 8000 results, but I'm pretty sure this is wrong.  I'll read through the guides again.  Any help would be appreciated.  Thanks.

  - Nick

**Comment by ebeshero** [comment]
@Pomilui Sorry for the delay! I was en route from Pittsburgh and just looking in now. Your expression works for me-- It *does* return thousands of results, but I'm getting 2651 here, not 8000. I wonder why you're seeing so many?

**Comment by ebeshero** [comment]
@Pomilui One thing of interest here is to notice the concept of a **parent** for an attribute. An attribute has no ancestors, but only has one parent, and that is the element it's sitting on. When I run the expression to find all the attributes down in the body, I see 3000 of them! But there are fewer parents, only 2651. Let's consider why: Some elements are holding multiple attributes--so there are more attributes than parents of attributes. (There will never be more parent elements than attributes.)
