### ISSUE TITLE
Project Team Switches?

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#458]
@alexfell06 @dorothealint @ebeshero @quantum-satire @jonhoranic @MarkTheShark01 

Hey, all.  Mark and I have been contemplating leaving the Akira project and joining different teams to ease the work load on all of us.  What do you all think?  Thanks.
 - Nick

**Comment by quantum-satire** [comment]
I think that Akira is a great project with a lot of potential, and shouldn't be abandoned unless it _has_ to. That's just my 5 cents, but I can understand feeling overwhelmed at this stage. If you don't think Akira is a good avenue in general, consider switching to another text or brainstorm for another project idea. This is just my opinion! Let me know if I can help any more.
