### ISSUE TITLE
Troubleshoot XSLT Exercise 3

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#46]
@nlottig94 Ok I see you pushed a [file](https://github.com/ebeshero/DHClass-Hub/blob/master/Troubleshooting/lottig_10-21_xsltExercise3.xsl) into the troubleshoot folder . You mentioned that you were getting errors. Let's walk through what you have and what you don't. First it looks like you are good with setting up your columns by writing all the necessary `<th>` elements inside of a single `<tr>` all inside of your first `<xsl:template match="/">` and you have all this sitting at the beginning of your document inside of the `<html>` tags because this is all stuff you want to happen once. Then you continue with making your first selection: `<xsl:apply-templates select="//div[@type='table']"/>` consider what all this is getting you and what the assignment is asking. You want to make sure you are  "selecting the nodes you want to process to build the table" and that the nodes you select are the ones that are binding the specific responses to the corresponding questions:
 
all of the `<what?>` that contain Questions with a possible response of Yes/No.

tell me what you have and how you might fix it to correspond with what I have hinted to here.
let's walk thru each part of your file so far step by step.

**Comment by nlottig94** [comment]
I was telling the XSLT to give me all of the elements in the `<div>` element.  I was using a greedy selection because it was too much.
I need to find the more specific XPath of: I need to grab all of the `<fs>` elements that have `<f>` elements which have `@name="response"` and `@select="no"`.  This will grab all of the yes and no questions because the yes is bound to the no.

**Comment by RJP43** [comment]
Right, so by grabbing the entire `<div>` element you are in reality selecting a lot more than what you are actually looking for... if the nodes to make the table are the ones that are bound with specific responses (as you say the No responses) then that is what you want to select! Great!

**Comment by RJP43** [comment]
And that can be a self-closing element that was a flummox in class.. doesn't really matter but for simplicity sake.

**Comment by nlottig94** [comment]
Now that I'm selecting these, I need to match on them a new row that the `<td>` elements correspond to the table headers.

**Comment by RJP43** [comment]
RIGHT!

**Comment by RJP43** [comment]
@CodyKarch look here to understand a bit more about what needs bound together and if you are still confused ping me back in your issue(#48) or here!

**Comment by nlottig94** [comment]
Closing for Spring 2016.
