### ISSUE TITLE
XQuery e

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#460]
@ebeshero @jonhoranic @quantum-satire @alexfell06 @MarkTheShark01 @dorothealint @garrettjoiner 

Hey, all.  I'm stuck on # 3 of the XQuery problem set.  So far, I tried `collection('/db/shakespeare/plays')/*/TITLE/count(distinct-values(.//PLAY//SPEAKER > 40))` which returned 3 "false" items.  

  I know that it's 1 play that has more than 40 speakers, and I'll keep trying.  Any help would be appreciated.  Thanks.  

 - Nick

Edit: I added `declare default element namespace "http://www.tei-c.org/ns/1.0";` before what I have above, and I'm getting "1" as the evaluation result.

**Comment by ebeshero** [comment]
@Pomilui Aha! The operative phrase here is the play _**that has**_ more than 40 speakers! You want to find a play, then, and you probably want to do the counting of its **descendant** speakers inside a predicate!

**Comment by ebeshero** [comment]
@Pomilui So one way to think of this is to break this into smaller pieces. First find the plays. Then find the plays that have descendant `<SPEAKER>` elements inside (that'll be all of them). Then find the plays that have a *count* of more than 40 *distinct* speakers that's greater than 40.

**Comment by Pomilui** [comment]
@ebeshero   Alright.  I'll give it another shot and report back.  Thanks.

**Comment by dorothealint** [comment]
@ebeshero I'm working on this too!  And I got my 2 false results and 1 true!  And then I'm making it way too complicated to return the title.  This probably doesn't need FLWOR functions, does it?

**Comment by quantum-satire** [comment]
@dorothealint You don't _need_ to use a FLWOR statement for # 3. You do for # 4 / # 6 though!

**Comment by Pomilui** [comment]
@quantum-satire @ebeshero @dorothealint 
Yikes!  No breakthroughs yet.

**Comment by dorothealint** [comment]
@Pomilui I got it to work with the FLWOR statements.  But I can't get it to work with a regular long xquery expression.

**Comment by dorothealint** [comment]
@Pomilui for your expression in the first comment...aren't you asking it to look only in the TITLE elements for speakers >40?  Don't know if I'm right but I think that's where it is looking to return 3 false items.  If you take that out, you get one true item...but then Idk where to go from there to get it to spit out the title rather than the true and false!

**Comment by quantum-satire** [comment]
@dorothealint What are you writing when you use the XPath statements in one expression?

**Comment by ebeshero** [comment]
@Pomilui Aha! I'm sorry I didn't notice that earlier--I was fixated on the *end* of your expression, and not the beginning! @dorothealint is absolutely right: The problem is that your expression is looking only inside the `<TITLE>` element, where there aren't any descendant speakers! Back up and make sure you're looking deep down inside the entire play!

**Comment by Pomilui** [comment]
@ebeshero @dorothealint @quantum-satire 
`collection('/db/shakespeare/plays')/*//count(distinct-values(.//PLAY//SPEAKER > 40))` returns 

1
1
1

back to the grind.  switching between subjects.

**Comment by ebeshero** [comment]
@Pomilui Your expression isn't landing on the plays. I'm not sure why you're returning the number 1 three times, but I think it's stopping on each play and getting a count of *something* that comes out to 1. Okay--we need to think about how you're writing this expression. Piece by piece:

1) You know how to get to all the plays--good. That's this part of the expression:
```
collection('/db/shakespeare/plays')/*
```
Stop a moment and contemplate this. The `/*` part is stopping on the root element of each play, and if you evaluate it, you return three plays.

Now, your job is to filter those plays and return only the play that has a count of distinct speakers greater than 40. That's tough to figure out--agreed! But first and foremost, you need to be stopping on the **play**, and filtering the plays with a predicate, like so:

```
collection('/db/shakespeare/plays')/*[get-only-this-condition]
```
Note the need for a predicate just there. Now, if the * is the root element of each play, you need to look down the descendant:: axis for speakers. Can you find the plays that have descendant speakers in them? Start there:
```
collection('/db/shakespeare/plays')/*[descendant::SPEAKER]
```
Now, work inside that predicate to figure out how to set this so you take the count of the distinct-values() of SPEAKER elements and make that greater than 40.

**Comment by ebeshero** [comment]
@dorothealint @quantum-satire and @Pomilui You don't need FLWOR statements for #4, but you can try them if you like! I notice that I have a blank #5 from when I was modifying the assignment--there is really no number 5--I have a blank `<li>` element sitting there on the assignment page. ;-). I'll leave it for now so you don't get confused by a sudden change to the assignment.
