### ISSUE TITLE
Class today

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#463]
@jonhoranic @quantum-satire Since we have no professors today it seems, and you two are in charge, I wanted to let you know that I won't be there for class today.  My dad was feeling weak this morning so I have him at the hospital for tests.

**Comment by jonhoranic** [comment]
@dorothealint No need to worry, today we have dedicated to project work, I hope things are going well!

Ally made me aware of some of the investigative paths you would wish to undertake. From what I gather your project is rolling pretty strong, but I would suggest settling on a single strong research question. It would be best to have a solid foundation that could be built upon later, as the time we have in the course is somewhat limited.

Let me know if you have any more questions about this upcoming assignment for Wednesday and/or Project Midterms.

**Comment by quantum-satire** [comment]
@dorothealint No worries. Hope your dad feels better!

Like Jon said, we should focus on one research question--I am thinking this will be tracking repetition in the scripts (ie characters repeatedly showing up, certain quirks or parts of dialogue, memes, etc.)

We can talk more about this on Wednesday!
