### ISSUE TITLE
DDoS attack on GitHub

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#467]
This article showed up in my inbox this morning, and I thought I'd share it if anyone else is interested! On the 28th, GitHub was the victim of the largest ever Denial-of-Service attack, which aims to bring down websites by overwhelming it with traffic. Apparently, GitHub is a major target for these types of attacks. You can read about the attack here:

https://www.wired.com/story/github-ddos-memcached/

**Comment by ebeshero** [comment]
And it survived with flying colors--pretty impressive! Meanwhile, this meme has been circulating on Twitter since ~2015: http://htmlpreview.github.io/?https://github.com/louim/in-case-of-fire/blob/master/in_case_of_fire_ink.svg

**Comment by jonhoranic** [comment]
@quantum-satire @ebeshero 
Oddly enough something like this would have come in handy if I was at the computer during my fire scare at the house! I would add "Plug Your Ears" to the list of steps though, those alarms are quite good at being alarms..but boy they will leave your head ringing if you gotta get those commits in!

**Comment by quantum-satire** [comment]
Can you imagine a little bell going off for every push to the class repo? Reminds me of a story I read on Cloudflare's startup--oddly fitting for the og content of this thread--they would have a bell ring every time a new customer signed up for their services. They ended up taking it down after too many customers were signing up. Haha!
