### ISSUE TITLE
XSLT 3.0 Features Not Supported in My Oxygen

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#469]
@ebeshero @MarkTheShark01 @quantum-satire @setriplette @dorothealint @garrettjoiner @alexfell06 

Hey, all.

   I got an error message saying that the stylesheet has the version 3.0, but I'm trying to transform it in XSLT 1.0.  Some XSLT 3.0 features won't be supported.  When switching to a recommended "Saxon" processor, I still get these errors:  

   "System ID: E:\Coding & Data Vis\XSLT\test.xsl
Severity: fatal
Description: method must be xml, html, or text, or a prefixed name
Start location: 8:0"

Do I need to update my Oxygen or add something from the XSLT intro to the XSL file to run it and output something?  Thanks.

 - Nick

**Comment by quantum-satire** [comment]
Are you able to include a screenshot of your screen? Seems like it may have an issue at a specific location 8:0.

**Comment by ebeshero** [comment]
@Pomilui Sounds like you're looking ahead and tinkering with XSLT--yay! How about pushing a copy of your code to the Troubleshooting directory here and we'll take a look...I suspect you may be missing the `<xsl:output method="something"/>` line, where you indicate what your output format is going to be...text, xml, xhtml...

**Comment by ebeshero** [comment]
@Pomilui Oh, wait a minute! Re-reading your message, I think I know what's wrong! Hang on a second--you need a change a setting in your oXygen, and I'll attach a couple of screenshots to show you how...

**Comment by ebeshero** [comment]
Look in the top left of your screen in the XSLT view for the box I'm highlighting here. This sets the parser for the XML processing languages in oXygen (which supports XSLT and XQuery): 

<img width="838" alt="screenshot 2018-03-15 23 06 55" src="https://user-images.githubusercontent.com/4014518/37501650-b961edbc-28a5-11e8-9c8d-8db85d10e71e.png">

Make sure yours is set to Saxon HE, PE, or EE (and really, EE is probably the best). We'll show you this in class tomorrow, but here's what you'd set:
<img width="838" alt="screenshot 2018-03-15 23 06 55" src="https://user-images.githubusercontent.com/4014518/37501742-0094bcfa-28a6-11e8-9daf-005d7c5cba18.png">

**Comment by ebeshero** [comment]
@Pomilui Sorry--let me attach that image again properly highlighted this time! 
<img width="838" alt="screenshot 2018-03-15 23 06 55" src="https://user-images.githubusercontent.com/4014518/37501826-5f28dbb6-28a6-11e8-82fb-eac7e352d430.png">
