### ISSUE TITLE
Getting unwanted output in XSLT Ex 1

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#470]
@ebeshero @quantum-satire @jonhoranic @MarkTheShark01 @alexfell06 @garrettjoiner @setriplette @dorothealint 

Hey, all.  I'm getting strange output from these template rules.  

   
```
  <xsl:template match="head//l">
        
        <xsl:apply-templates/><lb/>
        
    </xsl:template>   
```

   For all p and l elements, there are extra attributes of `part="N"`.  What could be causing this?  Thanks.

**Comment by ebeshero** [comment]
@Pomilui Aha! There's a setting we need to look at in oXygen to get rid of those pesky default attributes. In the oXygen top menu bar, go to Options --> Preferences. In the list of options on the left, 1) click the drop-down triangle next to XML, 
2) then open up the drop-down triangle for XSLT, 
3) then select Saxon-HE/PE/EE

On that screen, on the right, look for Saxon-HE/PE/EE options, and see if the checkbox next to "Expand attribute defaults" is selected. If it is, **unselect** it, and click "OK" at the bottom right.
 Then try running your XSLT transformation again-- does that get rid of those unwanted extra attributes?

**Comment by ebeshero** [comment]
@Pomilui I trimmed out some of your code so it's not unduly influential to others working on their homework... ;-)

**Comment by Pomilui** [comment]
@ebeshero   That did the trick, and I also was suddenly conscious of what I posted.  Thanks.

**Comment by ebeshero** [comment]
@Pomilui HINT: I expect your templates for books and chapters are likely not matching...take a closer look at how books and chapters are encoded in the source XML! :-)
