### ISSUE TITLE
Akira XSLT-to-HTML and ID Transform Examples

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#471]
I've pushed the examples we were working on in class on Monday 3/19 here to DHClass-Hub just now with [this commit](https://github.com/ebeshero/DHClass-Hub/commit/b10ae498d28e937ce56d0d98c5a45ad18bec70ac). You'll want to pull this in to study it as you're working on the homework XSLT. Look in Class Examples --> XSLT, and the Akira examples are in their own directory!

Here's the XSLT to HTML:
https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/Akira_Examples/Akira_to_HTML.xsl

@dorothealint @alexfell06 @Pomilui @MarkTheShark01 @garrettjoiner @quantum-satire @jonhoranic @setriplette

**Comment by dorothealint** [comment]
@ebeshero  THANK YOU! I just came here to cry because I started trying to do it from the assignment instructions and my very bad notes with tangled and not finished tags.  I uploaded what I did without this to the homework link in courseweb before I came here because it wasn't coming out right and I didn't want to give away the assignment by putting the code here.  But now I think I can see where I was going wrong and fix that much!

**Comment by Pomilui** [comment]
@ebeshero Well.  I'm just scrambling here.  I've been looking at this assignment, I'm undecided on what I want to transform and what I want to show.  I'll probably need tomorrow to turn in something close to the solution.

**Comment by ebeshero** [comment]
@dorothealint @Pomilui @alexfell06 If you submitted XSLT 1, I have written each of you some comments and returned your graded file, and that may help you as you are working on this. The first XSLT to HTML transformation is always challenging! Try simple things first that are like the little things we changed on the Identity Transformation XSLT....

**Comment by ebeshero** [comment]
@jonhoranic Take a peek at the incoming XSLT on Courseweb before class this AM so you can see where/how people got stuck.

**Comment by ebeshero** [comment]
All--I was just closing a bunch of old GitHub issues, and thought I'd send a ping from this one so it "surfaces" at the top in case you're getting notifications by e-mail.
