### ISSUE TITLE
Our DH Project Presentations in Oakland, Friday April 20 @ 9:30am

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#472]
@Pomilui @garrettjoiner @alexfell06 @jonhoranic @quantum-satire @dorothealint @MarkTheShark01 Here's an open issue on our Project Presentations, now slated for Friday April 20. Because there will be 7 project teams (between us and the Oakland DH course), we'd like to start at 9:30am to end by 10:50am. That should give you all plenty of time to return to Greensburg for afternoon classes. Will this work for us? Please respond here! Oh, they'll serve us coffee and doughnuts for breakfast, too!

**Comment by Pomilui** [comment]
I'm pretty sure that I'll be able to attend, since my last class won't be until 2:00.

**Comment by ebeshero** [comment]
Others in class today, from each of our three projects, indicated they'll attend!
