### ISSUE TITLE
Class Today and Inclement Weather [03-21]

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#473]
Hey All! 

@jonhoranic and I have been discussing possibly not meeting for class today because of the dangers of the roads. We wanted to get your input, as most of you are commuters and may struggle to get through the snow. We know you're also having troubles with the XSLT homework, but we could try to have an online discussion instead unless you feel that it would be for the best to meet today.

Thoughts?

**Comment by garrettjoiner** [comment]
As someone with a front wheel drive car that got stuck trying to get to class this morning for my 9 o'clock class that ended up being cancelled anyway. I would advise anyone who has not left yet to stay home these roads are horrible.

________________________________________

**Comment by Pomilui** [comment]
@quantum-satire @ebeshero @garrettjoiner @alexfell06 @MarkTheShark01 @dorothealint @setriplette @jonhoranic   I'm about ready to head out for our class.  I'll take my time, and see how it goes.  My other classes for the day are still on.  No biggie either way.

**Comment by dorothealint** [comment]
I'm here. My first class was cancelled but I got nothing on my 9:30 class...so got here 10 minutes late due to having to reroute for accidents and no one is in the room so apparently it is cancelled.  So should I stay or go home?  Are either one of you here?  Because if you're not I'd advise you to cancel for your safety and stay home!  If you're here and anybody wants to meet I have no problem staying.

**Comment by quantum-satire** [comment]
Jon is going to be in the classroom at regular time to help with anyone who is already there; I'll be online here to help if I can, but won't be able to make it to campus.

**Comment by alexfell06** [comment]
I won’t be able to make it to class today because of the conditions, the area around where I am at is barely plowed.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
