### ISSUE TITLE
Declarative programming: what you're doing with XQuery and XSLT

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#474]
For the IT students among us and those curious, here's a short piece about the specific kind of programming we're doing. The writing of XSLT and XQuery isn't quite like what you do in other programming languages like Java, which are called *imperative* programming languages, but what we're working with is *declarative programming*...read more about it:

https://tylermcginnis.com/imperative-vs-declarative-programming/

@Pomilui , this is the same link I plopped in my response to your XSLT Ex 1.

**Comment by Pomilui** [comment]
Those side-by-side code language comparisons help put things into perspective.
