### ISSUE TITLE
SVG Exercise 1

### ISSUE THREAD

**Issue by MarkTheShark01** [ebeshero/DHClass-Hub#478]
I've uploaded SVG 1, so when you get a chance, you can grade it

**Comment by ebeshero** [comment]
Thanks, @MarkTheShark01 ! 👍

**Comment by ebeshero** [comment]
@MarkTheShark01 All the SVG 1's are graded and returned: Find your graded file with comments in your privately shared Box file space for DH file returns. https://pitt.box.com/s/6j7nwfknf8creciskipqxjooulhiy9m5 (This link works only for you.)
