### ISSUE TITLE
JavaScript with mouseOver Function

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#481]
I'm working on the R&M project banner attempting to have a mouseover effect that will change the color of the text underneath the icons. Here is what I have so far (with init() function included to show the JS _is_ working):
```
window.addEventListener('DOMContentLoaded',init,false);
            
function init() {
    alert('The page loaded!');
}

document.getElementByClassName("p-for-banner").addEventListener("mouseover", mouseOver);

function mouseOver() {
    document.getElementByClassName("p-for-banner").style.color = "red";
}

```
And the HTML:
```
<div class="flex-container">
        <a href="index.html"><img class="banner" src="images/titlelogo.png" /></a>
        <div class="img-with-text"><a href="transcripts.html"><img class="bannerIcons" src="images/box.png" /></a><p class="p-for-banner">Transcripts</p></div>
        <div class="img-with-text"><a href="timeline.html"><img class="bannerIcons" src="images/portal.png" /></a><p class="p-for-banner">Culture Refs</p></div>
        <div class="img-with-text"><img class="bannerIcons" src="images/meeseeks.png" /><p class="p-for-banner">Results</p></div>
        <div class="img-with-text"><img class="bannerIcons" src="images/pickle.png" /><p class="p-for-banner">About</p></div>
        <div class="img-with-text"><img class="bannerIcons" src="images/placeholder2.png" /><p></p></div>
    </div>
```
Here is a screenshot of the text I'm working on:
![screen shot 2018-04-06 at 4 46 51 pm](https://user-images.githubusercontent.com/28074589/38443576-29b8bee0-39ba-11e8-9b4d-489420a65dcf.png)

Any ideas on what (probably obvious) thing I'm missing here?

**Comment by ebeshero** [comment]
@quantum-satire Aha! The console log in the web browser helped me to spot the error here. You have a typo in the line setting up your event listener for the mouseover:

As the console log properly tells me: `document.getElementByClassName is not a function`
This function is understood to be plural (unlike getElementById), so you set it as `getElementsByClassName` 

Does that fix it?

**Comment by ebeshero** [comment]
@quantum-satire If you push it to your project repo (I don't see it there right now?) I can add some line comments...

**Comment by ebeshero** [comment]
@quantum-satire The other issue here is that you have to deal with MULTIPLE elements, which you means you need JavaScript's for-loop to loop over each element you've selected and alter it. We'll go over this in class tomorrow, but I bet you can look this up.

**Comment by quantum-satire** [comment]
@ebeshero I've fixed the spelling error and uploaded the files [here](https://github.com/dorothealint/Rick-and-Morty/tree/master/websiteFiles)!

**Comment by ebeshero** [comment]
@quantum-satire I wrote [some line comments on your commit](https://github.com/dorothealint/Rick-and-Morty/commit/fa93edd260f444f05767b2fb21e9d4f85a0b166f) a while ago, but I'm not sure whether you saw them?

**Comment by quantum-satire** [comment]
@ebeshero I've been working with the line comments & Obdurodon's "JavaScript piece by piece" page for about two hours, but became frustrated. Made _some_ progress in the end with JS, but remembered everyone's favourite language had its own `:hover` function.

I ultimately decided to write the code in CSS, which is... immensely easier than JS for this purpose:
```
p.p-for-banner:hover,
p.p-for-banner:active{
    color: #5ec049;
}
```
This solution works perfectly for the site. I'm going to incorporate the "on mouseover" JS function into the timeline though, because I am seeing the (virtually) same use with a hover or click function over the circles to bring up a box of information.

I think I'm going to be the only person that _enjoys_ CSS...

**Comment by ebeshero** [comment]
@quantum-satire Well, you'll see the JavaScript solution in class tomorrow, or have a preview tonight in the JavaScript class examples for colorChange.
