### ISSUE TITLE
T-Shirts: Colors and Sizes Please!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#483]
**It's time to do our class T-shirt orders!**  Here is the [proof](https://cloud.githubusercontent.com/assets/4014518/11314432/822bb9c8-8fb3-11e5-9803-1e8607100160.jpg) .

Notes about the t-shirts:
a) Ink is applied to the fabric (so there's nothing plastic-y in the application).
b) We can order these in any combination of the available T-shirt colors (so they don't all have to be the same color):
c) The design would work on four different T-shirt colors, and those colors have official names that I need to ask about, but for our purposes, let's call them in order from left to right in the proof image:

**gold, grey, natural, and green**
(Yes, that counts as an array of colors, and if we were counting in JavaScript we'd call that 0) gold, 1) grey, 2) natural, and 3) green. ;-)

**Please provide your preferred size and color in this issue.**

**Comment by alexfell06** [comment]
Color: Natural
Size: Medium

**Comment by quantum-satire** [comment]
Color: Green
Size: Large

**Comment by ebeshero** [comment]
@MarkTheShark01 : Medium, grey

**Comment by Pomilui** [comment]
Color:  Gold
Size:  XXL

**Comment by ebeshero** [comment]
@garrettjoiner What T-shirt do you want? I'm going to guesstimate for you (for the purposes of ordering) Grey Large?

**Comment by ebeshero** [comment]
Everyone--here's an updated proof with the new lettering for our class this spring:

![sp18tshirtproof](https://user-images.githubusercontent.com/4014518/38518924-4e2b629c-3c0c-11e8-88dc-5637b7e7bdb1.png)

**Comment by ebeshero** [comment]
@garrettjoiner I went ahead and ordered a Large Grey for you-- it tends to look good on everyone, I think--the reds pop on it. Hope I guesstimated the size right...Let me know ASAP if you want to change that!
