### ISSUE TITLE
T-Shirt: Akira Network on the Back? 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#486]
Team Akira has produced a polished network graph for use on this spring's T-shirts, so that their design would go on the back of our newtfire shirts. View the design here ( it's on a transparent background):

https://github.com/Pomilui/Akira_Page/blob/master/Cytoscape%20Files/AkiraNet_Transp.png

I need to know from each of you: 
1) Would you like the Akira Network on the back of your T-shirt? Yes or no!
2) Since this costs extra to print, would you be willing to chip in $6 - $10 to help me cover the cost of our shirts?

@quantum-satire @Pomilui @MarkTheShark01 @dorothealint @garrettjoiner @alexfell06

**Comment by ebeshero** [comment]
Here's the proof of the back for our shirts: 
![newtfiretshirt_akiraback](https://user-images.githubusercontent.com/4014518/38618691-654072d0-3d68-11e8-8e1d-83a3484f5232.jpg)

**Comment by ebeshero** [comment]
Jon Horanic: Medium Grey
Garrett : CHANGE to Medium Grey

**Comment by quantum-satire** [comment]
@ebeshero May I change my t-shirt color to grey as well if still possible? If it's a hassle, no biggie!
