### ISSUE TITLE
Carpooling to Pittsburgh for Friday?

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#492]
Does everyone have a way to the Cathedral of Learning on Friday April 20? Who needs a ride? Who's picking up whom? Discuss!

**Comment by Pomilui** [comment]
@ebeshero @MarkTheShark01 @jonhoranic @quantum-satire @alexfell06 @garrettjoiner @dorothealint 

Mark and I are planning on meeting by the Bobcat statue at 8:00. am.  Hopefully, the traffic won't be too bad.  I'll be driving, and my car can fit 3 more (semi-comfortably).

**Comment by quantum-satire** [comment]
@Pomilui I'll be tagging along with you! See you on Friday :)

**Comment by ebeshero** [comment]
@ghbondar and I will pick up @dorothealint by the Bobcat at 8. :-)

**Comment by ebeshero** [comment]
CORRECTION: @dorothealint ! We want to pick you up at 7:45 to beat rush hour and get there in good time for coffee and doughnuts.

**Comment by thechum12** [comment]
@MarkTheShark01 @quantum-satire 

  Hey, Akira team.  Let's also update our meeting time to 7:45 as 8:00 would cut it too close.

**Comment by Pomilui** [comment]
@quantum-satire @MarkTheShark01 
  
Hey, Akira team.  Let's also meet at 7:45 as 8:00 would cut it too close.  Thanks.  

 - Nick
