### ISSUE TITLE
Halp my image wont shrink or go where I want it to!

### ISSUE THREAD

**Issue by garrettjoiner** [ebeshero/DHClass-Hub#493]
Here is my CSS.

html{

   margin: 0px;
    padding: 0px;
    
    background-repeat: repeat;
    background-size: 100%;
    }
    
body{
    font-family: "times new roman";
    color: black;
    width:100%;
    margin: 0px;
    padding: 0px;
}

h1{
    font-size: 70px;
    text-align: center;
    font-family: "Times new roman";
    color:black;
}

div.header{
    font-size: 20px;
    font-family: "times new roman";
    text-align: center;
    color: black;
    padding: 10px;
}

hr {
    border-color: black;
    border-width: 10px;
    border-style: solid;
}

.header{
    overflow: hidden;
    background-color: black;
}

.header a{
    float: none;
    color: black;
    text-align: center;
    padding: 15px;
    text-decoration: none;
    font-size: 25px;
}

.header a:hover{
    background-color: white;
    color: black;
}

.header a.active{
    background-color: white;
    color: black;
}

a{
    color: black;
}

a:hover{
    color: white;
}

a:active{
    color: white;
}

h2{
    font-size: 25px;
    text-align: left;
}

p{
    font-size: 16px;
}

div.img{
    float: right;
    width: 40%;
    padding-left: 5%;
    padding-right: 5%;
    margin-top: 2%;
    margin-bottom: 2%;
}
img[id]{
    width: 100%;
    border-width: 5px;
    border-style: solid;
    border-color: black;
}

div.main{
    font-family: "times new roman";
    font-size: 16px;
    color: black;
    padding-left: 5%;
    padding-right: 5%;
    padding-top: 1%;
    padding-bottom: 1%;
    width: 30%;
    margin-left: 5%;
    margin-top: 2%;
    margin-bottom: 2%;
    float: left;
    background: white;
    border-width: 5px;
    border-style: solid;
    border-color: black;
}

div.main2{
    font-family: "times new roman";
    color: black;
    padding-left: 5%;
    padding-right: 5%;
    padding-top: 1%;
    padding-bottom: 1%;
    width: 30%;
    margin-left: 5%;
    margin-top: 2%;
    margin-bottom: 2%;
    float: left;
    background: white;
    border-width: 5px;
    border-style: solid;
    border-color: black;
    }

h3{
    text-indent: 10px;
    font-size: 30px;
}

flex-container{
    display:flex; justify-content:space-around; align-items:flex-start; flex-direction:row;
    max-width: 960px;
    
}

img#Karl{
    height:100px;
    width: 100px;
}

Here is my HTML
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    

    <div class="flex-container"><div class="main">
        <h3> <p>West Overton was a small Mennonite community located in Westmoreland County, Pennsylvania
            that today is the location of <ref target="https://www.westovertonvillage.org/">West
                Overton Village and Museums</ref>, a museum displaying the history and
            accomplishments of the people who lived there. The first family to settle in this
            village where the Overholts led by Henry Kolb Overholt. They were a Mennonite family of
            German-Swiss heritage and Anabaptist religious roots. Henry Kolb's son Abraham began
            distilling and selling whiskey in the early nineteenth century, resulting in the
            Overholts becoming very wealthy. The focus of this project is a diary written by Karl
            Frick Overholt, one of the great-grandsons of Abraham Overholt. The contents of this
            diary include family stories, ancestry trees, diagrams, and newspaper clippings, among
            other things, making it an invaluable resource to the museum and interesting to analyze.
        </p></h3>
        
    </div>
        <div class="img"><img id="Karl" src="Karl_Frick_Overholt.jpg"/>   
    </div>
    
    

</html>
...
Here is my link http://overholt.newtfire.org/index.html

**Comment by garrettjoiner** [comment]
FORGET IT I GOT IT WOooO

**Comment by ebeshero** [comment]
@garrettjoiner It looks a lot better now! By the way, I just made a couple of spot repairs to your OVERHOLT.css to deal with that white on white text problem in the links, and make sure the SSI is right (it needed to point into the CSS directory on the website.) 

Take a look at the color of links in the body on [the diary thumbnails page](http://overholt.newtfire.org/Diary_Intro.html) and see what you think. (Before it was white-on-white.)

**Comment by ebeshero** [comment]
@garrettjoiner @alexfell06 Be sure to do a `git pull`: I noticed your thumbnail pix aren't up in the right order (and I know how it happened--it was the way we copied the filenames from the terminal). I think we can fix that--I'll send in a commit with the repair.

**Comment by garrettjoiner** [comment]
Working on the About page having trouble getting the picture to be to the left of the text.
http://overholt.newtfire.org/AboutPage.html
will do a get push as well
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    
    
    
    <div class="main2">
        <h2 class="about">MEET THE TEAM</h2>
        <div class="person">
            <h3>ALEX FELL</h3>
            <p class="about">Alex is a History and Public Policy major at the University of 
                Pittsburgh at Greensburg. He currently works at West Overton Village and 
                Museums, which is where the idea of the Karl Frick Overholt Diary project is from.</p>
        </div>
        <div class="flex-container> <div class="person">
            <h3>GARRETT JOINER</h3>
            <div class="img"><img id="Garrett" src="Garrett.jpg"/>
            <p class="about">Garrett is a Junior at the University of Pittsburgh at Greensburg.
                He is a history major as well he is pursuing a Digital Studies Certificate.
            </p>
        </div>
    </div>
</html>

**Comment by ebeshero** [comment]
@garrettjoiner Before we take a closer look--try this: While you're styling, **don't** set the SSI yet, but paste in the code that's in the SSI so you have the entire document all together locally. When you've got the styling figured out, remove that boilerplate code and re-set your SSI. This way you can work locally with the full page available. (Just don't change the styling of things that are in the SSI.)

**Comment by ebeshero** [comment]
@garrettjoiner That said, now that I look at it, the part with the SSI isn't the issue, so you're probably okay with leaving it there!

**Comment by ebeshero** [comment]
@garrettjoiner Here's what I see: You currently have a `<div class="img">` that holds both your `<img>` and your `<p>` element. In the CSS, do you have something to make those sit side by side? In your CSS, I would make your `div.img` be a flex container (give it the `display:flex property`, and give it a `flex-direction:row;` to align the items in a row. 

It's perfectly okay if this is a new flex-container inside your other flex container! You also don't need to rename any of your attributes--just make the div.img be flexible.

**Comment by garrettjoiner** [comment]
I have the code pushed into the Overholt directory

**Comment by ebeshero** [comment]
@garrettjoiner A couple of issues: 
1) The flex looks good, but above it, flex doesn't play with float. Also, doesn't this `div.img` simply *contain* the image and the paragraph? It's your parent div (a container) so you don't want it to be right-aligned--you want the image inside it to be on the right.  Anyway, I think if you're using flex *above* this (with your flex container), it's best to keep using it the whole way down. I'd remove the float. 

2) Be careful with how you're naming and identifying your divs, because if you're using the same CSS for both the index and the about page, you don't want to change the way you're handling the Overholt image on the index page!

**Comment by garrettjoiner** [comment]
http://overholt.newtfire.org/AboutPage.html

Okay, its looking better I changed it and made a new div class in my CSS
div.imgabout{
    
    display:flex property;
    flex-direction:row;
}

**Comment by garrettjoiner** [comment]
@alexfell06 could I get picture of you to put on the website?
