### ISSUE TITLE
Adding DHClass-Hub Collaborators 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#496]
Add your new GitHub usernames here so I can invite you to join the DHClass-Hub!

**Comment by ebeshero** [comment]
Hi everyone! I'm ebeshero! please add me to the DHClass-Hub!

**Comment by JustinCampbell9** [comment]
I'm Justin Campbell. Please add me to the DHClass-Hub.

**Comment by awoods25** [comment]
I'm Alec Woods. Please add me to the DHClass-Hub

**Comment by emb184** [comment]
I'm Emily Buckel, please add me to the DHClass-Hub!

**Comment by RLG95** [comment]
I'm Rachel Garstecki. Please add me to the DHClass-Hub.

**Comment by alexlavelle** [comment]
I'm Alex Lavelle, Please add me to DHClass-Hub

**Comment by bman8932** [comment]
I'm Ben McCoy. Please add me to DHClass-Hub.

**Comment by KSD32** [comment]
I'm Kiara DeVore. Please add me to DHClass-Hub.

**Comment by bnm29** [comment]
I'm Brooke Moon. Please add me to DHClass-Hub.

**Comment by BMT45** [comment]
I'm Brad Thomas.  Please add me to DHClass-Hub

**Comment by alnopa9** [comment]
I'm Alyssa Argento. Please add me to DHClass-Hub.

**Comment by mah319** [comment]
I'm Meghan Harris. Please add me to DHClass-Hub.

**Comment by Julegirl** [comment]
I'm Julie Moeslein. Please add me to DhClass-Hub.
