### ISSUE TITLE
GitHub and Mac 

### ISSUE THREAD

**Issue by KSD32** [ebeshero/DHClass-Hub#498]
I'm having some issues with the Github app on my Mac. I have been able to download it, however I am unable to use the terminal commands given. Do you have any suggestions?

**Comment by ebeshero** [comment]
Hi @KSD32 -- Let's see if we can figure it out. First, did you find the Terminal application? If you go to your Launchpad and type "Terminal", it'll come up. What happens if you type this at the Terminal prompt?

```

git --version
```
Tell me what message you see when you try that.

**Comment by ebeshero** [comment]
Also, this sleepy prof might not be awake much longer, so if I stop replying I've fallen asleep and will be back online probably around 8 or 9am...Bring your laptop to class and we can figure it out if someone else isn't able to help overnight!

**Comment by ebeshero** [comment]
Glad we got this working! :-)
