### ISSUE TITLE
XSLT Exercise 4 Stylesheet Head

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#50]
In the assignment we state "Because this document is not in a namespace, you should not add the @xpath-default-namespace attribute, and we do not need to alter `<oXygen>`'s default XSLT stylesheet template at all this time." To be more clear you actually do have to alter the template slightly by adding the output line so that you get html. I guess that was just something we implied in class when we are making a transformation into an html versus just an identity transformation into xml. 

In other words copy and paste what is below into the top of your stylesheet:
   
`<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" indent="yes" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"/>`

@amielnicki @spadafour @blawrence719 @CodyKarch @rCarls @nlottig94 @brookestewart @KariWomack

**Comment by RJP43** [comment]
Also I think we insinuated in class that you will be using Attribute Value Templates in this assignment, but you can actually get around using them by instead setting a very specific **match** that sets the `@category` of the `<workingConditions>` element equal to the `@id` associated with the `<workingCondition>` element with each specific `@tone` attribute sitting in the table at the beginning of the source document. So then you can output a template rule for each kind of tone (good, bad, neutral) instead for each `@category`

your match might look something like this:

`<xsl:template match="XPath leading you to the attribute [@category=XPath leading you to the attribute[@tone='good'] / @id]">
        <span class="good">
            <xsl:apply-templates/>
        </span>
    </xsl:template>`

We didn't exactly cover this in class so that is why I am writing it here. There are certainly other ways to do and that is fine if you are able to style all of the `<workingConditions>` your way without making the type of match mentioned above. Also using AVT in any way on this assignment will prep you for upcoming Exercise 5, 6, and 7 soooooo feel free to do so and to read up on them.

**Comment by ebeshero** [comment]
@RJP43 greetings from Lyon! if you want to make the output be most compatible with newtfire, set your HTML output line as we have been doing on the other XSLT assignments, thus:

`<xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>`

**Comment by ebeshero** [comment]
I will add this to the assignment sheet now!

**Comment by nlottig94** [comment]
Closing for Spring 2016.
