### ISSUE TITLE
Git Exercise 2: Whom to Invite to Your Personal Repo

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#501]
[Git Exercise 2](http://dh.newtfire.org/GitExercise2.html) asks you to invite the instructors to collaborate with your on your personal repository. To invite us, you'll need our GitHub names, so here we are:

* Prof. Gregory Bondar:  @ghbondar 
* Prof. Elisa Beshero-Bondar: @ebeshero
* Jon Horanic: @jonhoranic 
* Allyson Hall: @quantum-satire 
* Dorothea Lint: @dorothealint 

Invite us all! You can use your personal repository in any way you like, to keep practicing with GitHub or to develop your own projects. In about 2 or 3 weeks, you'll be building a little website for yourself on newtfire.org, and we recommend storing your website files in your personal GitHub repository. 

Last spring one of our most active students, Nick Pcsolar (@Pomilui), was really keen to get used to GitHub, so he pushed a practice file to DHClass-Hub and his personal repository every day for several weeks! It gave us something fun to pull in every day, and was great practice for the whole group--we hope we'll do the same this year, too! 

Remember, It's always best to start on a **shared** repo like DHClass-Hub with:

```
git pull
```
*Always pull before you push!*
Then, when you make changes in your local repository:
```
git add .     (don't forget the dot or period. Or use git add -A, they mean the same thing)
git commit -m "Write a commit message here!"
git push
```

**Comment by ebeshero** [comment]
Oops--I misrepresented my own GitHub username (I am really @ebeshero ), so I was able to get in an edit my message and fix it. When you start writing GitHub issues, notice that you can click the three dots on the side of the Issues panel to get in and edit, so you can add and change stuff.

**Comment by ghbondar** [comment]
Please create your repo, and invite your instructors! :)
@bman8932 @Julegirl  @JustinCampbell9
