### ISSUE TITLE
MAC terminal 

### ISSUE THREAD

**Issue by KSD32** [ebeshero/DHClass-Hub#504]
Hi! I'm still have trouble with pulling with mac terminal. When I do it, the terminal states that it has pulled from GitHub, however when I look nothing new has been added to the files I already had. Any advice?

**Comment by quantum-satire** [comment]
Hi @KSD32 ! Are you able to take a screenshot of the terminal and upload it into a comment here? You can drag and drop the image and it should automatically upload! :)

**Comment by quantum-satire** [comment]
Looks like you already have the most recent version of the repository! Here's what I'll do: I'll push a file into the sandbox and you can try pulling that change in locally. That way you can see the difference in status messages between pulling in a change and already having the most recent commit.

**Comment by KSD32** [comment]
I know it says its up to date. But still nothing as changed.

**Comment by KSD32** [comment]
Okay. Let me try.

**Comment by KSD32** [comment]
![screen shot 2018-09-03 at 8 32 38 pm](https://user-images.githubusercontent.com/42811975/45004195-9a28ab80-afb8-11e8-9a62-5253d8f88caa.png)

This is what I got.

**Comment by KSD32** [comment]
But nothing new on the DHClass file in my documents

**Comment by quantum-satire** [comment]
Looks like you did in fact pull in the image--so it's working from the Terminal. Are you sure you're opening the repo locally in the correct location? It looks like you've saved the repo in your Users folder here. Could you have cloned a second copy of the repo somewhere else on your computer? (i.e. you cloned it to the Desktop and opened it from there)

**Comment by KSD32** [comment]
I looked around and found that I have multiple DH Class folders, and one of them has files pulled in from Github.

**Comment by quantum-satire** [comment]
Aha! It might be best to save only one version of the repo (perhaps inside of a designated GitHub folder inside of your Documents folder--this is where many of us save ours).

**Comment by KSD32** [comment]
okay!
