### ISSUE TITLE
Relax NG exercise 1 confusion

### ISSUE THREAD

**Issue by emb184** [ebeshero/DHClass-Hub#508]
I've tried everything I can think of to make my schema well formed, but it isn't working. I'm left with an error that says "group of 'string' or 'data' element." Does anyone know what this means?

**Comment by ghbondar** [comment]
Notice there is a button to post code which looks like this<>------here^^^
`letter_2 = element letter_2 { date+, location+, pb+, greek_reference, money, person+ }
greek_reference = attribute greek_reference { text }
money = attribute money { xsd:integer, text }`

**Comment by ebeshero** [comment]
I just fixed it! :-)
The little `<>` button basically inserts 3 "tic" marks above and below your code and formats it. 
Greetings from Tokyo, by the way! It's 3:30am here, but jet lag is making me think it's the middle of the day still! :-)

**Comment by quantum-satire** [comment]
@emb184 Are you able to take a screenshot of your oXygen window including both the schema and the XML document? You can see how to split-screen the program [here](https://github.com/ebeshero/DHClass-Hub/issues/507).
You may be receiving the error right now because you haven't defined all of the elements and attributes yet.

**Comment by ebeshero** [comment]
@emb184 Two things: 
1) Your schema won't be well formed until you have accounted for every element and attribute label you have listed in it. (So you will need to define what a `date` is, what `location` is, and what `pb` is.) 
2) Your specific error I think is about the attribute money. An attribute can only contain *one* thing, its value. Here you have given it *two* things, and that I believe is why you see an error.

**Comment by ebeshero** [comment]
@quantum-satire  I don't think she needs to produce a screen shot. The description of the error message is good, and we don't need screen shots for every error.

**Comment by ebeshero** [comment]
By the way, there are two ways of formatting code in markdown here: one is inline (the way @ghbondar 's post looks), and one is as a block. The only difference is the number and position of tick marks that go around it. If you paste in your code, and highlight the block, and click the `<>` button, you get three ticks above and below, and it comes out like this:

```
letter_2 = element letter_2 { date+, location+, pb+, greek_reference, money, person+ }
greek_reference = attribute greek_reference { text }
money = attribute money { xsd:integer, text }
```

If you hit the `<>` first, and paste your code inside the tick marks, you only get *one* tick mark on each side, and that doesn't capture your white spaces and line breaks, making it harder to read.

And welcome to our first coding issue--yay! :-) We're off to a great start.

**Comment by emb184** [comment]
That makes a lot of sense. Thank you!
