### ISSUE TITLE
Discussion: Where Might We Go from Here?

### ISSUE THREAD

**Issue by ghbondar** [ebeshero/DHClass-Hub#510]
**Discussion Post on GitHub Issues: Where Might We Go from Here?** Comment on one of the following listed project sites under development. Describe (in your own words) at least one significant topic it seems to be exploring, and reflect on what research the developers might want to investigate next,  and/or what ideas it inspires for new projects.
[The Eldritch Project](http://eldritch.newtfire.org/)
[The Lope de Vega Project](http://lope.newtfire.org/)
[Victorian Ghost Stories](http://ghost.obdurodon.org/)
[The Nonsensical Seuss](http://seuss.obdurodon.org/index.xhtml)

_Those of us (instructors and returning students) who have been involved in these projects should help introduce them to our class and point out things that need work._

**Comment by BMT45** [comment]
The project site I looked over was The Eldritch Project.  The topic of the site was to analyze three of H.P. Lovecraft's work such as At the Mountains of Madness, The Shadow over Innsmouth, and The Call of Cthulu.    The site shows excerpts from these books and analyzes these texts for the viewer of the site.  The authors of the site can go onto adding more works from H.P. Lovecraft to add more information to the site and then analyze them for the reader.  They could also leave summaries of the texts and put them under a separate tab.

**Comment by RLG95** [comment]
The site I looked at was the Victorian Ghost Stories website. The site was based around analyzing female authors use of language to build suspense. There were five stories chosen and the placement of words and vocabulary was analyzed. Overall I think more stories need to be analyzed, and then I think next they should analyze male authors and compare the results to see if they differ or if they are similar.

**Comment by KSD32** [comment]
The site I looked at was the Lope de Vega Project. This site was examining a selection of texts written by the Spanish playwright Félix Lope de Vega y Carpio. Within the research done for the project, there are 5 plays, 5 prose (one of which is translated into English), an identification of people mentioned, a detailed and interactive map of places mentioned. The main purpose of this site is to identify and compare references to gender, geography, the body, family, emotion, money, honor, as well as the names of historical and fictional people in several different plays drawn from a variety of sub-genres. In all, the site is well established and detailed, however, I would only suggest more plays and prose to compare.

**Comment by bnm29** [comment]
The Victorian Ghost Stories mentions one major component, which is methodology. The website was created to linguistically analyze stories of ghosts written/told by female authors. Some background information, an analysis, and an overall conclusion is clearly stated at the top of the page that a person can click on to directly be sent where they were hoping to go.

**Comment by alexlavelle** [comment]
I looked at the Victorian Ghost Stories site.  The site provides an interesting graph that analyses the about of "scary words per story," categorizing them by story, and scaling the scariness of the words themselves. This site has interesting content and i find it entertaining to explore.
