### ISSUE TITLE
Confusion on Relax NG assignment 2

### ISSUE THREAD

**Issue by Julegirl** [ebeshero/DHClass-Hub#512]
Alright, so my schema is good, but my XML is still raising a couple of red flags. For two of my elements, it says that it's not allowed there and it wants me to replace it with another element I already used. What do I do?

**Comment by Julegirl** [comment]
Disregard this post. I figured it out.

**Comment by ebeshero** [comment]
Huzzah! Sometimes the act of writing up the problem leads you to a way to solve it.  👍
