### ISSUE TITLE
RelaxNG excerise 3

### ISSUE THREAD

**Issue by emb184** [ebeshero/DHClass-Hub#513]
Hey guys, I'm getting a syntax error and I'm not sure what I've done wrong. I could probably find it in the guide but I figured I'd bring it here so we can get some discussion going.
`letter = element letter { mixed { date+ | person+ | location+ | money }
date = element date { text | xsd:int }`

**Comment by BMT45** [comment]
Try typing it out as letter = element letter { mixed { (date+ | person+ | location+)} } I think you forgot an extra curly brace on your mixed statement

**Comment by ebeshero** [comment]
When you write mixed syntax with parenthetical grouping like that, try setting the repetition indicator (just one) outside the parentheses, like this:

```
letter = element letter { mixed { (date | person | location)+}}
 ```

Consider why! The parentheses around the element labels separated by “or” pipes mean, choose any one of these at any point in the mixed “tag soup” of text and elements. The repetition indicator means, let this selection (any of these) appear one or more times.
