### ISSUE TITLE
Project Proposal: Trends of Music

### ISSUE THREAD

**Issue by Julegirl** [ebeshero/DHClass-Hub#514]
Ok, I'm not completely sure on all of the details but I was thinking of doing a project involving music. I was thinking of analyzing the history of popular music over the last few decades. We would look for differences and similarities between trends and styles, and also see if there are any patterns that have stayed constant throughout the years. One thing that I have noticed is that even when you listen to different genres of music you will find things that make them similar and I want to delve into that a little. 

So here is my proposal. I hope this is something that we can work with.

**Comment by alnopa9** [comment]
I really like this idea and was considering something similar! You could look for similar themes or phrases within the lyrics. I was thinking about picking a band that has been around for a while (Red Hot Chili Peppers, Blink-182, or The Cranberries, really any band around more than a decade) and seeing how their music has evolved from when they started to the newest release.

**Comment by RLG95** [comment]
That's a good idea, I think looking for lyric similarities would be a cool idea.

**Comment by bnm29** [comment]
I plan on focusing a project on something I have been interested in and involved in since I was 2 years old. I do not expect anyone else to want to join in on the idea, but I would like to focus on motocross/supercross, the history and evolution of the sport, as well as the riders, bikes, and gear as a whole. Considering the first official stadium race took place in 1972, I believe that there have been a lot of obvious and interesting changes over the years.

**Comment by bnm29** [comment]
I like this idea a lot and think it is a great idea considering how long music has been around.

**Comment by Julegirl** [comment]
Wow! Awesome! Thank you guys! And I agree that we should look at one band. It would definitely give us a base to work with.

**Comment by quantum-satire** [comment]
@Julegirl [Here is a music project](http://jpop.obdurodon.org/) from our sibling course in Oakland that students worked on last semester. They studied gender in music after selecting a few specific songs, which helped to narrow down the project to keep it from becoming too big to work on. You could consider studying a specific theme within some artists' work, but choosing one single band may not be a big enough project to work on. Working within a genre might be something to look at!
