### ISSUE TITLE
project proposal : motocross/supercross

### ISSUE THREAD

**Issue by bnm29** [ebeshero/DHClass-Hub#515]
I plan on focusing a project on something I have been interested in and involved in since I was 2 years old. I do not expect anyone else to want to join in on the idea, but I would like to focus on motocross/supercross, the history and evolution of the sport, as well as the riders, bikes, and gear as a whole. Considering the first official stadium race took place in 1972, I believe that there have been a lot of obvious and interesting changes over the years.

**Comment by ebeshero** [comment]
This looks really interesting and unusual! How would it work as an XML-based project? For our semester, to save people a lot of work, it helps to start with some texts already written, to mark them up for the information or “data” they contain that you (and your team) want to be collecting systematically. So one thing I imagine you could do is find news coverage on the web of motocross, and mark it up for references to something interesting—maybe following references to tech innovations and changes in the sport? Think of some specific kinds of info you can follow using XML markup, and what kinds of resources you can find for doing that markup.

**Comment by alexlavelle** [comment]
I've also been around this stuff most of my live, I had my first ATV when I was 6. My grandfather owned one of the old 3-wheeler deathtraps and my dad and uncles grew up riding that stuff and passed that hobby down to me.  There could be a timeline that shows different tech-developments with the bikes during different decades.  There's a huge difference between the bikes our parents rode compared to what we have today.

**Comment by quantum-satire** [comment]
Something interesting to mark up here could be advertisements and language used to describe the bikes and gear then vs now! I think it would be cool to explore what the trends were throughout the years as far as written documents, which would be necessary for markup.
