### ISSUE TITLE
Project Proposal: Walt Whitman

### ISSUE THREAD

**Issue by emb184** [ebeshero/DHClass-Hub#519]
Last semester I started writing a paper about Walt Whitman being a bisexual (most people put him either in straight or homosexual category) but due to some whacky and unfortunate circumstances I was unable to finish the paper. I'd like to look at some of his poetry in relation to sexuality to compile data on both the men and women he's writing about, to show that he is in fact bisexual. I'd also like to look at words or phrases that he uses that could be indicators of sexuality from his time.

**Comment by KSD32** [comment]
I think this is a great idea! I love the uniqueness of the project, especially the fact that it's hitting the personal aspects of a writer and how that would effect what and how they wrote.

**Comment by quantum-satire** [comment]
This sounds like the perfect project for a Digital Humanities course! I'd really like to see this as one of the projects that runs this semester.
