### ISSUE TITLE
Project Proposal: Movies Over Time

### ISSUE THREAD

**Issue by RLG95** [ebeshero/DHClass-Hub#522]
I have no idea where I am exactly going with this and its a broad idea, but I was thinking of comparing popular movies over time. Maybe similarities in script or genre to find out if there is anything specific that makes these movies popular. Could also compare differences in things that are maybe allowed today that weren't in the past. Certain clothing styles, etc. Maybe even think of the score, like if there is a certain artist or soundtrack that makes the movies popular, directors, etc.

**Comment by ebeshero** [comment]
@RLG95 For this and some of the other project proposals I'm reading, it may help to browse movie scripts on the public web! Usually you can download and work with this, and in a unit of the course coming soon, you'll be learning how to automatically "up-convert" the text of regularly formatted documents like movie scripts into XML (so you don't have to do it by hand). I bet you and a team could make a collection of related scripts to investigate with XML markup. Here are some resources to help:
* The Internet Movie Script Database: https://www.imsdb.com/
* Simply Scripts: https://www.simplyscripts.com/movie-scripts.html 
* https://www.nyfa.edu/student-resources/10-great-websites-download-movie-scripts/

Take a look through these and if you can get text copies of scripts that you can copy into oXygen (or a text editor), we should be able to work with the material. We *may* have some copyright restrictions to deal with depending on the script, but it's unlikely that this will be a problem if the scripts are already released to the public. We'll help you investigate if there are problems. (The worst that could happen is that you may not be able to post the full scripts yourself, but you can post the results of your research.)
