### ISSUE TITLE
Project Proposal: Soccer Records

### ISSUE THREAD

**Issue by JustinCampbell9** [ebeshero/DHClass-Hub#525]
I was thinking about doing my project based on previous years soccer records for not only UPG but everyone in the division. When looking at the records I wanted to go into specific detail on where the games were playing, who scored what goal and previous formations . I'm more interested in organizing the information into a website where it's all accessible without needing to go to hundreds of different sites.

**Comment by ebeshero** [comment]
@JustinCampbell9 Great idea! Can you point us to some of the sites where the information is stored, so we can get a sense of what you'd be working with to start? Consolidating information from lots of sources into one place is a great use of XML.
