### ISSUE TITLE
Project check point 2

### ISSUE THREAD

**Issue by Julegirl** [ebeshero/DHClass-Hub#528]
So for the project, what is it that we have to do for the second check point? What is this directory we have to create?

**Comment by ebeshero** [comment]
@Julegirl This will make more sense as you gather files to mark up in XML for the project, and as we start work on the HTML and web development next. You'll be maintaining a project GitHub repository, which needs to be organized so it's easy to update your project schema as you're working without everyone having to reassociate the schema line. That means having all the project XML files in one central file directory on your GitHub repo, and establishing a good location for your schema file (whether it's a TEI ODD-generated schema or your own Relax NG schema). Your markup and your schema will be under development together for a while, but we want to make sure first of all you've made a good "home" for them to grow and change.

As your team works on developing a website for the project, you're going to be transferring files from the GitHub repo to our web server on newtfire.org. You'll be learning more about this starting next class, but this, too, involves setting up a well-organized file directory on the web server so you can easily make updates when you're ready.
