### ISSUE TITLE
XSLT Exercise 4

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#53]
I have the `<h4>` stuff in one tag, and I have the `<articlebody>` stuff in another. But I don't know how to seperate the lines of headlines into their each individual part. As well, I have to problem that my body won't go inside of any tags. Help?

**Comment by CodyKarch** [comment]
Let me refine that. I was able to catch the `<h4>` elements, but I have them in one bundle. How would I put them each in their place?

**Comment by CodyKarch** [comment]
<xsl:template match="/"> 
        <html>
            <head>
                <title>XSLT Exercise 4 HTML Transformation from Nelson Article</title>
                <link rel="stylesheet" type="text/css" href="" />
            </head>
            <body>
                <h1>Chicago Times </h1>
                <h2>CITY SLAVE GIRLS</h2>
                <h3>Nell Nelson</h3>
                <h3>Monday Morning, July 30, 1888.</h3>
                <xsl:apply-templates select="//head[headLine]"/>
                <xsl:apply-templates select="//articleBody"/>
            </body>
        </html>
    </xsl:template>
    <xsl:template match="head[headLine]">
        <h4><class span="headLine"><xsl:apply-templates select="//headLine"/></class></h4>
    </xsl:template>
    <xsl:template match="head[articleBody]">
        <p><xsl:apply-templates select="//articleBody"/></p>
    </xsl:template>
    
</xsl:stylesheet>

**Comment by CodyKarch** [comment]
I was able to get the articleBody into a p tag, but I still can't seperate the individual headLines

**Comment by ebeshero** [comment]
@CodyKarch Hi Cody! Greetings from Lyon! Think about how you're setting up your template matches so you're not grabbing all the headlines in ONE go, but so that you are picking up EACH one of them distinctly. This is like the distinction we make in setting up a list--in positioning a single `<ul>` element vs. a separate template rule for the `<li>` elements...

**Comment by ebeshero** [comment]
So--think of it like this: Your template @match for your headlines is actually NOT set on the headlines themselves, but on the one parent element that holds ALL the headlines--so when the template rule fires, it's grabbing all the headlines in one bundle (looking at the parent element) and wrapping them all together in one h4 element. Try changing your @match attribute and you'll have this one!

**Comment by CodyKarch** [comment]
OH! I understand that.. Let me try

**Comment by CodyKarch** [comment]
I tried multiple ways, but I can't seem the XPath to grab those headLine individually. It is the XPath that I need to fix, right?

**Comment by ebeshero** [comment]
Well, when you're writing `<xsl:template match="pattern">....</xsl:template>`, it's not really an XPath, since you're calling out to a headline wherever it might appear...

**Comment by CodyKarch** [comment]
`<xsl:template match="/headLine">` is the best thing I could find, but it picks up extra stuff and doesn't place tags in around it.

**Comment by ebeshero** [comment]
Well, remember what happens when you put one of those slashes on your @match attribute! Remember???

**Comment by ebeshero** [comment]
OK--I'm getting tired b/c it's 1:30 AM in France...It's more problematic to use that slash in a @select attribute in xsl:apply-templates. Still--you don't need slashes up in the @match attribute...and you put h4 tags around things by writing them inside your template rule...

**Comment by CodyKarch** [comment]
Okay, yeah, I remember that, but I have the h4 in my template rule and it still won't appear for each individually

**Comment by ebeshero** [comment]
If you need to filter out some headLines, try writing a predicate on them...or if it's just certain headlines you want, you can write pattern that gets ONLY headlines when they're the children or grandchildren of something--like:

Grandpa//grandkid

That's not exactly an XPath expression, because we don't indicate WHERE Grandpa lives on the document tree...

How are you writing your template rule? Put it here inside tick marks--I wonder if it's  typo or something?

**Comment by nlottig94** [comment]
@CodyKarch I was having the same problem when I was starting the homework.  Could you show me your entire template rule??

**Comment by nlottig94** [comment]
I may be able to help you out if I can see it written out.

**Comment by nlottig94** [comment]
Take lots of pictures @ebeshero and @ghbondar !!!  I'd love to see pictures of France!!

**Comment by ebeshero** [comment]
@nlottig94 Will do!

**Comment by CodyKarch** [comment]
`    <xsl:template match="headLine">
        <h4><span class="headLine"><xsl:apply-templates select="//headLine[sibling]"/></span></h4>
    </xsl:template>`

**Comment by ebeshero** [comment]
Hmmm... how come you've got a @select attribute on apply-templates? And remember what happens when you reach up to the document node like that with those slashes on the left of your XPath in @select? 

@select = the source of your problem here!

**Comment by ebeshero** [comment]
@CodyKarch Think about what @select is for--and what that XPath you've written there in @select literally is saying...

**Comment by nlottig94** [comment]
I was going to say the exact same thing!  Remember what we talked about in class?  If we are already matching all of the `<headLine>` elements, do we really need to select them again??  Or can we just apply our templates within the `<h4>` and `<span>` elements??

**Comment by CodyKarch** [comment]
Okay. Thank you so much! that got me what I needed. I can't believe I didn't need to select that again...

**Comment by nlottig94** [comment]
Just remember that that will go for almost everything in this assignment because we are being so specific on what we are matching to!!  Good luck!

**Comment by CodyKarch** [comment]
Oh, now I think I'll remember..
