### ISSUE TITLE
Mac Terminal 

### ISSUE THREAD

**Issue by KSD32** [ebeshero/DHClass-Hub#530]
HI, I'm having trouble with the mac terminal when trying to put in the firebelly.newtfire username and password. I am putting in the correct password, and I'm pretty sure the correct username, but I keep getting permission denied. 

![screen shot 2018-09-26 at 3 18 30 pm](https://user-images.githubusercontent.com/42811975/46103697-7c0d3000-c19f-11e8-8dfe-0412f281818c.png)

**Comment by KSD32** [comment]
I just tried again and its still not working.

**Comment by ebeshero** [comment]
?? I just tried as you, all lowercase ksd32, and got in again. I wonder if you might be mistyping the password? I don't want to air the password here because this is public-facing (beyond just our class)...

**Comment by ebeshero** [comment]
WAIT A MINUTE! I see the problem! I announced the correct password in class today, but it's not correct on my announcement on Courseweb...

**Comment by ebeshero** [comment]
...Let me just fix that right now--sorry!!!

**Comment by KSD32** [comment]
That's okay. Thank you!!

**Comment by KSD32** [comment]
I'm in now. Thank you!!!

**Comment by ebeshero** [comment]
Sorry for the trouble--but THANK YOU for posting or I wouldn't have caught that error on my own!
