### ISSUE TITLE
HINTS for regex HW#1

### ISSUE THREAD

**Issue by ghbondar** [ebeshero/DHClass-Hub#538]
1) As you can see in [the suggested xml output file for Regex Exercise #1](http://dh.obdurodon.org/shakespeare-sonnets.xml), we are only interested in marking-up the sonnets, and the Roman numerals identifying each sonnet. So, just **delete all of the introductory metadata** from Project Gutenburg both before and after the sonnets from the [initial input file that you are starting with](http://dh.newtfire.org/shakeSonnets.txt).

2) **You need to submit a file showing your _exact_ step-by-step FIND and REPLACE regex statements** from oXygen, with any additional commentary explaining what you are trying to do. When we grade your submissions, we will copy your steps into oXygen ourselves, and expect them to produce the desired output. We do not need to see your finished xml-file.

- For steps you are doing only once or twice, such as adding your root-element, you don't need to use regex at all: you can just modify your document manually. But, if it is an action that you need to repeat three or more times, then we expect to see you using regex. In any case, make sure that you are recording all of these actions on your list of steps.

3) In class, we showed you how to select multiple punctuation marks using: `[.?!]`
This can also be used to select a range of numbers `[1-4]` or letters `[a-z]`
or a collection of individual characters, such as those used for Roman numerals `[IVXCDL]`
Note that these statements are case-sensitive.

4) We added some more step-by-step examples demonstrating how we mark-up files using regex to the Class Examples folder. I recommend the [JohannForster-IntroToUpconversion folder](https://github.com/ebeshero/DHClass-Hub/tree/master/Class-Examples/regex/JohannForster-IntroToUpconversion).

5) Adding multiple tags: While we saw in class how to add opening and closing tags separately, you can combine multiple steps into longer find/replace statements:
Find: `^(.+)` Replace: `<item>\1</item>`
Of course, this will add the wrong tags to some lines that you will need to remove with other regex statements.

6) And, of course, **ask for help on GitHub! If you are having a problem, probably others are also.**

**Comment by ghbondar** [comment]
Additional hints have been added, so make sure to [view the complete Issue in GitHub](https://github.com/ebeshero/DHClass-Hub/issues/538)!

**Comment by bman8932** [comment]
When I use [IVXCDL]+ to attempt to find only lines with roman numerals, I find myself also selecting lines with a capital letter in it. How to I change this?

**Comment by ebeshero** [comment]
@bman8932 Good question! What is it that makes the lines with the Roman numerals on them different from the lines of poetry with capital letters like "I"? If you've turned on the formatting in oXygen, you can see the special white spaces...the Roman Numerals are probably all followed by multiple spaces or a newline, aren't they?

**Comment by bman8932** [comment]
Ok. How exactly would I indicate that the selection must be followed by a white space?
