### ISSUE TITLE
Regex Issue

### ISSUE THREAD

**Issue by Julegirl** [ebeshero/DHClass-Hub#540]
Ok, I'm getting frustrated. I've been trying to add an ending line element, but it won't go onto all of the ending lines. It will go onto all of them except for those that don't have whitespace or punctuation at the end.

**Comment by Julegirl** [comment]
Nevermind! I just figured it out.

**Comment by Julegirl** [comment]
Ok, scratch that. I still need help. I'm having trouble tagging the roman numerals. How do I exclude them so I am only writing a tag for them?

**Comment by ghbondar** [comment]
Are you using "capturing groups", you remember, enclosing your selected text inside parentheses and then referring to that text by \1 in the Replace-window?

**Comment by Julegirl** [comment]
Yes, but it still will highlight letters from the sonnets too.

**Comment by ebeshero** [comment]
Wrap capturing groups like this in the Find window:
```
(stuff in here you want to capture)
```
refer to them  like this in the Replace window:
```
\1  
```

**Comment by ebeshero** [comment]
@Julegirl Ahhh! To prevent that, take a look at what's *different* about the Roman numerals at the head of each sonnet.

**Comment by ebeshero** [comment]
@Julegirl There are lots of spaces around those Roman Numerals, aren't there? Do they sit by themselves on a line? Take a look at how to capture whitespaces like newlines: `\n` `\n+`

**Comment by Julegirl** [comment]
I know. But when I put in the "line" tag for the poems, it captured them too so now there isn't much space. Uhh! I don't know how much longer I can work on this. I have been literally working on this for hours.

**Comment by alnopa9** [comment]
I decided to delete my extra white space first, that way they would start at the beginning of a line and I could use ^ to find them. Since some roman numerals are more than just one character long, you include the +. They also have an immediate line break after them, so \n follows the expression.

**Comment by alnopa9** [comment]
This way, when you go to group your other lines with the <line></line> element tags, you can start that Find expression with ^\w, which excludes the < sign and only looks for alphanumeric characters.

**Comment by ebeshero** [comment]
Yep--caret and dollar sign are pretty awesome!  `^` signals at the beginning of the line, and `$` the ending of it, so you can sort of set them up together. 

Also, if you lost your white spaces, you may want to undo and then redo what you last did. Go to when you first captured the line (just undo to the previous stage), and when you set your line tags, leave yourself a line break after each line. Knowing there's a newline after each Roman Numeral heading can really help here.

**Comment by Julegirl** [comment]
I'm doing that right now! Thanks guys.

**Comment by Julegirl** [comment]
All good hear! Thank you! Hallelujah!
