### ISSUE TITLE
Regex: Pygmalion

### ISSUE THREAD

**Issue by bman8932** [ebeshero/DHClass-Hub#543]
How do we tag the stage directions? I can't seem to find them in the text...

**Comment by bman8932** [comment]
never mind I got it.

\[ : [ is a meta char and needs to be escaped if you want to match it literally.
(.*?) : match everything in a non-greedy way and capture it.
\] : ] is a meta char and needs to be escaped if you want to match it literally.

**Comment by ghbondar** [comment]
Yes, in this case, "escape" means:
`\[` and `\]`
As for "greedy" matching, you might sometimes need to select "Dot matches all" in your Find/Replace window. Remember to deselect it when you're done!

**Comment by Julegirl** [comment]
I am having a problem with the speakers. How do I exclude them from the rest of the text?

**Comment by ghbondar** [comment]
@Julegirl Like we saw in the example in class from War of the Worlds: What is distinctive about the speakers? They are in all-CAPS! Where else have you seen that? What are Roman Numerals, after-all. Try that, perhaps looking in our solution for Regex-1 if your own code doesn't help.

**Comment by Julegirl** [comment]
I've understood this, but when I put in [A-Z] with any code it will still give me other letters and words that aren't the speakers.

**Comment by Julegirl** [comment]
Ok, I've got the speakers highlighted now, but there are still some words that are being highlighted too. It's like my code made me over shoot.

**Comment by Julegirl** [comment]
Nevermind, I think I've got it.

**Comment by Julegirl** [comment]
I got it!!!!!! Yes! Man, I think I make it more complicated than it needs to be.
