### ISSUE TITLE
Regex 3

### ISSUE THREAD

**Issue by RLG95** [ebeshero/DHClass-Hub#544]
I cannot figure out how to wrap entire paragraphs. Every time I try anything it will either only grab a few separate lines here and there, or will tag each individual line even though its part of a paragraph. I have no idea what is going on.

**Comment by ghbondar** [comment]
@RLG95 Close/Open might be your friend...

**Comment by RLG95** [comment]
Nevermind it was just my editor, I had to restart it? Its all good now
