### ISSUE TITLE
XPath: Forster Issue

### ISSUE THREAD

**Issue by JustinCampbell9** [ebeshero/DHClass-Hub#545]
When searching for attributes in XPath, i though you were suppose to format it like this "/TEI/text/body/div/@div="chapter" however that's not working. Is there another way to do it?

**Comment by ghbondar** [comment]
@JustinCampbell9 I see a couple things that you should change:
1) Remember that the advantage of XPath is that you can streamline your search syntax: there is rarely any reason to start with the root and to type-in the full and complete path. Instead, you should take advantage of the Descendant-axis to jump down closer to the layer where you want to search, such as:
`//body/div` although you might be able to start at a div, but make sure that you account for one div being nested inside another div.
2) Another problem with your search is that **div is an element, not an attribute**. What attribute is attached to div-elements?

**Comment by JustinCampbell9** [comment]
Type is the attribute, that's my bad. Even something like //body/div/@type="book" isn't working

**Comment by ghbondar** [comment]
@JustinCampbell9 
1) If you look at the structure of the document, notice that div-elements are used at several different levels. Again, use the Descendant-axis if you don't know (or don't want to type-in) the level that you want. You probably don't even need to start at the body-element.
2) Now, you are swimming in a sea of div-elements! How can you specify the one that you want? Remember, that XPath uses **predicates** to identify a specific element. We saw predicates using numbers, but we can also use other identifying information, such as **attributes** inside your XPath search. So, how do you tell the div-elements containing books apart from the div-elements containing the chapters, _as attributes inside an XPath predicate_?

**Comment by ghbondar** [comment]
@JustinCampbell9 I added a bit to my previous response, so please check it out in GitHub.

**Comment by JustinCampbell9** [comment]
I believe I figured it out. I wasn't far enough into the /div I'm guessing
