### ISSUE TITLE
XPath homework 2

### ISSUE THREAD

**Issue by Julegirl** [ebeshero/DHClass-Hub#547]
I am having trouble with question four. I don't know how to find both attributes at the same time. I can find them individually, but I can't find them at the same time. Any hints?

**Comment by ghbondar** [comment]
@Julegirl Predicates are the key to filtering through elements, to specify one from the next:
1) While we demonstrated predicates containing numbers, predicates can also contain things, such as attributes, as you can see in our solution for XPath-1.
2) You can also have multiple predicates on the same node: `//div[3][@type="book"]`
3) Predicates can also be nested, [https://github.com/ebeshero/DHClass-Hub/wiki/XPath-activities](as we demonstrated last class:
https://github.com/ebeshero/DHClass-Hub/wiki/XPath-activities)

**Comment by Julegirl** [comment]
Yeah, I figured that predicates were the key. But I wasn't there for the last class so I'm a little unfamiliar with nesting.

**Comment by Julegirl** [comment]
I'm still stuck!! I don't know what I'm doing wrong. Help!

**Comment by ebeshero** [comment]
@Julegirl Okay--I'm taking a look at what we posted from the class examples on Friday to see if I can help. I noticed an error there that I just fixed--and I'll call attention to that now. This is a class example from a different file that isn't a direct answer to the homework, but I hope it'll point the way for you! 

In the class example, we were using my <http://digitalmitford.org/si.xml> file (which we opened in oXygen with File -> Open URL). There are lots of `<person>` elements inside, holding data about lots of individuals mentioned in my project. We were looking for 
How many females have a birth element coded with `@notBefore` that also contain a `<placeName>` element?
To get females, we had to find 
```
//div[@type='historical_people']//person[@sex="f"]`
```
Then, we stepped on down to find the females that have birth elements (notice how we're taking this one step at a time):
```
//div[@type='historical_people']//person[@sex="f"][birth]
```
Now, we had to find the persons whose `<birth> `elements held a `@notBefore` attribute (a handy attribute for guesstimating when someone was born when you don't have an exact date): 

```
//div[@type='historical_people']//person[@sex="f"][birth[@notBefore]]
```
See how we can nest one predicate inside another there?

I took it one step further. Some of those `<birth>` elements have a `<placeName>` coded inside to indicate where someone was born. We don't have that for everyone, and we may not have it for women whose birth dates we had to guesstimate. To add more to the filter, we added a new nested predicate:

```
//div[@type='historical_people']//person[@sex="f"][birth[@notBefore][placeName]]
```
Okay, in the homework you need to find the paragraphs that contain BOTH latitude and longitude readings. To start, you need to know how to find:
a) the latitude readings, and the longitude readings,
b) the paragraphs that hold latitude readings (and longitude readings)
c) to get both, you can set two predicates side-by-side, or you can try a boolean `and` in between. You're definitely going to have to nest some predicates and step through this carefully...

**Comment by Julegirl** [comment]
I've tried that too, but when I get the expressions written out it just tells me that it received no results. That and I have no idea how to use a boolean correctly. I've tried and it tells me I did it wrong.

**Comment by Julegirl** [comment]
Update: I think I'm getting somewhere. I wrote this expression: /**/div/div/p/geo/@select="lat and geo/select="lon"** and it now says it's true. Now all I have to do is get to give me a location.

**Comment by Julegirl** [comment]
I think I get it now.
