### ISSUE TITLE
Questions for #2 on Schematron hw

### ISSUE THREAD

**Issue by BMT45** [ebeshero/DHClass-Hub#558]
<pattern>
        <rule context="tei:persName | tei:forename | tei:surname | tei:placeName">
            <report test="contains(@xml:id,starts-with(.,A-Z))"></report>
        </rule>
           </pattern>
    <pattern>
I typed in this code but I don't understand why it would not work.  And would you be able to use a character case as the 2nd argument.  Could you add a not function in it as well so that it would pick up any of the names that are not capitalized

**Comment by jonhoranic** [comment]
@BMT45 Could you post your code so we can better see the construction of your Schematron rule? That would help us visualize what exactly you are trying to do. `You can insert code blocks with the <> button above, or with single quotes wrapped around the entire thing.`

**Comment by BMT45** [comment]
'<pattern>
        <rule context="tei:persName | tei:forename | tei:surname | tei:placeName">
         
            <report test="contains(@xml:id,starts-with(.,A-Z))"></report>
                
            
            
        </rule>
           </pattern>'

**Comment by BMT45** [comment]
<pattern>
        <rule context="tei:persName | tei:forename | tei:surname | tei:placeName">
            <report test="contains(@xml:id,starts-with(.,A-Z))"></report>
        </rule>
           </pattern>

**Comment by BMT45** [comment]
'<pattern>
        <rule context="tei:persName | tei:forename | tei:surname | tei:placeName" 
            <report test="contains(@xml:id,starts-with(.,A-Z))"></report>
        </rule>
           </pattern>'

**Comment by BMT45** [comment]
'<pattern>'
        '<rule context="tei:persName | tei:forename | tei:surname | tei:placeName">'
            '<report test="contains(@xml:id,starts-with(.,A-Z))"></report>'
        '</rule>'
           '</pattern>'

**Comment by BMT45** [comment]
'<pattern>
        <rule context="tei:persName | tei:forename | tei:surname | tei:placeName">
            <report test="contains(@xml:id,starts-with(.,A-Z))"></report>
        </rule>
           </pattern>'

**Comment by BMT45** [comment]
<pattern>
<rule context="tei:surname | tei:forename | tei:placeName | tei:persName"
<report test="contains(xml:id,starts-with(.,A-Z))"</report>
</rule>
</pattern>

**Comment by ebeshero** [comment]
@BMT45 Had a long day of meetings in Pittsburgh so I'm not seeing this until now (and I see the issue is closed)--Did you figure it out?
