### ISSUE TITLE
SVG 2 Help

### ISSUE THREAD

**Issue by BMT45** [ebeshero/DHClass-Hub#575]
```
                      <xsl:for-each select="//chapter">
                            
                            <xsl:variable name="xpos" select="60+ position()*$interval"/>
                            <xsl:variable name="ypos" select="//chapter[@which]//q[sp='alice']*$yint"/>
                            <circle cx='{$xpos}' cy='-{$ypos}' r='5' fill='teal'/>
                        </xsl:for-each>
```
When I tried this code, I could not get my y values to work.  I would only get the - and that's it.  Everything else works fine.  I was wondering if I applied the xpath wrong for either the xsl:each statement or the ypos value.

**Comment by BMT45** [comment]
It would put all the circles on their respective x values on the x axis and would be set at 0 for their y values

**Comment by ebeshero** [comment]
@BMT45 Aha! Notice the relationship between your `@select` on `<xsl:for-each>` and your `@select` on the `ypos` variable. That'll likely be the issue.

**Comment by ghbondar** [comment]
@BMT45 Also, the `$yint` variable might not be necessary, as we only used it for scaling our in-class example.
