### ISSUE TITLE
Introduce yourself and experiment with markdown (day 2)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#588]
Once you have set up your GitHub account, introduce yourself here! Type in your name and your GitHub username, so I can add you to share this class repo!

Also, get familiar with how to write issues in markdown here! Can you include code blocks? Can you create a link? Can you include a screen capture? Can you write a list, and a checklist?

https://guides.github.com/features/mastering-markdown/

**Comment by koshinf** [comment]
This is *Frank Koshinskie*

**Comment by Skapfer13** [comment]
This is Sarah Kapfer

**Comment by ebeshero** [comment]
Example: I am *Elisa Beshero-Bondar*

**Comment by abdual1100** [comment]
This is _Abdual Nadeem_

**Comment by SparkTheDragon** [comment]
Donald Denne 
Github name -SparkTheDragon

**Comment by James-f117** [comment]
This is James Farley

**Comment by achen298** [comment]
This is Alan Chen

**Comment by JAG240** [comment]
I am *Jacob Gonos*

**Comment by frabbitry** [comment]
I am Fiona Carter

**Comment by jonhoranic** [comment]
I am also here! Prior student Jonathan Horanic, just snooping for the moment.

**Comment by NADGIT** [comment]
~~This is Nathan Dietz~~
