### ISSUE TITLE
A Quick Question

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#59]
I am trying to create a newline after text within a `string-join()` function, but I can't figure out how to do this.  Right now I am just separating the variations throughout Dickinson's poems by using a semicolon.  Here is what I am selecting when applying my template: `string-join((.//l/app/rdg[@wit='var0']), '; ')`
I also have one of these for the other variants of the lines, line var1 and var2.  If anyone can help, I'd appreciate it!

**Comment by RJP43** [comment]
@ebeshero @ghbondar @alexkrongel @andrewntz23 Any ideas?

**Comment by ebeshero** [comment]
@nlottig94 If I understand what you're doing, you're matching on something, and then processing a string-join function, and you want a line break to go where you're putting the semicolon. You need the special Unicode character for a line break, and there are actually a few you could use! Here is more than you ever wanted to know about newline or linebreak or carriage return characters: https://en.m.wikipedia.org/wiki/Newline

The one I typically use is a line feed character: `&#10;` Try that in your XSL template rule and see if it works!

**Comment by nlottig94** [comment]
I have tried the `&#10;` but it will not work.  it just inserts an extra space...Sorry, I've worked all weekend, and I'm just getting on here now!

**Comment by RJP43** [comment]
try this `&amp;#10;`

**Comment by nlottig94** [comment]
That gives this result:
![image](https://cloud.githubusercontent.com/assets/14095715/10873821/278000e4-80e8-11e5-85d3-bce52383d6e5.png)

**Comment by RJP43** [comment]
maybe try setting up a variable 
`<xsl:variable name='newline'><xsl:text>
</xsl:text></xsl:variable>`

 and then do this `string-join((.//l/app/rdg[@wit='var0']), '$newline')`

**Comment by nlottig94** [comment]
Where would this be located in my xslt?

**Comment by RJP43** [comment]
same place you put the variable declaration for the collection

**Comment by RJP43** [comment]
you want to make sure you hit enter in between the `<xsl:text>` and the `</xsl:text>`

**Comment by RJP43** [comment]
or this `<xsl:variable name="newline"><xsl:text>&#10;</xsl:text></xsl:variable>` then
`<xsl:value select="string-join((.//l/app/rdg[@wit='var0']), $newline)" />`

**Comment by nlottig94** [comment]
It didn't work....

**Comment by RJP43** [comment]
`<xsl:variable name="newline" select="'&#10;'"/>`

**Comment by nlottig94** [comment]
Nope.  Oh well, I'll have it pulled up at the beginning of class tomorrow and you can look at it then :)

**Comment by RJP43** [comment]
`&nl;` or maybe `\r\n`  ... ok we can check it out tomorrow... sorry :(

**Comment by ebeshero** [comment]
@nlottig94 @RJP43 I'm looking at the file you've turned in on Courseweb, and I notice you're outputting variants inside <ul> elements within your table cells. You don't want to do that--it's not valid HTML--but I think your own idea to set up a list in a very good one! It would deal with the problem of outputting the variants each on its own line, if you have a list set inside a table cell. To do this, you'll need to adjust your XSLT so you're outputting list items inside those cells--do you need another template rule? (Maybe you don't need string-join after all.) 

I think the immediate issue with the output of the newline or line-feed character might be this: When I use that line-feed, I'm actually outputting a plain text file (not HTML) now that I think about it, and it's possible that the HTML formatting for a table cell is overruling the linebreak characters we're entering--I'm not sure exactly, though! Let's keep experimenting with this.

**Comment by nlottig94** [comment]
FIXED IT!!
