### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by SparkTheDragon** [ebeshero/DHClass-Hub#591]
I am still unable to pull fetch or issue any of those commands on my git bash. I have the repository copied, but I can't figure out what to do next.

I took a snippet of my console, I hope it proves helpful

![troubleshoot](https://user-images.githubusercontent.com/46506618/51217255-5a25ed80-18f5-11e9-91bc-410ec48af53b.PNG)

**Comment by ebeshero** [comment]
@SparkTheDragon Also, I'm concerned about **where** you've cloned the DHClass-Hub, because it looks like you might have cloned it outside your GitHub directory. Go take a look in your File Manager and see whether you've cloned it in a couple of different locations. You need to be VERY AWARE of where your GitHub repos are sitting and you need to be clear on navigate in your directory system when you work in GitHub.

**Comment by SparkTheDragon** [comment]
![troubleshoot 2](https://user-images.githubusercontent.com/46506618/51218830-1b476600-18fc-11e9-8708-dcf79f4731d6.PNG)

this is what I have after using ls

**Comment by ebeshero** [comment]
Okay-- looks like that's a list of directories in your "home" location. I can see Documents there...can you step down into it and see what's inside?

**Comment by SparkTheDragon** [comment]
also, here is where I stored the directory
![troubleshoot3](https://user-images.githubusercontent.com/46506618/51218885-56499980-18fc-11e9-9142-b1749a5d2800.PNG)

**Comment by ebeshero** [comment]
@SparkTheDragon Okay--good. You don't need to clone it again--you just need to learn how to navigate to that location at your command line. You can do it!

**Comment by SparkTheDragon** [comment]
![troubleshhot4](https://user-images.githubusercontent.com/46506618/51218927-7aa57600-18fc-11e9-9fcc-eb13447f0b20.PNG)

heres my documents

**Comment by ebeshero** [comment]
Okay--one more step...

**Comment by ebeshero** [comment]
Okay--you're ALREADY in 'documents` so it literally will not work to try to step into it again.

**Comment by ebeshero** [comment]
And then you'll need to `ls` to see if DHClass-Hub is there...and step down into that.

**Comment by SparkTheDragon** [comment]
![troubleshoot6](https://user-images.githubusercontent.com/46506618/51219045-06b79d80-18fd-11e9-936f-9f3d7aa9b007.PNG)

Like this?

**Comment by ebeshero** [comment]
yep

**Comment by ebeshero** [comment]
You still need to find DHCLass-Hub, but guess where it is?

**Comment by SparkTheDragon** [comment]
Alright, I got it! Yea it was in GitHub

**Comment by ebeshero** [comment]
Yep...go on into it with `cd` and *then* do your `git` stuff.
