### ISSUE TITLE
Lost flash drive

### ISSUE THREAD

**Issue by NADGIT** [ebeshero/DHClass-Hub#593]
Hey, everyone. Sorry about this, but I lost my flash drive after class and I may have left it in the classroom on 1/16/2019 (Wednesday). It's a regular black San Disk USB drive with a little red slider. If you look inside, you'll see a folder labeled "current classes", and inside my assignments, with my name "Nathan Dietz" on them. If you see it or found it, please reply to this issue, and maybe leave it at the lost and found or meet up with me on campus. Thank you so much for your time!

**Comment by alnopa9** [comment]
@NADGIT I am heading over to the school around 2:00 tomorrow and can look for it if you still haven't found it by then.

**Comment by NADGIT** [comment]
@alnopa9 That's fine, you don't need to look for it. I already looked all over the classroom, so I think it's not there or somebody already picked it up. I was just wondering if someone knew what happened to it. Thank you for your consideration though!

**Comment by ebeshero** [comment]
@NADGIT I keep thinking about this. I was back in 136 McKenna at 2pm for class and we were both looking for it then. There was at least one class in between (the group that came in after DH class), but I wouldn’t expect someone to pull out a plugged in drive unless they had to. We looked around the teaching area, in the drawers next to my console,  and the printer at the back of the room—but we could still stand to take another look. I am sure you are mentally retracing your steps: but here is a question— In the rush to exit class, a bunch of us swirled into that other classroom with the movable desks, McKenna 138. Did you stop there a moment?

 Also, in exiting quickly, what would you typically do to grab or collect your drive? Would you do anything to disconnect it on logout of the lab machines? (Were you plugged in to a lab machine?) I wonder if the lab machines notify you on logout if you have a USB drive connected...or if they stop someone else from logging in if you do. Of course you looked around that area. 

Where were you in between our class and the moment you discovered you lost it? 

Last thing, I am sure you have been doing this, but check every pocket in your coat/clothes/bag...Good luck with finding it! Should we get in touch with the instructor of the next class after ours  in McKenna 136?
