### ISSUE TITLE
I think this is me pushing an Issue headed for Sandbox?

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#6]

**Comment by ebeshero** [comment]
Yes! You have successfully posted an issue! Now, I need to orient you (the group of you) to using labels and setting milestone markers here. We'll do that as part of class tomorrow!

**Comment by ebeshero** [comment]
@CodyKarch I just added you as a Collaborator on this GitHub repository, so you should be able to push a new file or push a change to an existing file in the Sandbox directory! Give it a try when you've got your desktop client running. :+1:

**Comment by amielnicki** [comment]
Here is an example comment to this Issue
