### ISSUE TITLE
Project Proposal:Washington

### ISSUE THREAD

**Issue by KSD32** [ebeshero/DHClass-Hub#607]
The project that I am prosing is a continuation of the project that I began last semester. Washington Paper's purpose is answering the question of who George Washington was based on his writings. What the project is doing is looking at the writings of Washington, letters and diaries, and detailing names, places, and subjects that were occurring during the time period. This is used to compare how we perceive George Washington from what we read in history textbooks. 

For the project, I am looking to add more visualization in the terms of people/places/events most referenced, building a detailed timeline of events both politically and personally in Washington's life, and developing a better comprehension of Washington's writing style and personality. 

Some of the source documents that were used last semester were actively available from the Library of Congress website: https://www.loc.gov/collections/george-washington-papers/about-this-collection/
While others were taking from the Mount Vernon archives: https://rotunda.upress.virginia.edu/founders/GEWN

**Comment by frabbitry** [comment]
This sounds like an interesting project, and it looks like you've already got a lot of data at your disposal. 

I like the idea of mapping everything out on a timeline, to see the relationships between things references and when they were referenced. How would you look at Washington's writing style and personality?
