### ISSUE TITLE
Project Proposal: Banksy

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#609]
Banksy is an anonymous graffiti artist who is known for politically inspired art. With last semester's Magellan project in mind, I'd like to use KML to create a map showcasing Banksy's work as well as a timeline of when it was made. Based on each work, you could tag the different colors used and create a chart showing which colors were used the most. The map could show what percentage of his taggings happened in each country and the timeline could show his frequency. Although not on Facebook or Twitter, Banksy does have an Instagram where he posts his works with captions that tell of the general area of each tagging. Banksy also has his own website that has galleries of his work. There are also numerous articles on most taggings describing the account and what the meaning of the image is. I would also be interested in identifying the cause that Banksy is either trying to support or bring in to focus and see if any occur more frequently than others.
Instagram - https://www.instagram.com/banksy/?hl=en
Personal Site - http://www.banksy.co.uk/menu.asp
I'd like to use TEI tags for this, but it may be simpler to create a schema and tag layout. Some possible tags and attributes would be: location, date, color, description, cause, whether any popular themes occur (children, mice, police, script), size, and whether a stencil was used or not.

**Comment by abdual1100** [comment]
This is my first choice.

**Comment by SparkTheDragon** [comment]
this is my fourth choice
