### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#61]
Not sure if this is just me, but I'm having issues accessing newfire right now to be able to get to the assignment page. I read it quickly beforehand and know that we are basically picking any file from one of the projects, but there was a list of things that we needed to pick two to apply to the document and I don't know what the list was.

**Comment by brookestewart** [comment]
I'm having trouble too. I didn't get to look at it at all, however.

**Comment by CodyKarch** [comment]
Yeah, I just came on, and I can't see this... What should we do? @RJP43

**Comment by RJP43** [comment]
Please refer to issue #63 ... sorry I just saw this!!
