### ISSUE TITLE
Project Proposal: A Study in Magic Project

### ISSUE THREAD

**Issue by James-f117** [ebeshero/DHClass-Hub#610]
This project is a look into the magic world of Skyrim and a study of specifically the magic and the lore surrounding the magic of the game. I would like to establish the patterns and overlap of the magic lore for the game and possibly get a look into the development of the magical system for Skyrim. I think this would be a fun and interesting project for any gamer's in the class and also those in the creative writing field. Some resources that could possibly be used are:
https://www.imperial-library.info/books/skyrim
https://en.uesp.net/wiki/Skyrim:Magic

**Comment by ebeshero** [comment]
A quick comment here--I think Skyrim is likely a great choice for a game lore project...those interested in working on one of the game proposals might want to compare the lore material available and get a sense of the kinds and quantities of available documents for markup.

**Comment by Skapfer13** [comment]
I think this is a great idea! There is tons of information one could incorporate into this project based on Skyrim, from the make up of the game to different aspects within. I like that you added in additional information already for those who may not be familiar with the game. Great proposal!
