### ISSUE TITLE
Final Voting: A Study in Magic (Skyrim)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#614]
Vote here your interest in joining the "A Study in Magic (Skyrim)" project by replying to this issue and indicating whether this would be your **first** or **second** choice. [Review the Project Proposal for A Study in Magic](https://github.com/ebeshero/DHClass-Hub/issues/610).

**Comment by alnopa9** [comment]
This is my **second** choice. I know there is an extensive amount of lore in the form of books. Those and the dialogue in the game would provide a good bit of mark up!
Lots of books:
https://elderscrolls.fandom.com/wiki/Books_(Skyrim)
https://en.uesp.net/wiki/Skyrim:Books

**Comment by koshinf** [comment]
This is my second choice

**Comment by JAG240** [comment]
This is my second choice

**Comment by abdual1100** [comment]
This is my second choice

**Comment by achen298** [comment]
this is my second choice also

**Comment by James-f117** [comment]
This is my 3rd choice.
