### ISSUE TITLE
Final Voting: The Ulysses Project

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#615]
Vote here your interest in joining the Ulysses project by replying to this issue and indicating whether this would be your **first** or **second** choice. [Review the Ulysses Project Proposal](https://github.com/ebeshero/DHClass-Hub/issues/603).

**Comment by BMT45** [comment]
This is my second choice

**Comment by frabbitry** [comment]
This is my first choice.

**Comment by KSD32** [comment]
This is my first choice.

**Comment by achen298** [comment]
fourth choice
