### ISSUE TITLE
Final Voting: Pokemon Map Project 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#616]
Vote here your interest in joining the Pokemon Map project by replying to this issue and indicating whether this would be your **first** or **second** choice. [Review the Pokemon Map Project Proposal](https://github.com/ebeshero/DHClass-Hub/issues/600).

**Comment by JAG240** [comment]
This is my first choice

**Comment by achen298** [comment]
this is my first choice

**Comment by SparkTheDragon** [comment]
This is my third choice

**Comment by BMT45** [comment]
This is my fourth choice

**Comment by James-f117** [comment]
This is my 4th choice.

**Comment by abdual1100** [comment]
This is my 3rd choice.

**Comment by alnopa9** [comment]
This is my 3rd choice.
