### ISSUE TITLE
Final Voting: Tangerine Dream Project

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#617]
Vote here your interest in joining the Tangerine Dream project by replying to this issue and indicating whether this would be your **first** or **second** choice. [Review the Tangerine Dream Project Proposal](https://github.com/ebeshero/DHClass-Hub/issues/602).

**Comment by NADGIT** [comment]
This is my first choice!
Also, in case you're wondering what they sound like, I have three tracks for your listening pleasure:

[This is one of their earliest tracks, and is more progressive and ambient](https://www.youtube.com/watch?v=Euhwq1IGWIk)

[Here's a recent one, from the first album published after their founding member's passing.](https://www.youtube.com/watch?v=2QnbNwCxWqY)

[Finally, here's a cover of a rock song, just for fun!](https://www.youtube.com/watch?v=X3RpDb4hgBA)

**Comment by BMT45** [comment]
This is my first choice

**Comment by frabbitry** [comment]
This is my second choice.
