### ISSUE TITLE
Final Voting: Bloodborne Lore Project

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#618]
Vote here your interest in joining the Bloodborne Lore project by replying to this issue and indicating whether this would be your **first** or **second** choice. [Review the Bloodborne Lore Project Proposal](https://github.com/ebeshero/DHClass-Hub/issues/601).

**Comment by NADGIT** [comment]
This is my **second** choice!

**Comment by koshinf** [comment]
This is my first choice

**Comment by James-f117** [comment]
This is my 2nd choice.

**Comment by frabbitry** [comment]
This is my fourth choice

**Comment by abdual1100** [comment]
this is my fourth choice.
