### ISSUE TITLE
Linking Issues

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#62]
Despite Newtfire being down, I've attempted to start the assignment with a collection of Nelson articles and I'm having trouble linking them in the same way that we linked the Dickinson poems. Here's what I have: 

`
        <xsl:template match="$nelsonColl//body" mode="toc">
            <li>
                <a href="#article{//body/div/@n}"> 
                <xsl:text>Title: </xsl:text><xsl:apply-templates select="//body/div/head/title"/>
                </a>
            </li>
        </xsl:template>`

and then:

    `<xsl:template match="title">
        <span id="article{//body/div/@n}">
            <span class="title"><strong>
                <xsl:apply-templates/>
            </strong></span>
        </span>
        </xsl:template>`

and my problem is that in my table of contents, I am getting both parts of the link. Here's what it looks like in my output: 

`
         <li><a href="#article1">Title: <span id="article1"><span class="title"><strong>Chicago Times Monday Morning, July 30, 1888</strong></span></span></a></li>
        `

and I'm still getting `<span id "article1">` etc in my actual body of text, so how do I make it so that I only get my `<span>` elements in the body and not the toc. If this isn't making any sense, I can push it to the troubleshooting folder.

**Comment by RJP43** [comment]
go ahead and push your file... I am not exactly sure what you  mean?

**Comment by blawrence719** [comment]
Okay, one second

**Comment by blawrence719** [comment]
Okay, I pushed my file. And the collection I was working with was from the Nelson project, it was called ChicagoTimes_CSG_XML on your github

**Comment by RJP43** [comment]
ok and you want to make a table of contents with all of the article names and then in the body output each of the articles having the titles in the body linked in the table of contents, right?

**Comment by blawrence719** [comment]
Yeah and the way it's set up now, it's literally linking to the table of contents

**Comment by RJP43** [comment]
`<xsl:template match="body" mode="toc">
            <li>
                <a href="#article{//div[@n]}"> 
                <xsl:text>Title: </xsl:text><xsl:apply-templates select="//div/head/title"/>
                </a>
            </li>
        </xsl:template>
    
    
    <xsl:template match="body">
        <span id="article{//div[@n]}">
            <span class="title"><strong>
                <xsl:apply-templates select="//div//title"/>
            </strong></span>
            <xsl:apply-templates/>
        </span>
        
    </xsl:template>`

**Comment by RJP43** [comment]
Ok so a couple of things.... 

This wasn't giving you an issue, but just so you know... since you already specified in your first match that you your apply-templates is selecting the collection you do not need to include that path step in future matches. You very simply want to just match on any and all `<body>` elements therefore you just put `<xsl:template match="body">` and `<xsl:template match="body" mode="toc"`.

Ok next ... where the problem was occuring... since you had the match for the title set to  `<xsl:template match="title">` XSLT couldn't find your `<span id="article{//div[@n]}">` because the `@n` attribute sits above the `<title>` elements on  the `<div>` elements. What I did to fix this problem is I called in the match on all the body elements and then selected in the apply-templates to grab the titles. See above comment!

Is that what you wanted to do?

**Comment by blawrence719** [comment]
Whenever I use what you put above, I'm getting a weird output for my links. Now I have ` href="#article%0A ` for all of them

**Comment by RJP43** [comment]
whoops yea I forgot to change something back that I was messing with .. you want your AVTs to contain `{//div/@n}` not `{//div[@n]}`

**Comment by blawrence719** [comment]
I literally just figured that out as you posted that. Thank you!

**Comment by RJP43** [comment]
yes .. of course ... does my explanation clarify what your issue was?

**Comment by blawrence719** [comment]
Yes, I kind of thought that the issue had something to do with me matching on title and I had tried a different way of matching on body earlier, but then I wasn't getting the rest of the document and I was creating more issues.

**Comment by RJP43** [comment]
Yea I saw in you commented out a match on body and that is when it hit me what was going on ... nice work though overall!! I am going to  remove your file from troubleshooting since it has so much work done already. If you have any more issues ping me!

**Comment by blawrence719** [comment]
Okay, thank you again!
