### ISSUE TITLE
Project Teams: First Checkpoint for All Teams

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#620]

**Comment by ebeshero** [comment]
- [ ] Get XML
- [ ] Get More XML
- [ ] Autotag relentlessly!
- [ ] Profit

**Comment by alnopa9** [comment]
- [ ] Set up repo
- [ ] Invite team members
- [ ] Check notifications (each member should be a part of 3 repos; DHClass-Hub, personal, and project)
- [ ] Team leaders set up a kanban project board
- [ ] Set up schema
- [ ] Post issue to set up possible meeting times
