### ISSUE TITLE
Help with XPath 4

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#631]
One of you wrote to me by e-mail with a question about [XPath Ex 4](http://dh.newtfire.org/XPathExercise4.html) just now, and I just want to remind you all that you really want to use the DHClass-Hub to post a question when you're stuck. There's no shame in this--XPath is challenging! So, remember how I sent you to study the functions on [The XPath functions we use most](http://dh.obdurodon.org/functions.xhtml) page? If you're trying to figure out how to work with the `string-join()` function to deal with the first question, you'll see some potentially confusing syntax on my colleague's site. He is trying to model the syntax for you, and you need to learn how to read his notation:
```
string-join((string+),string)
```
Here's how to read this (and this may help you with other mentions of (string+) in the string functions section: The function `string-join()` takes two arguments. The first argument (string+) is *any XPath sequence that returns one or more strings*. That is what (string+) means. So that can be something you're pulling right off the XML tree that delivers you a sequence of one or more nodes containing text. Note: You actually don't have to do anything to those nodes to limit them to text or string() because string-join() will do that for you. It'll just take that XPath expression you put in the first argument and convert it to strings. 
The second argument in string-join(), after the comma, has to go in quotation marks and is a literal string, your separator. ", " 
In class on Monday, I was modeling this with placeName elements from some project code:
```
string-join(//placeName, ", ")
```
See how that works? The first argument, `//placeName`, returns a sequence of placeName element nodes, and the second argument inside quotation marks is a literal string that I want to set in between them to join the sequence of strings. 

Post questions here as you have them!  Your question may be shared by others!

**Comment by koshinf** [comment]
That helped a bunch for that question, I was thinking waaaay too hard about it.
