### ISSUE TITLE
Working with QGIS

### ISSUE THREAD

**Issue by frabbitry** [ebeshero/DHClass-Hub#634]
@ebeshero asked me to write up some information on how to import data into QGIS, an open-source GIS (Geographical Information System) that we're using with the Ulysses Project.

Quite frankly, it looks like it's going to be super easy to import data into QGIS and map it. If you have a csv file that contains at the very least columns for x and y (or lat and lon) coordinates, you can upload it into QGIS and create a map with it. The only requirement placed on the format of the csv file is that there be columns for x and y coordinates. From there, you can add attributes, layers, and fun things like that. The tutorial for uploading csv (and similar) documents into QGIS can be found [here](https://www.qgistutorials.com/en/docs/importing_spreadsheets_csv.html). 

However, QGIS is also very compatible with Open Street Maps, and [you could also import .osm files as geodata.](https://www.qgistutorials.com/en/docs/downloading_osm_data.html) This could prove to be very useful, because Open Street Maps is kind of like Google Maps in that you can query basic information about a location and come up with a plethora of information. 

I'm looking forward to learning about how to pull data from our markup into a spreadsheet or csv file so that we can start layering extra information on top of the location information that we've already got.

**Comment by ebeshero** [comment]
@frabbitry In the CSV do the lat and lon coords need to be in positions 1 and 2? Where would you position a placename in the CSV?
``
col_1, col_2, col_3, etc
``

**Comment by frabbitry** [comment]
@ebeshero The only restriction placed on the csv file is that there exist columns for latitude and longitude coordinates. When importing the file, you specificy which columns contain the coordinate information, so there isn't a need to format the csv with regard to that. Other attributes, such as placename, can also have arbitrary locations in the csv file, because you also indicate where that information is located when importing the file.

**Comment by ebeshero** [comment]
@frabbitry Yay--good to know. You're starting to see now how `concat()` and `string-join()` will get you these structured outputs...eXist-db can also, I'm reading, handle JSON outputs. I haven't tried that yet, but we can experiment.
