### ISSUE TITLE
Choose, If, and For-Each Conditionals

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#64]
This might be silly (meaning, already know), but can conditionals like If, When, and For-Each be used to pull out lines of text; not just for fine-tuning attributes? Or am I just imagining possibilities too far? @ebeshero @ghbondar

**Comment by ebeshero** [comment]
Yes, you can process the same kinds of things with XSL if and when that that you do with other kinds of XSLT. Only XSL if and when are conditionals, though. For-each and for-each-group, as we were discussing earlier, help you process multiple values. And yes, all f these can process the text node of an element, or walk up and down the tree, or process attributes.
