### ISSUE TITLE
Schematron 

### ISSUE THREAD

**Issue by KSD32** [ebeshero/DHClass-Hub#641]
Hi. I'm having trouble getting my schematron to work. This is the code that I currently have. 
![Screen Shot 2019-03-22 at 5 38 09 PM](https://user-images.githubusercontent.com/42811975/54854516-8ed56d00-4cc9-11e9-90f9-b1588546fd90.png)

**Comment by ebeshero** [comment]
@ksd32 Sorry for the delay! I was away from my computer this evening. I do see the problem in your code. Look at your report test! You are attempting to convert the element node contents of `<location>` into a number, but that is really a text string. Isn’t it the attribute value you want to convert? You won’t be converting it if it’s in a predicate filter!
