### ISSUE TITLE
Presentation Days

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#644]
Please leave a comment on which days you are able to go to Pitt Main for presentations.
I am able to go both Wednesday and Friday.

**Comment by BMT45** [comment]
I’m good for Wednesday but not on Friday

**Comment by frabbitry** [comment]
I'm good for Friday but not Wednesday.

**Comment by NADGIT** [comment]
When are we going to Oakland? I have a class on the afternoons of Wednesday and Friday, but I'm not sure if going out there will affect them.

**Comment by ebeshero** [comment]
@NADGIT Project presentation days in Oakland (at the Cathedral of Learning) will be on Wednesday 4/17 and Friday 4/19 at 10am! The Pittsburgh class starts **one hour earlier** than ours does. What that means is, if you have morning classes, they'd be affected, but you can easily get back to Greensburg for a 1pm class if you leave maybe a bit before noon. Often it takes me around 45 to 50 minutes to do the commute from Greensburg to the Pittsburgh--you want to leave some time to find parking, probably at Soldiers and Sailors garage or near Hillman library. We will figure out carpooling arrangements!

**Comment by NADGIT** [comment]
I'm alright with either day, I'll leave it up to my team.

**Comment by SparkTheDragon** [comment]
Any day works for me.

**Comment by KSD32** [comment]
I can do Friday, not Wednesday.

**Comment by koshinf** [comment]
Weds and Fridays are fine for me

**Comment by achen298** [comment]
i can do either class day in Oakland. I live 15 minutes away from Oakland

**Comment by ebeshero** [comment]
So far (after chatting with @BMT45 and @KSD32 yesterday), we know that Team Ulysses will need to present on Friday. 

Let's see if we can figure out the other project teams' schedule today.

**Comment by ebeshero** [comment]
On Wednesday, we will be in Wesley Posvar Hall Room 4130.

On Friday, we will be in the Cathedral 501. This is the English department’s presentation space.

**Comment by ebeshero** [comment]
Resolved! 
Pokemon and Banksy teams present on Wednesday

Bloodborne and Ulysses teams present on Friday.
@djbpitt @gabikeane

**Comment by djbpitt** [comment]
@ebeshero @zme1 Zac will be constructing the schedule, so I am tagging him on this response by way of ensuring that he knows which Greensburg projects will be presented on which days.
