### ISSUE TITLE
Using Javascript to Zoom

### ISSUE THREAD

**Issue by frabbitry** [ebeshero/DHClass-Hub#646]
@ebeshero I managed to do something kind of neat with Javascript, even though it looks aesthetically awful at the moment. The Ulysses website is definitely a work in progress, but [this page](http://ulysses.newtfire.org/Graphics.html) currently shows one of the Ulysses network graphs with a little zoom box that you can use to zoom in on the picture while mousing over it. 

My code for this borrows _heavily_ from [this W3C tutorial](https://www.w3schools.com/howto/howto_js_image_zoom.asp).

**Comment by ebeshero** [comment]
Thanks for experimenting with this, @frabbitry! It works wonderfully for me in Firefox and Safari, but the zoom window is not showing up at all in my Chrome (on a Mac). I have an idea, but I'm not sure if it holds water. You did this with inline JS, and I wonder if there's something Chrome isn't responding to--if you need something different to initiate the event or set an event listener. I wonder if we can try redoing this with an external JS file and if that might take care of the trouble! Let's talk more tomorrow...

**Comment by ebeshero** [comment]
Update! I hit refresh twice to reload the page in Chrome and it now works as advertised! But I wonder if we want to tinker with a DOM window.onload event listener to trigger the zoom...

**Comment by frabbitry** [comment]
@ebeshero I've been developing the website all... day... (and it still isn't anywhere near finished) but I came up with some new Javascript for zooming, which you can see on [the Telemachiad web page](http://ulysses.newtfire.org/TheTelemachiad.html) and [the Homecoming web page](http://ulysses.newtfire.org/TheHomecoming.html). I think that it might be a little bit cleaner because it gets rid of that extra viewing box that used to be there.

**Comment by ebeshero** [comment]
@frabbitry The new developments are wonderful to see! Yes, the JavaScript is improved, but the newly filtered and edge-bundled network graphs and discussion are even better—and I bet that is the part taking the most time...
