### ISSUE TITLE
T-Shirt Design: Please Respond ASAP with Sizes, by NOON Thursday 4/4!

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#647]
Greetings, all! We have a T-Shirt Design for this spring! 
<https://github.com/ebeshero/DHClass-Hub/blob/master/T-Shirt-Designs/newtFireBanksy_CDVsm.jpg>
It'll be printed on light grey shirts to mimic the idea of Banksy graffiti on concrete. 

Please leave a comment on what shirt size you want for our class shirts!
Thanks!
I would like a medium.
@koshinf @SparkTheDragon @JAG240 @James-f117 @achen298 @abdual1100 @NADGIT @frabbitry @alnopa9 @KSD32 @BMT45

**Comment by ebeshero** [comment]
![newtFireBanksy_CDVsm](https://user-images.githubusercontent.com/4014518/55510616-a77c4600-562c-11e9-8716-dd4f0d234ea9.jpg)

**Comment by BMT45** [comment]
I would like a large

**Comment by NADGIT** [comment]
I'll take a medium.

**Comment by ebeshero** [comment]
Also--donations are welcome, though I will not charge anyone for shirts. This is a thing we do as a kind of artistic rivalry with our sibling course in Oakland. :-) I need to get the shirt orders in before the good people at the T-shirt place place orders for ice-grey shirts tomorrow afternoon! I'll need to place the order around 1pm.

**Comment by frabbitry** [comment]
I will also have a medium.

**Comment by KSD32** [comment]
I will have a medium, please.

**Comment by ebeshero** [comment]
@koshinf @achen298 @JAG240 @SparkTheDragon T-shirt size, please? I need to place our class's order around 1pm today.

**Comment by JAG240** [comment]
I'll do a medium

**Comment by koshinf** [comment]
Large would probably work for me

**Comment by achen298** [comment]
Sorry if I’m to late. I didn’t get the chance to look after work yesterday. I would be a medium if it’s not to late

**Comment by ebeshero** [comment]
@achen298 Got it! I ordered an extra one that was medium when I placed the order. Good to know I guessed right! :-)
