### ISSUE TITLE
Schematron Help!

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#65]
Here is what I have. I have no clue how to structure this. I think the rules I want are supposed to go into the quotations, but I am not sure. 
`<?xml version="1.0" encoding="UTF-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"
    xmlns:sqf="http://www.schematron-quickfix.com/validator/process"
    xmlns="http://purl.oclc.org/dsdl/schematron">`
    `<ns uri="http://www.tei-c.org/ns/1.0" prefix="tei"/>`
   `<pattern>`
        `<rule context="xsd:int">`
            `<assert test="."></assert>`
        `</rule>`
   `</pattern>`
`</sch:schema>`

**Comment by blawrence719** [comment]
From what I can tell, you have the document set up correctly and you're right that your rules should go in the `@test` attribute where you have your quotations. Your `@context` attribute should be matching on something in the document, though - similar to how we use matched on things in xslt. Then in your `<rule>` you will specify exactly what you want from your document. Not sure if this helps your problem.

**Comment by ebeshero** [comment]
Completely agreed with @blawrence719. :+1:
