### ISSUE TITLE
Project Presentation Schedule + Carpooling Arrangments

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#651]
# [Project Presentation Schedule](http://dh.obdurodon.org/presentations_2194.xhtml)
### Cathedral of Learning 501 (English department)

* *[Such syntax, much meme](http://meme-syntax.obdurodon.org/)* [(GitHub)](https://github.com/rmf96/MEMECULTURE): 10:00-10:08
   * 10:08-10:10: transition
* *[The Banksy project](http://banksy.newtfire.org)* [(GitHub)](https://github.com/alnopa9/banksy): 10:10-10:18
   * 10:18-10:20: transition
* *[Catch and release in Edgar Allan Poe](http://poe.obdurodon.org/)* [(GitHub)](https://github.com/Ethandaniel47/EdgarAllanPoeProject): 10:20-10:28
   * 10:28-10:30: transition
* *[Pokemon map](http://pokemon.newtfire.org)* [(GitHub)](https://github.com/JAG240/Pokemon-Map): 10:30-10:38
   * 10:30-10:40: transition
* *[Mapping Gulshani's gazetter of Bukhara](http://gazetteer.obdurodon.org/)* [(GitHub)](https://github.com/pickettj/central_asia_gazetteer): 10:40-10:48

---

### 4130 Posvar Hall 
(take the escalators all the way up to the 4th floor)

* *[Comparative literary analysis of midrashic texts](http://midrash.obdurodon.org)* [(GitHub)](https://github.com/sjw82/Midrash): 10:00-10:08
   * 10:08-10:10: transition
* *[Bloodborne lore](http://bloodborne.newtfire.org)* [(GitHub)](https://github.com/koshinf/Bloodborne_Lore): 10:10-10:18
   * 10:18-10:20: transition
* *[Gender analysis of women's Serbian songs](http://serb-songs.obdurodon.org/)* [(GitHub)](https://github.com/emmamamula/Yugoslav-Folklore): 10:20-10:28
   * 10:28-10:30: transition
* *[The Ulysses project](http://ulysses.newtfire.org)* [(GitHub)](https://github.com/frabbitry/Ulysses): 10:30-10:38
   * 10:30-10:40: transition
* *[Detecting orientalism in Sherlock Holmes](http://sherlock-orient.obdurodon.org/)* [(GitHub)](https://github.com/loreese/sherlock): 10:40-10:48

@koshinf @SparkTheDragon @JAG240 @James-f117 @achen298 @abdual1100 @NADGIT @frabbitry @alnopa9 @KSD32 @BMT45 @djbpitt @zme1

**Comment by ebeshero** [comment]
Who's riding in with whom? And where are we meeting each other? Please be sure to exchange contact info, either here or privately.

**Comment by ebeshero** [comment]
And we'll coordinate this in person in class on Monday!

**Comment by ebeshero** [comment]
Friday: Who's driving?
* 8:30am:  **Dr. B** and Frank, Brad, and Kiara  --possibly Donald? (be in the UPG main parking lot where the sidewalk leads to McKenna)
* Nathan and **Fiona** driving in together
*

**Comment by ebeshero** [comment]
Here's a map with presentation locations for **Wednesday: (4130 Posvar Hall)**, and **Friday: (501 Cathedral of Learning)** marked: 

https://www.google.com/maps/d/viewer?mid=1B3OJfU5nJFaMk2inntFrciuN5Dv47mrl&ll=40.44164340000003%2C-79.95381850000001&z=15

**Comment by ebeshero** [comment]
![upgDH2019PresentationDay](https://user-images.githubusercontent.com/4014518/56308775-14f0a200-6116-11e9-8f35-9baaa38d3c83.jpg)

Banksy and Pokemon teams survive the Pittsburgh presentations! :-D You all did brilliantly!

**Comment by djbpitt** [comment]
Great job, Team Banksy and Team Pokemon!

**Comment by ebeshero** [comment]
Just updated our schedule with revised locations. Obdurodon has posted the room change as well: http://dh.obdurodon.org/presentations_2194.xhtml

Map: https://www.google.com/maps/d/viewer?mid=1uQOIeeRLA9f7NHkwMbqVYDY_47ulg6pC&ll=40.443020270326144%2C-79.95395649091148&z=15
