### ISSUE TITLE
Saxon JS tutorial

### ISSUE THREAD

**Issue by NADGIT** [ebeshero/DHClass-Hub#655]
**Using Saxon JS is easier than you think.** Seriously, it's really simple to use its basic functionality. There is apparently some really advanced stuff, but that should fall out of the bounds of this class.

**First of all, you need to install a plugin into oXygen:**

1. Connect to the internet, open oXygen, and click 'Help' on the toolbar.

2. Click 'Install new add-ons...'

3. In this new window, click the drop down menu labeled "show add-ons from:". Select All Available Sites.

4. There should be an entry labeled "Saxon 9.(something number here) XSLT and XQuery Transformer. Check the box next to that entry and click Next. Upon clicking next, the download and installation of the plugin will install.

5. You should notice a new button on the same row as your "new", "open", and "save" buttons which reads "Compile XSLT Saxon (version number)".

(if you need a visual guide on how to install, [here is a nifty video](https://youtu.be/hxWJjRGQ3ls?t=204))

So, what is it that you just did? Saxon JS can use your XSLT code to do transformations on XML, but it can't access XSLT files. Instead, it uses SEF files. In order to export an XSLT file to SEF, click the "Compile" button, and a dialogue will appear. The top bar is the file you'd like to export to SEF, and the bottom bar is the name and location of the exported file. Make sure the target is set to "JS", and click on the folder next to the bottom bar to determine where you'd like to save your file and what its name should be.

**Implementing Saxon JS serverside**

First of all, a bit of an important note: I say "serverside" here because, though Saxon JS runs completely in the browser, your server will store the files for Saxon JS, _and_ Saxon JS can only access files held on a server. It uses HTTP requests to access files, and these requests cannot be used to access files stored locally on your computer.

1. So, the first step is to put all of your XML files on your web server, preferably in their own folder.

2. You should also upload any .SEF files you plan on using too, and give them their own folder.

3. You must now add Saxon JS itself to your server. This too is rather simple: go to [this page](https://www.saxonica.com/saxon-js/index.xml) and click the download button. You will be taken to a downloads page, and choose the latest version of Saxon-JS. Saxon-JS comes as a zip archive file. Adding Saxon JS is as simple as extracting this archive into a folder in your server. Within it, you'll notice two folders of resources and two scripts: Saxon JS and its miniature form. These two scripts are the entirety of Saxon JS. **Do not mess with anything in this folder. You will only reference these scripts as a link in your HTML page.**

Saxon JS' miniature form has less features, but runs faster. Most projects you undertake shouldn't need those extra features, so it's best just to use the miniature version.

**Finally, the HTML page!**

Writing the HTML so that it runs an XSLT transformation has specific syntax. Your XSLT must also be written in a special way, but that will be discussed below. 

1. First, you'll have to link Saxon JS itself. Since it's a script, you can link it like any other script. Your link should look something like "<script src="(filepath to Saxon JS)"></script>". Once you've done that, you should be able to reference its functions like any other script.

2. You need to write the script in a very specific way. Something like this:

SaxonJS.transform({
                                stylesheetLocation: "XSLT/yourStylesheet.sef",
                                sourceLocation: "XML/mainXML.xml",
                                });

3. You're done! Place that in a function and run it.

... But wait, my page isn't doing anything. Why?

**XSLT and the "Result document" tag**

As I said before, your XSLT has to be written in a different manner than normal. XSLT, on the surface, seems like a script that simply takes in an XML file and output a transformed file. In reality, it's capable of a lot more. For one, an XSLT stylesheet can interact with an existing document and edit it. This is done via the result document tag:

`<xsl:result-document href="#bodyDiv" method="ixsl:replace-content">`

The above line of code says "Look in the document I'm interacting with, find the node that has "bodyDiv" for the value of its id attribute, and replace its content". These are used instead of the "apply-templates" tag. The result-document paradigm is something you should really look into - it's an extensive and powerful method for running your stylesheets. 

How do I make sure that the result document is the webpage that Saxon JS is running in? Saxon JS does that for you: simply make sure that you have nodes for the XSLT stylesheet to insert values into. You can use the href attribute to locate nodes via a URI statement, but using ids might be easier most of the time.

**Using IXSL to get parameters**

Sometimes you'd like to pass a value to an XSLT stylesheet so that it can use it. This can apparently be done through xsl:params, and you specify the parameters when you run the Saxon JS transform function... But I cannot get it to work and the documentation on the subject is quite poor. On the other hand, there is another way to pass values from your HTML to the XSLT.

Once again, XSLT runs much deeper... Much deeper... _Much darker.... Into the beautiful dark..._

Hm? What was I saying? Ah, whatever. Basically, XSLT is a full-fledged programming language, even capable of interaction during processing. This includes simply extracting data from the document it is editing and extends to even receiving input from the user in the form of key presses and clicking.

For parameters however, only one function of IXSL (Interactive XSL) is necessary: ixsl:page(). ixsl:page() is an XPath function that returns the DOM of the result document. This way you can use XPath to access your result document and get text from it.

For instance, for my project, before my Javascript function ran the XSLT stylesheet, I had it grab the [query string](https://en.wikipedia.org/wiki/Query_string) and insert it into a div. I then could use ixsl to set a variable equal to the contents of this div:

`<xsl:variable name="pQString" as="xs:string" select="ixsl:page()//div[contains(@id,'queryString')]/text()"/>`

You can use IXSL and JavaScript to make [some really deep applications](http://www.saxonica.com/saxon-js/documentation/index.html#!samples).

**And you're done!**

[But, it's probably good to keep your documentation on hand...](http://www.saxonica.com/saxon-js/documentation/index.html#!about)

**Comment by ebeshero** [comment]
Thank you, @NADGIT ! @djbpitt , here is that tutorial we requested! :-)

**Comment by crazymontecristo** [comment]
Hi! I'm new to this, so this is more of a probe than a comment. I'm using Saxon-JS for my own project and here's what I've discovered so far. The intermediary sef file needs to have a JSON extension as far as I understood the Saxonica documentation on the subject, so it would be "XSLT/yourStylesheet.sef.json". (Node.js has a library XSLT3 to transform xsl file to sef.json from the command line). And the xslt tag <xsl:result-document> seems to be optional now, if the goal is only a static xhtml page (i.e. no interactivity involved). I think the differences could be attributed to the latest updates of the technology rather than anything else in this post.

**Comment by ebeshero** [comment]
@crazymontecristo Thanks—this is very helpful! @NADGIT was exploring SaxonJS in spring 2019 so we should revisit this and update it as you suggest!
