### ISSUE TITLE
Seeking volunteers: DH Conference in Pittsburgh: ACH 2019, July 23-26

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#658]
Hi DH students all and sundry! We are seeking volunteers to help staff and support the ACH Regional Conference in Pittsburgh, PA at Duquesne University. It's July 23-26, and I need (very soon) to send a list of student volunteers willing to help coordinate the event. Please let me know (@ebeshero) if you want to help out, by the end of May if possible. Here's the link to the conference: http://ach2019.ach.org/ 

@frabbitry @bmt45 @rjp43 @jonhoranic

**Comment by alnopa9** [comment]
@ebeshero I'd love to help volunteer! 🙋‍♀️
