### ISSUE TITLE
Welcome to DHClass-Hub! Introduce yourself here!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#660]
Welcome to our DHClass-Hub, our class "mothership repo" where you can post issues when you need help and where we'll be hosting discussions. I need to invite you as members so you have authority to post new issues, close old ones, and "move in" to this space. I'd also like us to take this opportunity to get to know each other a little! Please introduce yourself 

oh cool you can edit the top comment too

**Comment by ebeshero** [comment]
Welcome all!

**Comment by ajw120** [comment]
Hello anyone who can help!
I'm currently working on XML exercise 2 and I just needed some advice on incorporating attributes. I'm still slightly confused. I'm sorry if this is such a simplistic task to have confusion on!

**Comment by ebeshero** [comment]
@ajw120 Let's open this question in a new issue!

**Comment by Bennediction** [comment]
Hi I'm Ben Hill!
