### ISSUE TITLE
CourseWeb won't let me submit XML Exercise 2

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#663]
When I try to upload my file, it tells me that "It may contain a security threat"? Does anyone know how to fix this?

**Comment by ebeshero** [comment]
Aha! First one of the semester. Courseweb randomly seems to balk
at code we submit thinking we are a bunch of hackers. If you get the security threat error, here’s what to do: Try zipping your file—on your computer, try right-clicking on an icon of your file to see if you can save it as a “zipped archive”. It’ll produce something with a .zip extension that is a compressed version of your file, which Courseweb should then be able to accept.

**Comment by amberpeddicord** [comment]
That worked. Thank you so much!
