### ISSUE TITLE
Can't find directory on GitBash

### ISSUE THREAD

**Issue by haggis78** [ebeshero/DHClass-Hub#664]
I have a GitBash command line window open, but it's not showing anything like the directory list shown under "Navigating directories" in the course page for today, and I can't figure out how to get there.

**Comment by alnopa9** [comment]
Do you know where you are in your directory files? Also, if you want to see your files in your current directory, type "ls". To navigate to another directory, "cd" followed by the directory name will navigate you to it. Or "cd .." will take you up exactly one directory.

**Comment by haggis78** [comment]
That helped me along -- thanks!
