### ISSUE TITLE
Office Hours for DH Help

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#669]
Here is when and where you can find our instructor team for in-person help!

**Alyssa Argento**: M W F right after class: 4 - 5pm either McKenna 136, or in FOB 131, our Center for the Digital Text

**Kiara De Vore**: T H 12 - 2pm in FOB 131, our Center for the Digital Text

**Dr. B**: W 4 - 5:30pm either in McKenna 136 or FOB 204; H 1:15 - 3pm in FOB 204, and by appointment

**Comment by haggis78** [comment]
I'm not sure whether I created a repo last week or not. I know that I have a folder labeled "GitHub", which is what we were told to call it, inside my general DH folder; but there is nothing inside that GitHub folder. I'm worried that solving the problem by definitely creating a new repo might, if I *did* create one already, wreak some kind of havoc. How can I know whether I created a repo? Where would I look to make sure?

**Comment by alnopa9** [comment]
@haggis78 You did create a [repo](https://github.com/haggis78/testing123). Since your GitHub folder on your computer is empty, you probably didn't clone your repo from GitHub to you computer. The easiest way is to click on the arrow next to your profile icon. This brings a dropdown list. Click on 'my repositories'. This will show you all of your repos and forks.

**Comment by alnopa9** [comment]
@haggis Do you need help cloning your personal repo to your computer?

**Comment by alnopa9** [comment]
@haggis78 To clone your repo to your PC:

1. Open Git Bash and move into your GitHub folder
    - ``cd [space]`` 
    - ``cd documents``
    - ``cd GitHub``
2. Copy the link for your personal repo from the main page. It's a green button that says 'Clone or Download'
    - ``git clone [paste link here]``
3. This will clone the current version of the repo to your computer. Remember to always pull before you push anything!
