### ISSUE TITLE
Modify in XSLT 7

### ISSUE THREAD

**Issue by KariWomack** [ebeshero/DHClass-Hub#67]
If the file we choose is too simple to do a lot of XSLT with, am I allowed to add element and attribute tags to the XML document for the sake of the assignment, or do I have to choose a different file? @ebeshero @ghbondar @RJP43

**Comment by KariWomack** [comment]
Really trying to get a lot of makeup work done. The sooner I know, the better. @ebeshero @ghbondar @RJP43

**Comment by KariWomack** [comment]
I also just pushed an issue of mine into the troubleshooting folder. Any insight on that would be wonderful as well.

**Comment by ghbondar** [comment]
Kari, for the purpose of this assignment, it's up to you. The goal of this assignment is to demonstrate your understanding of XSLT. Choosing a different file might be easier than spending time on additional markup, but in any case, please make sure to submit all of the files you use and those you produce. @KariWomack

**Comment by nlottig94** [comment]
Closing for Spring 2016.
