### ISSUE TITLE
Revealing Hidden File Extensions

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#670]
# Revealing Hidden File Extensions

## Windows
**Through Windows File Manager**
* In Windows 10/8.1 File Explorer, you can access it via View > Options > Change folder and search options. In Windows 7, open Explorer, press Alt on your keyboard to make the Classic bar appear. Next, click on Tools > Folder Options. Now follow the steps mentioned above. 

**Through Folder Options**
* Open Control Panel > Appearance and Personalization.  Now, click on Folder Options or File Explorer Option, as it is now called > View tab. In this tab, under Advanced Settings, you will see the option Hide extensions for known file types. Uncheck this option and click on Apply and OK.
[Credit](https://www.thewindowsclub.com/show-file-extensions-in-windows)

**Comment by KSD32** [comment]
## Macs
**Using Finder**
* Open new Finder window. In Menu bar, go to Finder > Preferences. Click on Advanced tab. Select the box that says "Show all filename extensions".
