### ISSUE TITLE
Syntax error: salutatio

### ISSUE THREAD

**Issue by haggis78** [ebeshero/DHClass-Hub#671]
In writing my schema, oXygen is saying that my use of the Latin word "salutatio"  is a syntax error. Specifically, it is unhappy with the first five letters. Is this a reserved word? 

What is odd is that it is only marked as a syntax error in one of the three places in which it appears in my schema, and moreover I used it as an element name in the xml document for which I am creating this schema and it did not cause any problems there.

![image](https://user-images.githubusercontent.com/39171157/64480478-438b1a00-d196-11e9-9062-97a5ce33f43a.png)

**Comment by haggis78** [comment]
And now it's fine with salutatio -- not sure how it worked itself out -- but doesn't like "date", even though it's part of a block that I copied and pasted in from newtfire! Whatever the problem is, note that it's still identifying the problem as five letters (or four and a space)  at the beginning of a line.

![image](https://user-images.githubusercontent.com/39171157/64480851-eb581600-d19d-11e9-8eee-676ddf026f50.png)

**Comment by ebeshero** [comment]
@haggis78 Can you paste in your code (using a code block in markdown) here? Or push your files so far up to Troubleshooting here on DHClass-Hub? I can't quite see enough to figure out what's going wrong. It *could* be that you're computer is very slowly parsing the RNG file, or a syntax error to do with a missing line ending...? But I can't see enough from the screen captures to tell.

**Comment by ebeshero** [comment]
@haggis78 And no, as far as I know, "salut", "salutatio", and "date" are not reserve words in Relax NG. The ones to watch are "start", "empty", "mixed".

**Comment by i-myers** [comment]
@ebeshero 

I am having the same problem. When I typed in the following:
paragraph = element paragraph { 1?, 2+ }, oXygen ended up highlighting just parag, not the raph of paragraph and keeps saying syntax error. I don't know if I am doing something wrong, but it keeps saying syntax error at just paragraph and I would like it to stop so I can finally align it with the XML document I am doing it for.

**Comment by ebeshero** [comment]
@i-myers Are you still seeing this error? I think you may need to account for text (just plain text) being inside your paragraph elements. It looks to me like you're accounting for attributes or elements, but not indicating that text could be inside the paragraph.

There are a couple of ways to do this. If your paragraph only has a couple of attributes on it, and inside is all text, you could just add the reserve word `text` in your content model.

But usually in a paragraph, you have elements floating unpredictably around text in what we think of as "element soup", with text as the broth and elements like noodles. In that case, Relax-NG uses a special reserve word and structure called `mixed{}`. Here is how it works for a paragraph that looks like this:

```
<paragraph n="1">text text text <elemA>....</elemA> text text text <elemB>....</elemB>text text text</paragraph>
```

To write a schema rule for the content of the element `paragraph` we need this structure:

```
paragraph = element paragraph {n, mixed{ (elemA | elemB)* }}
```
This keeps LOTS of options open: `mixed{}` syntax means, text can appear anywhere: before, after, in between any elements that turn up here. It means: make text soup. 
Then inside the `mixed{}` content we have a grouping: `(elemA | elemB)*`
This tells the computer: evaluate ANY element you see. It may be either `elemA` or `elemB`, and it may appear zero or more times. 
This rule, then, says that you may have elemA or elemB, both, or neither, as many times as you want and in ANY order, with text flowing freely around. 

Hope this helps! We'll go over it in class today.
