### ISSUE TITLE
"repeat of "string" or "data" element"

### ISSUE THREAD

**Issue by i-myers** [ebeshero/DHClass-Hub#673]
So I was finishing up my Relax NG but when I got to my last three, mainly the paragraphs, an error showed up that said "repeat of "string or "data" element". Now, I have absolutely no idea what it means or how to fix it. It mainly highlights the following **"introduction = el**ement introduction { "zero"*}. If I get rid of it, it just moves to the next line. So I honestly have no idea what is going on here. How do I fix this? What does it all mean?

**Comment by ebeshero** [comment]
@i-myers I might need to take a look at this in person, but check your `introduction` element, as well as the element that contains it. Do you want to permit text inside either of these? If so, are you actually permitting the presence of text in your schema rule for these elements? 

Take a look at my response to your earlier post: https://github.com/ebeshero/DHClass-Hub/issues/671#issuecomment-529602333 

And I'm in my office now (FOB 204) until I come to class so if you're free, come over and I'll take a look!
