### ISSUE TITLE
Working with Class Examples in DHClass-Hub

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#675]
# Working with examples from class 

Whenever we work on examples in class, be sure to save them locally to your computer! This save us from each pushing up the same changed file and chancing merge conflicts.

## What to do when you save over the files in the repo

Remember that git is used for **version control**. The easiest way to fix saving your changes over the original in the repo, would be to replace your changed file back the original. Git sees this as no changes made to the file, so there's nothing new to push to the repo.

**Comment by ebeshero** [comment]
I'm re-opening this issue because we'll all need a reminder the next time we need to use files in the Class Examples directory! Let's leave this up for a bit. :-)

**Comment by alnopa9** [comment]
@ebeshero sounds good! You know me, I just love closing issues.
