### ISSUE TITLE
Can't update association

### ISSUE THREAD

**Issue by haggis78** [ebeshero/DHClass-Hub#676]
Still pounding away  at the assignment due yesterday, I fear!

OK, so I associated the schema with the XML doc, and then got to work debugging. This involved fixing both the schema and the XML doc. However, now I have some new features in the schema that should validate things in the XML that were problems before, and I've saved both docs, but the XML still gives me the red square and says it's invalid. Of course, I haven't associated again yet to fix this -- but it won't let me! When I try, it brings up the Associate window, but it won't let me click on OK. What am I doing wrong here?
![image](https://user-images.githubusercontent.com/39171157/64618255-e79ade00-d3ad-11e9-9aa8-aff62fc5cde0.png)

**Comment by ebeshero** [comment]
@haggis78 It looks like this is the same schema file, right? That is, you updated your schema but saved it with the same file name to the same place, that is `C:\Users\Fay\Desktop\DH\GitHub\testing123\Charter_schema.rnc`. At least that is what I am seeing in your screen capture. If that is the case, you shouldn't need to associate a new schema line. You just want to refresh the validation by using the red checkmark button in oXygen. 

What the interface is telling you is basically, you already have a schema line that is associating this very file with your XML document. You *could* mark the box that keeps existing schema associations, but that would just duplicate the same schema line (if it works).

If I'm understanding you correctly, you changed your schema, maybe a lot, but saved it in the same location. If that's the case, you really do not have to update your schema association line. All that the schema association line does is make a connection to the Relax NG file stored at a particular location. It doesn't matter if you've changed that file a lot--it's still in that location.

**Comment by ebeshero** [comment]
@haggis78 When you make changes to your schema, you do sometimes have a wait a moment for those to register over on the XML file. And one thing you *must* do is make sure that your current schema is saved. oXygen shows you if the file is not saved by putting an asterisk (splat) after the filename in the tab just above it on your screen. If it is unsaved it would look like this:
 `Charter_schema.rnc*`
