### ISSUE TITLE
element "insert title here" not allowed, expected element or element end-tag "other tag here"

### ISSUE THREAD

**Issue by i-myers** [ebeshero/DHClass-Hub#677]
So I decided to go back to the first relax-ng exercise to maybe try and patch things up. Also to use it as a template for relax ng exercise 2. Now good news is I fixed up the text problem. Problem is now that for every main category (individuals, dates, letter, ideologies, etc) it says the following here:

element "insert an element from above here" not allowed anywhere; expected the element or element end-tag "introduction", "conclusion", or "paragraph"

Now thing is, those tags are at the very bottom, the schema itself is organized in the exact order of the XML assignment I based it off of. What do I do? How can I fix this? Apologies if these constant issues I face seem really, really annoying!

**Comment by ebeshero** [comment]
@i-myers Good to hear you're making progress! Your XML is pretty intricate. We were going through your schema this afternoon, and @alnopa9 was working her way through your XML. I'm taking a look now, too, but we have what you turned in yesterday. 

From what you're reporting here, my first thought is, check in your schema for the element that is supposed to hold each of these main category elements on your list. Is it the element you think it is? Check your spelling: if one letter doesn't match the code in your XML, your computer won't recognize it as the appropriate parent of these elements.

**Comment by i-myers** [comment]
@ebeshero I went through my schema and my XML, all of it spelled correctly and corresponding to each element and attribute. Now the attributes themselves are not affected. So let's take this for example 

main category #1 - Individuals (the element of the category, also first element tag)
author (sub element, then attribute for Lord Byron)
religious figure (sub element, then attribute for Jesus Christ
deceased friend (sub element, then attribute for Charles Matthews)
acquaintance (sub element, then attribute for Scrope Davies)
                               Individuals (element of the main category, element end-tag)

For some reason only the main category element tags are affected. Like I said, all of the elements and attributes are each spelled correctly. Not to mention for example when I typed up the schema, I did the main element tag, then said all the sub elements, then put the attributes within the sub elements. Not to mention it is only doing it with those 3, introduction, paragraph, and conclusion. Nothing on ideologies or dates. This is where I'm drawing the blank here. So how would I "allow" the tags like individuals, ideologies, etc?

**Comment by ebeshero** [comment]
@i-myers Look up one level above the affected elements. What is your element rule that indicates how much and how many `<author>` elements are permitted? 

Also, want to push your current schema and XML up to Troubleshooting here?

**Comment by alnopa9** [comment]
@i-myers @ebeshero The first problem with your schema is that you don't have your root element properly defined.
You have two 'letter elements
```
<letter> <!-- Which is your root element -->
<Letter> <!-- Which is what holds the actual contents of the marked up letter -->
```
You need to change your ```<letter>``` in your schema to contain the author, date, individuals, ideologies, locations, dates, and Letter.

**Comment by i-myers** [comment]
@ebeshero Here, I'll push both up to the Troubleshooting folder on here. Now though I am getting that repeat of "string" or "data" elements error again though. I'll let you see. I'm just trying to fix this relax ng exercise so I can do the 2nd relax ng exercise using this as a template.

**Comment by alnopa9** [comment]
@i-myers I think the easiest thing to do would be to start a new schema from scratch. Sometimes you can get lost and flustered when you keep trying to tinker with same one, and starting with a blank canvas can really help. When I was going over your XML file, I found it easier to rebuild your schema and work my way through the XML document.

**Comment by i-myers** [comment]
@alnopa9 I actually just did that first, but now the problem is that the (repeat of "string" or "data" elements) is running back on again, mainly at the element for Lord_Byron.

**Comment by i-myers** [comment]
@alnopa9 
Then maybe it would be for the best that I try to just do that instead. Apologies for all of this, unfortunately all of this for me is very, very new. So I am still trying to get all this down in my head on what *to* do and what not *to* do.

**Comment by alnopa9** [comment]
@i-myers Your 'Lord_Byron' is a value for an attribute, ```@I``` if I recall. You do not need to define attribute string values.

**Comment by ebeshero** [comment]
...so you'd want something like:

```
I = attribute I {"Lord_Byron" | "Someone_Else" | "Next_Person" }
```

**Comment by alnopa9** [comment]
@i-myers I can help you walk through the whole process if you have time tonight on here, or I have time after class to you as well.

**Comment by i-myers** [comment]
@alnopa9 I have time right now for it. Unfortunately I can't stick around after class because I have a class straight after our's. Though quick question, how do I disassociate a schema?

**Comment by ebeshero** [comment]
@i-myers The issue we saw is that your XML code is super complicated because you have some element names that are very similar to each other. When you go to write a new schema for new XML, you may want to keep it super simple: not so many element names. Think of categories you can use that broadly repeat.

**Comment by alnopa9** [comment]
@i-myers There's an orange/red push pin in the top toolbar of Oxygen. Click that and it will open the schema association window. On the right hand side of that window, there's a folder button. Click that and search for your schema file to associate with the XML.

**Comment by i-myers** [comment]
@alnopa9 I know that part, but I mean like is there a way to disassociate the schema I already have associated with the XML? Or is it just permanently associated with it and cannot be undone?

**Comment by alnopa9** [comment]
@i-myers Just delete the association line from your schema. It's the second line of code in your XML file.
```
<?xml-model href="argento_attempt.rnc" type="application/relax-ng-compact-syntax"?>
```
It will be in purple and resembles the line of code above.

**Comment by i-myers** [comment]
@ebeshero I will have to keep that in mind, thank you for the tip. So try and cut down on element names, and differentiate each of them so they do not get mixed up.

**Comment by ebeshero** [comment]
@i-myers Yes! That's key to what we want you to learn from the art of schema writing! :-)

**Comment by i-myers** [comment]
@ebeshero that makes it so much easier. Though now I should probably go back to my XML exercise 2 and rephrase the attributes to make it easier so then it can be easy for writing up the schema ;)
@alnopa9 thank you, I didn't know until now but now thankfully I do. I'm gonna go redo my XML exercise 2 and simplify it so then I can easily do the 2nd attempt of new schema (which will be easy!).

**Comment by i-myers** [comment]
@alnopa9 Is there any way we could ever meet up in person? I think it'd be really helpful if you could show me this to where I can actually see what to do. I ended up redoing the schema and simplified it a ton, but somehow more errors end up popping around. I don't think I'll ever truly learn this if I just don't really see it being done right in front of me.

Is there just a way we can contact one another to set up a meeting tomorrow?

**Comment by alnopa9** [comment]
@i-myers We sure can! That's what Kiara and I are here for, to help you guys learn and be confident with your XML coding! What time wrks best for you?

**Comment by i-myers** [comment]
@alnopa9 Well, for me I think tomorrow at 9 o'clock would be very helpful. I'm free for the whole morning and afternoon up to 1 as I have a class at that time. I also live up in the villages, so if you want to meet in my dorm or the village hall we can do either. Either works fine with me.

**Comment by alnopa9** [comment]
@i-myers Would 11 work, instead? And we can meet at our Center for Digital Text, FOB 131.

**Comment by i-myers** [comment]
@alnopa9 That can work, I will mark it on my calendar for tomorrow. I just need some help on how to do the relax ng 2 assignment, a walkthrough would be very helpful. So we'll meet there then!

**Comment by alnopa9** [comment]
@I-Myers Sounds good! See you tomorrow!

**Comment by alnopa9** [comment]
I'm going to be a few minutes late, but I'm on my way!!

**Comment by i-myers** [comment]
@alnopa9 
I'm right at the waitin' area here on the first floor, you'll find me there.
