### ISSUE TITLE
Having validation errors and not sure what to fix

### ISSUE THREAD

**Issue by ajw120** [ebeshero/DHClass-Hub#678]
So I have my code written and wrote my schema along with it. However when I associated them I must've done something wrong because every line shows an error that I am unsure what to do. It either says "text not allowed here; expected end-tag" or element 'blank' missing required attribute for 'blank' even though I have it written into my schema that it should associate. Just very confused and very stuck. Please help if possible.

**Comment by ebeshero** [comment]
@ajw120 One way to begin debugging is to start from the very top, and check to see which lines of your schema do not quite match what you have in your XML document.

Another way is to start with the very first error you see in the XML, and see if you can figure out what line of your schema is causing it to fire an error. If an error says "text not allowed here; expected end-tag" that usually means you have created a rule for an element that doesn't allow text inside. Did you use the reserve word `text` in your content model? So for example, if you want an element like `<author>` to contain text, you would need to write:
```
author = element author {text}
```
If you want an element like `<p>` to contain text, as well as other elements, remember you want to use the `mixed{}` syntax, like this:

```
p = element p {mixed{ (person | someOtherElement)* }}
```
If you want your element `<p>` to *also* have an attribute, that's not part of the mixed{} content, so we keep it separate:

```
p = element p {n, mixed{ ( person | someOtherElement)* }}
```
Does any of this help?
