### ISSUE TITLE
Project: The Foundation of Brecon Collegiate Church and School, 1541

### ISSUE THREAD

**Issue by haggis78** [ebeshero/DHClass-Hub#680]
**Project title:** The Foundation of Brecon Collegiate Church and School, 1541 (Dr. Campbell)

This is the leading edge of a larger scholarly project, and by participating in it at this stage, your name will be associated with the project going forward.

**Background:** When King Henry VIII was reorganizing the English church after the Reformation, he closed down all of the monasteries and took their property. Some of their buildings were re-purposed. In 1541, he issued a Letter Patent (formal royal proclamation) closing down the collegiate church (sort of a mini-cathedral) at Abergwili, in south Wales, and re-establishing it 40 miles west in the town of Brecon, giving them the buildings of the now-defunct Dominican friars there. The transplanted organization was given a new name, Christ College Brecon, and a new purpose, running a school. 478 years later, the school is still in operation.

**The sources:** The original Letter Patent is lost, but the government’s original file copy still exists at The National Archives in London, where I photographed it in 2018. Several other copies were made in the 1700s and 1800s, which I have also photographed. Except for the file copy, all of the other copies appear as an appendix to a collection of records of St. David’s Cathedral, which I am studying. This Letter Patent was printed in an obscure book in 1719.

**The question:** No two manuscripts are ever quite the same. The task will include a line-by-line comparison of all of the surviving copies (called “manuscript collation”). By looking for small alterations, it is usually possible to reconstruct a family tree (“stemma codicum”) of the manuscript copies. Using that, we can figure out which variations belong to the original text and which ones are copyists’ errors. Together with other evidence, this information can help us to determine how these manuscripts circulated among scholars and clergy in the 1700s. We would also research the history of Abergwili and Brecon to provide site users with some background information, such as old maps.

Do you need to know Latin? No! But you may learn some along the way, and you will definitely learn about palaeography (old handwriting). At first it looks entirely illegible, but you develop an eye for it surprisingly quickly. Also, I will be doing the actual transcription, and you would be comparing the transcription to the manuscripts to look for certain features.

![image](https://user-images.githubusercontent.com/39171157/64814672-eb775d80-d571-11e9-8de9-0ba76f2ab0c7.png)

![image](https://user-images.githubusercontent.com/39171157/64814692-f500c580-d571-11e9-8914-17f4b78657e7.png)

**Comment by ajw120** [comment]
As per Dr. B I am here to leave a comment and leave some feedback! This is very interesting and a crazy idea for a project! it's really awesome actually and you put a lot of thought and effort into this clearly. May be a bit difficult coding and attempting to translate latin documents into xml and html without exactly knowing what is being said, but I think it's a really interesting idea regardless.

**Comment by haggis78** [comment]
@ajw120  Good point -- I think I would want to write an English translation of the text anyway, and if I do that sooner rather than later, then we would all have the translation to place alongside the transcription. That would make it much easier and more interesting!

**Comment by haggis78** [comment]
Connor, the overlay is a cool idea. The challenge (aside from the technical challenges) would be that the word order would be different in Latin and English, so while it might be possible to do that with chunks of text, not every word would map onto the word it's translating. Still, I would ideally like to have a site where it is easy to call up the images and compare them with the text and translation, and this would be one way to do it.

**Comment by ebeshero** [comment]
@haggis78 @ChinoyIndustries The image overlay is quite a cool idea, and also possible. There are a few ways to do it: One is with annotations over images posted on the project website--as in what we see on our Dickinson project: http://dickinson.newtfire.org/16/1605.html

And here's an image overlay experiment! http://research.cch.kcl.ac.uk/proust_prototype/index.html (click on the MS image)!

**Comment by ghbondar** [comment]
@haggis78 How many image files do you have to work with? How many pages of manuscript are there?

**Comment by haggis78** [comment]
@ghbondar That remains to be seen. There are about 7 or 8 manuscripts, but so far I only have permission to reproduce one (the earliest) on the web. That one consists of 11 photographs, which is probably about par for the course. Most of the remaining manuscripts belong to St. David's Cathedral, and I think that they would be very happy to have them made available this way, but I haven't approached them yet. Assuming the project flies past today, that will be the next step. I don't expect to get permissions for the one manuscript from the British Library, at least not without paying a lot of money, but it's arguably less important anyway and can be eliminated. So can some other manuscripts post-1800, just to make for a more manageable scale of the project.

So: minimum 11, maximum maybe 80, realistically probably somewhere in between.
