### ISSUE TITLE
oXygen won't open on my Mac

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#681]
This morning, I updated my Macbook Pro so that I could download Filezilla (it required the most recent Apple update to download) for class and now oXygen won't open. 

I still haven't quite finished today's assignment, so if anyone has an idea on how to fix this that would be great!

**Comment by ebeshero** [comment]
@amberpeddicord I haven’t seen this problem before! But maybe try:

* restarting your Mac, and seeing if oXygen launches then.
* if not, try uninstalling oXygen ( look up how to uninstall software on your computer) and then reinstall it. 

And keep us posted!

**Comment by amberpeddicord** [comment]
@ebeshero Reinstalling thankfully worked! Thanks!
