### ISSUE TITLE
Project Proposal: Undertale 

### ISSUE THREAD

**Issue by ajw120** [ebeshero/DHClass-Hub#684]
**Project Title**: The Tale of Undertale

**Background**: I'm sure a some of you, if not a majority, have heard of the role playing game (RPG) game by the name of _Undertale_. It is a very popular game that is known by not only all PC gamers, but now it has ventured into the realm of console gaming. If you are not aware of what _Undertale_ is, I can give you a quick summary. It is the story of a fallen human that finds themselves in a different world. You're objective is to escape and find your way home, however there will be obstacles along the way. You meet a variety of other characters, some of which are enemies and others you can befriend. This game allows you to have alternative endings (depending on what choices you make)

**Idea**: I thought it would be fun and interesting to make a catalog type of website, like that of The Hamilton Project and The Pokemon Map Project. We'd have to go through and create markup for identifying each of the characters (there are a lot). This will be fun! We, as a project team, would have to follow through with the story line and properly identify each of the game's lead, supporting, and even enemy characters that are present throughout the game. We'd also have to go through and markup each of the actions that correlate with the highlighted character. With this, we could lead into explaining and showing the endings that the player is able to receive while playing. Even if you haven't played the game and aren't a fan, I'm sure by the end of it you will find a character that you will fall in love with (My personal fav is Sans), maybe even want to start playing the game for yourself. 

**Goal**: Our main goal would be to create an interactive site that allows players and viewers alike to click their way through _Undertale_ and get a taste of what they could experience if they decided to play the game. 

> "Take care of yourself, kid. Cause someone really cares about you." - Sans

**Comment by alnopa9** [comment]
@ajw120 The [Bloodborne Project](http://bloodborne.newtfire.org/index.html) did something similar last semester with the items and locations for Bloodborne and finding common themes. I think it would be fun to create a sort of database for the game!

**Comment by bobbyfunks** [comment]
sounds interesting to me because I love rpgs.  I've never played Undertale but seems like I'd be into it after looking into it a bit.  There's a lot of information to work with so that's good.  The game is free to play right? so that's also an added bonus.

**Comment by dylanmore** [comment]
This seems really cool! I've never personally played the game, but it would be interesting to highlight key moments that change the story with bold, or different colors, so that it would be easy for the users to look for a specific ending or path, and where it can diverge into another possible ending. It would let the users use the site as a guide to get the ending they want

**Comment by ebeshero** [comment]
@ajw120 What a fun project idea, getting into *game analysis*, which has been a great source of projects in the past! In addition to the [Bloodborne Lore](http://bloodborne.newtfire.org) and [Pokemon project](http://pokemon.newtfire.org) here at Greensburg that worked with game lore collected by fans, there was a terrific one at the Pittsburgh campus on [Twilight Princess](http://zelda.obdurodon.org/) that worked with an actual script of the game. 

It sounds like you might want to work with scripts of the game's interactions--and fans sometimes have made these documents available to share--for example, for Undertale: https://www.wattpad.com/story/74405311-undertale-the-game%27s-script 
Are there better resources you might want to work with? (I just found this one, for example: https://www.quotev.com/story/11185498/Undertales-Script, and notice that there's a button on the upper left leading you to more areas/ narratives in the game.)

If you're able to work with a game script like these, that can help a lot with writing markup toward a research question about the game. Here are some thoughts that occurred to me as I'm browsing to learn more about this game:
* What kinds of interactions do we see between the characters? 
* I've read that interactions don't have to be violent in this game, but there's a lot of puzzle solving. What kinds of challenges do game players face? What kinds of choices to game players have to make?
* What kinds of objects do we see shared/exchanged? (Could that give us perspective on what has value in this game world?)
* How do we experience the *world* of the game--from its settings? That might be something you need to supply to the text scripts, from playing the game--and add to the game lore with your project.

These are just some ideas. Game analysis is really a wonderful avenue to explore in a semester project!

**Comment by lmcneil7** [comment]
This is a really cool idea. I've never played Undertale, but I've always wanted to. This might be kind of crazy, but another addition to this idea would be as we provide information, also offer information about where they show up in the game or what roles they play in your process as you play the game. In essence, create a semi-timeline that shows the game and different endings and the involvement of each character in the game itself. I don't know much about Undertale, so it would be cool to see the game constructed like that in a website.

**Comment by amberpeddicord** [comment]
I think it would be so interesting to see how the different interactions and characters can lead to different endings! I've never played *Undertale*, but I have seen people talk about it and I know that it's something that people are really attached to. Mapping it out would add a whole new layer to the game experience that I think would be fun to dive deeper into!
