### ISSUE TITLE
Project Proposal: Grimm Brothers' Works

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#685]
# Jacob and Wilhelm Grimm
I think we are all familiar with fairy tale's like Cinderella, Rapunzel, and Hansel & Gretel, but for this project I'd like to look into the brothers who collected, wrote, and arranged the world's most influential and well-known works of folklore in the world, Jacob and Wilhelm Grim. Over the course of their lives, the Grimm brothers published multiple editions of these folktales, with almost every following edition becoming more rich and detailed in writing. For this project, I'd like to use XML to markup and compare the editions between each other, create a timeline of the Grimm brothers' lives, and create a sort of database for others to use to read and enjoy these tales.

## Questions
 * How were the tales changed from edition to edition
 * Relationships between characters changed from edition to edition
 * Religious/cultural impact on writings
 * Why were some stories cut
 * Map of where the Grimm Brothers' gathered info for the stories

### Some sources
 * [Project Gutenberg with different editions](https://www.gutenberg.org/files/59508/59508-h/59508-h.htm)
 * [Article that inspired topic](https://www.neh.gov/humanities/2015/marchapril/feature/how-the-grimm-brothers-saved-the-fairy-tale)
 * [Timeline for reference](http://www.grimms.de/en/content/timeline)
 * [D. L. Ashliman: Former Pitt Professor's Page](http://www.pitt.edu/~dash/grimm.html)
 * [Image catalog for 1812 printing of Kinder und Hausmärchen (German)](https://commons.wikimedia.org/wiki/Category:Kinder_und_Hausm%C3%A4rchen_(Grimm)_1812_I)
 * [1916 edition (English)](https://archive.org/details/fairytalesofbrot00grim/page/n5)
 * [1913 edition (German)](https://archive.org/details/anmerkungenzuden03grim?q=Kinder+und+Hausm%C3%A4rchen)
 * [Nice article that gives ideas for some research questions](http://mentalfloss.com/article/63113/5-ways-grimms-fairy-tales-changed-after-first-edition)

**Comment by bobbyfunks** [comment]
I had a similar idea of just folktales in general but you beat me to it.  Focusing on the Grimm Brothers (or Brothers Grimm) makes sense because that in itself is a lot of informatoin.  I like fairtales and myths and there are many different versions.  You could even get into common themes and motifs that are found throughout the tales.  I'd be into this idea.

**Comment by alnopa9** [comment]
@bobbyfunks My first thought was doing something with Aesop's fables; finding themes, using data to compare which animals occur the most often, and using string length to find the longest and shortest works. I didn't thinkk there'd be enough for a whole semester project, so I switched to the Grimms' works. I'd like to use the markup for your points as well!

**Comment by ebeshero** [comment]
@bobbyfunks @alnopa9 There's a project from the Pittsburgh campus a few years back on Aesop's fables that investigated character types and actions across the fables: http://aesop.obdurodon.org/ If you click through their site you'll get a sense of what they were marking up. I can't find where they got a copy of the fables to work with, but here they are on the project site: http://aesop.obdurodon.org/reading-view.html It looks like they're pretty enormous until you see how short they are! It isn't clear to me where they found their source for the fables, but it must be a freely available version in English online, and it looks like the team stored all the fables in [one giant XML file](http://aesop.obdurodon.org/aesopsfables_all.xml).

 Is there a good online "base text" to start with to build an XML project on Grimm's fairy tales? One great place to look is Project Gutenberg: http://www.gutenberg.org/files/2591/2591-h/2591-h.htm 
and we'll be working with some of their texts in a few weeks to show you how to use "auto-tagging" to rapidly turn those into a simple XML document that you can use as a base for project markup.

**Comment by ebeshero** [comment]
By the way, *either* Aesop's fables or Grimm's fairy tales, or some other collection would work well as the basis for a semester project! If you took on Aesop, you'd just want to approach the fables in a distinct way. (I remember I had lots of questions about why they chose to categorize the language in the tales the way they did.) A new project team should take a fresh approach.  

And Grimm's fairy tales look really interesting for a markup project!

**Comment by Bennediction** [comment]
As someone that loves to see how drafts change over time, this project is interesting to me. I think it'd be interesting to come up with XML tags that highlight changes between each edition and to examine possibly why they made the changes that they did.

**Comment by lmcneil7** [comment]
I think this is good idea, not just because I like fables like the ones the Grimm Brothers write, but I like analyzing stories to see how even small details that were changed from edition to edition could change a story. Maybe one way to do that is to point or highlight a change between two editions and have a comparison on how the change affects the story. Also in like footnotes, how that change affected people's reception to the story and whether or not it was positive or negative change. Or if the change was intentional even with the Grimm Brothers expected a negative reaction.

**Comment by smdunn921** [comment]
This project seems super interesting-- I know I was interested looking at the Emily Dickinson project and seeing how those editions changed over time, but opening it up to look at fairytales could definitely bring a wider audience. Lauren's comment about how it would be cool to see how a change affects the story made me smile; I think it could definitely be a very cool and (as I keep saying) interesting project
