### ISSUE TITLE
Project Proposal: WW2 Timeline

### ISSUE THREAD

**Issue by dylanmore** [ebeshero/DHClass-Hub#687]
Obviously covering the whole war would be way too time consuming, but covering a specific period such as D-Day and after, or Operation Barbarossa's first months. Specific units could be discussed, tracking a few key divisions or something similar. As well, it could keep track of casualties on both sides, such as the changes in leadership as battles were won and lost.

The real goal of this would be to show how WW2 was ever-changing, and to show how many lives were lost in exchange for the most minor of victories

**Comment by ebeshero** [comment]
@dylanmore An XML project needs some good "base texts" to start with. Is there some good online material that a project team could start with to investigate World War II events in the way you're thinking of here?

**Comment by dylanmore** [comment]
Some online sources that would be useful:
http://www.holocaustresearchproject.org/nazioccupation/opbarb.html - timeline of Operation Barbarossa
https://www.ranker.com/list/a-list-of-all-operation-barbarossa-battles/reference - list of operations during Barbarossa

**Comment by mattnowakowski** [comment]
I would suggest possibly doing the U.S. campaign in the Pacific during the same time period, specifically island hopping.  There is more documentation, that is easier to obtain.

**Comment by ads171** [comment]
I'd be interested in seeing how many Russian soldiers were killed by their comrades when taking Berlin from the Germans.
