### ISSUE TITLE
Project proposal - Pokedex

### ISSUE THREAD

**Issue by Bennediction** [ebeshero/DHClass-Hub#688]
My project proposal is to create an online pokedex that contains information such as the types and stats of each pokemon. Creating entries containing all of this information could be useful in sorting Pokemon by their stats or number of available moves or for seeing trends such as which stats tend to be higher in certain Pokemon types over others.

**Comment by ajw120** [comment]
I am a huge Pokemon fan, so this made me happy to see on this board. There's another Pokemon project that was done by students and I loved that one too! This would be rather fun with going through each region and identifying which Pokemon came from which region and also personalizing their Pokedex entries!

**Comment by ebeshero** [comment]
Just last spring a student team made http://pokemon.newtfire.org, which does just this—categorize Pokemon characters by Pokedex, powers, and region on the Kanto map. Can you think of a way to differentiate this proposal from that project?

**Comment by Bennediction** [comment]
This project would be different than the one from last spring due to my project having a focus on every Pokemon, not just the first 151. My project would not focus on where each Pokemon can be found, but would focus on the individual statistics of the Pokemon, such as their attack, defense, and health, which was not covered by last year's project. Whereas last year's project found the correlation between type and where the pokemon were located, my project would instead focus on the correlation between pokemon typing and the statistics of the pokemons' powers. This project could potentially expand to examine the abilities and attack moves available to each pokemon.
