### ISSUE TITLE
Project Proposal The effects of industry on the environment and CO2 emmisions

### ISSUE THREAD

**Issue by jwa32** [ebeshero/DHClass-Hub#689]
I would like to create a project set around the changes in the environment due to industry and CO2 emissions. Due to these changes the Earth is beginning to warm up and it is very important to our way of life. Recently a large portion of the amazon rain forest was destroyed due to cattle farmers burning down trees and plants to open more land for hundreds of cattle, but at the cost of thousands of acres of life giving oxygen created by trees and other plants. In China one of the largest manufactures of the world, they utilize coal burning power plants to produce around 70% of their electricity. Because there is so much coal being burned daily people in China must wear face masks to avoid breathing in toxic fumes that are linked to cancer and respiratory failure.

**Comment by lewisabia** [comment]
The fact that people in China have to wear masks and have been for a while now is insane because they and most of world continue expand industrialization when scientists have been telling us about this for a long time now. I think this will be great project to bring awareness in a visual and interactive way.

**Comment by ghbondar** [comment]
An important subject! What kind of texts do you anticipate marking-up for this project? Perhaps, you could compare the 5 or 6 reports by the IPCC, which are one of the definitive summaries of the subject: https://www.ipcc.ch/reports/
