### ISSUE TITLE
Project Proposal: Greek Mythology

### ISSUE THREAD

**Issue by lmcneil7** [ebeshero/DHClass-Hub#690]
I had an idea about taking Greek mythology and categorizing it by the Gods and Goddesses. 
**Background:** My first in-depth look into Greek mythology was the _Percy Jackson Series_ which is kind of cheesy, but they're really good books and actually talk a lot about Greek mythology. The problem is I would like to know more, but there's so much information that's kind of intimidating. Just typing Greek mythology in Google isn't going to just start giving you stories. However, the idea started up when I realized that Greek mythology is like a map. If you just look at the twelve Olympians (Zeus, Poseidon, Hades, Athena, etc.), that family tree is complicated. Not to mention heroes like Hercules have relations to those twelve.

**Idea:** My idea is what if we created a map of some sort (maybe based of the familial relations or involvement in their personal stories) and build from the Olympians to stories like Calypso, an nymph and daughter of the Titan Atlas, who is visited by Hermes who was ordered by Zeus. Since there's a lot of stories, we can make an ending point so that the information becomes too much. For both options, if we do familial relations, then we can include a lot of people. Zeus alone had a lot of kids. Then we can include documents about what story has the most significance to the Heroes or Gods, etc. I wasn't sure if this was possible, but it would really helpful.

**End Goal:** To create an interactive map that gives people more insight into Greek mythology, but also categorizes a lot of that information in a simple format that's understandable. It would also be cool if we could create it where you click on a person and get their story, but also offers links to the people involved in the story. For instance, Calypso: being able to click on her and read about her story on keeping Odysseus on her island, but then be able to click for information on Odysseus , Zeus and Hermes for their involvement in her story.

**Comment by amberpeddicord** [comment]
I *love* this idea! I've had the same problem with wanting to know more about Greek Mythology but not knowing how to go about it (though I haven't read the Percy Jackson books unfortunately!). A map would be a great way to pull it all in and organize it to make it easier to understand for people who want to know more.

**Comment by lewisabia** [comment]
I like this idea it actually inspired mine on ancient Egypt. I used to play the game God of War which is based on Greek mythology so this project seems like it would be fun to be reminded of those many different characters, ideas, and believes.

**Comment by ajw120** [comment]
I love love love this! I am also a huge Percy Jackson nerd, or at least was whenever the books were in their prime time. Greek Mythology has so many loops and different storylines to follow so it would be super interesting to have it all marked down a map that allows people to click their way through it.

**Comment by ghbondar** [comment]
Interesting idea! Are you planning to map location around the _real_ Mediterranean landscape, or perhaps create a map of the mythical landscape? Think about finding specific texts to mark-up.

**Comment by haggis78** [comment]
You should be able to find out-of-copyright translations of Greek mythology online easily enough, though you'll want to make sure they are not so old that they are difficult to read (archaic language) and that they are consistent with one another. Ideally, you would want to look for a set all translated by the same person. An additional source could be the appearances of the gods and goddesses in Homer's Iliad and Odyssey, which you can also find online in out-of-copyright translations. I'm sure that these have been mapped, too, so when (say) Athena shows up at place X, that's an addition to your map -- though as Prof. Bondar says, you'd have to decide whether it's a real or mythical map, since some of the locations don't exit on the real map.
