### ISSUE TITLE
William Blake Project

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#691]
**Background:** William Blake was a poet, artist, and engraver from the 19th century. He has a poetry collection titled *Songs of Innocence and Experience* that is split into two books, Innocence and Experience, as is in the title. Each poem in the collection is accompanied by an engraving also done by William Blake. In the series, there are "Contraries" between certain poems (i.e., Innocence vs. Experience, etc.). There are tons of contrary possibilities that I think are really interesting to study!

**Project Idea:** For the project, the goal would be to code for different images and themes in the poems in *Songs of Innocence and Experience* to see if we could code for these contraries and see which images connect across the whole series. We could also find a way to include code that covers the artwork that goes with each poem!

**Comment by ghbondar** [comment]
This sounds like an interesting textual mark-up and analysis project. One key will be to avoid duplicating the achievements at the William Blake Archive http://www.blakearchive.org/, although this can likely be a useful source for texts and images.

**Comment by smdunn921** [comment]
I dig this idea because I definitely do think it would be interesting to look at the different themes and contraries. It also might just be that I really enjoy poetry though so I obviously would dig something where I'd get to analyze it.
