### ISSUE TITLE
Project proposal - Ancient Egyptian Pharoahs

### ISSUE THREAD

**Issue by lewisabia** [ebeshero/DHClass-Hub#692]
I've always been interested in the many different pharaohs from ancient Egypt. My proposal is to create a timeline of some of the most impactful pharaohs from Egyptian history with their accomplishments and innovations. Each addition to the timeline will include the various writings, images, and family information that are still available. There will also be a map that expresses the changes in the empires, explanations of the various pyramids' constructions and their significance to astronomy.

**Comment by ghbondar** [comment]
This sounds very interesting (not even considering the fact that I am an archaeologist who digs in Egypt)! The trick will be to find documents to mark-up, but I bet there are some available texts online.
