### ISSUE TITLE
HTML Exercise 1 Submissions

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#693]
Post your links here to your sites after you complete HTML Exercise 1!

**Comment by dylanmore** [comment]
https://newtfire.org/~dym7/

**Comment by lmcneil7** [comment]
https://newtfire.org/~lam289/

**Comment by smdunn921** [comment]
https://newtfire.org/~shd79/

**Comment by lewisabia** [comment]
https://newtfire.org/~lea31/

**Comment by haggis78** [comment]
https://newtfire.org/~whc7/
I know I'll need to learn to resize graphics!

**Comment by Bennediction** [comment]
https://newtfire.org/~bjh101/

**Comment by amberpeddicord** [comment]
https://newtfire.org/~amp293/index.html

**Comment by bobbyfunks** [comment]
https://newtfire.org/~rap159/

**Comment by jwa32** [comment]
file:///C:/Users/jesha/Desktop/DIGITAL%20HUMANTIES/index.html.xhtml

I need to work on renaming or using the existing link at newtfire.org
