### ISSUE TITLE
Project Proposal: Vampires in American Folklore

### ISSUE THREAD

**Issue by smdunn921** [ebeshero/DHClass-Hub#694]
Okay so this was all I could come up with because apparently my brain doesn't want to cooperate with me for ideas but hey at lease I have *something*. 

**Idea:** The idea of vampires has changed plenty nowadays versus how they used to be spoken about, so I figured why not like compare what they used to be perceived as, especially just in America. I did a quick search in Google Ngram Viewer (shoutout to Dr. Greenfield) and there's not really any hits shown until around 1760-- this makes sense, as the vampires we're familiar with today (human-esque ones, that is) have Slavic origins, I believe, so I didn't expect many early hits.  Basically, we can like search for anything people were saying about vampires whenever they first started being spoken about in America through like now and see the different ways people have portrayed them. We can look for similarities and differences and basically how the idea of them in America has changed through the years.

I have no sources on hand, but we always have access to databases and whatnot and can use some of those to see what people were saying, especially because a quick google search won't get anything substantial.

**Comment by haggis78** [comment]
Interesting. There are definitely stories of the restless undead from medieval England and Scotland, and sometimes they harm people and have to be dug up and reburied at a crossroads with a stake through the heart, but I don't recall any that are specifically blood-suckers. Still, those older stories of  wraiths and revenants probably fed into the ways in which vampires were conceived of once the stories reached Western Europe.

Perhaps you could have part of the site where a timeline shows when each characteristic (association with bats, cannot tolerate sunlight, sleeps in a coffin, etc.) first shows up in American literature, film, etc. Then you could have a link from each point to the relevant passage in the text. In the case of films, you probably couldn't post the film clip yourself, but you can create a link to a specific moment anywhere in a YouTube video.

You would also want to think about whether to include books published abroad that would have been sold/read in America.

**Comment by ghbondar** [comment]
The n-grams are a good start. What kinds of documents do you anticipate marking-up with XML? Remember that these are mark-up projects first-and-foremost... the website is for displaying the results of your mark-up, it is not the goal in itself.
