### ISSUE TITLE
Project Proposal: Teen Titans

### ISSUE THREAD

**Issue by lmcneil7** [ebeshero/DHClass-Hub#695]
Okay, so Dr. B said that I could post more than one project proposal and I just wanted to mention this one because it's one that I would want to do, but also I was wondering if I could receive feedback to make it more realistic. 

**Background:** As mentioned in the title, the proposal is about Teen Titans. If you don't know what Teen Titans is, then I'm going to give a brief summary about it. It's a cartoon network show that was created in July 19, 2003 and aired until January 16, 2006. It's based off the DC Comics's superhero team of the same name. The Teen Titans are made out of a lot of people, but the primary characters are Robin, Raven, Starfire, Cyborg and Beastboy. There was also a movie called _Teen Titans: Trouble in Tokyo_ and recently was rebooted as Teen Titans Go! which is still currently airing on cartoon network. There's another reboot called Titans which is live-action and currently airing on DC Universe. Titans started in 2018 and Teen Titans Go! started in 2013.

**Idea:** This is where it starts to become unrealistic. My idea was making an interactive comic using Teen Titans animated series and the comic books surrounding the Teen Titans. While I mentioned Titans and Teen Titans Go! in the background, I don't plan to use them in the project. The idea is to go through each episode and pull out similarities or differences to the comic books; since the show has five seasons, I would stick to the first season. It would be constructing an analysis of Teen Titans and it's accuracy to the original content.

**End-Goal:** My goal is to create a comparison between the comics and the cartoon in a way where you could learn about both without even watching the show.  It's showing the involvement of the comics in the animated series and where it differs. 

**Problem:** Does this even count as a proposal? I wasn't too sure if the information would be relevant or it would be hard to actually accomplish because how much we would have to look at to make this possible. I was wondering if anyone had any ideas. Another problem would be attaining the comics. 

**Sources:**
Transcripts of the Episodes:  https://transcripts.fandom.com/wiki/Teen_Titans
Origin Explanation: https://www.ign.com/articles/2018/10/10/history-of-the-teen-titans-explained-who-is-dcs-youthful-superhero-team

**Comment by alnopa9** [comment]
@lmcneil7 I **love** DC's Teen Titan's in all forms! This sounds like a good project proposal! I think it's pretty reasonable to do. One thing you can do is see how similar the characters' backstories are in Teen Titans TV show to the comic; this can be our main protagonists and secondary superheroes that get included as well as our beloved baddies, like the H.IV.E and Slade. Another would be to see if the first season (or any season, really) centered on a specific arc from the comics and the differences between them.

**Comment by ghbondar** [comment]
Having transcripts means that you already have texts to mark-up... that is a BIG plus!

**Comment by smdunn921** [comment]
I love this idea so so much. And it's not just because I love Teen Titans either-- though that *is* a plus. It definitely just seems like an overall cool and fun project.
