### ISSUE TITLE
Project Proposal: Woodbury Clay Co. Papers

### ISSUE THREAD

**Issue by ChinoyIndustries** [ebeshero/DHClass-Hub#696]
**Title:** Woodbury Clay Co. Papers: a Portrait of the Fire Clay Mining Industry in Central Pennsylvania 

**Background:** (Apologies for the wall of text.)

I'm in this class because I already have an existing document digitization project underway--I collect and maintain a small library/archive of railroad-specific books, documents, paperwork, timetables, maps, diagrams, artifacts etc., with the eventual goal of making the bulk of it publicly accessible online. One particularly unusual item in my archive is the Woodbury Clay Co. papers: a special collection consisting of a cache of around 120 pieces of loose Pennsylvania Railroad shipping paperwork, originating from the clay mines of Oreminea, PA in the 1930s, which I managed to recover from a large dump of random old paper at a flea market near Altoona in the spring of 2017.

From the late 19th century, through the years immediately after WWII, the mining of "fire clay” was one of the predominant industries that developed in the mountains of south-central Pennsylvania. (What is fire clay? It’s a special type of silicate clay, fired to make bricks which can withstand high temperatures, aka “fire bricks”—an integral material in the construction of furnaces and steel mills.) Along the Pennsylvania Railroad's main line and branches through Huntington and Blair counties, a number of clay mining companies and company towns sprung up and brought population and prosperity to otherwise uninviting areas. Manufacturers of fire brick products, called Refractories, constructed various clay mines and brick kilns throughout the region. Both raw fire clay and manufactured fire bricks were exported from this area throughout the eastern U.S. and Canada, providing much of the refractory products used by the steel industry here in Pittsburgh.

The documents found from the Woodbury Clay Co. detail individual shipments of fire clay out and supplies into the clay mining town of Oreminea in the years 1925, 1931, 1933 and 1937. They include Reports of Carloads Weighed—that is, receipts for outbound shipments of fire clay—and Freight Bills, or receipts for inbound supplies and merchandise for the company and the surrounding town, plus a handful of other items. Put all together, these offer an interesting glimpse into the workings of a company town from one of Pennsylvania’s less well-remembered industries during the Great Depression.

**Potential Project**
This is pretty much a ready-made project—I actually went through and digitized this collection about a year ago, scanning all 120 individual sheets and tabulating summaries of them in various ways. Upon completion, I had no way to readily publish it anywhere, so I ended up just sending copies to a few pertinent historical societies and museums, as a donation to their library collections, and to a few interested individuals. This class offers an outlet not only for publishing this collection online in the interim (while I develop an actual website to host my library), but for expanding on the usefulness of the information it contains. 

By tracking and mapping the various companies to which the Woodbury Clay Co.  shipped boxcars of fire clay, we can illustrate a piece of the logistics network that fueled the steel industry, as well as the oversized impact this small area had on the industrial landscape throughout the eastern US and Canada. The inbound shipments can be mapped in the same way based on where they came from, illustrating a bit of the amazing complexity of merchandise shipments in the days when everything down to a carton of matches was shipped by the railroad. (there is a receipt in here for a carton of matches!)

There are really two particular groups of people who would find this collection to be a useful historical reference: those interested in the history of the clay-mining towns and companies themselves, and model railroaders of the Pennsylvania Railroad. Most folks in the model railroad community who build and operate their own layouts are very focused on being “prototypical”—that is, being accurate to the prototype, or the real thing. A boxcar has to have the right number of rivets; the factories along the tracks have to match the real ones from the time and place the layout is set in, and so on. A record of individual carload shipments like this, in such large numbers all from one source, is a rare and invaluable resource for these folks—it provides exact information on what cars would have been seen arriving and departing from a particular place, and allows modelers to more accurately represent this industry in miniature. I compiled a rough index of the car numbers found in these documents and the type of car represented by each one, and, in collaboration with the Steamtown National Historic Site up in Scranton, where I had an internship this summer, I have access to nationwide freight car roster tables from these exact years to allow a refinement of this data. With that, we can make a visual representation by year of the different kinds of freight car used in the service of the Woodbury Clay Co., an interesting subject to modelers especially since the spread of years included in this data happens to depict the demise of the final variety of wood-sheathed boxcar used by the Pennsylvania Railroad.

------

If anyone can stomach the boring subject matter and would like to work on this project, it would mean a lot to me to be able to expand this work and finally make something useful out of the labor that’s gone into it so far. If you'd like to take a look at the collection itself, I uploaded it in a folder in the Sandbox, or you can find the zip file [here](https://drive.google.com/file/d/1p-Ube94Z_x172RFFdmAkVcEJOPubRM68/view?usp=sharing).

**Comment by haggis78** [comment]
That's a very cool idea. I like in particular the way that you are already thinking about multiple potential audiences. Do these documents shine any light on the people who worked on the railways? If so, that might bring in another potential audience, labor historians. And has anyone else worked on the history of this company? You might be able to cross-reference this material with, say, the workers' wages or the company's profitability, or even more broadly the volume of steel being produced by furnaces in the region served by this company or the number of new furnaces coming on line. That might tell us some things about economic activity during the Depression, taking the user all the way from a carload of clay or bricks to the operational status of one of America's great industries in a time of stress.

**Comment by ghbondar** [comment]
This sounds like a great mark-up project! Are the documents in text-file form or only as pdf's? If they are not text-files, they will need to be transcribed, although OCR might be possible.
