### ISSUE TITLE
Project proposal: Stats of Steelers Seasons by Years

### ISSUE THREAD

**Issue by mattnowakowski** [ebeshero/DHClass-Hub#699]
I will do my project on the Steelers seasons throughout their extensive history and all of the statistics involved.  Starting with the "bad" years leading up until the early 1970's.  Then, I will include all of the years where Pittsburgh made the playoffs and specialize my project on those years and when they win their super bowls.  Then finish with the latest years leading up until 2018.

**Comment by ghbondar** [comment]
What kinds of documents do you anticipate marking-up with XML? Remember that these are mark-up projects first-and-foremost... the website is for displaying the results of your mark-up, it is not the goal in itself.
