### ISSUE TITLE
Is this how it works?

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/DHClass-Hub#7]

**Comment by ebeshero** [comment]
Yep! See if you can assign a milestone...

**Comment by spadafour** [comment]
I think this is how it works...comment!

**Comment by ebeshero** [comment]
Yes, you've got it. If you "close" the issue in the next comment it gets tucked into "closed" issues--so it's not an "open" issue calling for attention. Try closing this issue with your next comment!

**Comment by ebeshero** [comment]
Okay, I'll leave this issue open for one of you students to close, so you can see how to close an issue. :-)

**Comment by ghbondar** [comment]
Is this issue closed yet??
