### ISSUE TITLE
Project Checkpoint One

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#700]
# Teams are formed. Now what?

For project checkpoint number one you must 
 * The Project Leader must create a repo for your project
 * Into this repo, they should invite collaborators
   * Your fellow teammates
   * Dr. Bs (ebeshero & ghbondar)
   * Kiara DeVore (KSD32) and Alyssa Argento (alnopa9)
 * Create an issue in the Project Repo to find the best time for team meetings

### [Teen Titans](https://github.com/lmcneil7/teen-titans)
 * [Lauren](https://github.com/lmcneil7): Leader
 * [Shannon](https://github.com/smdunn921)

### [Environment](https://github.com/jwa32/CO2-Emissions-and-deforistaion-)
 * [Jeshua](https://github.com/jwa32): Leader
 * [Anthony](https://github.com/ads171)
 * [Lewis](https://github.com/lewisabia)

### [WW2: Barbarossa](https://github.com/dylanmore/OperationBarbarossa)
 * [Dylan](https://github.com/dylanmore): Leader
 * [Matt](https://github.com/mattnowakowski)

### [Undertale](https://github.com/ajw120/Undertale)
 * [Alexis](https://github.com/ajw120): Leader
 *  [Robert](https://github.com/bobbyfunks)
 * [Benjamin](https://github.com/Bennediction/RepositoryBen)

### [Brecon Church](https://github.com/haggis78/BreconChurch)
 * [Dr. Campbell](https://github.com/haggis78): Leader
 * [Amber](https://github.com/amberpeddicord)
 * [Connor](https://github.com/ChinoyIndustries)

**Comment by ghbondar** [comment]
We have assumed that the person who proposed the project will act as the project Leader, who creates the Project Repo, and does a few other tasks. If this is incorrect, or changes, please let us know!

**Comment by ebeshero** [comment]
And we are missing three, I understand. May I try to persuade @amberpeddicord and @ChinoyIndustries to try working with @haggis78 ? I know each of you has experience, unusually strong experience in fact, with working with primary spices—that is, manuscripts! From what I have seen of each of your work, you are well suited to work together, even though you may not knew each other yet...

**Comment by amberpeddicord** [comment]
@ebeshero I can join @haggis78 's project!

**Comment by haggis78** [comment]
@amberpeddicord Glad to have you aboard!
