### ISSUE TITLE
Project Websites Created on Newtfire

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#703]
I've now created a website directory for each of our semester projects.
To access your project webspace, when you access newtfire with your SFTP client (FileZilla or WinSCP), go up to the root `/` and browse down to:
`/var/www/html/yourprojectname` as listed below.

Make a bookmark there, and make another bookmark at your own personal webspace, so you can quickly locate each. Your bookmark should also get you started from the right local directory: 
* your personal GitHub :: personal webspace on NewtFire
* your team project Github :: your team webspace on NewtFire

We can help you set up those bookmarks if you need help! They will ease your file management. :-) You may start moving into your team webspace as soon as you're ready, and you may wish to create a "splash page" to get you started with Project Checkpoint 2.

**********

### Barbarossa: web directory name: barbarossa
 * [Website: http://barbarossa.newtfire.org](http://barbarossa.newtfire.org)
 * [GitHub](https://github.com/dylanmore/OperationBarbarossa)
 * [Dylan](https://github.com/dylanmore): Leader
 * [Matt](https://github.com/mattnowakowski)

### Brecon Church: web directory name: brecon
 * [Website: http://brecon.newtfire.org](http://brecon.newtfire.org)
 * [GitHub](https://github.com/haggis78/BreconChurch)
 * [Dr. Campbell](https://github.com/haggis78): Leader
 * [Amber](https://github.com/amberpeddicord)
 * [Connor](https://github.com/ChinoyIndustries)

### Environment: web directory name: eco 
 * [Website: http://eco.newtfire.org](http://eco.newtfire.org)
 * [GitHub](https://github.com/jwa32/CO2-Emissions-and-deforistaion-)
 * [Jeshua](https://github.com/jwa32): Leader
 * [Anthony](https://github.com/ads171)
 * [Lewis](https://github.com/lewisabia)

### Teen Titans: web directory name: teentitans
 * [Website: http://teentitans.newtfire.org](http://teentitans.newtfire.org)
 * [GitHub](https://github.com/lmcneil7/teen-titans)
 * [Lauren](https://github.com/lmcneil7): Leader
 * [Shannon](https://github.com/smdunn921)

### Undertale: web directory name: undertale
 * [Website: http://undertale.newtfire.org](http://undertale.newtfire.org)
 * [GitHub](https://github.com/ajw120/Undertale)
 * [Alexis](https://github.com/ajw120): Leader
 *  [Robert](https://github.com/bobbyfunks)
 * [Benjamin](https://github.com/Bennediction/RepositoryBen)

**Comment by alnopa9** [comment]
@ebeshero I just pushed the updated version of [2019CDASites.md](https://github.com/ebeshero/DHClass-Hub/commit/1f3c0ac46f30b75d79db7011149da975b27cc53b) that includes project teams, websites, and GitHub repos.
