### ISSUE TITLE
Help with a time increment in TEI?

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#704]
I'm currently trying to find the TEI element for an increment or span of time (so, where it says in the recipe to cook for 2-3 more minutes, I want to code the "2-3" as one element). 

Is there a good way to do this, or should I code both the 2 and 3 as separate measurements?

**Comment by ebeshero** [comment]
@amberpeddicord Great question! Take a look at the the `<time>` element and the examples for it on its element Spec page here: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-time.html  The `@dur` attribute is for time duration, and the examples with it show its use with a time duration datatype. This example is probably best for our purposes:
```xml
<time dur="PT45M">quarante-cinq minutes</time>
``` 
That's showing a duration of 45 minutes. Now, you could encode with two `<time>` elements, for each end of the range, but I might be tempted to just  encode a value in the middle: `dur=PT2M30S` (for two minutes and 30 seconds).  

That would be a way of splitting the difference on a range!
