### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by haggis78** [ebeshero/DHClass-Hub#707]
FYI -- the link to the Newtfire Regex tutorial from Friday's homework list on the syllabus is broken:

![image](https://user-images.githubusercontent.com/39171157/66333957-04bbc180-e906-11e9-914f-708a8dea54a0.png)

However, the link from the previous Wednesday correctly takes you there:
![image](https://user-images.githubusercontent.com/39171157/66334083-55cbb580-e906-11e9-9365-46170e42b237.png)

**Comment by ebeshero** [comment]
@haggis78  Thank you for the bug report! I've just repaired the link on the regex homeworks so afflicted, and posted the changes on the website. :-) They should work now.
