### ISSUE TITLE
Oxygen markdown preview window

### ISSUE THREAD

**Issue by ChinoyIndustries** [ebeshero/DHClass-Hub#708]
I can't believe **this** is what's finally made me ask a question on here, but when editing markdown files in Oxygen, the right-hand pane showing the document preview has disappeared and I absolutely cannot figure out how to toggle it back on. I've tried pressing at least 20 different buttons. Please advise.

**Comment by ebeshero** [comment]
@ChinoyIndustries Right-click in the window of the markdown file you're editing, and click "Show preview".

**Comment by ebeshero** [comment]
@ChinoyIndustries Does that work on your computer? It's what I do on my Mac!

**Comment by alnopa9** [comment]
@ChinoyIndustries @ebeshero Right-clicking and selecting 'Show preview' works on my windows computer as well
