### ISSUE TITLE
Autotagging Speakers

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#709]
I'm trying to find the speakers in the play, and at this point my search looks like this:
```
\n\n^[A-Z ]{3,}\s?
```
This worked pretty well except it's only grabbing the "MRS." part of the "MRS. PEARCE" speaker labels. How can I fix this?

**Comment by alnopa9** [comment]
This is because you're not including the period that is in 'MRS.' in your search. Since not all names include a period in the middle, you'll have to include a question mark to the period. You then need to add a repetition indicator to that group stating it may appear more than once.
```
\n\n^([A-Z ]{3,}\.+\s?)+
```

**Comment by amberpeddicord** [comment]
@alnopa9 You're a lifesaver! Thanks!
