### ISSUE TITLE
SVG Assignment 2 Update: Modified xsl:stylesheet and xsl:output statements

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#71]
We discovered in tinkering with our files after class that after all, if we want to be able to write XSLT with more than one template rule, we need to modify the `xsl:stylesheet `and `xsl:output` lines at the top of the file. I've added those lines to our [SVG Assignment 2](http://newtfire.org/dh/SVGExercise2_Alice.html), so you can just copy them from that page.

You can keep using this other XSLT you write, say, for SVG for projects, but you'll need to make another modification to add a default xpath namespace if you want to read from a TEI file. (You can find this in one of our XSLT assignment pages, and we'll post that info on the next assignment.

I've modified that on the sample XSLT files here on Github, and I've also pushed an alternate version of the XSLT that we ran in class, without using xsl:for-each, and with a template match on each chapter element in Alice. You may see the two slightly different stylesheets in our Class Examples directory, with my comments added inside the files. 

@amielnicki @CodyKarch @blawrence719 @brookestewart @ghbondar @RJP43 @rCarls @spadafour @KariWomack @spadafour @nlottig94

**Comment by nlottig94** [comment]
Closing for Spring 2016.
