### ISSUE TITLE
Test 3 (take-home): Regular Expressions

### ISSUE THREAD

**Issue by jwa32** [ebeshero/DHClass-Hub#714]
there is no link or download to the test on Blackboard

**Comment by ebeshero** [comment]
@jwa32 It’s there—I just checked. Click on “Tests” in Courseweb. Follow the link, which sends you to the test page on newtfire, here: https://dh.newtfire.org/RegexExerciseWarofWorlds.html

**Comment by jwa32** [comment]
Thank you
