### ISSUE TITLE
REGEX Test 

### ISSUE THREAD

**Issue by ajw120** [ebeshero/DHClass-Hub#715]
Hi, I'm sorry, I went to turn in my test and there isn't a link available on courseweb to submit it. Will that be up before class or sometime soon? Thank you!

**Comment by ebeshero** [comment]
@ajw120 The link is up! It's under "Tests" (and not the usual place where you submit homework). Go to Tests, and click on the title line: "Regular Expressions Test (due M 10/14)" and you'll be prompted to submit your files.
