### ISSUE TITLE
SVG 2 Question

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#72]
So I am having trouble with how to put the `preceding::` XPath inside my x and y values for my connecting lines.  I am trying to use `$xPosition` and `$yPosition` inside these as well.  For example, I would like to put `y2="-{preceding::$yPosition}"` , but it keeps giving me an error.  I'm sorry if this isn't explained well.  It is hard to put into words.

**Comment by ebeshero** [comment]
@nlottig94 I think I understand what you're trying to do, but the computer parser isn't getting it. That's because it understands $yPosition only as it sits in connection with the current context node you're matching on in your XSLT.  You want to make a new variable to tell it how to find the preceding (or preceding-sibling?) node in relation to the current node. You could call that new variable something like $prev-Ypos or something like that. Does that help?

**Comment by nlottig94** [comment]
Okay, so I added a new variable; however, I cannot figure out how to connect the lines to the preceding chapter's count of Alice's quotes.  This is what I currently have: `<xsl:variable name="prevYposition" select="preceding-sibling::chapter/count(preceding-sibling::q[@sp='alice'])"/>`, which is giving me a graph that looks like this: 
![image](https://cloud.githubusercontent.com/assets/14095715/11052340/0e6cb104-8725-11e5-8d5e-8968a2607f7a.png)

**Comment by nlottig94** [comment]
I am so lost right now.  I am going to try to look at it again tomorrow and see if a fresh set of eyes in the morning will help.  @ebeshero @RJP43 @ghbondar If you could look at this and see what I'm doing wrong, I would really appreciate it!

**Comment by ebeshero** [comment]
@nlottig94 Looks like some lovely candles on a cake! ;-) Okay, you need to take out the old lines from our class example. You're currently drawing lines from the x axis up to each count, but you need to make lines that move from the preceding point to the next one. If you can make a *local variable* as you say, try just writing a new `<line>` element right after you draw your circle, and see if you can make one end of that line have the x and y coordinates of the count for the preceding chapter, and make the other end be the current x and y position, where your circle is poised. If you've got the circles plotted, you've got one end of each line drawn!

**Comment by nlottig94** [comment]
Okay, I have tried to do this with the local variables with XPath, but no matter what I did, I couldn't figure it out.  I have just applied my initial mathematical formula to the points and did it by hand.  Everything looks good as it is now, but I'm still going to try to figure a new XPath.
