### ISSUE TITLE
XSLT 5: Directory file error

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#723]
I keep getting an error message that says my directory doesn't exist. This is what I have so far: 
```
 <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    <xsl:variable name="dickinsonColl" select="collection('Dickinson/?select=*.xml')"/>
    
    <xsl:template match="/">
        <html>
            <head><title>Dickinson Poems</title></head>
            <body>
                <xsl:apply-templates select="$dickinsonColl//body"/>
            </body>
        </html>
    </xsl:template>
```

What am I doing wrong?

**Comment by amberpeddicord** [comment]
Never mind! I was able to figure it out!

**Comment by ebeshero** [comment]
@amberpeddicord What was the issue? I was about to respond that I think it's to do with the location of your file directory in relation to your XSLT file on your computer...

**Comment by amberpeddicord** [comment]
Yes! The issue was that I wasn't specific enough with where the directory was located, so I fixed it by typing out the entire path.

**Comment by ebeshero** [comment]
Good. And yes, it has to be identified in relation to where you save the XSLT file. You're basically configuring where XSLT is supposed to be looking to process its trees for the collection.
