### ISSUE TITLE
posting markup?

### ISSUE THREAD

**Issue by bobbyfunks** [ebeshero/DHClass-Hub#725]
how can you post examples of markup in an issue on GitHub?

**Comment by ebeshero** [comment]
@bobbyfunks You use the tick marks, top left key on your keyboard, to set up a code block in markdown, like this:

```
Code
Code
```
Click on the pencil to edit this and you will see how I placed three tick marks above and below the block of text.

**Comment by bobbyfunks** [comment]
cool thanks!
