### ISSUE TITLE
DH T-Shirts!

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#727]
Hey DH Team!

So, here is the proof for what the fall semester DH shirts usually look like. [DH Shirt Proof](https://raw.githubusercontent.com/ebeshero/DHClass-Hub/master/Sandbox/dh-shirt-proof.jpg)

Comment below your size and color!

@KSD32 @lewisabia @amberpeddicord @Bennediction @smdunn921 @lmcneil7 @haggis78 @ajw120 @jwa32 @bobbyfunks @ChinoyIndustries @dylanmore @mattnowakowski @ads171

**Comment by ajw120** [comment]
Alexis Williams: Small and Yellow

**Comment by lmcneil7** [comment]
large and green

**Comment by Bennediction** [comment]
Ben Hill: XL and blue

**Comment by smdunn921** [comment]
large and grey

**Comment by jwa32** [comment]
Jeshua anderson: Large Green

**Comment by mattnowakowski** [comment]
Large and yellow please

**Comment by lewisabia** [comment]
medium grey thanks

**Comment by amberpeddicord** [comment]
large and yellow please!

**Comment by ebeshero** [comment]
@Bennediction I don't have a blue option here, though I can ask about it. Do you mean the light grey? Or the green? Here's [the proof](https://raw.githubusercontent.com/ebeshero/DHClass-Hub/master/Sandbox/dh-shirt-proof.jpg) again.

**Comment by ebeshero** [comment]
@Bennediction: In case it's a little unclear (colors can be weird on monitors), you could indicate the color based on position from left on the proof. 

Also, I don't think I heard from @bobbyfunks or @haggis78 ?

**Comment by haggis78** [comment]
XL grey. Thanks!

**Comment by alnopa9** [comment]
Medium in grey, please! 
And if they can do toddler sizes, a 4T for Parker, please! 😊

**Comment by KSD32** [comment]
Medium grey please!

**Comment by lmcneil7** [comment]
Hey @ebeshero, I didn't realize that there was a grey one; can i get a grey one instead of the green?

**Comment by bobbyfunks** [comment]
large green please!!!

**Comment by ebeshero** [comment]
@lmcneil7 Okay! I'll hide your earlier post so I don't get confused tallying this up. :-)
