### ISSUE TITLE
XSLT Exercise 7 Separate files?

### ISSUE THREAD

**Issue by lmcneil7** [ebeshero/DHClass-Hub#728]
@ebeshero Hey Dr.B, what's popping? I was wondering if for XSLT Exercise 7 if we should be doing separate files or if we can collaborate on one file and just both turn it in. -teentitans team

**Comment by ebeshero** [comment]
@lmcneil7 Well, my idea for this homework is that each of you does it in your own way, and you can decide which one (or all) of what you make is something you can use on the project!

**Comment by lmcneil7** [comment]
@ebeshero okay thank you!
