### ISSUE TITLE
GitBash Error

### ISSUE THREAD

**Issue by ajw120** [ebeshero/DHClass-Hub#729]
Hi!

I've been trying to push changes to Undertale's project repo and there continuously is an error, not allowing me to do so. Would someone be able to help me fix this issue, whether it be in class today or some time soon?

**Comment by ebeshero** [comment]
@ajw120 Happy to help--is it a merge conflict? I'm in my office right now if you want to come over. Or I can help right after class today.

**Comment by ebeshero** [comment]
@ajw120 I think you're sorted now, so I'm closing this--reopen if something goes wrong!
