### ISSUE TITLE
SVG 2 Circles: Plotting in Coordinate Space from 0, 0

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#73]
I'm having issues plotting my circles and the issue lies within my yPosition variable. Here is what I have:

`<xsl:variable name="yPosition" select="count(./q[@sp='alice'])*27.5"/>`
              
 `<circle cx="{$xPosition}" cy="{$yPosition}" r="5" stroke="black" stroke-width="1" fill="red" />`

I'm having trouble finding the xpath that I need to count the quotes. Even in the xpath window, I can't quite figure it out. Any guidance would be helpful.

**Comment by ebeshero** [comment]
@blawrence719 Is your current context a `<chapter>` element? I'm pretty sure it is, and I'm pretty sure you just need another forward slash after the dot, because you're looking only for `<q>` elements that are children of chapter, not all the descendants. All of the `<q>` elements are, I think, sitting inside `<p>` elements, so they're descendants, not children of `<chapter>`. Hope that helps!

If you're defining the variable inside <xsl:template match="chapter">, I think you want to step down two

**Comment by blawrence719** [comment]
Okay, I definitely tried that earlier and was getting an error, but now it is working, I think?

**Comment by ebeshero** [comment]
How's your output looking?

**Comment by blawrence719** [comment]
I took out my multiplier because I couldn't figure out to get it to work. Now I just have `<xsl:variable name="yPosition" select="count(.//q[@sp='alice'])"/>` and I'm unsure how to get these numbers into something that would translate onto the graph. Because obviously just counting the quotes gets me small numbers like 21, 40, etc. I'm not sure how to get these numbers to match up with my y axis. 

My labels on the y axis are like this: `<text x="10" y="750" text-anchor="middle">0</text>
          <text x="10" y="650" text-anchor="middle">10</text>'
and so the y goes down and the texts go up by tens. Not sure how to multiply my counted quotes to get y values in the hundreds. Does this make sense?

**Comment by ebeshero** [comment]
@blawrence719 You're going to need a multiplier, and it would make sense to try just multiplying by 10 to turn your 21 into 210 and your 40 into 400. Think about where those numbers are going to sit in relation to your axes, though, knowing that lower numbers are positioned higher.

When I write SVG like this, I find it easier to make calculations with an X and Y axis that meet at 0,0 (x=0 and y=0. And I subtract from zero so all my y's are just negative numbers. Now, that would be plotting off screen, except I can move the entire graph downward by a factor of say 600 or 700 units using the `<g transform="translate(x,y)">` element. `<g>` just means a group, and it's a way of bundling the parts of an SVG plot together. So if you've wrapped your whole graph in a `<g>` you can shift it down into viewable coordinate space on your monitor, but still do all your calculations from a zero baseline, which just makes life easier, I think. Here's how we did the X and Y axes in the class example today:

`<g transform="translate(70, 525)">
                <line x1="20" x2="20" y1="0" y2="-500" stroke="black" stroke-width="1"/>
                <line x1="20" x2="900" y1="0" y2="0" stroke="black" stroke-width="1"/>`

See how that's giving us a zero baseline? This way, you can multiply your count() by -10, and move *up* the screen from zero. Then the `<g>` element pushes the whole thing down into viewable space. Does that help?

**Comment by ebeshero** [comment]
@blawrence719 Just a quick update--I corrected a couple of errors in my post just now. Basically, I'm just recommending you try to
1) set your x axis at a y value of 0, and plot upwards using a negative number on your Y position. (Just put a negative sign on your multiplier, or in front of the variable for Y position when you use it.)
2)  multiply your count() by 10 (or -10)
3) use `<g transform="translate(x,y)">` to shift your graph into someplace readable, where all the values would be positive.

**Comment by blawrence719** [comment]
This helped a lot, I figure it out! Thank you!

**Comment by ebeshero** [comment]
Yay! Let's leave this open a while in case anyone else needs it. :+1:

**Comment by nlottig94** [comment]
Closing for Spring 2016.
