### ISSUE TITLE
Joining DHClass-Hub: Reply to this issue!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#738]
Welcome to our DHClass-Hub, our class "mothership repo" where you can post issues when you need help and where we'll be hosting discussions. I need to invite you as members so you have authority to post new issues, close old ones, and "move in" to this space. I'd also like us to take this opportunity to get to know each other a little! 

Please say hi to everyone here as soon as you have created your GitHub account, and I will add you as a collaborator to our class repo.

**Comment by alnopa9** [comment]
Welcome to DH, everyone! 😸 
I'm Alyssa, and I look forward to this semester with everyone!

**Comment by ChinoyIndustries** [comment]
Hi y'all, I'm Connor. Here's to a good semester of DH!

**Comment by benjaminc2020** [comment]
Hello, I'm Benjamin.

**Comment by Bryant-LettucePrime** [comment]
Heyyo

**Comment by amberpeddicord** [comment]
Hello all! I'm Amber, and I'm looking forward to another semester of DH.

**Comment by bobbyfunks** [comment]
how do class? im bobby and coding is fun.

**Comment by ChinoyIndustries** [comment]
> how do class? im bobby and coding is fun.

you sure about that?

**Comment by smdunn921** [comment]
Hi I'm Shannon! my favorite reaction emoji is the eyes. expect a lot

**Comment by biancamaginley** [comment]
Hi all! I'm Bianca

**Comment by bobbyfunks** [comment]
> how do class? im bobby and coding is fun.
> 
> you sure about that?

don't scare people away.

**Comment by robftg** [comment]
Hello I'm Robbie and my laptop is a toaster

**Comment by Bryant-LettucePrime** [comment]
> Hello I'm Robbie and my laptop is a toaster

relatable af

**Comment by lmcneil7** [comment]
sup dudes its me lauren yes

**Comment by smdunn921** [comment]
> sup dudes its me lauren yes

yes

**Comment by alnopa9** [comment]
> > sup dudes its me lauren yes
> 
> yes

yes

**Comment by amberpeddicord** [comment]
> > > sup dudes its me lauren yes
> > 
> > 
> > yes
> 
> yes

yes

**Comment by smdunn921** [comment]
> > > > sup dudes its me lauren yes
> > > 
> > > 
> > > yes
> > 
> > 
> > yes
> 
> yes

yes

**Comment by lmcneil7** [comment]
> > > > > sup dudes its me lauren yes
> > > > 
> > > > 
> > > > yes
> > > 
> > > 
> > > yes
> > 
> > 
> > yes
> 
> yes

yes

**Comment by ebeshero** [comment]
# MARKDOWN!!!!!

**Comment by alnopa9** [comment]
[Line Comment Issue from last semester](https://github.com/ebeshero/DHClass-Hub/issues/711#issue-504849677)

**Comment by frabbitry** [comment]
@biancamaginley debugging RelaxNG is my jam. What's up? (Also if you want, you could create a new issue on the DHClass-Hub about it)

**Comment by biancamaginley** [comment]
So I figured out how to make my RelaxNG green, but my XML is now red and when I try to find the syntax error, it sends me to my RelaxNG but I can't figure out which part isn't matching up
