### ISSUE TITLE
SVT 2 Following Y-Axis Issue

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#74]
I'm having an issue referring to my y2 variable. Basically, I'm attempting to count only the instances of Alice's speech in the DIRECTLY FOLLOWING sibling of the current chapter, but I keep getting a count of all instances throughout the rest of the document.
This is what I have:
`select="count(./following::chapter//q[@sp= 'alice']) * 7"/>`
I'm using `following::` and I thought that this would grab ONLY the directly following sibling, but it's grabbing all following siblings (its doing what I thought `following-sibling::` was meant to do).

It's probably a stupid thing that I'm overlooking; any advice???

**Comment by spadafour** [comment]
Hmmm...I seemed to have solved it, but with a solution that works for both `following-sibling::` and `following::` (defining the position of the following node in the predicate). However, I'm still not sure what the difference is between `following::` and `following-sibling::` (because my theory was wrong). Why did my initial code not work?

**Comment by spadafour** [comment]
Well, I've done a little googling and found my answer. Here's an explanation for anyone as stubborn as me that's still getting confused by this (the links use very helpful visual aids):

`following-sibling::` is a subset of `following::`

The `following::` axis grabs all descendants of the same parent node as the node you're working with, as well as their descendants.
http://www.zvon.org/xxl/XPathTutorial/Output/example17.html

The `following-sibling::` axis grabs JUST the descendants of the same parent node as the node you're working with and ignores their descendants.
http://www.zvon.org/xxl/XPathTutorial/Output/example15.html

**Comment by ebeshero** [comment]
@spadafour great resources! By the way, after our discussion of preceding:: and following:: with the recent Schematron Assignment (see Issue #70 ), I added more info on these interesting axes to our Follow the XPath tutorial: http://newtfire.org/dh/explainXPath.html#axes
Maybe I should link out to these nifty visuals you've located! Thank you! :+1:
