### ISSUE TITLE
Project Proposal: William Blake's *Songs of Innocence and of Experience*

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#744]
My proposal is one that I'm reintroducing from last semester! This idea focuses on a poetry collection that I read in Dr. B's 19th Century British Literature course by William Blake, titled *Songs of Innocence and Experience*. 

**Background:** In this collection, Blake sets up and heavily focuses on the concept of contraries. That is, he has poems and ideas *within* those poems that are meant to be contrasts to each other. The title is one example: innocence and experience. Many of the poems from the first half ("Innocence") have counterparts in the second half ("Experience"). This is done with different uses of images and language, and there are tons of different contraries that he sets up. 

**Project Goal:** The project goal is to visualize these contraries, and to see if we could markup these poems to code for these contraries. This will involve coding for different images, as well as including metadata about the poems themselves. 

Another idea with this (and one that I invite suggestions on!) is the artwork that Blake uses. Blake wasn't just a poet but an engraver and artist as well. Each of his poems are engraved on carefully designed plates that have images related to the poem surrounding it. I thought it would be interesting to find a way to somehow markup his art as well and incorporate it into the project (as it was so integral to the collection and to Blake's life and work). 

As an English major, I always seek opportunities to incorporate literature into my coding endeavors, and this project could be one way for a team to do so!

**Comment by Bryant-LettucePrime** [comment]
I love this idea.  Blake's work is easily accessible, fairly simple to deal with, and illustrating the contraries provided is a fun challenge.  I have no idea how we'd even begin to illustrate the artwork, but it's a crucial component to getting insight into the text - I think it's something we'd have to consider pretty closely.

Gotta be honest, I'd rather work on this project than any of the ones I've come up with lol.

**Comment by ebeshero** [comment]
About the artwork, there's a major [William Blake Archive](http://blake.obdurodon.org/) that has been working with old SGML to integrate images and text (it launched in the late 1990s and has been through many transmutations over the decades). There's also an older Pitt Obdurodon student project (from years ago)  on Songs of Innocence and Experience that worked specifically on lining up the poems as contraries on the site. See http://blake.obdurodon.org/

I don't mean to say this to discourage the project at all! I love these poems, too, and they'd be very tractable to work with, even for making connections out to the images on the William Blake Archive. But let's think about what you would be doing in a semester project that would take your own path through the poems in our Coding and Data Visualization course?

**Comment by djbpitt** [comment]
The Obdurodon Blake project is due for reclamation. It was written for an old version of eXist, and when the evolution of eXist caused it to stop working, we patched it pretty minimally. You’re welcome to anything you can reuse and reinvigorate.

**Comment by frabbitry** [comment]
I just wanted to comment that I think that there are some angles you could pursue with Blake's artwork that could be kinda cool. 

There has recently been some scholarly discussion about the perhaps inappropriate emphasis on text analysis in the Digital Humanities as a whole. While text analysis is of course extremely important and valuable, other types of analysis and other fields can also utilize digital methods to produce fruitful research. 

Using digital methods to explore artwork itself, such as digital image files, hasn't come along quite as quickly or as easily as using digital methods to explore text files. I attribute that largely to advances in computing power, which have arisen only recently. Media files are much larger and more difficult to work with than text files, and computers of the past just didn't have the capability to work with them without it using up a LOT of resources and it taking a LONG time. 

I think it might be interesting if you found a way to study the contraries in the artwork itself. I believe that the main thing that the William Blake Archive has going for it is that it stores Blake's art really well: "We supply reproductions that are more accurate in color, detail, and scale than the finest commercially published photomechanical reproductions and texts that are more faithful to Blake's own than any collected edition has provided" ([William Blake Archive](http://www.blakearchive.org/staticpage/archiveataglance?p=archiveataglance)). Developments in, for example, deep learning have proved extremely useful for finding features of artwork that allow it to be compared and contrasted with other works of art. What if you used deep learning methods to explore Blake's contraries through his artwork? Do the poems that are contraries of one another (The Lamb vs. The Tyger, etc.) have similar or different artwork, and what features of the artwork would tell us that? How does using digital methods compare to more traditional research done on this? After a quick glance it looks like the Blake Archive does allow access to an API, and maybe that could be used to get some of their data.

After writing out this long comment, I realize that I don't know if pursuing that kind of a research method using those digital methods would even work in this class, which is very focused on the tet analysis side of DH and doesn't cover any machine learning techniques, even the basic ones (and you'd want to use more advanced ones for image analysis). It would be a lot of work and you'd have to learn a lot, using material and software that isn't covered in this class, so maybe it's not the best idea. Still, I just wanted to say that I think that there are definitely ways to bring DH research to Blake's images (and I'm not sure if that's been done before??). Basically, I read your project proposal and was like "Oh! That would be a cool thing to do with Blake's images!" and then graced you with a needlessly long and possibly useless comment. Happy project-team forming!

**Comment by djbpitt** [comment]
With respect to representing image information in XML, you may find https://listserv.brown.edu/cgi-bin/wa?A1=ind2001&L=TEI-L#11 useful.

**Comment by smdunn921** [comment]
I liked this proposal last semester and was going to pick it if not for teen titans, but I still really enjoy it! Since you have so much you can use, I genuinely think it could run really well.
