### ISSUE TITLE
Project proposal 1/3: Revision History of Lord Byron's Giaour

### ISSUE THREAD

**Issue by Bryant-LettucePrime** [ebeshero/DHClass-Hub#746]
I'm cheating a bit.  I had three(+) project ideas and this discussion has seemed pretty dead so far.

In 1813, Lord Byron published _The Giaour: Fragment of a Turkish Tale._  In 1815, after seven revisions and over 1300 lines, he finished it - or rather - discarded it.  This mammoth piece has a fairly storied history of being roasted by English Literature critics; Writes E.H. Coleridge: "It is a hard matter to piece together the 'fragments' that make up the rest of this poem." From William A Marshall: "[The additions are] of little regard to the poem's plot or coherence"  In Byron's own words, writing _Giaour_ was "laborious."

After last semester's 19th century Brit Lit assignment, I see where they're coming from.

Any modern edition of the poem pulls pieces from a variety of editions and typically provides an outline for reference.  Footnotes are also readily available for clarity/discrepancies between iterations.

- **Background**

Much like its edition history, the poem itself is an epic tragedy.

Taking place in the aftermath of a [disastrous proxy war](https://en.wikipedia.org/wiki/Orlov_revolt) between the Russian and the Ottoman Empires, our tortured protagonist, a Christian in Muslim occupied Greece, avenges the death of his lover by killing her murderer... _her husband,_ a man instrumental to bringing safety and order back to the region.

The story is told from four different perspectives and illustrates a country in turmoil: at war with its glorious past after being conquered by the Turks, at war with its religion after being integrated into the Islamic world, at war with its church after being betrayed by its Eastern Orthodox allies in Russia, and at war with its very definition of _peace_ after righteous violence sows nothing but destruction for everyone involved.

By keeping track of how Byron made his life miserable writing this poem, we may gain a better understanding of how characters in _the Giaour_ are made miserable by the unfolding events.

- **Proposal**
Tag, track, or otherwise contextualize the revision history of _the Giaour._  Track important additions included in each revision, as well as any changes to existing pieces of the text.  Attempt to find patterns and/or themes that may provide some insight into Byron's decision to update it _seven times._ Focus of on how viewpoints of POV characters change with each iteration (if they do).

- **Text**
[_The Giaour: Fragment of a Turkish Tale_ from Project Gutenberg](http://www.gutenberg.org/files/21811/21811-h/21811-h.htm#Page_75) An outline of _the Giaour_ in all it's horrifying glory may be found after the Intro, in the Bibliographic note.

- **Additional Info**
I wrote a paper on this last semester and used Hypothesis.is to track working notes, further readings, and notes on revisions for the assignment.  Unfortunately, in my lack of foresight, this entire record is hidden from public view and relegated to our, now obsolete, class-specific group.

**Comment by ebeshero** [comment]
@Bryant-LettucePrime We can certainly add others to that hypothes.is group, and the content of your annotations could well be useful in the project. I can also help by outputting your annotations in a nice text format that you could work with, if you like, in your encoding! I can do that over the weekend and post the output here on DHClass-Hub if it's okay with you (though I might need a nudge if you don't see it by Monday...)

**Comment by ebeshero** [comment]
@Bryant-LettucePrime You might want to give a stronger pitch for this project, though! *The Giaour* is unusual and strange and fascinating for all kinds of topical reasons, too...such as. . . . .?????

**Comment by Bryant-LettucePrime** [comment]
>You might want to give a stronger pitch for this project, though! 

10-4. One second.

**Comment by amberpeddicord** [comment]
@Bryant-LettucePrime I love seeing another literary project in here! 

I think this could be an opportunity to use an element from the TEI (which we'll learn about relatively soon in class!). I've used it both on last semester's project and on the Digital Mitford Project. The element is the **critical apparatus** and it's a way to compare editions of textual documents. (You can see this in use in the [Brecon Project](http://brecon.newtfire.org/html/methodology.html) and in the [Emily Dickinson Project](http://dickinson.newtfire.org/) ). 

If you wanted to code for differences in the text of each revised edition, this could be a useful tool, and I would be completely willing to help out with it! (The critical apparatus is my favorite TEI XML tool to play with, so I seek every opportunity to use it. It's like...the most fun game of spot-the-difference).

**Comment by frabbitry** [comment]
Sorry for closing and reopening, guys. 

But LITERARY PROJECTS!!!! 

I'll keep this short, but I think that it might be really interesting to do some East vs. West orientalism analysis. Maybe look at which events or what kinds of events are happening in which locations, and maybe see if or how that changes with revisions.
