### ISSUE TITLE
Proposal: Breweries of PA

### ISSUE THREAD

**Issue by bobbyfunks** [ebeshero/DHClass-Hub#747]
My proposal is BEER! Pennsylvania is one of the beer capitals of the world and I would like to map out the various breweries and the kinds of beer they brew.  It could be reduced to western pa or by county.  But there are and have been lots of breweries so it could be interesting to see the rise and fall (during prohibition) and then rise again of breweries in Pennsylvania.

I don't have specific data to markup but I am confident that it is out there!

*i found some good info on ratebeer.com. It has all the current breweries and the varieties of beer they brew. Also recently closed breweries.
https://www.ratebeer.com/beer/breweries/brewers-directory-38-213.htm

**Comment by robftg** [comment]
Both of these seem like great ways to to use location mapping and overlay it onto a map of the relevant area. My only question would what kind of location precision would be used, cities and addresses would work for breweries but artillery would be better suited to gps coordinates

**Comment by ChinoyIndustries** [comment]
I suspect information on Pennsylvania's breweries would be easier to obtain, and sounds like a fun project to me. Could even map out some of the countless defunct breweries that have come and gone in PA over the years--there were thousands of them in the early 1900s and it could be very interesting to see where they concentrated over time, especially before and after Prohibition!

**Comment by lmcneil7** [comment]
I think this is a good start for a proposal, but as mentioned, it's missing texts for mark-up. I know data for locations of breweries is out there, but even then, I'm not sure if there's anything for you to mark-up with that in mind. However, I think you could get away with that by using a comparison of the breweries through meta-data. Or something similar to what Banksy did, which was not using any texts, but still producing a cool project! The main goal for a map is a good start, but it would probably be helpful to think of what else to do in terms of XML.
