### ISSUE TITLE
XSLT/Making SVG

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#75]
What does this do? `* $Interval"` I don't understand it's purpose.

**Comment by ghbondar** [comment]
That depends upon how you define this variable, so it's up to you. In the sample code we used in class on Monday, it was a variable we defined as the spacing between bars in our plot.

**Comment by CodyKarch** [comment]
Oh.. Okay. I get that.. Now, I have another question. What do I do to connect lines between points on my graph? Essentially, how do I find the "rule to govern them all" to pick out points individually?

**Comment by CodyKarch** [comment]
And why are we `* 7` ing the quotes by Alice? what does that do?

**Comment by ghbondar** [comment]
Our example from class calculates the plot for each chapter. To connect them, you take the point you've just calculated and use it as the endpoint for a line that either moves to the point for the next chapter, or to the previous chapter... or both if you want to impress us for a checkPlus! If I recall correctly, these data were used to make an argument about the changing frequencies that each gender speaks: http://alice.obdurodon.org/

**Comment by ebeshero** [comment]
@CodyKarch Multiply your count by some factor to make it more visible in your plot. It doesn't have to be 7. Try plotting without multiplying, and you'll see why you want to do that. Also, you may want to review my conversation about much of this from last night in #73

**Comment by CodyKarch** [comment]
Here is the best I can find to get my line: 
`<line x1="{preceding-sibling::xes}" y1="0" x2="{$xes}" y2="-{$yPos}" color="black" stroke="black" stroke-width="3"/>`

**Comment by ebeshero** [comment]
@CodyKarch We need more info to help now: What is $xes? And what is $yPos? How have you defined these variables?
One thing I notice is that you have not indicated that xes is a variable when you call the `preceding-sibling::xes` in your `x1` attribute. You're missing your dollar sign ($)there.  I'm not sure it will work anyway, without knowing how you have defined your variables.
