### ISSUE TITLE
Project Proposal 2/3 Ecology of Arrakis

### ISSUE THREAD

**Issue by Bryant-LettucePrime** [ebeshero/DHClass-Hub#750]
This one is SUPER nerdy.

_Dune_ by Frank Herbert is, rightly or wrongly, considered to be one of the most successful pieces of science fiction ever written, leaving tangible influences on the likes of George Lucas, Ridley Scott, Kim Stanley Robinson, George R. R. Martin, etc.  Baked into the text is a host of philosophical and political commentary, densely packed religious motifs and descriptions of spirituality, and an entire subtext of questions about environment and ecology - this last one now unfortunately outdated by the fifty years of research since.

The Planet Dune, or Arrakis, is the setting and itself the fulcrum of the novel's plot.  Its export, the Spice Melange, is secretly essential to spacefaring human civilization, but the world is inhospitable, covered in a desert and haunted by Sandworms the size of skyscrapers.  Its native people, the Fremen, have adopted a martial, self-sufficient culture that reclaimates and worships the other most valuable resource on Arrakis: _water._  Deep in their religion is hope of a _Mahdi_ who will fulfill the dream of terraforming Arrakis, creating a breathable, livable world for the Fremen - a place where water sits in huge pools called 'oceans' and falls from the sky in an event called 'rain.'

Spoiling the book slightly as it's essential for this assignment:
- The Worms produce the Spice.
- Water is poison to the Worms.
- The Fremen's dream will kill the Spice.

The ecological tension between the Fremen and the Intergalactic Community becomes the spark that sets off a firestorm and topples the balance of the novel's universe forever.  The details of Herbert's web are extensive and, for its time, well researched.  And like so many things in the book, it _presciently_ echoes modern hostilities between indigenous communities and global capitalist hegemonies, despite being based on information from the late 50's and early 60's.

- **Proposal**
Track references to Arrakis' ecology in Dune.  Map out the contexts of the conversations, the outcomes of the desired changes, how much information the speakers have on the topic, and which of the many competing factions they represent.

- **Text**
_Dune,_ 1964, by Frank Herbert.  Any edition probably.  I, um, have a pirated zip file of the full novel if anyone wants. :3

- **Additional info**
As anyone who's had the misfortune of reading my XML exercise 3 can tell you - Herbert's prose is fucking dense and this book is t h i c c.  The scope of the project may be the first thing we need to reconsider.  There are a handful of explicitly ecological conversations and observations that may suit our purposes better than scouring the entire text.

**Comment by ebeshero** [comment]
Alas, a problem with this is copyright! Now, if you could find an open-source game script based on Dune...
