### ISSUE TITLE
Project Proposal: Adventure Time

### ISSUE THREAD

**Issue by lmcneil7** [ebeshero/DHClass-Hub#751]
If you can't already tell from the Teen Titans project, I'm a kid at heart. Most of my ideas stem from things that I enjoy, but I would love to gain more info. Similar to how I came up with the proposal of Teen Titans, I went with an idea of something that was on my mind. In this time frame, it's Adventure Time.

**Background:** Adventure Time is another animated cartoon created for Cartoon Network by Pendleton Ward. It started airing in 2010 and is about the adventures of a boy named Finn and his dog Jake. It ran from April 5, 2010, to September 3, 2018. It has ten seasons and 283 episodes, each season having a different amount of episodes. Other main characters besides Finn and Jake are Princess Bubblegum, Marceline the Vampire Queen, and Ice King.

**Idea:** Keeping in mind that most of our projects will be to map/graph the information, I plan to map the route Finn and Jake take throughout their adventures. It's to give a detailed map of the Land of Ooo and indicate what places they visit frequently and which areas they visit once or twice. The route will start at the house and map where they go from there; it's to show the different locations of each episode. Similar to Teen Titans, for the sake of time, I will be focusing on season one only which has 26 episodes. 

**Research question:** What's the route that Finn and Jake take and is there a pattern based on the locations in chronological order of the episodes? Can a map be created of the Land of Ooo based on the locations that Finn and Jake explore?

**Sources:**
Transcripts: https://adventuretime.fandom.com/wiki/Category_talk:Transcripts
Description of the Land of Ooo: https://adventuretime.fandom.com/wiki/Land_of_Ooo
The current map of Ooo: https://www.reddit.com/r/adventuretime/comments/4eariz/a_nice_map_of_the_land_of_ooo/
~note: I said the current map of Ooo because of this project's goal is to create a fan-made version via the show itself.

**Comment by biancamaginley** [comment]
This looks like a really interesting project that wouldn't be hard at all to make fun! I'm also a kid at heart and wouldn't mind watching Adventure Time again. You seem to have the sources pretty well thought out already.

**Comment by smdunn921** [comment]
You seem to have a lot figured out on this and it would be super cool to see it happen!
