### ISSUE TITLE
Project Proposal: Behind the Minds of Composers Jessie Lacey and Vincent Accardi of 'Brand New'

### ISSUE THREAD

**Issue by benjaminc2020** [ebeshero/DHClass-Hub#753]
I'll first mention that I'm fanatic about music so I couldn't stop myself from picking a project proposal that encompasses some aspect of music. 

**Proposal and Background**
In short, my proposal is to depict and determine interesting patterns behind composers' lyrics over time through the lens of every song and album they've created. I chose composers Jessie Lacey (lead singer) and Vincent Accardi (lead guitarist) of the band 'Brand New'. Brand New is an interesting band that more or less peaked in the mid-'00s, popular for its rock/teenage angst feels. Nowadays Brand New has somewhat matured from their edgier style, but they still create music with very fascinating and deep, meaningful lyrics.

**Goal**
With all that being said, the question I'd hope to answer through this project is 'What are common messages and/or topic & word patterns behind this band's lyrical work?" Of course, this question can and is meant to be answered in multiple ways. Through encoding each song, (there's around 70) and then taking a broader view with the albums (there's around 9), the team behind this project would correlate themes, words, backstories, and anything else pertinent to our study and research.
Another reason I chose Brand New is that I already know quite a bit about their background and songs, so I know there would be some cool things to discover when looking at the data visualizations that would ultimately come about/what they relate to and the composers' intentions. I should mention, in case this proposal turns out to be a project, that if members were to absolutely insist on doing this type of research on another band, I'd hear them out.

**Comment by ebeshero** [comment]
This looks exciting! I did a quick search and located some lyrics for Brand New openly available here: https://www.azlyrics.com/b/brandnew.html, but perhaps there are better resources? One thing you can do with music as add metadata about the performances and production based on your listening. I imagine you won't be able to share music from your website the way the [Hamilton project](https://hamilton.newtfire.org) did unless this band is proudly open access in their production and distribution...

**Comment by alnopa9** [comment]
@benjaminc2020 I love Brand New and this idea! You could look for themes in each album and if they are present in the individual songs.

**Comment by lmcneil7** [comment]
Your project proposal is an exciting project idea! I like the idea of looking for a pattern of a composer's music, and as I can see, you have a good focus on what to do with it. I would recommend limiting the amount that you want to look at. For instance, pick one lyrist or choose one album. While song lyrics are a lot easier to mark-up because they are short, it would give you more freedom to add more specific reasons for certain words and such. It also helps, so you're not doing 70 XML documents that you have to pay attention to. You could also map at certain songs and their association to the location or what reason might of lead the composer to write the song.

**Comment by smdunn921** [comment]
This seems super cool; i dont really see a lot of research with music, so this is automatically intriguing. Lyrics, especially ones you've been listening to would be way interesting to work with!
