### ISSUE TITLE
Project Checkpoint 1 'Brand New'

### ISSUE THREAD

**Issue by benjaminc2020** [ebeshero/DHClass-Hub#758]
We have successfully created our Repo and cloned it to our computers. We've invited all the collaborators. The README file is created and we've started organizing our repo. 

For meeting times, I am available after class M, W, F until 5:30, and then available again at 7PM.

**Comment by ebeshero** [comment]
We'll want to see these first posts show up on the project repos, but hooray for a swift project launch!
