### ISSUE TITLE
RegEx Homework Submissions

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#760]
A heads up with the homework, your answer sheet should have a markdown file extension. I know we haven't used markdown very often in this class, but [GitHub has a handy tutorial on it](https://guides.github.com/features/mastering-markdown/)! When writing up your homework, make sure to copy and paste you find and replace searches so as not to have any spelling mistakes! 

@robftg @ChinoyIndustries @BMT45 @frabbitry @bobbyfunks @Bryant-LettucePrime @benjaminc2020 @biancamaginley @amberpeddicord @smdunn921 @lmcneil7

**Comment by ebeshero** [comment]
Thanks, @alnopa9 ! Yes, we want you to write up your homeworks for these next units in markdown files (with `.md` file extensions like a Readme on your GitHub) really to give you practice writing markdown.

**Comment by ebeshero** [comment]
Try out writing your Find and Replace expressions in steps for each stage, and try setting your expressions inside code blocks using the tick marks on your keyboard so they come out like this:

Find: `\n\n`
