### ISSUE TITLE
GIF Favicon

### ISSUE THREAD

**Issue by frabbitry** [ebeshero/DHClass-Hub#763]
@ChinoyIndustries 
[Google Chrome doesn't support GIF Favicons](https://stackoverflow.com/questions/16090206/putting-gif-image-in-favicon-not-working-on-chrome)

I think Firefox is the last holdout to support it.

**Comment by ChinoyIndustries** [comment]
aw dang

**Comment by frabbitry** [comment]
"it doesn't look like anyone is interested in implementing it."

Oof
