### ISSUE TITLE
Who Knew You Could Bend Lines?

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#77]
![wow](https://cloud.githubusercontent.com/assets/14117210/11170632/148c7ca4-8ba8-11e5-8a57-bc257211cc19.png)
I was just starting, and one of my results was this.. I thought it was neat, so I shared it with you guys. Enjoy!

**Comment by ebeshero** [comment]
@CodyKarch very cool! Can you post a sample of the code that generated this?

**Comment by CodyKarch** [comment]
Sorry haha I proceeded onward from this...
