### ISSUE TITLE
SOS: Cytoscape is my mortal enemy

### ISSUE THREAD

**Issue by biancamaginley** [ebeshero/DHClass-Hub#773]
I still can't get Cytoscape to download onto my laptop and I'm not sure what to do about it.

**Comment by ebeshero** [comment]
@biancamaginley For right now? Set it aside and don't worry about it. We made the Cytoscape assignment an extra credit assignment anyway, and if we find a project application for it for the Rocket project, we'll use it. Let's turn our attention to the QGIS unit for this week. Can you get QGIS installed [following our tutorial](https://github.com/ebeshero/DHClass-Hub/blob/master/Assignments/QGIS/qgis_intro.md)?

**Comment by ebeshero** [comment]
@biancamaginley Also, you have a TSV you created to import into Cytoscape, you can respond to the Network Analysis assignments with it for some credit, and one of us can tinker with it in Cytoscape on our end if you like.

**Comment by ebeshero** [comment]
@biancamaginley Can you join us for class on Zoom right now? https://pitt.zoom.us/j/862800079

**Comment by biancamaginley** [comment]
So apparently I'm going to continue to be having problems with my laptop. The QGIS won't work on my laptop (even the older version) because the IOS is too outdated. So I drove to IUP to borrow a friends laptop to try and complete these assignments and there isn't enough storage for me to download it on theirs. I'm not sure what to do.

**Comment by frabbitry** [comment]
Have you seen the Virtual Lab thing on My Pitt? I think you can use it to remotely connect to a lab machine and access the software installed there. I believe that QGIS is installed on all of the lab machines... I know Cytoscape is. Maybe that's a solution?

**Comment by ebeshero** [comment]
Here's what I'm finding on Pitt's Virtual Lab: instructions on how to access it:
https://www.technology.pitt.edu/services/virtual-lab

Can you get in?

**Comment by ebeshero** [comment]
@biancamaginley @frabbitry The good news is, oXygen is there in the Virtual Lab and opens just fine. I imagine you can get in and set up GitHub there.

The bad news is...I don't think they installed Cytoscape or ANY GIS software, let alone QGIS. I am calling the Pitt Technology Help Desk about this in hopes they can get it installed for us--both of these are free and we have a need for them right now in our class.

**Comment by ebeshero** [comment]
@biancamaginley @frabbitry: An update: I've filed at ticket with the Pitt Technology Help desk to ask them to install Cytoscape and QGIS for us. I'm going to call them back because I think I'm not finding Git Bash shell there. None of these cost Pitt anything to install and we need them to support our class, so I'm optimistic it will resolve well. Stay tuned...
