### ISSUE TITLE
M 3/23 Class Sign-in

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#774]
Welcome to the QGIS unit, organized by @frabbitry with help from the instructor team! We'll handle attendance this week here in DHClass-Hub Issues. Please sign in to indicate your presence in our 2pm Zoom class today (Monday 3/23) by replying here.

**Comment by BMT45** [comment]
BMT45 was here as usual

**Comment by alnopa9** [comment]
Checking in and excited for the QGIS class! 😄

**Comment by ChinoyIndustries** [comment]
setting up zoom, be there in a minute

**Comment by ebeshero** [comment]
Zoom Link for meeting: https://pitt.zoom.us/j/862800079

**Comment by lmcneil7** [comment]
hello i am here - lam289

**Comment by amberpeddicord** [comment]
here!

**Comment by robftg** [comment]
Robbie Fencil RWF17

**Comment by smdunn921** [comment]
hello it is me

**Comment by Bryant-LettucePrime** [comment]
👋

**Comment by benjaminc2020** [comment]
Here

**Comment by biancamaginley** [comment]
Here

**Comment by bobbyfunks** [comment]
yo
