### ISSUE TITLE
zoom video

### ISSUE THREAD

**Issue by bobbyfunks** [ebeshero/DHClass-Hub#777]
@ebeshero the video of today's class isn't the right one.  I had accidentally logged in again after I left and that's what it appears to be.

**Comment by ebeshero** [comment]
Oops! Thanks @bobbyfunks ! I didn't check...I'll go and find the right one. It's a little confusing because setting these to "record" means we gets lots of recorded snips...

**Comment by ebeshero** [comment]
I think I resolved it--go see @bobbyfunks !

**Comment by bobbyfunks** [comment]
@ebeshero yea its good
