### ISSUE TITLE
Pitt-Greensburg Digital Humanities T-Shirts

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#79]
![newt-mosaic4](https://cloud.githubusercontent.com/assets/4014518/11198799/d6825cb4-8c95-11e5-85da-907ee1e91caf.png)
![image](https://cloud.githubusercontent.com/assets/4014518/11198248/5a812022-8c91-11e5-855b-954015cf2f39.jpeg)
So...rumor has it we might do a run of T-shirts in honor of our very wonderful DH class. We did a first run of T-shirts last year, pulling a weird graphic from a project of mine: it's a network analysis built on mythical and geographic place names in an epic poem. While I like it a lot, unfortunately your class hasn't heard me speak about that--and we're working network analysis into the Coding and Data VIsualization course for spring... So I think we need a more authentic T-shirt design for this fall's class. I wonder if anyone here would like to volunteer a design from the project you're working on, or from a homework assignment, or from something fun you've drawn in SVG? 

Or we could do something whimsical with our firebelly newt logo from newtFire!

**Comment by ebeshero** [comment]
# T-shirt Design! 
Notes: 
1) Ink is part of the fabric (so there's nothing plastic-y in the application).
2) We can order these in any combination of the available T-shirt colors (so they don't all have to be the same color):
[proof](https://cloud.githubusercontent.com/assets/4014518/11314432/822bb9c8-8fb3-11e5-9803-1e8607100160.jpg)

Please [send me an e-mail privately](mailto:ebb8@pitt.edu) with your preferred color and size, and if I hear from you all over the weekend I'll place the order on Monday!

@amielnicki @blawrence719 @brookestewart @djbpitt @setriplette @CodyKarch @rCarls @KariWomack @nlottig94 @ghbondar @spadafour @alexkrongel @andrewntz23

**Comment by ghbondar** [comment]
Geez! We havn't seen the Quadruplet brothers in class in AGES!

**Comment by amielnicki** [comment]
I don't mean this as an insult to anyone's design, in any way, but could I make a small suggestion? Would it be too difficult to go with a different font? The newt is so cool and the font doesn't seem to do it justice. Nothing crazy, just something a little spicier lol.

**Comment by ebeshero** [comment]
@amielnicki This is a tough call! We spent some time looking at fonts yesterday and decided on something simple so as not to distract from the newt! We chose colors from the newt's "palette" and tried not to make the lettering too busy--It was tricky to choose a font that would space itself readably inside the curve of the newt's tail. One thing we did that might not be clear in the proof is to add a shadow around the letters of "Digital Humanities" so that would "pop" out a bit. When we tried two different fonts the shirt started to look a little busy--but I think if we altered anything it would be the font for "Digital Humanities" and leave the other words alone in the simple sans serif. Do you have a font in mind? I can run over today and take a look at it on their software. (We are working with Big Frog here in Greensburg on Rte 30).

Anyone want to meet me over there sometime today (Saturday)? They are open from 11am to 3pm and not open after that until Monday, when I'd like to place our print order. As I am looking at the proofs again this morning, I wonder about something with a forward slant on "Digital Humanities"? Font suggestions are welcome!

**Comment by ebeshero** [comment]
All: Here are some suggested fonts we might try for "Digital Humanities" on our shirt: 
![fonts](https://cloud.githubusercontent.com/assets/4014518/11320033/59f969b6-905b-11e5-8f1f-a9414cece316.jpg)

Preferences?

**Comment by nlottig94** [comment]
I like 2, 5, and 8.

**Comment by ebeshero** [comment]
Greg likes 1, 2, and 8.
I like 1, 5, and 8.

**Comment by amielnicki** [comment]
I like 1, 2 and 8 as well!! :)

**Comment by amielnicki** [comment]
I think it makes the "digital" part of digital humanities match the newt appropriately.

**Comment by ebeshero** [comment]
okay--let's narrow it down: which is best  of 1, 2, and 8?

**Comment by ebeshero** [comment]
ah! I still like 5! ;-)

**Comment by nlottig94** [comment]
I really like 5 too @ebeshero  !!!!  But if we're choosing between 1, 2, and 8, I like 8 the best.

**Comment by amielnicki** [comment]
Yep, 8 for me too!

**Comment by RJP43** [comment]
def 8 ... and i love these shirts :)

**Comment by ghbondar** [comment]
I concur with 8! ... #2 is too gratuitously digital, and #5 strikes me as a bit "paleo" like something carved in stone, if you want some dissonance. We like #1 for it's dynamic, classic, forward-leaning, Star Trekky optimism, but we're also old-school, from when "digital" was still analog.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
