### ISSUE TITLE
SVG 4: Dickinson

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#80]
I have come to the conclusion that I have no idea what to do with SVG. I am attempting to create a bar graph which charts how many variants each poem has. I thought that I would try this:

`<xsl:apply-templates select="//app"> `
       
                   ` <xsl:variable name="var0" select="count(./rdg[@wit='var0'])*100"/>
                      <xsl:variable name="var1" select="count(./rdg[@wit='var1'])*100"/>
                      
                    <line x1="30" x2="30" y1="0" y2="{$var0}" stroke="pink" stroke-width="10"/>
                   <line x1="50" x2="50" y1="0" y2="{$var1}" stroke="purple" stroke-width="10"/>
                    </xsl:apply-templates>`

but no matter what I do, I get an error saying that there is an invalid element within apply-templates. I'm probably just making a silly mistake with my xslt or something, but I just have no idea. Any help is appreciated. Without having apply-templates I don't get any numbers for my y2, but I'm not sure if having `<xsl:apply-templates>` would even help. I'm lost.

**Comment by ebeshero** [comment]
@blawrence719 Your message is making me realize how little we actually use `<xsl:apply-templates>` in plotting SVG. You use it with a `@select` attribute to pull only the elements you need to process and ignore the rest, and then start a new xsl:template match rule to process what you need from within those elements. We can open it up to apply an `<xsl:sort>`, but not to actually plot elements in HTML or SVG.

In fact, a template rule doesn't require an `<xsl:apply-templates>` at all! Or maybe you only use it to filter out parts of the XML as I describe above. In writing SVG, mostly what we do is write one or two template rules--one matching on the document node and maybe another on a particular element holding all the data we want to plot. When you go to plot line or rect or circle or other kinds of SVG shapes and SVG text, you are usually just using Attribute Value Templates inside curly braces `{$stuff}` to process XSLT, run an XPath function or calculate the value of a variable. There's a longhand way of writing out those attributes with xsl:value-of and what's called an Attribute Value Constructor, but we find it hard to read for drawing SVG and only use it very rarely when the values we're calculating are themselves going to require multiple lines of code. You can read more about it in the last section on Obdurodon's AVT page: http://dh.obdurodon.org/avt.xhtml

So, what I'm ultimately saying is, you don't need `<xsl:apply-templates>` for this job of drawing SVG elements!

**Comment by djbpitt** [comment]
`<xsl:apply-templates>` can't contain `<line>` elements. The only elements allowed inside `<xsl:apply-templates>` are `<xsl:sort>` and `<xsl:with-param>` elements. See Michael Kay p. 240. It looks as if what you want is something like:

    <xsl:template match="/">
        <xsl:apply-templates select="//app"/>
    </xsl:template>
    <xsl:template match="app">
        
    </xsl:template>

**Comment by ebeshero** [comment]
Thanks, @djbpitt! And for anyone curious, djbpitt is my good friend and Pitt colleague who runs Obdurodon. Now and again he may turn up with a comment on our discussions, especially if I call his attention to something interesting like this post. We'll sometimes turn up to talk to each other's students and mix up our student instructors.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
