### ISSUE TITLE
NewtFire and PSC down: Alternative Access

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#81]
NewtFire is down this evening. I've reported the problem to the PSC and I'm waiting to hear back. In the meantime, here is an alternative access to our current assignment page from my GitHub backup: 

https://raw.githubusercontent.com/ebeshero/newtFire-webDev/master/dh-course/JavaScript_SSI_Exercise1.html

You can download this file locally and read it (without my SSI or CSS styling). Or, if you're missing the firebelly (as I am), you could clone my newtFire repository and read everything locally from the syllabus page: https://github.com/ebeshero/newtFire-webDev
If you clone my newtFire repository, just note that the DH class files are all in the dh-course directory, and you should locate CDAsyll.html to find your way to our syllabus. If you've cloned this as a local directory, my CSS and JavaScript will work, and all my links will function locally outside newtFire.  Find your way to our current assignment by date as usual, or if you're looking for the file, just note that what you want is JavaScript_SSI_Exercise1.html and not the old JavaScript Exercise 1 from last year. 

Meanwhile, I'd updated the assignment page and written a new newtFire SSI tutorial to explain how to set the x-bit to activate your SSI since that information was missing from the Obdurodon tutorial, but now, ironically enough, we have to wait for the PSC to come back online for us to implement that! (sigh) Fortunately, JavaScript doesn't depend on newtFire access, so I'd suggest working on the JavaScript exercise while we're waiting for our server to come back online!

**Comment by ebeshero** [comment]
I've just posted an entire Mirror Site for our course on my GitHub Io webspace, so you can access the entire course from here: http://ebeshero.github.io/newtfire/dh/CDASyll.html when the power goes down at the PSC. 

Unfortunately, that still doesn't get you access to your project sites. We'll see if we can work out a GitHub Io backup for those, too.

**Comment by amielnicki** [comment]
Please refer to my posting on the other Issue #82 for information on how you can still complete the SSI portion of the homework.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
