### ISSUE TITLE
Mirror Site for our DH Course posted on GitHub Io

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#82]
Just to make sure this reaches as widely as possible, I'm posting this as a new issue.
I've created a Mirror Site for newtFire on GitHub Io, and you can now access a fully functioning alternate version of our course site here: 
http://ebeshero.github.io/newtfire/dh/CDASyll.html 

One comment on the process: GitHub Io (or Github Pages) does not support SSIs, so I wrote an Identity Transformation XSLT this morning to match on my SSI comments and transform them to the snippets of HTML I needed to include. And I found a JavaScript workaround to give me the date last modified, since GitHub pages won't let its server tell us that directly. 

At this point, I know there has been a massive power failure at the Pittsburgh Supercomputing Center, which seems really strange, and lots of systems are down. We'll have to monitor the situation, but if they can't bring our newtFire and our project team space back online today, we'll obviously have to postpone the SSI portion of your JavaScript homework. If things look like they're crashing and burning all over at the PSC (okay maybe that's a little dire) we'll figure out a way to get your projects running in GitHub Io! It's good we have GitHub as our backup.

**Comment by ebeshero** [comment]
In case they don't restore newtFire access today, just do the JavaScript Exercise, and upload your files on Courseweb. I've created an upload link in Courseweb for JavaScript Exercise 1 in the event that we can't get into newtFire.

**Comment by amielnicki** [comment]
Hello everyone!

@spadafour @blawrence719 @brookestewart @CodyKarch @KariWomack @nlottig94 @rCarls @spadafour @RJP43 @ebeshero @ghbondar 

I apologize for my lack of posting to help people on GitHub over the semester, but this is a problem that I know I can help with, so hopefully this will be my saving grace.

I own server space for my own hosting and professional purposes. And guess what... It supports Server Side Includes! I have setup a folder on my server that you are all welcome to access to upload your SSI homework for tomorrow. Below are the credentials to access the server space. Once you are logged in, you will see a folder for each of you. Your folder name is based on your GitHub username.

Everyone will use the same username and password, and will not be able to navigate to anywhere else on my server except the folder containing all of our folders. Everyone will be able to access EVERYTHING in this folder, so be sure not to but things anywhere but in the folder labeled with your name. **Also, by no circumstance should you touch the .htaccess file in this directory. This file is enabling the use of server side includes for us, and if it is edited, it could break that functionality.**

Professors: Once people upload their data here, you are free to use the information below to check the work. 

Field | Information
------------ | -------------
Server: | s194963.gridserver.com
Username: | dh-class@asmdevelopments.com
Password: | 2015@Newt
Protocol: | FTP
Port: | 21
Web Accessible URL: | http://asmdevelopments.com/ssi/[your_username]

If you have any questions, please let me know!

I hope this helps!! - Alex

**Comment by ebeshero** [comment]
Alex--wow! Thank you very much indeed! Everyone, you heard him--let's go ahead and post those SSI files!

**Comment by nlottig94** [comment]
Closing for Spring 2016.
