### ISSUE TITLE
Getting SSI to work

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#83]
I'm attempting to employ SSI in my html document by following the instructions, but I can't seem to get it to work. As far as I understand it, I have my basic `index.html` document, well formatted and everything like that. When I want to put on the header, I just paste this: `<!--#include virtual="menu.html" -->` (`menu.html` being the name of my SSI).
Inside the file `menu.html`, I have the excerpt of code that is my header, but I do not need it to be properly formed, right? I'm obviously getting an error on it. Well, when I attempt to load my page `index.html` with `menu.html` attached to it, I do not see the header. What am I doing wrong?

**Comment by ghbondar** [comment]
@spadafour Rob, the code in menu.html _does_not_ need to be well-formed html (it does need to be well-formed xml). If it is well-formed html, that might be causing the error because it will duplicate some of the structure of your main html page.

**Comment by spadafour** [comment]
hmmmm.... when I copy and paste the xml back into the document (just to make sure it is well-formed), I DO get the expected output. So I do have properly formed xml, but not complete html.

**Comment by blawrence719** [comment]
I'm also having an issue with this same thing.

**Comment by amielnicki** [comment]
I think I know what the problem is... I logged into my web server, and see that you guys haven't uploaded any files there.

Server Side Includes will not work just on your local computer. They must be uploaded to a server that supports them. Try following the info I posted in issue #82 to upload your items to the web space.

**Comment by spadafour** [comment]
Ah! Thank you!

**Comment by amielnicki** [comment]
@spadafour I see files in there now... I am so glad it worked, as I think you are the first one other than me to try. I am really happy you were able to get in!

**Comment by ebeshero** [comment]
Thanks, @amielnicki for hosting and explaining! Yes--you can only "see" SSIs actually work when you post them to web server space.
