### ISSUE TITLE
Hide/Show in Javascript

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#84]
I'm having an issue getting my button to work to hide/show an element. I am attempting to work off my Dickinson homepage example and have a button above the table and I'm trying to make the button so that when you click it, the table with disappear/appear. I have two things attempted in my Javascript and am unsure how to make the button work. Here is what I have:

`var buttons = document.getElementsByTagName("button");
var button = buttons[0];
button.onclick = show_hide;
if (table.style.display="none"){
    $("table").show(1000)
}
else {
    $("table").hide(1000)}`

That I got from reading on obdurodon and then this next attempt was from w3schools:

`    $(document).ready(function(){
    $("button").click(function(){
        $("table").hide(1000);
    });
});`

**Comment by amielnicki** [comment]
Hi Brooke!

In order for this to work, you must write a function to house the if statement, as such:

`function show_hide {
`
`}

**Comment by blawrence719** [comment]
Where exactly does that go and am I putting anything inside it?

**Comment by amielnicki** [comment]
So first you define a function called buttons to house the two "var" lines and the "onClick" line, and then a separate one to house the if/else statements. Like such:

`function buttons() {`
`<!--Put var button lines and "onClick" line in here-->`
`}`
`function show_hide() {`
`<!--Put if/else statement in here-->`
`}`

**Comment by blawrence719** [comment]
Okay, yeah I had the show_hide right and just added the buttons one and it still isn't doing anything. Here is what I have now:

`function buttons(){

var buttons = document.getElementsByTagName("button");
var button = buttons[0];
button.onclick = show_hide;
}


function show_hide() { 

if (table.style.display="none"){
    $("table").show(1000)
}

else {
    $("table").hide(1000)}
       
 }`

**Comment by amielnicki** [comment]
Does your table in your HTML file have an id attribute?

**Comment by blawrence719** [comment]
No. I'm guessing it needs one?

**Comment by amielnicki** [comment]
Yep, you should give it one so you can call it more easily in your Javascript.

Once you do that, you will call it in the if statement like I have in mine below. I used the visibility style attribute, but the display one should work the same.

Also make sure you have the top line in your file as well, or nothing will ever work.

`window.addEventListener('DOMContentLoaded',buttons,false);`
            
`function buttons() {`
    `var buttons = document.getElementsByTagName("button");`
	`var button = buttons[0];`
	`button.onclick = show_hide;`
`}`
`function show_hide() {`
    `if (pToggle.style.visibility != "hidden") {`
    `pToggle.style.visibility = "hidden";`
	`}`
	`else {`
	`pToggle.style.visibility = "visible"`
	`}`
`}`

**Comment by amielnicki** [comment]
So, line by line, my code says the following:

Listen for the page to finish loading.
Here is my function called "buttons"
Let the variable "buttons" equal the HTML collection, or array, of elements of tag name "button"
Let the variable "button" equal the first button in the collection
When someone clicks the button, invoke the function "show_hide"

Here is my function called "show_hide"
If my paragraph with an id of "pToggle" has a style attribute of visibility that does not equal "hidden", then set the visibility style attribute of id "pToggle" to "hidden"
Else, set the visibility style of id "pToggle" attribute to "visible"

**Comment by blawrence719** [comment]
Okay so I gave my table an id of "table" and I'm still not getting anything. Is there something wrong with my if statement? I wasn't really sure how to write it.

**Comment by amielnicki** [comment]
I am not sure what the "1000"s mean in your code. Take a look at my if/else statements above.

**Comment by blawrence719** [comment]
I don't know, I got those from w3schools which was telling me to put it as a speed or something? I honestly don't even know.

**Comment by amielnicki** [comment]
Ah I see. That would be useful if you wanted to slow it down so you could see it slowly disappear, and slowly reappear. That is probably something you don't want to mess with now.

Try plugging `table` into my code every where that you see `pToggle` and see if that works. Then experiment from there once you get that working.

**Comment by blawrence719** [comment]
I already tried doing that and still got nothing.

**Comment by amielnicki** [comment]
Also, be sure you are calling your ".js" file in your HTML as follows:

`<script src="filename.js"></script>`

**Comment by blawrence719** [comment]
I'm pretty sure I have that set up right because earlier I had the code in for a popup saying the page is loaded and that worked just fine.

**Comment by amielnicki** [comment]
Oh okay, good! Try giving your table an id that is something other than table, like tableOfValues or something, so it doesn't have the same name as the tag that creates it.

**Comment by blawrence719** [comment]
I don't know what the heck I'm doing wrong, but that isn't working either.

**Comment by amielnicki** [comment]
AH! I think I know!!! Anywhere in your HTML Document do you have the button defined?

`<div><button>Show/Hide</button></div>`

If you don't have something like that on your page, then there is nothing for it to call.

**Comment by blawrence719** [comment]
I didn't have `<div>` but I just added it and still nothing

**Comment by amielnicki** [comment]
As soon as I put that on your homepage, I got it to work on my computer.

Your .js file should look like this:

window.addEventListener('DOMContentLoaded',buttons,false);
            
function buttons() {
    var buttons = document.getElementsByTagName("button");
	var button = buttons[0];
	button.onclick = show_hide;
}
function show_hide() {
    if (tableOfValues.style.visibility != "hidden") {
    tableOfValues.style.visibility = "hidden";
	}
	else {
	tableOfValues.style.visibility = "visible"
	}
}

Your HTML table should look like this:
        <table id="tableOfValues">

With something like this in your HTML:

<button>Show/Hide</button>

**Comment by amielnicki** [comment]
Here is your working HTML from what I pulled down from GitHub

http://asmdevelopments.com/ssi/amielnicki/lawrence/

**Comment by blawrence719** [comment]
I don't understand why I can't get it to work then

**Comment by amielnicki** [comment]
I just pushed my working .js file into the Troubleshooting Directory as well as the HTML file I am working with. Try downloading them, and seeing if that works. They are called "lawrence.js" and "lawrence.html"

**Comment by blawrence719** [comment]
Okay when I open yours, they work. I will investigate why mine don't work and post in a second.

**Comment by blawrence719** [comment]
Oh my gosh. Would it have been because my file was saved as xhtml? I changed it to html and it works. I remember something about this in class, but I forgot. Embarrassing.

**Comment by amielnicki** [comment]
I thought about that just a minute ago haha. That is probably it. Oh well, it's good we went through everything anyway.

**Comment by blawrence719** [comment]
Thank you so much for all of your help!

**Comment by spadafour** [comment]
I've been reading this thread as you guys are discussing, and I'm trying to follow along. Where are all of these rules of javascript coming from? Is there a page that we were direct to or something that I'm missing? I really don't understand where any of this came from.

On top of that, I'm trying to follow your help with Brooke's work, but I'm just trying to apply it to the basic example on Obdurodon, and none of this has clicked with me yet. If I were to copy/paste all of this in to a new javascript document, all I would need to change is the @id from tableOfValues to whatever @id I'm trying to hide, right?

**Comment by amielnicki** [comment]
Yep, that is correct! Part of this comes from discussions of Javascript you can find online, like the W3 schools, other parts are just from me having prior coding experience in both Java and JavaScript. When I started reading the Obdurodon stuff, something about how those pages are laid out just makes me want to scream lol. I basically ignored it and figured it out based on my past experience.

That is correct though, just change the id to whatever id you are trying to apply it to. The most important part is that you understand what the code is saying. Be sure you read through my line by line explanation above in this thread.

**Comment by amielnicki** [comment]
@blawrence719 It was my pleasure!! See you tomorrow!

**Comment by spadafour** [comment]
I did, thank you VERY MUCH for the explanation. So I've changed the @id to the one from the example from Obdurodon (the id is paragraphToToggle), it just doesn't seem to be firing?

**Comment by spadafour** [comment]
lol, wait, I had a typo in there. Oops.

**Comment by spadafour** [comment]
It's working now. Thank you so much for your help!

**Comment by ebeshero** [comment]
I'd like to walk through an example of JavaScript working with an associated HTML and SVG file tomorrow so the coding of events and syntax will make a little more sense...thanks for being "on call" this evening, Alex! @amielnicki

**Comment by ebeshero** [comment]
@amielnicki shows a way to control whether something is displayed or hidden using the style property **visibility** instead of **display**. I was puzzling over this a little, until I looked it up. There's a difference between the two. Both are actually CSS properties that we often invoke with JavaScript to toggle things to be seen or not. But there's a small but significant difference between the two. When visibility is set to hidden, the element takes up the same amount of space as it did before, whereas with display set to none, the element takes up no space and it's as if it was never there.

Alex writes it this way with visibility set to hidden or *not* hidden (using the exclamation point to indicate inequality):

````
function show_hide() {
if (tableOfValues.style.visibility != "hidden") {
tableOfValues.style.visibility = "hidden";
}
else {
tableOfValues.style.visibility = "visible";
}
}
````
 Here's an alternative way to write this with the display property, so the element takes up no space when it disappears:

````function show_hide() {
if (tableOfValues.style.display != "none") {
tableOfValues.style.display = "none";
}
else {
tableOfValues.style.display = "inline";
}
}
````
Each of these, visibility and display, can take a range of style values, but we typically just work with one or two of them to toggle a show/hide function. For details on the difference between the two and the range of properties you can set, see w3schools: http://www.w3schools.com/css/css_display_visibility.asp

Yep, that's a CSS page: the style properties display or visibility are properties we can write in CSS, too. (The style properties are places where CSS and JavaScript overlap, and JavaScript is often used to toggle and change CSS properties like this).

**Comment by ebeshero** [comment]
And here's a neat w3schools demo page to help show the difference between visibility and display:
http://www.w3schools.com/css/tryit.asp?filename=trycss_display

**Comment by RJP43** [comment]
JavaScript Conditionals as mentioned in class found [here](http://www.w3schools.com/js/js_comparisons.asp)

**Comment by RJP43** [comment]
JavaScript Event Listener list found [here](https://developer.mozilla.org/en-US/docs/Web/Events)

**Comment by nlottig94** [comment]
Closing for Spring 2016.
