### ISSUE TITLE
Highlighting Help

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#85]
Okay, so I am having a few issues.  I am cannot get my variants highlighted when I use toggle boxes...

This is what I have in my javascript:
`window.onload = init;
function init() {
    var fieldset = document.getElementsByTagName('input');
    for (var i = 0; i < fieldset.length; i++) {
        fieldset[i].addEventListener('click', toggle, false);
    }
}

function toggle() {
    var id = this.id;
    switch (id) {
        case "var0toggle": {
            var var0 = document.getElementsByClassName("var0");
            for (var i = 0; i < chars.length; i++) {
                var0[i].classList.toggle("on")
            }
        };
        break;
        case "var1toggle": {
            var var1 = document.getElementsByClassName("var1");
            for (var i = 0; i < places.length; i++) {
                var1[i].classList.toggle("on")
            }
        };
        break;
        case "var2toggle": {
            var var2 = document.getElementsByClassName("var2");
            for (var i = 0; i < objects.length; i++) {
                var2[i].classList.toggle("on")
            }
        };
        break;
    }
  }`

And this is what I have in my html:
`<div>
         <fieldset>
            <legend>Click to Highlight:</legend>
            <input type="checkbox" id="var0toggle"/>
            <span>Variant 1</span>
            <input type="checkbox" id="var1toggle"/>
            <span>Variant 2</span>
            <input type="checkbox" id="var2toggle"/>
            <span>Variant 3</span>
         </fieldset>
      </div>`

I believe it is connecting everything, but when I try it out in my browser, it doesn't work...
@ebeshero @amielnicki  Help?

**Comment by ebeshero** [comment]
@nlottig94 Sorry for the delayed response! Your code looks right to me here, but there could be something small going wrong. Also, is there more to your HTML that we're not seeing here? You showed us your `fieldset` code, or the part that sets up your checkboxes, but what about the text that's supposed to be highlighted on click? (I'm pretty sure I know what that code looks like from the Dickinson project, but it'll be easier for us to debug if you push everything to the Troubleshooting folder!)

**Comment by ebeshero** [comment]
@nlottig94 AHA! I spotted the error! Look inside each of your "cases" in the toggle() function: For example, for the first one, you have:

````
case "var0toggle": {
var var0 = document.getElementsByClassName("var0");
for (var i = 0; i < chars.length; i++) {
var0[i].classList.toggle("on")
````

This line is the problem:
` for (var i = 0; i < chars.length; i++) `

You have defined a variable named `var0`, but you're not invoking it in the for loop: you're instead invoking some other variable called `chars` (I think from my code on the tutorial page). And you've done the same thing in each of the other cases. For this first case, you just need to change the line to refer to *your* variable, like this:

`for (var i = 0; i < var0.length; i++)  `

Does that make sense? In the for-loop, you're actually referring to *two* variables: the range variable named `i` which ranges or loops through an array, made of each of your `var0` variables--or all the elements you've marked with an `@class` named `var0`.

**Comment by nlottig94** [comment]
Yes!  That is what I noticed I was doing wrong!  I was reading through my JavaScript at work and it clicked in my brain that those two things should really match!!

**Comment by ebeshero** [comment]
Yay! Let's leave this open for a bit in case anyone else needs to see it while working on this homework.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
