### ISSUE TITLE
SVG Question

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#86]
I was making an artsy thing with SVG and was wondering if there is any way to make the width of lines get smaller or bigger over the span of a line. @ebeshero @ghbondar @RJP43

**Comment by CodyKarch** [comment]
![liness](https://cloud.githubusercontent.com/assets/14117210/11321473/b9fe7850-908e-11e5-8114-050bf14a8dfc.jpg) Like the varying widths with curvy lines like these.

**Comment by ebeshero** [comment]
@CodyKarch Very cool! I think you'll be treating these SVG's image files in your HTML, right? If you call them with `<img src="wavyLine.svg" alt="19th-century style wavy line"/>` I'd adjust their width and height properties in CSS on your img element. You could add an `@id` to the `<img>` so you can style just that particular image. And experiment with setting widths using pixel values (like 500px). (You could also use percent values, but somehow pixel values seem to work better.)

**Comment by nlottig94** [comment]
Closing for Spring 2016.
