### ISSUE TITLE
Automate Everything.

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#87]
I had to share this to everyone, because it reminds me of our XSLT work. I found this article about a person who programmed everything in his life, from texts to his coffee machine at work. Check it out. http://www.businessinsider.com/programmer-automates-his-job-2015-11?utm_content=buffer195bd&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer

**Comment by ebeshero** [comment]
Thanks, @CodyKarch ! It's high time that @ghbondar and I wired our coffee-maker into household network! ;-)

**Comment by nlottig94** [comment]
Closing for Spring 2016.
