### ISSUE TITLE
Let's Talk About Versioning

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#88]
[Critical Apparatus Versioning](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TC.html#TCAPEN)

Different variants are witnesses:
Witnessing an edition --- 19th cent. print edition (editor) versus manuscript (transcriber) --- Define the witness 

Mark divergences between versions of the same text with TEI apparatus mark-up

two types of version mark-up

`<app>`
`<lem wit="#ebb">`
`--If she told who the husband was to be she should never`
`<del rend="squiggles">`
`<gap quantity="1" unit="word"/>`
`</del>`
`get him.`
`</lem>`
`</app>`

`to whom I gave a bit just now`
`<app>`
`<rdg wit="#LEst1870">,</rdg>`
`</app>`
`that she should tell me her dream--but she says that would destroy the charm`

`<rdg @wit`> = reading witness
`<lem>` = lemma (the version that is meant to rule over all the others)

**Comment by RJP43** [comment]
digital versions --- make different versions of a text able to be studied side by side

**Comment by RJP43** [comment]
Using [Juxta Commons](http://juxtacommons.org/) ... for example on [Digital Mitford](http://digitalmitford.org/letters.html)

**Comment by RJP43** [comment]
Explore how to use our XML markup with JavaScript to create possible mouse-overs where multiple versions appear upon user interaction

**Comment by nlottig94** [comment]
Closing for Spring 2016.
