### ISSUE TITLE
Here is an Issue directing you to a helpful Website on the Basics of XML

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#9]
http://www.pitt.edu/~upgstd/2015Convention/index_conventionPrep.xhtml

go ahead and try to comment on this issue :)

**Comment by amielnicki** [comment]
This is super helpful!

**Comment by blawrence719** [comment]
Commenting

**Comment by brookestewart** [comment]
"something silly"

**Comment by KariWomack** [comment]
commenting on this issue.

**Comment by nlottig94** [comment]
Thank you, Becca!  Have a flower!
![dscn1082](https://cloud.githubusercontent.com/assets/14095715/9687395/41536e1c-52f7-11e5-87ca-8921b38f31c8.JPG)

**Comment by KariWomack** [comment]
SOOOOOO PRREEEEETTTTTYYYYYY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ebeshero** [comment]
:+1:
