### ISSUE TITLE
Project Guidelines Page Updated, with Portfolio Standards for DS Certificate

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#91]
@amielnicki @blawrence719 @brookestewart @ghbondar @CodyKarch @rCarls @KariWomack @nlottig94 @spadafour 
I have (at last!) repaired [our Project Guidelines page](http://newtfire.org/dh/projectGuide.html) so it doesn't contain dated information from last fall's course, and so it now links to a page of standards my colleagues and I are working on for your [Individual Portfolio pages](http://newtfire.org/dh/dsPortfolio.html). An online portfolio is a requirement for each student to graduate with the Digital Studies Certificate, but even if you aren't (or aren't sure if) you are pursuing the Certificate, you may really want to work on a public-facing page that represents your work, designed for potential employers and/or graduate school programs to see. I'm meeting today with the group of us faculty supervising the DS Certificate and we may add or revise the Portfolio Standards page a bit, butt his page should get you started. 

Here is something to try to coordinate as you develop your project websites: If members of the team have a portfolio page, it should (of course) link to the project site, but the project site should (probably) link to a portfolio page to provide information on the team members. You want to represent yourselves on your sites somehow, and an area on an About page or a separate page just of bios could be in order depending on your site designs.

**Comment by RJP43** [comment]
And just so everyone knows the SSI work now for our personal pages as well as the project sites hosted by the Pittsburgh Supercomputing Center.

**Comment by ebeshero** [comment]
Huzzah! Yes, they managed to activate SSIs for all our individual directories--and quickly too, just when we asked about it.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
