### ISSUE TITLE
Hello returning students / fellow teaching assistants

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#97]
@nlottig94 @spadafour @brookestewart Hey everyone when is a good time for us to meet up tomorrow after class? There are some class logistics that @ebeshero and @ghbondar need to review with the group of us. I also want to encourage all of you, who haven't already, to clone the [newtFire Web Development repository](https://github.com/ebeshero/newtFire-webDev). That space is where we will discuss (once you all have been added as collaborators), you guessed it, **development** of the course separate from the more general student interaction. Meanwhile, comment on this issue with the times you are all available to meet after tomorrow's class. Thank you! See you tomorrow.

**Comment by RJP43** [comment]
I personally am available anytime after class before 7PM.

**Comment by ebeshero** [comment]
I have a next class after DH from 3 - 3:50 PM, so sometime before or after
that is good.

On Tue, Jan 5, 2016 at 1:26 PM, Rebecca Parker <notifications@github.com>
wrote:

> I personally am available anytime after class before 7PM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebeshero/DHClass-Hub/issues/97#issuecomment-169089050>
> .
>



-- 
Elisa Beshero-Bondar, PhD
Associate Professor of English
University of Pittsburgh at Greensburg
Humanities Division
150 Finoli Drive
Greensburg, PA  15601  USA
E-mail: ebb8@pitt.edu
about.me/ebbondar

**Comment by nlottig94** [comment]
I am available after class until whenever because it's my only class!  :)

**Comment by brookestewart** [comment]
My next class is at 1, so I'll be available right after class or between 2 and 4

**Comment by RJP43** [comment]
@ebeshero @nlottig94 @ghbondar @brookestewart @spadafour 
We decided, after class today, we will be having an instructor meeting every Thursday from 12:30- 1:30. @ebeshero will create a dropbox folder for the student instructors to work in (outside of the main course dropbox folder) so be expecting that invite before Friday.
